# $FreeBSD: head/polish/Makefile 495967 2019-03-16 21:55:51Z tcberner $
#

    COMMENT = Polish language support

    SUBDIR += aspell
    SUBDIR += ekg
    SUBDIR += ekg2
    SUBDIR += fortunepl
    SUBDIR += gnugadu2
    SUBDIR += hunspell
    SUBDIR += hyphen
    SUBDIR += kadu
    SUBDIR += libgadu
    SUBDIR += libreoffice
    SUBDIR += libtlen
    SUBDIR += mythes
    SUBDIR += qnapi
    SUBDIR += tleenx2
    SUBDIR += trf
    SUBDIR += webalizer2

.include <bsd.port.subdir.mk>
