# $FreeBSD: head/x11-drivers/xf86-video-dummy/Makefile 476013 2018-07-31 18:41:30Z zeising $

PORTNAME=	xf86-video-dummy
PORTVERSION=	0.3.8
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org dummy display driver

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

XORG_CAT=	driver

.include <bsd.port.mk>
