# Created by: Thomas Gellekum <tg@FreeBSD.org>
# $FreeBSD: head/devel/gnustep/Makefile 492056 2019-02-03 15:37:58Z theraven $

PORTNAME=	gnustep
PORTVERSION=	1.28.0
PORTREVISION=	6
CATEGORIES=	devel lang gnustep

MAINTAINER=	theraven@FreeBSD.org
COMMENT=	Objective-C libraries based on the OpenStep standard

USES=		metaport gnustep
USE_GNUSTEP=	back gui base

.include <bsd.port.mk>
