# Created by: thierry@pompo.net
# $FreeBSD: head/games/cardpics/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=		cardpics
PORTVERSION=		0.4
CATEGORIES=		games devel
MASTER_SITES=		SAVANNAH

MAINTAINER=		thierry@FreeBSD.org
COMMENT=		Free cards for your free card games!

LICENSE=		GPLv2

USES=			tar:bzip2
NO_ARCH=		yes
GNU_CONFIGURE=		yes

.include <bsd.port.mk>
