# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/databases/php56-interbase/Makefile 468288 2018-04-25 18:40:14Z acm $

PORTREVISION=	1
CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-interbase

.include "${MASTERDIR}/Makefile"
