# Created by: kevit
# $FreeBSD: head/textproc/p5-Template-Plugin-XML-Escape/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	Template-Plugin-XML-Escape
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	simarg@gmail.com
COMMENT=	Escape variables to suit being placed into XML

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Template-Toolkit>=2.20:www/p5-Template-Toolkit

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
