# $FreeBSD: head/devel/rubygem-prometheus-client-mmap/Makefile 466445 2018-04-04 16:32:18Z mfechner $

PORTNAME=	prometheus-client-mmap
DISTVERSION=	0.9.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	idefix@fechner.net
COMMENT=	Suite of instrumentation metric primitives

LICENSE=	RUBY

LIB_DEPENDS+=	libunwind.so:devel/libunwind

USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
