# $FreeBSD: head/devel/rubygem-prometheus-client-mmap/Makefile 449058 2017-09-01 07:40:33Z tz $

PORTNAME=	prometheus-client-mmap
DISTVERSION=	0.7.0.beta17
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	tz@FreeBSD.org
COMMENT=	Suite of instrumentation metric primitives

LICENSE=	RUBY

RUN_DEPENDS=	rubygem-mmap2>=2.2.7:devel/rubygem-mmap2

NO_ARCH=	yes
USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
