# $FreeBSD: head/devel/rubygem-prometheus-client-mmap/Makefile 455591 2017-12-05 16:44:09Z tz $

PORTNAME=	prometheus-client-mmap
DISTVERSION=	0.7.0.beta18
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	idefix@fechner.net
COMMENT=	Suite of instrumentation metric primitives

LICENSE=	RUBY

RUN_DEPENDS=	rubygem-mmap2>=2.2.7:devel/rubygem-mmap2

NO_ARCH=	yes
USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
