# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: head/textproc/rubygem-sax-machine/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	sax-machine
PORTVERSION=	1.3.2
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Declarative sax parsing library backed by Nokogiri

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
