# Created by: Yuri Victorovich <yuri@rawbw.com>
# $FreeBSD: head/dns/py-dnschain/Makefile 446786 2017-07-28 01:14:54Z dbaio $

PORTNAME=	dnschain
PORTVERSION=	0.1.0
CATEGORIES=	dns python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	yuri@rawbw.com
COMMENT=	Library for looking up blockchain data via DNSChain

LICENSE=	MPL20

USES=		python
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
