# Created by: SimaMoto,RyoTa <liangtai.s4@gmail.com>
# $FreeBSD: head/korean/gimp-help/Makefile 493763 2019-02-24 15:08:19Z tobik $

CATEGORIES=	korean graphics

MAINTAINER=	liangtai.s16@gmail.com
COMMENT=	GIMP User Manual in Korean

LICENSE=	GFDL

MASTERDIR=	${.CURDIR}/../../misc/gimp-help-en

DOCLANG=	ko

.include "${MASTERDIR}/Makefile"
