# $FreeBSD: head/devel/rubygem-aws-sdk/Makefile 486425 2018-12-02 15:34:53Z sunpoet $

PORTNAME=	aws-sdk
DISTVERSION=	2.11.182
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	AWS SDK for Ruby

LICENSE=	APACHE20

RUN_DEPENDS=	rubygem-aws-sdk-resources>=${PORTVERSION}:devel/rubygem-aws-sdk-resources

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
