# $FreeBSD: head/devel/rubygem-aws-sdk/Makefile 444272 2017-06-25 15:02:18Z sunpoet $

PORTNAME=	aws-sdk
PORTVERSION=	2.10.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	AWS SDK for Ruby

LICENSE=	APACHE20

RUN_DEPENDS=	rubygem-aws-sdk-resources>=${PORTVERSION}:devel/rubygem-aws-sdk-resources

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
