# $FreeBSD: head/devel/rubygem-aws-sdk/Makefile 496370 2019-03-20 18:03:23Z sunpoet $

PORTNAME=	aws-sdk
DISTVERSION=	2.11.243
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	AWS SDK for Ruby

LICENSE=	APACHE20

RUN_DEPENDS=	rubygem-aws-sdk-resources>=${PORTVERSION}:devel/rubygem-aws-sdk-resources

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
