# $FreeBSD: head/sysutils/hs-disk-free-space/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	disk-free-space
PORTVERSION=	0.1.0.1
PORTREVISION=	2
CATEGORIES=	sysutils haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Retrieve information about disk space usage

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
