# $FreeBSD: head/sysutils/hs-disk-free-space/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	disk-free-space
PORTVERSION=	0.1.0.1
PORTREVISION=	3
CATEGORIES=	sysutils haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Retrieve information about disk space usage

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
