# Created by: John Chen <johnpupu@gmail.com>
# $FreeBSD: head/devel/pecl-msgpack0/Makefile 481545 2018-10-08 15:08:13Z antoine $

PORTNAME=	msgpack
PORTVERSION=	0.5.7
CATEGORIES=	devel

MAINTAINER=	johnpupu@gmail.com
COMMENT=	Provides API for communicating with MessagePack serialization

LICENSE=	BSD3CLAUSE

USES=		php:pecl
IGNORE_WITH_PHP=70 71 72 73

.include <bsd.port.mk>
