# Created by: John Chen <johnpupu@gmail.com>
# $FreeBSD: head/devel/pecl-msgpack0/Makefile 485511 2018-11-21 12:41:57Z joneum $

PORTNAME=	msgpack
PORTVERSION=	0.5.7
CATEGORIES=	devel

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Provides API for communicating with MessagePack serialization

LICENSE=	BSD3CLAUSE

USES=		php:pecl
IGNORE_WITH_PHP=70 71 72 73

.include <bsd.port.mk>
