# Created by: John Chen <johnpupu@gmail.com>
# $FreeBSD: head/devel/pecl-msgpack0/Makefile 456296 2017-12-14 13:57:28Z tz $

PORTNAME=	msgpack
PORTVERSION=	0.5.7
CATEGORIES=	devel
PKGNAMESUFFIX=	0

MAINTAINER=	johnpupu@gmail.com
COMMENT=	Provides API for communicating with MessagePack serialization

LICENSE=	BSD3CLAUSE

USES=		php:pecl
IGNORE_WITH_PHP=70 71 72

.include <bsd.port.mk>
