# $FreeBSD: head/multimedia/gstreamer1-plugins-openh264/Makefile 446388 2017-07-22 11:35:44Z kwm $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	GStreamer (openh264) plugin

GST_PLUGIN=	openh264
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
