# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-show/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	show
PORTVERSION=	0.6
PORTREVISION=	10
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	'Show' instances for Lambdabot

LICENSE=	GPLv2

USE_CABAL=	syb

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
