# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-show/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	show
PORTVERSION=	0.6
PORTREVISION=	8
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	'Show' instances for Lambdabot

LICENSE=	GPLv2

USE_CABAL=	syb

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
