# Created by: Tom Judge <tj@FreeBSD.org>
# $FreeBSD: head/devel/p5-MooseX-ArrayRef/Makefile 484353 2018-11-06 21:13:54Z rene $

PORTNAME=	MooseX-ArrayRef
PORTVERSION=	0.005
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Moose blessed array references

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Moose>=2.00:devel/p5-Moose

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
