# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/security/pear-Auth_SASL2/Makefile 485144 2018-11-17 17:30:29Z sunpoet $

PORTNAME=	Auth_SASL2
PORTVERSION=	0.2.0
CATEGORIES=	security pear

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Abstraction of various SASL mechanism responses

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	${PEAR_PKGNAMEPREFIX}Auth>=0:security/pear-Auth@${PHP_FLAVOR}

USES=		pear

NO_ARCH=	yes

.include <bsd.port.mk>
