# Created by: Carlo Strub
# $FreeBSD: head/devel/bzr-colo/Makefile 415839 2016-05-25 15:43:34Z mat $

PORTNAME=	bzr-colo
PORTVERSION=	0.4.0
PORTREVISION=	1
CATEGORIES=	devel
MASTER_SITES=	https://launchpadlibrarian.net/91504187/ \
		http://www.c-s.li/ports/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Plugin for bzr to support colocated branches

LICENSE=	GPLv2

BUILD_DEPENDS=	bzr:devel/bzr
RUN_DEPENDS=	bzr:devel/bzr

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
