# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/www/php70-opcache/Makefile 422569 2016-09-21 15:43:47Z tz $

CATEGORIES=	www

MASTERDIR=	${.CURDIR}/../../lang/php70

PKGNAMESUFFIX=	-opcache

USES=	php:zend

.include "${MASTERDIR}/Makefile"
