# $FreeBSD: head/sysutils/u-boot-sinovoip-bpi-m3/Makefile 455629 2017-12-05 21:51:11Z kevans $

MAINTAINER=	uboot@FreeBSD.org
MASTERDIR=	${.CURDIR}/../u-boot-master

MODEL=		sinovoip-bpi-m3
BOARD_CONFIG=	Sinovoip_BPI_M3_defconfig
FAMILY=		allwinner

.include "${MASTERDIR}/Makefile"
