# Created by: Ben Woods <woodsb02@FreeBSD.org>
# $FreeBSD: head/devel/py3-pluggy/Makefile 443060 2017-06-10 02:32:08Z woodsb02 $

MASTERDIR=	${.CURDIR}/../py-pluggy

TEST_DEPENDS=	${PYTHON_PKGNAMEPREFIX}pytest>0:devel/py3-pytest

USES=		python:3.3+

.include "${MASTERDIR}/Makefile"
