# $FreeBSD: head/x11-drivers/xf86-video-chips/Makefile 476013 2018-07-31 18:41:30Z zeising $

PORTNAME=	xf86-video-chips
PORTVERSION=	1.2.7
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org chips display driver

XORG_CAT=	driver

.include <bsd.port.mk>
