# Created by: Yuri Victorovich <yuri@rawbw.com>
# $FreeBSD: head/audio/py-hsaudiotag/Makefile 462307 2018-02-19 11:10:43Z antoine $

PORTNAME=	hsaudiotag
PORTVERSION=	1.1.1
PORTREVISION=	1
CATEGORIES=	audio python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	yuri@rawbw.com
COMMENT=	Read metdata (tags) of mp3, mp4, wma, ogg, flac and aiff files

LICENSE=	BSD3CLAUSE

USES=		python:2.7
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
