# Created by: Yuri Victorovich <yuri@rawbw.com>
# $FreeBSD: head/audio/py-hsaudiotag/Makefile 440240 2017-05-06 07:39:30Z miwi $

PORTNAME=	hsaudiotag
PORTVERSION=	1.1.1
CATEGORIES=	audio python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	yuri@rawbw.com
COMMENT=	Read metdata (tags) of mp3, mp4, wma, ogg, flac and aiff files

LICENSE=	BSD3CLAUSE

USES=		python:2
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
