# Created by: Simon Barner <barner@in.tum.de>
# $FreeBSD: head/mail/p5-Mail-RFC822-Address/Makefile 487663 2018-12-17 09:00:15Z amdmi3 $

PORTNAME=	Mail-RFC822-Address
PORTVERSION=	0.3
PORTREVISION=	1
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module to validate RFC822 conformance of email addresses

LICENSE=	MIT

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

INSTALL_TARGET=	pure_site_install

.include <bsd.port.mk>
