# $FreeBSD: head/net/hs-network-info/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	network-info
PORTVERSION=	0.2.0.8
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Access the local computer's basic network configuration

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
