# $FreeBSD: head/science/py-qspin/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	qspin
DISTVERSION=	0.1.8
PORTREVISION=	1
CATEGORIES=	science
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	yuri@FreeBSD.org
COMMENT=	Learn quantum spin and entanglement

LICENSE=	GPLv3

RUN_DEPENDS=	${PYNUMPY}

USES=		python
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
