# Created by: Mikhail T. <michael@fun-box.ru>
# $FreeBSD: head/www/rubygem-davclient/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	davclient
PORTVERSION=	0.0.8
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Command line WebDAV client and Ruby library

LICENSE=	GPLv2

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

PLIST_FILES=	bin/dav

.include <bsd.port.mk>
