# $FreeBSD: head/graphics/gstreamer1-plugins-gdkpixbuf/Makefile 405242 2016-01-04 14:21:56Z kwm $

PORTREVISION=	0
CATEGORIES=	graphics
PKGNAMESUFFIX=	1-plugins-gdkpixbuf

COMMENT=	GStreamer image decoder/overlay plugin

GST_PLUGIN=	gdk_pixbuf
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
