# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-metaid/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	metaid
PORTVERSION=	1.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby metaprogramming helpers

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
