# Created by: Daichi GOTO <daichi@FreeBSD.org>
# $FreeBSD: head/devel/py-gyp/Makefile 415345 2016-05-16 17:43:22Z hrs $

PORTNAME=	gyp
PORTVERSION=	20160504
CATEGORIES=	devel python
MASTER_SITES=	LOCAL/hrs
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	${PORTNAME}-e679e688ba6db12336b79650c27fcf8a5ed21e60

MAINTAINER=	hrs@FreeBSD.org
COMMENT=	Build System That Generates Other Build Systems

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python:2
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
