# Created by: Jille Timmermans <jille@quis.cx>
# $FreeBSD: head/devel/pecl-ncurses/Makefile 486751 2018-12-06 11:22:12Z rene $

PORTNAME=	ncurses
PORTVERSION=	1.0.2
PORTREVISION=	1
CATEGORIES=	devel pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PECL extension for ncurses

DEPRECATED=	Works only with EOL php 5.6
EXPIRATION_DATE=	2018-12-30

LICENSE=	PHP301

USES=		php:pecl,cli ncurses
IGNORE_WITH_PHP=71 72 73

.include <bsd.port.mk>
