# $FreeBSD: head/security/pinentry-gnome3/Makefile 409822 2016-02-29 18:35:00Z rakuco $

PORTNAME=	pinentry
PORTREVISION=	0

COMMENT=	GNOME 3 version of the GnuPG password dialog

PINENTRY_GUI=	gnome3

MASTERDIR=	${.CURDIR}/../pinentry

.include "${MASTERDIR}/Makefile"
