# $FreeBSD: head/misc/kde4-l10n-bs/Makefile 449969 2017-09-16 16:52:48Z tcberner $

PORTNAME=	kde-l10n
PORTVERSION=	${KDE4_VERSION}
PORTREVISION=	2
CATEGORIES=	misc kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Bosnian messages and documentation for KDE SC 4

KDE4_L10N=	bs

.include "${.CURDIR}/../kde4-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
