# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: head/textproc/py-Chameleon/Makefile 482376 2018-10-18 19:56:02Z sunpoet $

PORTNAME=	Chameleon
PORTVERSION=	3.5
CATEGORIES=	textproc www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	python@FreeBSD.org
COMMENT=	Fast HTML/XML Template Compiler

LICENSE=	BSD4CLAUSE

USES=		python
USE_PYTHON=	autoplist concurrent distutils

NO_ARCH=	yes

.include <bsd.port.mk>
