# Created by: Zhen REN <bg1tpt@gmail.com>
# $FreeBSD: head/net/pear-File_Bittorrent2/Makefile 443275 2017-06-11 07:41:03Z sunpoet $

PORTNAME=	File_Bittorrent2
DISTVERSION=	1.3.1
CATEGORIES=	net pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Decode and Encode data in Bittorrent format

USES=		pear

.include <bsd.port.mk>
