# $FreeBSD: head/net/rubygem-omniauth-github/Makefile 441593 2017-05-24 13:03:59Z sunpoet $

PORTNAME=	omniauth-github
PORTVERSION=	1.3.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Official OmniAuth strategy for GitHub

LICENSE=	MIT

RUN_DEPENDS=	rubygem-omniauth>=1.5:security/rubygem-omniauth \
		rubygem-omniauth-oauth2>=1.4.0:net/rubygem-omniauth-oauth2

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
