# Created by: Nick Hilliard <nick@foobar.org>
# $FreeBSD: head/devel/pear-Structures_DataGrid_Renderer_XUL/Makefile 443236 2017-06-11 07:36:52Z sunpoet $

PORTNAME=	Structures_DataGrid_Renderer_XUL
PORTVERSION=	0.1.3
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	XUL Renderer for pear-Structures_DataGrid

RUN_DEPENDS=	${PEARDIR}/Structures/DataGrid.php:devel/pear-Structures_DataGrid \
		${PEARDIR}/XML/Util.php:devel/pear-XML_Util

USES=		pear

.include <bsd.port.mk>
