# Created by: jyyou@cs.nctu.edu.tw
# $FreeBSD: head/databases/hs-mysql/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	mysql
PORTVERSION=	0.1.5
PORTREVISION=	1
CATEGORIES=	databases haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Low-level MySQL client library

LICENSE=	BSD3CLAUSE

USES=		mysql ssl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
