# $FreeBSD: head/comms/pear-Horde_ActiveSync/Makefile 483477 2018-10-30 11:58:47Z joneum $

PORTNAME=	Horde_ActiveSync
DISTVERSION=	2.39.4
CATEGORIES=	comms www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde ActiveSync Server Library

USES=	horde
USE_PHP=	ctype
USE_HORDE_RUN=	Horde_Compress \
		Horde_Date \
		Horde_Exception \
		Horde_Icalendar \
		Horde_Mapi \
		Horde_Mime \
		Horde_Stream \
		Horde_Support \
		Horde_Util

.include <bsd.port.mk>
