# $FreeBSD: head/devel/hs-asn1-parse/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	asn1-parse
PORTVERSION=	0.9.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple monadic parser for ASN1 stream types

LICENSE=	BSD3CLAUSE

USE_CABAL=	asn1-encoding>=0.9 asn1-types>=0.3 mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
