# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: head/sysutils/pear-File_Find/Makefile 443325 2017-06-11 07:45:17Z sunpoet $

PORTNAME=	File_Find
PORTVERSION=	1.3.3
CATEGORIES=	sysutils www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR class that facilitates the search of filesystems

LICENSE=	PHP301

USES=		pear

.include <bsd.port.mk>
