# $FreeBSD: head/textproc/hs-HStringTemplate/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	HStringTemplate
PORTVERSION=	0.8.6
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	StringTemplate implementation in Haskell

LICENSE=	BSD3CLAUSE

USE_CABAL=	blaze-builder mtl old-locale parsec syb text void

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
