# $FreeBSD: head/textproc/hs-HStringTemplate/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	HStringTemplate
PORTVERSION=	0.8.7
PORTREVISION=	2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	StringTemplate implementation in Haskell

LICENSE=	BSD3CLAUSE

USE_CABAL=	blaze-builder mtl old-locale syb void

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
