# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: head/textproc/p5-XML-Atom-Filter/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	XML-Atom-Filter
PORTVERSION=	0.07
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Easy creation of command line Atom processing tools

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-XML-Atom>=0:textproc/p5-XML-Atom

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
