# Created by: Palle Girgensohn <girgen@partitur.se>
# $FreeBSD: head/databases/postgresql94-pltcl/Makefile 423057 2016-10-01 13:05:01Z antoine $

WANT_PGSQL_VER=	9.4

.include "${.CURDIR}/../postgresql96-pltcl/Makefile"
