# $FreeBSD: head/devel/py-epdb/Makefile 438314 2017-04-11 21:00:00Z swills $

PORTNAME=	epdb
PORTVERSION=	0.15.1
DISTVERSIONPREFIX=	${PORTNAME}-
CATEGORIES=	devel python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	swills@FreeBSD.org
COMMENT=	Enhanced Python Debugger

USES=		python
USE_GITHUB=	yes
USE_PYTHON=	autoplist distutils

GH_ACCOUNT=	sassoftware

.include <bsd.port.mk>
