# $FreeBSD: head/x11/xwd/Makefile 469540 2018-05-10 13:37:50Z zeising $

PORTNAME=	xwd
PORTVERSION=	1.0.7
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Dump an image of an X window

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	x11 xkbfile

PLIST_FILES=	bin/xwd man/man1/xwd.1.gz

.include <bsd.port.mk>
