# $FreeBSD: head/devel/kf5-kunitconversion/Makefile 488341 2018-12-25 20:25:39Z tcberner $

PORTNAME=	kunitconversion
DISTVERSION=	${KDE_FRAMEWORKS_VERSION}
CATEGORIES=	devel kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KF5 library for unit conversion

USES=		cmake compiler:c++11-lib gettext kde:5 pkgconfig qt:5 tar:xz
USE_KDE=	ecm i18n
USE_QT=		buildtools_build core network qmake_build xml

.include <bsd.port.mk>
