# $FreeBSD: head/devel/kf5-kunitconversion/Makefile 475857 2018-07-29 22:18:44Z gerald $

PORTNAME=	kunitconversion
DISTVERSION=	${KDE_FRAMEWORKS_VERSION}
PORTREVISION=	1
CATEGORIES=	devel kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KF5 library for unit conversion

USES=		cmake:outsource compiler:c++11-lib gettext kde:5 pkgconfig qt:5 tar:xz
USE_KDE=	ecm i18n
USE_QT=		buildtools_build core network qmake_build xml

.include <bsd.port.mk>
