# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: head/textproc/es-aspell/Makefile 438338 2017-04-12 09:09:47Z mat $

PORTNAME=	${DICT}-aspell
SPELLVERSION=	6-es-1.11-2
PORTEPOCH=	1
CATEGORIES=	textproc spanish

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Spanish dictionary

DICT=	 	es

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
