# $FreeBSD: head/devel/elixir-gen_state_machine/Makefile 478023 2018-08-25 11:29:32Z olgeni $

PORTNAME=	gen_state_machine
PORTVERSION=	2.0.3
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	erlang@FreeBSD.org
COMMENT=	Idiomatic Elixir wrapper for gen_statem in OTP 19

LICENSE=	APACHE20

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	antipax

MIX_REWRITE=	yes

.include <bsd.port.mk>
