# $FreeBSD: head/devel/py3-verboselogs/Makefile 447007 2017-08-01 05:09:51Z araujo $

MASTERDIR=	${.CURDIR}/../py-verboselogs

PORTSCOUT=	ignore:1

USES=		python:3.3+

.include "${MASTERDIR}/Makefile"
