# Created by: Boris Samorodov <bsam@FreeBSD.org>
# $FreeBSD: head/devel/es-eric6/Makefile 458671 2018-01-10 18:39:31Z dbn $

CATEGORIES=	devel python
I18N_LANG=	es

.include "${.CURDIR}/../../devel/eric6/Makefile.inc"
