# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD: head/devel/rubygem-akismet/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	akismet
PORTVERSION=	2.0.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby client for the Akismet API

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
