# $FreeBSD: head/news/suck-cnews/Makefile 409731 2016-02-28 09:32:43Z dinoex $

CATEGORIES=	news

MAINTAINER=	dinoex@FreeBSD.org

MASTERDIR=	${.CURDIR}/../suck

OPTIONS_DEFAULT=	SSL CNEWS

.include "${MASTERDIR}/Makefile"
