# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: head/net/py-speedtest-cli/Makefile 446455 2017-07-23 07:19:06Z nivit $

PORTNAME=	speedtest-cli
PORTVERSION=	1.0.6
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Command line interface for testing internet bandwidth

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
