# $FreeBSD: head/sysutils/uefi-edk2-bhyve-csm/Makefile 465522 2018-03-25 15:28:36Z novel $

PKGNAMESUFFIX=	-csm

COMMENT=	UEFI-EDK2 firmware for bhyve with CSM

MASTERDIR=	${.CURDIR}/../uefi-edk2-bhyve

WITH_CSM=	yes

.include "${MASTERDIR}/Makefile"
