# Created by: chinsan <chinsan.tw@gmail.com>
# $FreeBSD: head/www/p5-WWW-Baseball-NPB/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	WWW-Baseball-NPB
PORTVERSION=	0.03
PORTREVISION=	1
CATEGORIES=	www japanese perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Fetches Japanese baseball games information

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-libwww>=0:www/p5-libwww

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
