# $FreeBSD: head/japanese/p5-Lingua-JA-Regular-Unicode/Makefile 412347 2016-04-01 14:08:37Z mat $

PORTNAME=	Lingua-JA-Regular-Unicode
PORTVERSION=	0.12
PORTREVISION=	1
CATEGORIES=	japanese perl5
MASTER_SITES=	CPAN

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to convert Japanese chars

TEST_DEPENDS=	\
	p5-Text-TestBase>0:textproc/p5-Text-TestBase

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.pre.mk>

PKGNAMEPREFIX:=	${PKGNAMEPREFIX}p5-

.include <bsd.port.post.mk>
