# $FreeBSD: head/sysutils/cfengine/Makefile 482115 2018-10-14 20:59:30Z cy $

VERSIONS=		22 32 33 34 35 36 37 38 39 310 311 312
CFENGINE_VERSION?=	312

MASTERDIR=		${.CURDIR}/../cfengine${CFENGINE_VERSION}

.include "${MASTERDIR}/Makefile"
