# $FreeBSD: head/sysutils/cfengine/Makefile 465140 2018-03-21 01:32:10Z cy $

VERSIONS=		22 32 33 34 35 36 37 38 39 310 311
CFENGINE_VERSION?=	311

MASTERDIR=		${.CURDIR}/../cfengine${CFENGINE_VERSION}

.include "${MASTERDIR}/Makefile"
