# $FreeBSD: head/sysutils/cfengine/Makefile 447760 2017-08-11 13:59:57Z cy $

VERSIONS=		22 32 33 34 35 36 37 38 39 310 311
CFENGINE_VERSION?=	310

MASTERDIR=		${.CURDIR}/../cfengine${CFENGINE_VERSION}

.include "${MASTERDIR}/Makefile"
