# $FreeBSD: head/devel/elixir-hex/Makefile 448862 2017-08-28 12:38:37Z olgeni $

PORTNAME=	hex
PORTVERSION=	0.17.0
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Package manager for the Erlang VM

LICENSE=	APACHE20

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	hexpm

.include <bsd.port.mk>
