# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: head/www/py-python-digitalocean/Makefile 412351 2016-04-01 14:33:55Z mat $

PORTNAME=	python-digitalocean
PORTVERSION=	1.8
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	API to manage digitalocean.com droplets

LICENSE=	GPLv3

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}requests>=2.0.0:www/py-requests

USES=	python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
