# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/textproc/php70-xmlreader/Makefile 422569 2016-09-21 15:43:47Z tz $

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php70

PKGNAMESUFFIX=	-xmlreader

.include "${MASTERDIR}/Makefile"
