# Created by: Shin-ya MURAKAMI <murashin@gfd-dennou.org>
# $FreeBSD: head/devel/rubygem-slop3/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	slop
PORTVERSION=	3.6.0
CATEGORIES=	devel ruby
MASTER_SITES=	RG
PKGNAMESUFFIX=	3

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Simple DSL for gathering options and parsing the command line

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
