# Created by: will
# $FreeBSD: head/devel/p5-Tie-IxHash/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Tie-IxHash
PORTVERSION=	1.23
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module implementing ordered in-memory associative arrays

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
