# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: head/games/p5-Algorithm-Pair-Swiss/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Algorithm-Pair-Swiss
PORTVERSION=	0.14
PORTREVISION=	1
CATEGORIES=	games perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Generate unique pairings for tournaments

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-Exception>=0:devel/p5-Test-Exception

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
