# Created by: Kozlov Sergey <kozlov.sergey.404@gmail.com>
# $FreeBSD: head/www/py-django-tinymce/Makefile 455210 2017-11-30 15:50:30Z mat $

PORTNAME=	django-tinymce
PORTVERSION=	2.0.4
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	kozlov.sergey.404@gmail.com
COMMENT=	Django application to use TinyMCE editor

LICENSE=	MIT

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}django18>=0:www/py-django18@${FLAVOR}

NO_ARCH=	yes

USES=		python zip
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
