# Created by: vanilla
# $FreeBSD: head/mail/p5-Mail-Procmail/Makefile 412348 2016-04-01 14:16:16Z mat $

PORTNAME=	Mail-Procmail
PORTVERSION=	1.08
PORTREVISION=	2
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module provides procmail-like tools

RUN_DEPENDS= 	p5-LockFile-Simple>=0:devel/p5-LockFile-Simple \
		p5-Mail-Tools>=0:mail/p5-Mail-Tools

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
