# $FreeBSD: head/devel/hs-cereal/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	cereal
PORTVERSION=	0.5.5.0
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Binary serialization library

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
