# Created by: Dennis Herrmann <adox@mcx2.org>
# $FreeBSD: head/devel/rubygem-trollop/Makefile 480137 2018-09-20 00:22:56Z sunpoet $

PORTNAME=	trollop
PORTVERSION=	2.9.9
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Commandline option parser for Ruby that gets out of your way

LICENSE=	MIT

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
