# $FreeBSD: head/devel/hs-word8/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	word8
PORTVERSION=	0.1.2
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Word8 library

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
