# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: head/science/p5-Chemistry-Elements/Makefile 447509 2017-08-07 18:51:48Z sunpoet $

PORTNAME=	Chemistry-Elements
PORTVERSION=	1.072
CATEGORIES=	science perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension for working with Chemical Elements

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
