# Created by: ijliao
# $FreeBSD: head/devel/alf/Makefile 393429 2015-08-02 15:03:19Z tijl $

PORTNAME=	alf
PORTVERSION=	0.1
PORTREVISION=	3
CATEGORIES=	devel python
MASTER_SITES=	SF/largefiles/largefiles/${PORTNAME}-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Abstract Large File

USES=		libtool python
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
