# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-rlang/Makefile 464241 2018-03-12 09:39:55Z tota $

PORTNAME=	rlang
PORTVERSION=	0.2.0
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Functions for Base Types and Core R and 'Tidyverse' Features

LICENSE=	GPLv3

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
