# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-rlang/Makefile 494535 2019-03-04 01:54:29Z wen $

PORTNAME=	rlang
PORTVERSION=	0.3.1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Functions for Base Types and Core R and 'Tidyverse' Features

LICENSE=	GPLv3

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
