# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: head/devel/nuitka/Makefile 468793 2018-05-01 19:50:39Z sunpoet $

PORTNAME=	nuitka
PORTVERSION=	0.5.30
CATEGORIES=	devel python
MASTER_SITES=	https://nuitka.net/releases/
DISTNAME=	Nuitka-${PORTVERSION}

MAINTAINER=	python@FreeBSD.org
COMMENT=	Compatible and efficient Python compiler

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		python tar:bzip2
USE_PYTHON=	autoplist concurrent distutils optsuffix

.include <bsd.port.mk>
