# Created by: Joe Horn <joehorn@gmail.com>
# $FreeBSD: head/devel/pear-channel-twig/Makefile 441000 2017-05-16 13:37:51Z joneum $

PORTNAME=	twig
PORTVERSION=	20140108
CATEGORIES=	devel www pear
MASTER_SITES=	#

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	pear.twig-project.org

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.channel.mk"
.include <bsd.port.post.mk>
