# Created by: Joe Horn <joehorn@gmail.com>
# $FreeBSD: head/devel/pear-channel-twig/Makefile 463949 2018-03-09 09:26:52Z mat $

PORTNAME=	twig
PORTVERSION=	20140108
CATEGORIES=	devel www pear
MASTER_SITES=	#

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	pear.twig-project.org

.include "${.CURDIR}/../../devel/pear/bsd.pear.channel.mk"
.include <bsd.port.mk>
