# $FreeBSD: head/emulators/virtualbox-ose-additions-nox11/Makefile 423391 2016-10-05 21:09:51Z jkim $

PKGNAMESUFFIX=	-additions-nox11

OPTIONS_EXCLUDE=	DEBUG OPENGL X11

MASTERDIR=	${.CURDIR}/../virtualbox-ose-additions

.include "${MASTERDIR}/Makefile"
