# $FreeBSD: head/emulators/virtualbox-ose-additions-nox11/Makefile 482272 2018-10-17 06:49:30Z jkim $

PKGNAMESUFFIX=	-additions-nox11

OPTIONS_EXCLUDE=	DEBUG OPENGL X11

MASTERDIR=	${.CURDIR}/../virtualbox-ose-additions

.include "${MASTERDIR}/Makefile"
