# Created by: clsung@dragon2.net
# $FreeBSD: head/textproc/p5-RTF-Tokenizer/Makefile 420179 2016-08-14 07:31:49Z wen $

PORTNAME=	RTF-Tokenizer
PORTVERSION=	1.20
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module for reading RTF files

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
