# Created by: Dmitry Marakasov <amdmi3@FreeBSD.org>
# $FreeBSD: head/devel/py-rubymarshal/Makefile 440613 2017-05-11 06:02:25Z antoine $

PORTNAME=	rubymarshal
PORTVERSION=	1.0.3
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	amdmi3@FreeBSD.org
COMMENT=	Read and write Ruby-marshalled data

LICENSE=	WTFPL
LICENSE_FILE=	${WRKSRC}/LICENSE

USES?=		python
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
