# Created by: Frederic Culot <frederic@culot.org>
# $FreeBSD: head/devel/p5-Devel-CheckLib/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Devel-CheckLib
PORTVERSION=	1.11
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Check that a library is available

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-IO-CaptureOutput>=1.08:devel/p5-IO-CaptureOutput

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
