# Created by: renchap@cocoa-x.com
# $FreeBSD: head/devel/rubygem-mixlib-log/Makefile 446976 2017-07-31 15:50:18Z sunpoet $

PORTNAME=	mixlib-log
PORTVERSION=	1.7.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	renchap@cocoa-x.com
COMMENT=	Provides a simple mixin for log functionality

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
