# $FreeBSD: head/devel/hs-async/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	async
PORTVERSION=	2.2.1
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Run IO operations asynchronously and wait for their results

LICENSE=	BSD3CLAUSE

USE_CABAL=	hashable

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
