# Created by: Samy Al Bahra <sbahra@kerneled.org>
# $FreeBSD: head/devel/hs-Stream/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	Stream
PORTVERSION=	0.4.7.2
PORTREVISION=	5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Library for manipulating infinite lists

LICENSE=	BSD3CLAUSE

USE_CABAL=	lazysmallcheck>=0.3 QuickCheck>=2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
