# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/science/py-pygeodesy/Makefile 486956 2018-12-08 15:43:07Z sunpoet $

PORTNAME=	pygeodesy
PORTVERSION=	18.11.12
CATEGORIES=	science python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	PyGeodesy-${PORTVERSION}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Pure Python geodesy tools

LICENSE=	MIT

USES=		python zip
USE_PYTHON=	autoplist concurrent distutils

USE_LOCALE=	en_US.UTF-8

.include <bsd.port.mk>
