# $FreeBSD: head/devel/hs-enclosed-exceptions/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	enclosed-exceptions
PORTVERSION=	1.0.2
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Catching all exceptions from within an enclosed computation

LICENSE=	MIT

USE_CABAL=	async>=2.0 lifted-base>=0.2 monad-control transformers-base

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
