# Created by: Yuri Victorovich <yuri@rawbw.com>
# $FreeBSD: head/math/py-pyvtk/Makefile 415525 2016-05-19 18:58:51Z pi $

PORTNAME=	pyVTK
PORTVERSION=	0.5.18
CATEGORIES=	math python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	PyVTK-${PORTVERSION}

MAINTAINER=	yuri@rawbw.com
COMMENT=	Tools for manipulating VTK files in Python

LICENSE=	GPLv2

USES=		python
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
