# $FreeBSD: head/devel/hs-GenericPretty/Makefile 476202 2018-08-01 21:53:17Z arrowd $

PORTNAME=	GenericPretty
DISTVERSION=	1.2.2
CATEGORIES=	devel haskell

MAINTAINER=	hello@blubee.me
COMMENT=	Pretty printing for Generic value

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
