# Created by: osa
# $FreeBSD: head/devel/lua-rds-parser/Makefile 470802 2018-05-24 18:49:17Z pi $

PORTNAME=	lua-rds-parser
PORTVERSION=	0.06
DISTVERSIONPREFIX=	v
CATEGORIES=	devel

MAINTAINER=	arcade@b1t.name
COMMENT=	Resty-DBD-Stream (RDS) parser for Lua written in C

LICENSE=	BSD2CLAUSE

USES=		lua:51
USE_GITHUB=	yes
GH_ACCOUNT=	openresty

PLIST_FILES=	${LUA_MODLIBDIR}/rds/parser.so

.include <bsd.port.mk>
