# $FreeBSD: head/security/hs-cryptohash-conduit/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	cryptohash-conduit
PORTVERSION=	0.1.1
PORTREVISION=	5
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cryptohash conduit

LICENSE=	BSD3CLAUSE

USE_CABAL=	conduit conduit-extra cryptohash resourcet

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
