# $FreeBSD: head/security/hs-cryptohash-conduit/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	cryptohash-conduit
PORTVERSION=	0.1.1
PORTREVISION=	7
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cryptohash conduit

LICENSE=	BSD3CLAUSE

USE_CABAL=	conduit conduit-extra cryptohash resourcet

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
