# $FreeBSD: head/devel/py-calendar/Makefile 438214 2017-04-10 21:49:02Z mat $

PORTNAME=		calendar
PORTVERSION=	2.1
CATEGORIES=		devel python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	axel.rau@chaos1.de
COMMENT=	Library for iCalendar/vCard data

LICENSE=	APACHE20

USE_GITHUB=	yes
GH_ACCOUNT=	apple
GH_PROJECT=	ccs-pycalendar
GH_TAGNAME=	b0118d4

USES=		python:2.7
USE_PYTHON=	distutils autoplist
NO_ARCH=yes

.include <bsd.port.mk>
