# $FreeBSD: head/x11-drivers/xf86-video-sunffb/Makefile 441503 2017-05-23 05:03:14Z rezny $

PORTNAME=	xf86-video-sunffb
PORTVERSION=	1.2.2
PORTREVISION=	8
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org sunffb display driver

USE_GL=		gl
XORG_CAT=	driver

ONLY_FOR_ARCHS=	sparc64

.include <bsd.port.mk>
