# $FreeBSD: head/x11-drivers/xf86-video-sunffb/Makefile 476013 2018-07-31 18:41:30Z zeising $

PORTNAME=	xf86-video-sunffb
PORTVERSION=	1.2.2
PORTREVISION=	9
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org sunffb display driver

USE_GL=		gl
XORG_CAT=	driver

ONLY_FOR_ARCHS=	sparc64

.include <bsd.port.mk>
