# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/converters/php56-mbstring/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	converters

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-mbstring

.include "${MASTERDIR}/Makefile"
