# Created by: Raphael Kubo da Costa <kubito@gmail.com>
# $FreeBSD: head/audio/gstreamer-plugins-gme/Makefile 428152 2016-12-08 19:52:19Z tijl $

PORTREVISION=	2
CATEGORIES=	audio

COMMENT=	Gstreamer game-music-emu (libgme) frontend

GST_PLUGIN=	gme

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
