# $FreeBSD: head/security/rubygem-rex-registry/Makefile 441380 2017-05-21 11:19:44Z antoine $

PORTNAME=	rex-registry
PORTVERSION=	0.1.3
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Ruby Exploitation(Rex) library for parsing offline registry files

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
