# Created by: Olivier Duchateau
# $FreeBSD: head/x11-themes/adwaita-qt4/Makefile 442026 2017-05-29 16:30:38Z tcberner $

PORTREVISION=	0

MASTERDIR=	${.CURDIR:H:H}/x11-themes/adwaita-common

OPTIONS_SLAVE=	QT4

.include "${MASTERDIR}/Makefile"
