# $FreeBSD: head/multimedia/rubygem-av/Makefile 438204 2017-04-10 19:40:29Z jrm $

PORTNAME=	av
PORTVERSION=	0.9.0
CATEGORIES=	multimedia rubygems
MASTER_SITES=	RG

MAINTAINER=	jrm@FreeBSD.org
COMMENT=	Programmable Ruby interface for FFMPEG/Libav

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

RUN_DEPENDS=	rubygem-cocaine>=0.5.3:devel/rubygem-cocaine

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
