# $FreeBSD$

PORTNAME=	snmp_passpersist
DISTVERSION=	2.0.0
DISTVERSIONPREFIX=	v
CATEGORIES=	net-mgmt python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	james@french.id.au
COMMENT=	Python client library for Net-SNMP pass persist backend

LICENSE=	GPLv3

RUN_DEPENDS=	net-snmp>=0:net-mgmt/net-snmp

USE_GITHUB=	yes
GH_ACCOUNT=	nagius

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
