# Created by: will
# $FreeBSD: head/mail/p5-Mail-MailStats/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	MailStats
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module to detect newer messages in procmail-generated mailboxes

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-AppConfig>=0:devel/p5-AppConfig

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
