# $FreeBSD: head/devel/hs-unordered-containers/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	unordered-containers
PORTVERSION=	0.2.9.0
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Efficient hashing-based container types

LICENSE=	BSD3CLAUSE

USE_CABAL=	hashable>=1.0.1.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
