# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/net/php70-xmlrpc/Makefile 422569 2016-09-21 15:43:47Z tz $

CATEGORIES=	net

MASTERDIR=	${.CURDIR}/../../lang/php70

PKGNAMESUFFIX=	-xmlrpc

.include "${MASTERDIR}/Makefile"
