# Created by: Florent Thoumie <flz@freebsd.org>
# $FreeBSD: head/x11-drivers/xf86-video-scfb/Makefile 479538 2018-09-11 18:34:27Z zeising $

PORTNAME=	xf86-video-scfb
PORTVERSION=	0.0.4
PORTREVISION=	7
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org syscons display driver

USE_GITHUB=     yes
GH_ACCOUNT=     rayddteam

XORG_CAT=	driver

.include <bsd.port.mk>
