# $FreeBSD: head/devel/i386-gcc/Makefile 475319 2018-07-25 17:46:55Z jhb $

PKGNAMEPREFIX=	i386-
PLIST=	${.CURDIR}/pkg-plist

MASTERDIR=	${.CURDIR}/../powerpc64-gcc
FREEBSD_EXTENSION=	yes

.include "${MASTERDIR}/Makefile"
