# Created by: Mathieu Arnold <mat@FreeBSD.org>
# $FreeBSD: head/devel/p5-DateTime-Functions/Makefile 418076 2016-07-05 09:08:55Z mat $

PORTNAME=	DateTime-Functions
PORTVERSION=	0.13
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Procedural interface to DateTime functions

BUILD_DEPENDS=	p5-DateTime>=0:devel/p5-DateTime
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
