# Created by: Scott Sanders <scott@jssjr.com>
# $FreeBSD: head/textproc/rubygem-fast_xs/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	fast_xs
PORTVERSION=	0.8.0
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Systems integration framework. Expander

LICENSE=	MIT

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
