# $FreeBSD: head/devel/hs-exceptions/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	exceptions
PORTVERSION=	0.8.3
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Extensible optionally-pure exceptions

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl stm transformers-compat

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
