# $FreeBSD: head/devel/hs-easy-file/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	easy-file
PORTVERSION=	0.2.1
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cross-platform File handling

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
