# $FreeBSD: head/devel/hs-easy-file/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	easy-file
PORTVERSION=	0.2.1
PORTREVISION=	5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cross-platform File handling

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
