# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/science/R-cran-e1071/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	e1071
DISTVERSION=	1.6-8
PORTREVISION=	1
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Misc Functions of the Department of Statistics (e1071), TU Wien

LICENSE=	GPLv2

USES=	cran:auto-plist,compiles

.include <bsd.port.mk>
