# $FreeBSD: head/net/hs-bsb-http-chunked/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	bsb-http-chunked
PORTVERSION=	0.0.0.4
PORTREVISION=	1
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Chunked HTTP transfer encoding for bytestring builders

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
