# $FreeBSD: head/net/hs-bsb-http-chunked/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	bsb-http-chunked
PORTVERSION=	0.0.0.2
PORTREVISION=	1
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Chunked HTTP transfer encoding for bytestring builders

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
