# $FreeBSD: head/devel/hs-setlocale/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	setlocale
PORTVERSION=	1.0.0.6
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell setlocale package

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
