# $FreeBSD: head/devel/hs-setlocale/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	setlocale
PORTVERSION=	1.0.0.5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell setlocale package

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
