# $FreeBSD: head/devel/hs-setlocale/Makefile 429826 2016-12-28 21:00:27Z tcberner $

PORTNAME=	setlocale
PORTVERSION=	1.0.0.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell setlocale package

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
