# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-iterators/Makefile 464573 2018-03-15 08:08:38Z tota $

PORTNAME=	iterators
PORTVERSION=	1.0.9
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Iterator construct for R

LICENSE=	APACHE20

USES=	cran:auto-plist

.include <bsd.port.mk>
