# $FreeBSD: head/devel/erlang-poolboy/Makefile 479406 2018-09-10 13:14:50Z mat $

PORTNAME=	poolboy
PORTVERSION=	1.5.2
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	erlang@FreeBSD.org
COMMENT=	Pooling library for Erlang

LICENSE=	ISCL

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	devinus

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
