# Created by: Alexander Logvinov <avl@FreeBSD.org>
# $FreeBSD: head/russian/rubygem-russian/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	russian
PORTVERSION=	0.6.0
CATEGORIES=	russian devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Russian language support for Ruby and Rails, based on I18n library

LICENSE=	MIT

RUN_DEPENDS=	rubygem-i18n>=0.5.0:devel/rubygem-i18n

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
