# $FreeBSD: head/deskutils/tasksh/Makefile 445286 2017-07-07 23:32:00Z swills $

PORTNAME=	tasksh
PORTVERSION=	1.2.0
CATEGORIES=	deskutils
MASTER_SITES=	http://taskwarrior.org/download/

MAINTAINER=	swills@FreeBSD.org
COMMENT=	Shell command that wraps Taskwarrior commands

USES=		cmake readline

.include <bsd.port.mk>
