# $FreeBSD: head/devel/py-python-engineio/Makefile 442367 2017-06-02 10:32:38Z mmokhi $

PORTNAME=	python-engineio
PORTVERSION=	1.5.3
CATEGORIES=	devel python net
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	mmokhi@FreeBSD.org
COMMENT=	Python Engine.IO server

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
