# $FreeBSD: head/databases/rubygem-activerecord-import/Makefile 440662 2017-05-11 21:02:46Z sunpoet $

PORTNAME=	activerecord-import
PORTVERSION=	0.18.3
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Bulk import many records into an ActiveRecord DB

LICENSE=	BSD2CLAUSE RUBY
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-activerecord4>=3.2:databases/rubygem-activerecord4

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
