# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-chron/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	chron
DISTVERSION=	2.3-43
PORTREVISION=	9
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	R package for creating objects which can handle dates and times

LICENSE=	GPLv2

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
