# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: head/textproc/py-pygments/Makefile 438660 2017-04-16 13:38:25Z nivit $

PORTNAME=	pygments
PORTVERSION=	2.2.0
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Pygments-${PORTVERSION}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Syntax highlighter written in Python

LICENSE=	BSD2CLAUSE

USES?=		python
USE_PYTHON=	distutils concurrent autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
