# $FreeBSD: head/audio/gstreamer1-plugins-a52dec/Makefile 405242 2016-01-04 14:21:56Z kwm $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	GStreamer ATSC A/52 stream aka AC-3 (dvd audio) plugin

GST_PLUGIN=	a52dec
DIST=		ugly

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
