# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/devel/p5-Exporter-Easy/Makefile 476632 2018-08-08 09:08:00Z amdmi3 $

PORTNAME=	Exporter-Easy
PORTVERSION=	0.18
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Takes the drudgery out of Exporting symbols

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
