# $FreeBSD: head/security/hs-monadcryptorandom/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	monadcryptorandom
PORTVERSION=	0.7.1
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monad for using CryptoRandomGen

LICENSE=	BSD3CLAUSE

USE_CABAL=	crypto-api exceptions tagged transformers-compat

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
