# $FreeBSD: head/textproc/hs-hxt-unicode/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	hxt-unicode
PORTVERSION=	9.0.2.4
PORTREVISION=	2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unicode en-/decoding functions for utf8, iso-latin-* and other encodings

LICENSE=	MIT

USE_CABAL=	hxt-charproperties>=9.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
