# $FreeBSD: head/textproc/hs-hxt-unicode/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	hxt-unicode
PORTVERSION=	9.0.2.4
PORTREVISION=	4
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unicode en-/decoding functions for utf8, iso-latin-* and other encodings

LICENSE=	MIT

USE_CABAL=	hxt-charproperties>=9.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
