# $FreeBSD: head/devel/hs-js-flot/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	js-flot
PORTVERSION=	0.8.3
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Obtain minified flot code

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
