# $FreeBSD: head/devel/hs-js-flot/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	js-flot
PORTVERSION=	0.8.3
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Obtain minified flot code

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
