# $FreeBSD: head/ports-mgmt/port-index-uniquifier/Makefile 424147 2016-10-18 04:52:14Z cperciva $

PORTNAME=	port-index-uniquifier
PORTVERSION=	${OSVERSION}
CATEGORIES=	ports-mgmt

MAINTAINER=	cperciva@FreeBSD.org
COMMENT=	Dummy port to ensure major versions have different INDEX files

USES=	metaport

.include <bsd.port.mk>
