# Created by: mat@FreeBSD.org
# $FreeBSD: head/net/rubygem-epp-client-base/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	epp-client-base
PORTVERSION=	0.15.1
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	mat@FreeBSD.org
COMMENT=	Extensible EPP client library

LICENSE=	MIT

RUN_DEPENDS=	rubygem-builder>=2.1.2:devel/rubygem-builder \
		rubygem-nokogiri>=1.4:textproc/rubygem-nokogiri

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
