# Created by: will
# $FreeBSD: head/security/p5-Crypt-CipherSaber/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Crypt-CipherSaber
PORTVERSION=	1.01
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module providing an OO interface to CipherSaber encryption

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-Warn>=0.30:devel/p5-Test-Warn

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
