# $FreeBSD: head/devel/hs-geniplate-mirror/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	geniplate-mirror
PORTVERSION=	0.7.6
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Use Template Haskell to generate Uniplate-like functions

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
