# $FreeBSD: head/devel/hs-geniplate-mirror/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	geniplate-mirror
PORTVERSION=	0.7.6
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Use Template Haskell to generate Uniplate-like functions

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
