# Created by: will
# $FreeBSD: head/astro/p5-Geo-METAR/Makefile 451691 2017-10-10 11:20:58Z sunpoet $

PORTNAME=	Geo-METAR
PORTVERSION=	1.15
PORTREVISION=	1
CATEGORIES=	astro geography perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module that processes METAR information from NOAA sources

LICENSE=	GPLv2+

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
