# $FreeBSD: head/devel/hs-th-reify-many/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	th-reify-many
PORTVERSION=	0.1.8
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Recurseively reify template haskell datatype info

LICENSE=	BSD3CLAUSE

USE_CABAL=	safe th-expand-syns

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
