# Created by: Mark Felder <feld@FreeBSD.org>
# $FreeBSD: head/www/redmine-graphs/Makefile 471175 2018-05-30 21:20:07Z feld $

PORTNAME=	graphs
PORTVERSION=	0.0.20170403
CATEGORIES=	www
PKGNAMEPREFIX=	redmine-

MAINTAINER=	feld@FreeBSD.org
COMMENT=	Additional Redmine graphs

LICENSE=	GPLv2+

NO_ARCH=	yes

USE_GITHUB=	yes
GH_ACCOUNT=	bradbeattie
GH_PROJECT=	redmine-graphs-plugin
GH_TAGNAME=	a625da4

REDMINE_PLUGIN_NAME=	redmine_${PORTNAME}

.include "${.CURDIR}/../../www/redmine/bsd.redmine.mk"
