# $FreeBSD: head/textproc/p5-YAML/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	YAML
PORTVERSION=	1.14
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	YAML implementation in Perl

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-YAML>=1.05:devel/p5-Test-YAML

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
