# Created by: asami
# $FreeBSD: head/astro/xphoon/Makefile 422433 2016-09-19 13:01:11Z amdmi3 $

PORTNAME=	xphoon
PORTVERSION=	20000613
CATEGORIES=	astro
MASTER_SITES=	SF

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Set the root window to the moon in its current phase

USES=		imake
USE_XORG=	x11 xext

PLIST_FILES=	bin/xphoon man/man1/xphoon.1.gz

.include <bsd.port.mk>
