# Created by: Dmitry Marakasov <amdmi3@FreeBSD.org>
# $FreeBSD: head/devel/py3-flake8-quotes/Makefile 433406 2017-02-05 13:55:45Z amdmi3 $

MASTERDIR=	${.CURDIR}/../py-flake8-quotes

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}flake8>=0:devel/py3-flake8

USES=		python:3

.include "${MASTERDIR}/Makefile"
