# $FreeBSD: head/sysutils/u-boot-pine64/Makefile 474544 2018-07-13 02:57:57Z linimon $

MASTERDIR=	${.CURDIR}/../u-boot-master

MODEL=		pine64
BOARD_CONFIG=	pine64_plus_defconfig
FAMILY=		allwinner64

.include "${MASTERDIR}/Makefile"
