# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libXv/Makefile 423473 2016-10-07 18:01:45Z kwm $

PORTNAME=	libXv
PORTVERSION=	1.0.11
PORTEPOCH=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Video Extension library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 xext xextproto videoproto:both xproto:both
USES+=	cpe
CPE_PRODUCT=	libxv
CPE_VENDOR=	x

.include <bsd.port.mk>
