# $FreeBSD: head/devel/hs-haddock-api/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	haddock-api
PORTVERSION=	2.17.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Documentation-generation tool for Haskell libraries

LICENSE=	BSD3CLAUSE

USE_CABAL=	ghc-paths haddock-library>=1.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
