# Created by: Robert Gogolok <gogo@cs.uni-sb.de>
# $FreeBSD: head/sysutils/rubygem-god/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	god
PORTVERSION=	0.13.7
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Monitoring framework written in Ruby

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_RUBY=	yes
USES=		gem

PLIST_FILES=	bin/god

.include <bsd.port.mk>
