# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/databases/rubygem-dbf/Makefile 493660 2019-02-23 09:52:29Z sunpoet $

PORTNAME=	dbf
PORTVERSION=	4.1.2
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Library for reading dBase, xBase, Clipper and FoxPro database files

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

PLIST_FILES=	bin/dbf

.include <bsd.port.mk>
