# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/databases/rubygem-dbf/Makefile 466736 2018-04-07 16:32:13Z sunpoet $

PORTNAME=	dbf
PORTVERSION=	3.1.1
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Library for reading dBase, xBase, Clipper and FoxPro database files

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

PLIST_FILES=	bin/dbf

.include <bsd.port.mk>
