# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/math/p5-Math-Polygon/Makefile 429849 2016-12-29 01:34:36Z wen $

PORTNAME=	Math-Polygon
PORTVERSION=	1.05
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Class for Maintaining Polygon Data

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
