# $FreeBSD: head/devel/py-aenum/Makefile 490549 2019-01-17 12:13:38Z swills $

PORTNAME=	aenum
PORTVERSION=	2.1.2
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	a.wolk@fudosecurity.com
COMMENT=	Advanced Enumerations compatible with stdlib Enum

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/aenum/LICENSE

USES=		python:3.4+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
