# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: head/sysutils/rubygem-sys-filesystem/Makefile 460102 2018-01-27 10:24:56Z sunpoet $

PORTNAME=	sys-filesystem
PORTVERSION=	1.1.9
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby interface for getting filesystem information

LICENSE=	ART20

RUN_DEPENDS=	rubygem-ffi>=0:devel/rubygem-ffi

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
