# $FreeBSD: head/devel/elixir-libring/Makefile 451748 2017-10-11 12:55:21Z olgeni $

PORTNAME=	libring
DISTVERSION=	1.2.1
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Fast consistent hash ring implementation in Elixir

LICENSE=	MIT

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	bitwalker

MIX_REWRITE=	yes

.include <bsd.port.mk>
