# $FreeBSD: head/devel/elixir-libring/Makefile 439135 2017-04-22 07:34:50Z olgeni $

PORTNAME=	libring
DISTVERSION=	1.0.2
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Fast consistent hash ring implementation in Elixir

LICENSE=	MIT

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	bitwalker

MIX_REWRITE=	yes

.include <bsd.port.mk>
