# $FreeBSD: head/devel/elixir-libring/Makefile 476721 2018-08-09 06:38:46Z olgeni $

PORTNAME=	libring
DISTVERSION=	1.3.2
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	erlang@FreeBSD.org
COMMENT=	Fast consistent hash ring implementation in Elixir

LICENSE=	MIT

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	bitwalker

MIX_REWRITE=	yes

.include <bsd.port.mk>
