# Created by: Bill Fumerola <billf@mu.org>
# $FreeBSD: head/net/tshark/Makefile 494666 2019-03-05 01:02:00Z marcus $

PORTNAME=	tshark
CATEGORIES=	net ipv6

MASTERDIR=	${.CURDIR}/../wireshark

OPTIONS_EXCLUDE=	GUI

.include "${MASTERDIR}/Makefile"
