# $FreeBSD: head/graphics/hs-dia-base/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	dia-base
PORTVERSION=	0.1.1.4
PORTREVISION=	5
CATEGORIES=	graphics haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	EDSL for teaching Haskell with diagrams - data types

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
