# $FreeBSD: head/graphics/hs-dia-base/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	dia-base
PORTVERSION=	0.1.1.4
CATEGORIES=	graphics haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	EDSL for teaching Haskell with diagrams - data types

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
