# $FreeBSD: head/graphics/hs-dia-base/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	dia-base
PORTVERSION=	0.1.1.4
PORTREVISION=	3
CATEGORIES=	graphics haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	EDSL for teaching Haskell with diagrams - data types

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
