# $FreeBSD: head/devel/pear-Horde_Util/Makefile 417904 2016-07-01 22:05:48Z mm $
PORTNAME=	Horde_Util
PORTVERSION=	2.5.8
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Utility Libraries

USES=	horde
USE_PHP=	dom

.include <bsd.port.mk>
