# Created by: John Chen <johnpupu@gmail.com>
# $FreeBSD: head/devel/pecl-msgpack/Makefile 485511 2018-11-21 12:41:57Z joneum $

PORTNAME=	msgpack
PORTVERSION=	2.0.2
CATEGORIES=	devel

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Provides API for communicating with MessagePack serialization

LICENSE=	BSD3CLAUSE

USES=		php:pecl
IGNORE_WITH_PHP=	56 73

.include <bsd.port.mk>
