# Created by: John Chen <johnpupu@gmail.com>
# $FreeBSD: head/devel/pecl-msgpack/Makefile 481878 2018-10-12 06:23:47Z antoine $

PORTNAME=	msgpack
PORTVERSION=	2.0.2
CATEGORIES=	devel

MAINTAINER=	johnpupu@gmail.com
COMMENT=	Provides API for communicating with MessagePack serialization

LICENSE=	BSD3CLAUSE

USES=		php:pecl
IGNORE_WITH_PHP=	56 73

.include <bsd.port.mk>
