# Created by: Dmitry Sivachenko <dima@Chg.RU>
# $FreeBSD: head/misc/p5-I18N-LangTags/Makefile 471657 2018-06-04 18:10:22Z sunpoet $

PORTNAME=	I18N-LangTags
PORTVERSION=	0.35
PORTREVISION=	2
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Functions for dealing with RFC-1766-style language tags

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
