# Created by: Li-Wen Hsu <lwhsu@lwhsu.org>
# $FreeBSD: head/devel/py-pp/Makefile 462307 2018-02-19 11:10:43Z antoine $

PORTNAME=	pp
PORTVERSION=	1.6.6
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	http://www.parallelpython.com/downloads/pp/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	Parallel python execution server

LICENSE=	BSD3CLAUSE

USES=		python:2.7
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
