# $FreeBSD: head/graphics/php72-gd/Makefile 475984 2018-07-31 08:47:33Z tz $

CATEGORIES=	graphics

PORTREVISION=  1

MASTERDIR=	${.CURDIR}/../../lang/php72

PKGNAMESUFFIX=	-gd

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"

LIB_DEPENDS+=	libgd.so:graphics/gd
