# $FreeBSD: head/converters/php71-mbstring/Makefile 447218 2017-08-03 14:54:24Z tz $

CATEGORIES=	converters

MASTERDIR=	${.CURDIR}/../../lang/php71

PKGNAMESUFFIX=	-mbstring

.include "${MASTERDIR}/Makefile"
