# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/textproc/rubygem-loggability/Makefile 433613 2017-02-07 20:33:31Z sunpoet $

PORTNAME=	loggability
PORTVERSION=	0.14.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Composable logging system built on the standard Logger library

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
