# $FreeBSD: head/devel/hs-quickcheck-io/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	quickcheck-io
PORTVERSION=	0.2.0
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Use HUnit assertions as QuickCheck properties

LICENSE=	MIT

USE_CABAL=	HUnit>=1.2.5 QuickCheck>=2.5.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
