# Created by: Max Khon <fjoe@FreeBSD.org>
# $FreeBSD: head/devel/p5-Term-Animation/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	Term-Animation
PORTVERSION=	2.6
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	fjoe@FreeBSD.org
COMMENT=	ASCII sprite animation framework

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Curses>=0:devel/p5-Curses

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
