# Created by: Max Khon <fjoe@FreeBSD.org>
# $FreeBSD: head/devel/p5-Term-Animation/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	Term-Animation
PORTVERSION=	2.6
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	fjoe@FreeBSD.org
COMMENT=	ASCII sprite animation framework

BUILD_DEPENDS=	p5-Curses>=0:devel/p5-Curses
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
