# $FreeBSD: head/databases/rubygem-pghero/Makefile 447652 2017-08-09 19:36:12Z sunpoet $

PORTNAME=	pghero
PORTVERSION=	2.0.0
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Performance dashboard for Postgres

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

RUN_DEPENDS=	rubygem-activerecord4>=0:databases/rubygem-activerecord4

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
