# $FreeBSD: head/devel/p5-Signal-Mask/Makefile 473016 2018-06-22 06:28:47Z krion $

PORTNAME=	Signal-Mask
PORTVERSION=	0.008
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bokutin@bokut.in
COMMENT=	Signal masks made easy

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	p5-IPC-Signal>=0:devel/p5-IPC-Signal

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
