# Created by: Ultima <ultima1252@gmail.com>
# $FreeBSD: head/archivers/py-rcssmin/Makefile 443845 2017-06-18 18:09:16Z dbn $

PORTNAME=	rcssmin
PORTVERSION=	1.0.6
PORTREVISION=	1
CATEGORIES=	archivers python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ultima1252@gmail.com
COMMENT=	Fast CSS minifier for Python

LICENSE=	APACHE20

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
