# Created by: Ultima <ultima1252@gmail.com>
# $FreeBSD: head/archivers/py-rcssmin/Makefile 413464 2016-04-16 17:27:05Z pi $

PORTNAME=	rcssmin
PORTVERSION=	1.0.6
CATEGORIES=	archivers python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ultima1252@gmail.com
COMMENT=	Fast CSS minifier for Python

LICENSE=	APACHE20

USES=		python
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
