# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: head/devel/py-Breve/Makefile 472732 2018-06-19 01:22:32Z yuri $

PORTNAME=	Breve
PORTVERSION=	1.3.0
PORTREVISION=	3
CATEGORIES=	devel python
MASTER_SITES=	http://breve.twisty-industries.com/downloads/ \
		LOCAL/nivit/${PORTNAME}
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Python s-expression style template engine

LICENSE=	MIT

USES=		python:2.7
USE_PYTHON=	distutils concurrent autoplist

.include <bsd.port.mk>
