# Created by: Ben Woods <woodsb02@FreeBSD.org>
# $FreeBSD: head/sysutils/py3-ptyprocess/Makefile 442848 2017-06-07 15:39:37Z woodsb02 $

MASTERDIR=	${.CURDIR}/../py-ptyprocess

USES=		python:3.3+

.include "${MASTERDIR}/Makefile"
