# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/devel/py-jsonlib2/Makefile 455210 2017-11-30 15:50:30Z mat $

PORTNAME=	jsonlib2
PORTVERSION=	1.5.2
PORTREVSION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	JSON Serializer/Deserializer for Python

USES=		python:2.7
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
