# Created by: Michael Moll <kvedulv at kvedulv.de>
# $FreeBSD: head/sysutils/rubygem-yell/Makefile 429838 2016-12-28 23:14:12Z swills $

PORTNAME=	yell
PORTVERSION=	2.0.7
CATEGORIES=	sysutils ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Extensible logging library for Ruby

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
