# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/converters/R-cran-rjson/Makefile 470524 2018-05-21 09:25:32Z tota $

PORTNAME=	rjson
PORTVERSION=	0.2.19
CATEGORIES=	converters
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	JSON for R

LICENSE=	GPLv2

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
