# $FreeBSD: head/devel/hs-strict/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	strict
PORTVERSION=	0.3.2
PORTREVISION=	13
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Strict data types and String IO

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
