# $FreeBSD: head/x11-toolkits/rubygem-uh/Makefile 452678 2017-10-22 19:10:22Z ultima $

PORTNAME=	uh
PORTVERSION=	2.1.0
CATEGORIES=	x11-toolkits rubygems
MASTER_SITES=	RG

MAINTAINER=	tj+freebsd_ports@a13.fr
COMMENT=	Xlib ruby toolkit

LICENSE=	BSD3CLAUSE

USE_RUBY=	yes
USES=		gem
USE_XORG=	x11 xinerama

.include <bsd.port.mk>
