# Created by: Jason Portwood <jason@iac.net>
# $FreeBSD: head/devel/p5-OLE-Storage_Lite/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	OLE-Storage_Lite
PORTVERSION=	0.19
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module for OLE document interface

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-IO-stringy>=0:devel/p5-IO-stringy

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
