# Created by: mat
# $FreeBSD: head/devel/p5-DateTime-Fiscal-Year/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	DateTime-Fiscal-Year
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Calculate the day or week of the Fiscal Year with an arbitrary start date

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-DateTime>=0:devel/p5-DateTime

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
