# Created by: mat
# $FreeBSD: head/devel/p5-DateTime-Fiscal-Year/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	DateTime-Fiscal-Year
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Calculate the day or week of the Fiscal Year with an arbitrary start date

BUILD_DEPENDS=	p5-DateTime>=0:devel/p5-DateTime
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
