# Created by: Mario Sergio Fujikawa Ferreira <lioux@FreeBSD.org>
# $FreeBSD: head/x11-themes/kde-icons-dark-glass/Makefile 446387 2017-07-22 11:01:38Z antoine $

PORTNAME=	dark-glass
PORTVERSION=	2.72
MASTER_SITES=	http://www.mentalrey.it/icon_set/ \
		ftp://ftp.itsinternet.net/pub/FreeBSD/ports/distfiles/KDE/ \
		ftp://simant.ru/Distrib/misc/Look/kde/Icon%20Themes/
DISTNAME=	DarkGlass_Reworked

COMMENT=	KDE Dark Glass iconset

BROKEN=		does not fetch
DEPRECATED=	Broken for more than 6 months
EXPIRATION_DATE=	2017-08-23

PLIST_FILE_PATTERN_EXTRA=	-v "^\./(buildset|README)"

.include "${.CURDIR}/../kde-icons-noia/Makefile.icons"
