# Created by: chinsan <chinsan.tw@gmail.com>
# $FreeBSD: head/math/pecl-stats/Makefile 440442 2017-05-08 17:21:49Z dbaio $

PORTNAME=	stats
PORTVERSION=	1.0.5
CATEGORIES=	math textproc pear

MAINTAINER=	dbaio@FreeBSD.org
COMMENT=	PECL extension with routines for statistical computation

LICENSE=	PHP301
LICENSE_FILE=	${WRKSRC}/LICENSE

PORTSCOUT=	limit:^1.*

USES=		php:pecl
IGNORE_WITH_PHP=	70 71

.include <bsd.port.mk>
