# $FreeBSD: head/devel/hs-base-unicode-symbols/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	base-unicode-symbols
PORTVERSION=	0.2.2.4
PORTREVISION=	12
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unicode alternatives for common functions and operators

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
