# $FreeBSD: head/devel/hs-base-unicode-symbols/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	base-unicode-symbols
PORTVERSION=	0.2.2.4
PORTREVISION=	11
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unicode alternatives for common functions and operators

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
