# $FreeBSD: head/sysutils/py-azure-cli-profile/Makefile 491291 2019-01-26 13:28:29Z dbaio $

PORTNAME=	azure-cli-profile
PORTVERSION=	2.1.2
CATEGORIES=	sysutils python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dbaio@FreeBSD.org
COMMENT=	Microsoft Azure Command-Line Tools Profile Command Module

LICENSE=	MIT

USES=		azurepy python
USE_PYTHON=	autoplist concurrent distutils

NO_ARCH=	yes

.include <bsd.port.mk>
