# $FreeBSD: head/sysutils/dsblogoutmgr/Makefile 459806 2018-01-23 23:48:42Z tobik $

PORTNAME=	dsblogoutmgr
PORTVERSION=	1.2
CATEGORIES=	sysutils
MASTER_SITES=	http://freeshell.de/~mk/download/

MAINTAINER=	mk@nic-nac-project.org
COMMENT=	Graphical logout manager

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		tar:tgz qmake

USE_GL=		gl
USE_QT5=	buildtools_build core gui linguisttools_build widgets

.include <bsd.port.mk>
