# $FreeBSD: head/net/gstreamer1-plugins-libmms/Makefile 405242 2016-01-04 14:21:56Z kwm $

PORTREVISION=	0
CATEGORIES=	net

COMMENT=	GStreamer mms:// and mmsh:// plugin

GST_PLUGIN=	libmms
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
