# Created by: vanilla
# $FreeBSD: head/x11-toolkits/p5-Tk-GBARR/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	Tk-GBARR
PORTVERSION=	2.08
PORTREVISION=	4
CATEGORIES=	x11-toolkits perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Some collection of Tk Widgets

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Tk>=0:x11-toolkits/p5-Tk

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
