# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/databases/R-cran-DBI/Makefile 440043 2017-05-03 21:04:12Z tota $

PORTNAME=	DBI
DISTVERSION=	0.6-1
CATEGORIES=	databases
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	R Database Interface

LICENSE=	LGPL20+

USES=	cran:auto-plist

.include <bsd.port.mk>
