# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/science/R-cran-DCluster/Makefile 412349 2016-04-01 14:25:16Z mat $

PORTNAME=	DCluster
DISTVERSION=	0.2-7
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Functions for the detection of spatial clusters of diseases

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

RUN_DEPENDS=	R-cran-spdep>0:math/R-cran-spdep

USES=	cran:auto-plist

.include <bsd.port.mk>
