# $FreeBSD: head/www/rubygem-best_in_place/Makefile 447386 2017-08-05 03:25:17Z jrm $

PORTNAME=	best_in_place
PORTVERSION=	3.1.1
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	jQuery script to edit fields by clicking on them

LICENSE=	MIT

RUN_DEPENDS=	rubygem-actionpack4>0:www/rubygem-actionpack4 \
		rubygem-railties4>0:www/rubygem-railties4

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
