# Created by: Cheng-Lung Sung <clsung@dragon2.net>
# $FreeBSD: head/devel/p5-Class-XPath/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Class-XPath
PORTVERSION=	1.4
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Base class to add xpath matching to object trees

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
