# $FreeBSD: head/www/rubygem-addressable23/Makefile 461935 2018-02-15 16:59:19Z tz $

PORTNAME=	addressable
PORTVERSION=	2.3.8
CATEGORIES=	www devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	23

MAINTAINER=	idefix@fechner.net
COMMENT=	Replacement for the URI implementation

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

PORTSCOUT=	limit:^2\.3

NO_ARCH=	yes
USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
