# $FreeBSD: head/databases/rubygem-arel-helpers/Makefile 441092 2017-05-17 17:14:55Z sunpoet $

PORTNAME=	arel-helpers
PORTVERSION=	2.4.0
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Helpers to construct database queries with ActiveRecord and Arel

LICENSE=	MIT

RUN_DEPENDS=	rubygem-activerecord4>=3.1.0:databases/rubygem-activerecord4

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
