# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/textproc/rubygem-elasticsearch-xpack/Makefile 476032 2018-07-31 23:43:11Z sunpoet $

PORTNAME=	elasticsearch-xpack
PORTVERSION=	6.1.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Ruby integrations for the X-Pack extensions for Elasticsearch

LICENSE=	APACHE20

RUN_DEPENDS=	rubygem-elasticsearch-api>=6:textproc/rubygem-elasticsearch-api

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
