# Created by: chinsan
# $FreeBSD$

PORTNAME=	uploadprogress
DISTVERSIONPREFIX=	${PORTNAME}-
DISTVERSION=	1.1.3
CATEGORIES=	devel pear

MAINTAINER=	daniel@morante.net
COMMENT=	Provides track progress of a file upload

LICENSE=	PHP301

USES=		php:pecl

USE_GITHUB=	yes
GH_ACCOUNT=	php
GH_PROJECT=	pecl-php-${PORTNAME}

CONFIGURE_ARGS=	--enable-uploadprogress

.include <bsd.port.mk>
