# Created by: chinsan
# $FreeBSD: head/devel/pecl-uploadprogress/Makefile 456296 2017-12-14 13:57:28Z tz $

PORTNAME=	uploadprogress
PORTVERSION=	1.0.3
PORTREVISION=	1
CATEGORIES=	devel pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Provides track progress of a file upload

LICENSE=	PHP301

USES=		php:pecl
IGNORE_WITH_PHP=	70 71 72

CONFIGURE_ARGS=	--enable-uploadprogress

.include <bsd.port.mk>
