# $FreeBSD: head/sysutils/msiklm/files/Makefile.bsd 469448 2018-05-09 14:05:22Z jhale $

BINDIR=		${PREFIX}/bin
PROG=		msiklm
SRCS=		src/main.c src/msiklm.c 
CFLAGS+=	-Wall -W -D_REENTRANT
LDADD=		-lhidapi
MK_MAN=		no

.include <bsd.prog.mk>
