# Created by: Hye-Shik Chang
# $FreeBSD: head/devel/py-pyrepl/Makefile 458928 2018-01-13 12:27:45Z amdmi3 $

PORTNAME=	pyrepl
PORTVERSION=	0.8.4
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Replacement for readline and interactive environment for Python

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
