# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/math/p5-Math-Utils/Makefile 447851 2017-08-12 18:58:48Z sunpoet $

PORTNAME=	Math-Utils
PORTVERSION=	1.11
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Useful mathematical functions not in Perl

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_PERL5=	modbuild
USES=		dos2unix perl5

.include <bsd.port.mk>
