# $FreeBSD: head/devel/rubygem-binding_of_caller/Makefile 458656 2018-01-10 16:03:12Z swills $

PORTNAME=	binding_of_caller
PORTVERSION=	0.8.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Retrieve the binding of a methods caller

LICENSE=	MIT

RUN_DEPENDS=	rubygem-debug_inspector>=0.0.1:devel/rubygem-debug_inspector

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
