# $FreeBSD: head/devel/rubygem-binding_of_caller/Makefile 452662 2017-10-22 16:10:18Z sunpoet $

PORTNAME=	binding_of_caller
PORTVERSION=	0.7.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Retrieve the binding of a methods caller

LICENSE=	MIT

RUN_DEPENDS=	rubygem-debug_inspector>=0.0.1:devel/rubygem-debug_inspector

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
