# Created by: Felippe de Meirelles Motta <lippemail@gmail.com>
# $FreeBSD: head/devel/p5-Exception-Class-TryCatch/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	Exception-Class-TryCatch
PORTVERSION=	1.13
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Syntactic try/catch sugar for use with Exception::Class

LICENSE=	APACHE20

BUILD_DEPENDS+=	p5-Exception-Class>=0:devel/p5-Exception-Class
RUN_DEPENDS+=	p5-Exception-Class>=0:devel/p5-Exception-Class

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
