# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/databases/rubygem-redis-namespace/Makefile 434296 2017-02-17 16:48:57Z sunpoet $

PORTNAME=	redis-namespace
PORTVERSION=	1.5.3
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby client class for Redis with namespace support

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-redis>=3.0.4:databases/rubygem-redis

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
