# $FreeBSD: head/misc/R-cran-xfun/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	xfun
PORTVERSION=	0.4
PORTREVISION=	1
CATEGORIES=	misc
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Miscellaneous Functions by Yihui Xie

LICENSE=	MIT

USES=		cran:auto-plist

.include <bsd.port.mk>
