# Created by: Dominic Fandrey <kamikaze@bsdforen.de>
# $FreeBSD: head/games/ioquake3-server/Makefile 430166 2016-12-31 21:07:50Z sunpoet $

PORTNAME=	ioquake3
PKGNAMESUFFIX=	-server

MAINTAINER=	kami@FreeBSD.org
COMMENT=	Ioquake3 dedicated server

LICENSE=	GPLv2

MASTERDIR=	${.CURDIR}/../${PORTNAME}

IOQ3=		SERVER GAMELIBS

.include "${MASTERDIR}/Makefile"
