# $FreeBSD: head/devel/hs-bits-atomic/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	bits-atomic
PORTVERSION=	0.1.3
PORTREVISION=	13
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Atomic bit operations on memory locations

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
