# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: head/textproc/p5-Lingua-EN-Syllable/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Lingua-EN-Syllable
PORTVERSION=	0.251
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Routine for estimating syllable count in words

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
