# Created by: Brooks Davis
# $FreeBSD: head/emulators/qemu-cheri128/Makefile 437229 2017-03-29 20:10:08Z brooks $

PKGNAMESUFFIX=	-cheri128

COMMENT=	QEMU emulator with CHERI CPU support (128-bit)

MASTERDIR=	${.CURDIR}/../qemu-cheri

EXTRA_CFLAGS=	-DCHERI_128

.include <${MASTERDIR}/Makefile>
