# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: head/converters/p5-Text-Unidecode/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Text-Unidecode
PORTVERSION=	1.30
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Text::Unidecode -- US-ASCII transliterations of Unicode text

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
