# $FreeBSD: head/sysutils/u-boot-cubieboard2/Makefile 472714 2018-06-18 20:22:13Z linimon $

MASTERDIR=	${.CURDIR}/../u-boot-master

MODEL=		cubieboard2
BOARD_CONFIG=	Cubieboard2_defconfig
FAMILY=		allwinner

.include "${MASTERDIR}/Makefile"
