# Created by: Pedro Giffuni
# $FreeBSD: head/math/R-cran-truncnorm/Makefile 443845 2017-06-18 18:09:16Z dbn $

PORTNAME=	truncnorm
PORTREVISION=	1
DISTVERSION=	1.0-7
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	pfg@FreeBSD.org
COMMENT=	Truncated normal distribution

LICENSE=	GPLv2

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
