# Created by: Pedro Giffuni
# $FreeBSD: head/math/R-cran-truncnorm/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	truncnorm
PORTREVISION=	3
DISTVERSION=	1.0-8
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	pfg@FreeBSD.org
COMMENT=	Truncated normal distribution

LICENSE=	GPLv2

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
