# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/print/hs-hscolour/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	hscolour
PORTVERSION=	${HSCOLOUR_VERSION}
PORTREVISION=	2
PORTEPOCH=	1
CATEGORIES=	print haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Colourise Haskell code

LICENSE=	GPLv2

EXECUTABLE=	HsColour

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
