# Created by: tcberner
# $FreeBSD: head/x11-toolkits/kf5-kitemviews/Makefile 449591 2017-09-10 20:55:38Z gerald $

PORTNAME=	kitemviews
PORTVERSION=	${KDE_FRAMEWORKS_VERSION}
PORTREVISION=	1
CATEGORIES=	x11-toolkits kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KF5 widget addons for Qt Model/View

USES=		cmake:outsource compiler:c++11-lib kde:5 tar:xz
USE_KDE=	ecm
USE_QT5=	buildtools_build core gui linguisttools qmake_build \
		testlib widgets

.include <bsd.port.mk>
