# $FreeBSD: head/devel/hs-data-default-instances-base/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	data-default-instances-base
PORTVERSION=	0.1.0.1
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Default instances for types in base

LICENSE=	BSD3CLAUSE

USE_CABAL=	data-default-class

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
