# Created by: Ed Schouten <ed@FreeBSD.org>
# $FreeBSD: head/devel/argdata/Makefile 444111 2017-06-22 12:37:35Z ed $

PORTNAME=	argdata
PORTVERSION=	0.4
DISTVERSIONPREFIX=v
CATEGORIES=	devel

MAINTAINER=	ed@FreeBSD.org
COMMENT=	Binary serialisation format inspired by YAML, MessagePack and nvlists

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	NuxiNL

USES=		cmake compiler:c11 tar:xz
USE_LDCONFIG=	yes

.include <bsd.port.mk>
