# Created by: Jose Alonso Cardenas Marquez <acm@FreeBSD.org>
# $FreeBSD: head/emulators/mupen64plus-video-rice/Makefile 441503 2017-05-23 05:03:14Z rezny $

PORTREVISION=	1
PKGNAMESUFFIX=	-video-rice

COMMENT=	The rice graphics plugin for Mupen64plus

USE_GL=		yes

MASTERDIR=	${.CURDIR}/../mupen64plus-core

OPTIONS_DEFINE=	#

.include "${MASTERDIR}/Makefile"
