# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: head/www/p5-CGI-Ajax/Makefile 437950 2017-04-07 18:50:22Z lth $

PORTNAME=	CGI-Ajax
PORTVERSION=	0.707
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Module for writing AJAX/DHTML-based web apps

BUILD_DEPENDS=	p5-Class-Accessor>=0:devel/p5-Class-Accessor
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
