# Created by: Andrew T. Bennett <potatosaladx@gmail.com>
# $FreeBSD: head/www/mod_xsendfile/Makefile 464189 2018-03-11 17:38:45Z brnrd $

PORTNAME=	mod_xsendfile
PORTVERSION=	0.12
PORTREVISION=	3
CATEGORIES=	www
MASTER_SITES=	https://tn123.org/mod_xsendfile/ GHC

MAINTAINER=	potatosaladx@gmail.com
COMMENT=	Apache2 module that processes X-SENDFILE headers

LICENSE=	APACHE20

USES=		apache:2.2+
AP_FAST_BUILD=	yes
AP_GENPLIST=	yes
USE_GITHUB=	yes
GH_ACCOUNT=	potatosalad

.include <bsd.port.mk>
