# $FreeBSD: head/math/p5-Number-Misc/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Number-Misc
PORTVERSION=	1.2
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension of handy utilities for numbers

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	YES

.include <bsd.port.mk>
