# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/lang/hs-brainfuck/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	brainfuck
PORTVERSION=	0.1.0.3
PORTREVISION=	2
CATEGORIES=	lang haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Brainfuck interpreter

LICENSE=	GPLv2

USE_CABAL=	mtl

EXECUTABLE=	bf

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
