# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/math/R-cran-VGAM/Makefile 494133 2019-02-28 07:38:36Z wen $

PORTNAME=	VGAM
DISTVERSION=	1.1-1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Vector Generalized Linear and Additive Models

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
