# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/math/R-cran-VGAM/Makefile 432020 2017-01-21 10:57:54Z wen $

PORTNAME=	VGAM
DISTVERSION=	1.0-3
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Vector Generalized Linear and Additive Models

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=	cran:auto-plist

.include <bsd.port.mk>
