# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/math/R-cran-VGAM/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	VGAM
DISTVERSION=	1.0-6
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Vector Generalized Linear and Additive Models

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
