# Created by: Michael Nottebrock <lofi@FreeBSD.org>
# $FreeBSD: head/graphics/poppler-utils/Makefile 430818 2017-01-07 18:15:08Z rakuco $

PORTREVISION=	1
PKGNAMESUFFIX=	-utils

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Poppler's xpdf-workalike command line utilities

MASTERDIR=	${.CURDIR}/../../graphics/poppler
SLAVEPORT=	utils
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
