# Created by: Rene Ladan <rene@FreeBSD.org>
# $FreeBSD: head/textproc/py-stemming/Makefile 490724 2019-01-19 16:48:20Z rene $

PORTNAME=	stemming
PORTVERSION=	1.0.1
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Algorithms for stemming

LICENSE=	PD

USES=		python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
