# Created by: Johann Visagie <wjv@FreeBSD.org>
# $FreeBSD: head/mail/exim-doc-postscript/Makefile 360749 2014-07-05 14:39:18Z vsevolod $

DOCFORMAT=	postscript
MASTERDIR=	${.CURDIR}/../exim-doc-html

.include "${MASTERDIR}/Makefile"
