# Created by: chinsan
# $FreeBSD: head/textproc/pecl-xslcache/Makefile 441000 2017-05-16 13:37:51Z joneum $

PORTNAME=	xslcache
PORTVERSION=	0.7.2
PORTREVISION=	1
CATEGORIES=	textproc pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Caches the parsed XSL stylesheet between sessions

LICENSE=	PHP301

USES=		php:pecl
USE_PHP=	dom:build xml:build xsl:build
IGNORE_WITH_PHP=	70

.include <bsd.port.mk>
