# Created by: Johannes Meixner <johannes@perceivon.net>
# $FreeBSD: head/textproc/rubygem-rubypants/Makefile 463137 2018-02-27 13:25:15Z sunpoet $

PORTNAME=	rubypants
PORTVERSION=	0.7.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Translates ASCII into smart typographic punctuation HTML entities

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
