# $FreeBSD: head/www/hs-cookie/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	cookie
PORTVERSION=	0.4.4
PORTREVISION=	2
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	HTTP cookie parsing and rendering

LICENSE=	BSD3CLAUSE

USE_CABAL=	blaze-builder data-default-class old-locale

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
