# $FreeBSD: head/www/hs-cookie/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	cookie
PORTVERSION=	0.4.4
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	HTTP cookie parsing and rendering

LICENSE=	BSD3CLAUSE

USE_CABAL=	blaze-builder data-default-class old-locale

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
