# $FreeBSD: head/www/hs-cookie/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	cookie
PORTVERSION=	0.4.2.1
PORTREVISION=	1
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	HTTP cookie parsing and rendering

LICENSE=	BSD3CLAUSE

USE_CABAL=	blaze-builder data-default-class old-locale text

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
