# $FreeBSD: head/devel/hs-utf8-light/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	utf8-light
PORTVERSION=	0.4.2
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unicode

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
