# $FreeBSD: head/devel/hs-utf8-light/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	utf8-light
PORTVERSION=	0.4.2
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unicode

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
