# $FreeBSD: head/devel/hs-utf8-light/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	utf8-light
PORTVERSION=	0.4.2
PORTREVISION=	5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unicode

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
