# $FreeBSD: head/security/hs-ed25519/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	ed25519
PORTVERSION=	0.0.5.0
PORTREVISION=	4
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A simple, fast, self-contained copy of the Ed25519 public-key signature system

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
