# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: head/devel/p5-IO-Capture/Makefile 437950 2017-04-07 18:50:22Z lth $

PORTNAME=	IO-Capture
PORTVERSION=	0.05
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Abstract Base Class to build modules to capture output

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
