# Created by: sumikawa
# $FreeBSD: head/japanese/jpilot/Makefile 464084 2018-03-10 17:46:04Z gerald $

MASTERDIR=	${.CURDIR}/../../palm/jpilot

PORTREVISION=	1
CATEGORIES=	japanese

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Desktop Organizer Software for the Palm Pilot (Japanized)

CONFLICTS=	jpilot-[0-9]*

CONFIGURE_ARGS=	--with-japanese

.include "${MASTERDIR}/Makefile"
