# Created by: sumikawa
# $FreeBSD: head/japanese/jpilot/Makefile 361849 2014-07-15 02:31:47Z vanilla $

MASTERDIR=	${.CURDIR}/../../palm/jpilot

CATEGORIES=	japanese

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Desktop Organizer Software for the Palm Pilot (Japanized)

CONFLICTS=	jpilot-[0-9]*

CONFIGURE_ARGS=	--with-japanese

.include "${MASTERDIR}/Makefile"
