# Created by: bf@FreeBSD.org
# $FreeBSD: head/math/xlapack/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	xlapack
PORTREVISION=	5

MAINTAINER=	fortran@FreeBSD.org
COMMENT=	Extended Precision LAPACK

XLAPACK_SLAVEPORT=	yes

MASTERDIR=	${.CURDIR}/../lapack

.include "${MASTERDIR}/Makefile"
