# Created by: Palle Girgensohn <girgen@partitur.se>
# $FreeBSD: head/databases/postgresql92-plperl/Makefile 417899 2016-07-01 17:45:51Z matthew $

WANT_PGSQL_VER=	9.2

.include "${.CURDIR}/../postgresql95-plperl/Makefile"
