# $FreeBSD: head/security/hs-crypto-numbers/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	crypto-numbers
PORTVERSION=	0.2.7
PORTREVISION=	3
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cryptographic numbers: functions and algorithms

LICENSE=	BSD3CLAUSE

USE_CABAL=	crypto-random>=0.0.0 vector

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
