# Created by: Johannes Meixner <johannes@perceivon.net>
# $FreeBSD: head/www/rubygem-semantic-ui-sass/Makefile 449296 2017-09-05 16:11:11Z sunpoet $

PORTNAME=	semantic-ui-sass
PORTVERSION=	2.2.12.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Semantic UI, converted to Sass and ready to drop into Rails & Compass

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

RUN_DEPENDS=	rubygem-sass>=3.2:textproc/rubygem-sass

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
