# Created by: Michael Moll <kvedulv at kvedulv.de>
# $FreeBSD: head/devel/rubygem-ice_nine/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	ice_nine
PORTVERSION=	0.11.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Deep freeze Ruby objects

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
