# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: head/graphics/p5-URI-GoogleChart/Makefile 479390 2018-09-10 11:16:59Z des $

PORTNAME=	URI-GoogleChart
PORTVERSION=	1.02
PORTREVISION=	1
CATEGORIES=	graphics www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Generate Google Chart URIs

BUILD_DEPENDS=	p5-URI>0:net/p5-URI
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
