# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-numDeriv/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	numDeriv
DISTVERSION=	2016.8-1
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Accurate Numerical Derivatives

LICENSE=	GPLv2

USES=		cran:auto-plist

.include <bsd.port.mk>
