# Created by: Toshiya Saitoh (<toshiya@saitoh.nu>)
# $FreeBSD: head/databases/pear-DB_Pager/Makefile 434346 2017-02-18 10:49:40Z miwi $

PORTNAME=	DB_Pager
PORTVERSION=	0.7.2
CATEGORIES=	databases www pear

MAINTAINER=	toshiya@saitoh.nu
COMMENT=	PEAR Database Abstraction Layer

LICENSE=	GPLv3

BUILD_DEPENDS=	${PEARDIR}/DB.php:databases/pear-DB
RUN_DEPENDS=	${PEARDIR}/DB.php:databases/pear-DB

USES=	pear

.include <bsd.port.mk>
