# $FreeBSD: head/devel/hs-temporary/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	temporary
PORTVERSION=	1.2.1
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Portable temporary file and directory support for Windows and Unix

LICENSE=	BSD3CLAUSE

USE_CABAL=	exceptions>=0.6

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
