# $FreeBSD: head/devel/hs-temporary/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	temporary
PORTVERSION=	1.2.1
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Portable temporary file and directory support for Windows and Unix

LICENSE=	BSD3CLAUSE

USE_CABAL=	exceptions>=0.6

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
