# $FreeBSD: head/net-mgmt/mdata-client/Makefile 454267 2017-11-15 19:31:55Z swills $

PORTNAME=	mdata-client
PORTVERSION=	20151001
CATEGORIES=	net-mgmt

MAINTAINER=	swills@FreeBSD.org
COMMENT=	Metadata tools for use within guests of the SmartOS

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	joyent

USES=		gmake

.include <bsd.port.mk>
