# $FreeBSD: head/devel/py-Dumper/Makefile 487539 2018-12-15 18:38:54Z pi $

PORTNAME=	Dumper
PORTVERSION=	1.1.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	pi@FreeBSD.org
COMMENT=	Conveniently print any Python datastructure

LICENSE=	PSFL

USES=		python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
