# Created by: Denis Pokataev <catone@cpan.org>
# $FreeBSD: head/textproc/p5-XML-Atom-Ext-OpenSearch/Makefile 412349 2016-04-01 14:25:16Z mat $

PORTNAME=	XML-Atom-Ext-OpenSearch
PORTVERSION=	0.03
PORTREVISION=	1
CATEGORIES=	textproc www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	XML::Atom extension for OpenSearch data

BUILD_DEPENDS=	p5-XML-Atom>=0:textproc/p5-XML-Atom
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
