# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-irlba/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	irlba
PORTVERSION=	2.3.2
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Fast partial SVD by implicitly-restarted Lanczos bidiagonalization

LICENSE=	GPLv3

USES=	cran:auto-plist,compiles

.include <bsd.port.mk>
