# $FreeBSD: head/security/rubygem-metasploit_payloads-mettle/Makefile 463236 2018-02-28 15:38:23Z antoine $

PORTNAME=	metasploit_payloads-mettle
PORTVERSION=	0.3.7
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Compiled binaries for Metasploit's next-gen Meterpreter

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes
STRIP=
USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
