# $FreeBSD: head/security/rubygem-metasploit_payloads-mettle/Makefile 470513 2018-05-21 07:32:11Z antoine $

PORTNAME=	metasploit_payloads-mettle
PORTVERSION=	0.3.8
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Compiled binaries for Metasploit's next-gen Meterpreter

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes
STRIP=
USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
