# $FreeBSD: head/security/rubygem-metasploit_payloads-mettle/Makefile 490048 2019-01-12 11:45:51Z antoine $

PORTNAME=	metasploit_payloads-mettle
PORTVERSION=	0.5.1
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Compiled binaries for Metasploit's next-gen Meterpreter

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes
STRIP=
USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
