# Created by: rpsfa@rit.edu
# $FreeBSD: head/devel/rubygem-simple_form-rails5/Makefile 441144 2017-05-18 11:32:48Z jrm $

PORTNAME=	simple_form
PORTVERSION=	3.5.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	-rails5

MAINTAINER=	jrm@FreeBSD.org
COMMENT=	Forms made easy

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

RUN_DEPENDS=	rubygem-activemodel5>0:databases/rubygem-activemodel5 \
		rubygem-actionpack5>0:www/rubygem-actionpack5

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
