# $FreeBSD: head/devel/hs-SafeSemaphore/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	SafeSemaphore
PORTVERSION=	0.10.1
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Much safer replacement for QSemN, QSem, and SampleVar

LICENSE=	BSD3CLAUSE

USE_CABAL=	stm

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
