# $FreeBSD: head/devel/hs-SafeSemaphore/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	SafeSemaphore
PORTVERSION=	0.10.1
PORTREVISION=	7
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Much safer replacement for QSemN, QSem, and SampleVar

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
