# Created by: Mario S F Ferreira <lioux@FreeBSD.org>
# $FreeBSD: head/math/p5-Math-Interpolate/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Math-Interpolate
PORTVERSION=	1.06
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Perl routines for data sets interpolation and interval search

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

NO_ARCH=	yes
USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
