# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: head/devel/p5-ExtUtils-Command/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	ExtUtils-Command
PORTVERSION=	1.20
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Utilities to replace common UNIX commands

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

CONFLICTS=	p5-ExtUtils-MakeMaker-[7-9].[1-9]*

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
