# $FreeBSD: head/devel/rubygem-get_process_mem/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	get_process_mem
PORTVERSION=	0.2.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@michael-fausten.de
COMMENT=	Get memory usage of a process in Ruby

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
