# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/devel/pear-Horde_Lock/Makefile 421524 2016-09-07 22:54:27Z mm $

PORTNAME=	Horde_Lock
PORTVERSION=	2.1.4
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Resource Locking System

USES=	horde
USE_HORDE_RUN=	Horde_Exception \
		Horde_Support

.include <bsd.port.mk>
