# Created by: Jean-Yves Lefort <jylefort@FreeBSD.org>
# $FreeBSD: head/x11-toolkits/gtksourceview3-reference/Makefile 440702 2017-05-12 19:11:02Z kwm $

PORTREVISION=	0

.include "${.CURDIR}/../../devel/glib20-reference/bsd.gnome-reference.mk"
