# Created by: ache
# $FreeBSD: head/net/p5-URI/Makefile 405959 2016-01-12 21:40:55Z sunpoet $

PORTNAME=	URI
PORTVERSION=	1.71
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 interface to Uniform Resource Identifier (URI) references

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
