# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: head/mail/p5-Mail-SendEasy/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Mail-SendEasy
PORTVERSION=	1.2
PORTREVISION=	1
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Send plain/html e-mails through SMTP servers

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

NO_ARCH=	yes
USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
