# Created by: Thierry Thomas (<thierry@pompo.net>)
# $FreeBSD: head/devel/pear-Console_Table/Makefile 441000 2017-05-16 13:37:51Z joneum $

PORTNAME=	Console_Table
PORTVERSION=	1.3.0
CATEGORIES=	devel pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PHP class that makes it easy to build console style tables

LICENSE=	BSD3CLAUSE

USES=	pear

.include <bsd.port.mk>
