# Created by: Johannes Meixner <johannes@perceivon.net>
# $FreeBSD: head/devel/rubygem-nprogress-rails/Makefile 430178 2016-12-31 23:51:00Z swills $

PORTNAME=	nprogress-rails
PORTVERSION=	0.2.0.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Rails implementation of nprogress progress bars library

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
