# $FreeBSD: head/devel/rubygem-mono_logger/Makefile 454216 2017-11-14 22:57:25Z dvl $

PORTNAME=	mono_logger
PORTVERSION=	1.1.0
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	dvl@FreeBSD.org
COMMENT=	Lock-free logger compatible with Ruby 2.0

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes
USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
