# Created by: Cory R. King <coryking@mozimedia.com>
# $FreeBSD: head/devel/p5-Params-Coerce/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	Params-Coerce
PORTVERSION=	0.14
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	coryking@mozimedia.com
COMMENT=	Allows your classes to do coercion of parameters  (Params::Coerce)

BUILD_DEPENDS=	p5-Params-Util>=0.20:devel/p5-Params-Util
RUN_DEPENDS=	p5-Params-Util>=0.20:devel/p5-Params-Util

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
