# Created by: Valerio Daelli <valerio.daelli@gmail.com>
# $FreeBSD: head/security/ossec-hids-client/Makefile 453334 2017-11-02 04:07:23Z jbeich $

PORTREVISION=	0
COMMENT=	Client port of ossec-hids

CLIENT_ONLY=	yes

MASTERDIR=	${.CURDIR}/../ossec-hids-server

PLIST=		${.CURDIR}/pkg-plist.client

.include "${MASTERDIR}/Makefile"
