# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-hike1/Makefile 447487 2017-08-07 10:14:08Z tz $

PORTNAME=	hike
PORTVERSION=	1.2.3
PORTEPOCH=	1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	1

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby library for finding files in a set of paths

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

PORTSCOUT=      limit:^1.*

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
