# Created by: Zhen REN <bg1tpt@gmail.com>
# $FreeBSD: head/net/pear-Net_MAC/Makefile 443285 2017-06-11 07:41:51Z sunpoet $

PORTNAME=	Net_MAC
PORTVERSION=	0.1.5
PORTREVISION=	1
CATEGORIES=	net pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR class that validates and formats MAC addresses

USES=		pear

.include <bsd.port.mk>
