# $FreeBSD: head/devel/hs-base-compat-batteries/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	base-compat-batteries
PORTVERSION=	0.10.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	base-compat with extra batteries

LICENSE=	MIT

USE_CABAL=	base-compat

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
