# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/devel/pear-channel-phpunit/Makefile 463949 2018-03-09 09:26:52Z mat $

PORTNAME=	phpunit
PORTVERSION=	20110327
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	pear.phpunit.de

.include "${.CURDIR}/../../devel/pear/bsd.pear.channel.mk"
.include <bsd.port.mk>
