# Created by: Jean-Yves Lefort <jylefort@FreeBSD.org>
# $FreeBSD: head/x11-toolkits/pango-reference/Makefile 465692 2018-03-27 11:39:52Z bapt $

REFERENCE_SRC=	${WRKSRC}/docs

.include "${.CURDIR}/../../devel/glib20-reference/bsd.gnome-reference.mk"
