# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: head/x11/nvidia-driver-340/Makefile 479538 2018-09-11 18:34:27Z zeising $

DISTVERSION=	340.107
# Explicitly set PORTREVISION as it can be overridden by the master port
PORTREVISION=	1

MASTERDIR=	${.CURDIR}/../nvidia-driver
PKGNAMESUFFIX=	-340

.include "${MASTERDIR}/Makefile"
