# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: head/x11/nvidia-driver-340/Makefile 459638 2018-01-22 09:05:44Z danfe $

DISTVERSION=	340.106
# Explicitly set PORTREVISION as it can be overridden by the master port
PORTREVISION=	0

MASTERDIR=	${.CURDIR}/../nvidia-driver
PKGNAMESUFFIX=	-340

.include "${MASTERDIR}/Makefile"
