# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: head/x11/nvidia-driver-340/Makefile 471954 2018-06-07 20:22:51Z danfe $

DISTVERSION=	340.107
# Explicitly set PORTREVISION as it can be overridden by the master port
PORTREVISION=	0

MASTERDIR=	${.CURDIR}/../nvidia-driver
PKGNAMESUFFIX=	-340

.include "${MASTERDIR}/Makefile"
