# Created by: tobez
# $FreeBSD: head/devel/p5-File-ReadBackwards/Makefile 479390 2018-09-10 11:16:59Z des $

PORTNAME=	File-ReadBackwards
PORTVERSION=	1.05
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	File::ReadBackwards -- read a file backwards by lines

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
