# Created by: Emanuel Haupt <ehaupt@FreeBSD.org>
# $FreeBSD: head/www/py-fake-useragent/Makefile 492684 2019-02-11 10:44:04Z ehaupt $

PORTNAME=	fake-useragent
PORTVERSION=	0.1.11
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ehaupt@FreeBSD.org
COMMENT=	Up to date simple useragent faker with real world database

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
