# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/textproc/rubygem-autoprefixer-rails/Makefile 470925 2018-05-26 17:48:50Z sunpoet $

PORTNAME=	autoprefixer-rails
PORTVERSION=	8.5.1
CATEGORIES=	textproc ruby
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Parse CSS and add vendor prefixes to CSS rules

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-execjs>=0:devel/rubygem-execjs

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
