# $FreeBSD: head/devel/hs-fast-logger/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	fast-logger
PORTVERSION=	2.4.10
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast logging system

LICENSE=	BSD3CLAUSE

USE_CABAL=	auto-update easy-file old-locale text unix-time

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
