# $FreeBSD: head/devel/hs-fast-logger/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	fast-logger
PORTVERSION=	2.4.11
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast logging system

LICENSE=	BSD3CLAUSE

USE_CABAL=	auto-update easy-file old-locale unix-time

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
