# Created by: Fernan Aguero <fernan@iib.unsam.edu.ar>
# $FreeBSD: head/math/p5-Math-Derivative/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Math-Derivative
PORTVERSION=	0.04
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Numeric 1st and 2nd order differentiation

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
