# $FreeBSD: head/devel/hs-directory-tree/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	directory-tree
PORTVERSION=	0.12.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple directory-like tree datatype, with useful IO functions

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
