# $FreeBSD: head/devel/hs-directory-tree/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	directory-tree
PORTVERSION=	0.12.1
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple directory-like tree datatype, with useful IO functions

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
