# Created by: Roman Neuhauser (<neuhauser@bellavista.cz>)
# $FreeBSD: head/net/pear-Net_URL/Makefile 475870 2018-07-30 09:07:53Z amdmi3 $

PORTNAME=	Net_URL
PORTVERSION=	1.0.15
CATEGORIES=	net www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Easy parsing of URLs

LICENSE=	BSD3CLAUSE

USES=		pear
NO_ARCH=	yes

.include <bsd.port.mk>
