# Created by: Ben Woods <woodsb02@FreeBSD.org>
# $FreeBSD: head/graphics/py3-pygraphviz/Makefile 446897 2017-07-29 19:26:36Z sunpoet $

MASTERDIR=	${.CURDIR}/../py-pygraphviz

TEST_DEPENDS=	${PYTHON_PKGNAMEPREFIX}nose>=0.10.1:devel/py3-nose

PORTSCOUT=	ignore:1

USES=		pkgconfig python:3.4+

.include "${MASTERDIR}/Makefile"
