# Created by: Daniel Roethlisberger <daniel@roe.ch>
# $FreeBSD: head/devel/rubygem-rscm/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	rscm
PORTVERSION=	0.5.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby SCM, an SCM-independent API for accessing SCMs

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
