# $FreeBSD: head/security/rubygem-rpam2/Makefile 465480 2018-03-24 21:11:45Z sunpoet $

PORTNAME=	rpam2
PORTVERSION=	4.0.1
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	PAM integration with ruby

LICENSE=	MIT

USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
