# $FreeBSD: head/security/rubygem-rpam2/Makefile 464333 2018-03-13 00:57:09Z jrm $

PORTNAME=	rpam2
PORTVERSION=	3.1.0
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	PAM integration with ruby

LICENSE=	MIT

LIB_DEPENDS=	libunwind.so:devel/libunwind

USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
