# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: head/lang/p5-Modern-Perl/Makefile 482852 2018-10-23 17:48:50Z sunpoet $

PORTNAME=	Modern-Perl
PORTVERSION=	1.20181021
CATEGORIES=	lang perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:CHROMATIC
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Enable all of the features of Modern Perl with one import

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		perl5
USE_PERL5=	configure

NO_ARCH=	yes

.include <bsd.port.mk>
