# $FreeBSD: head/dns/rubygem-idn-ruby/Makefile 446619 2017-07-25 19:46:46Z jrm $

PORTNAME=	idn-ruby
PORTVERSION=	0.1.0
CATEGORIES=	dns rubygems
MASTER_SITES=	RG

MAINTAINER=	jrm@FreeBSD.org
COMMENT=	LibIDN Ruby Bindings

LICENSE=	APACHE20

LIB_DEPENDS=	libunwind.so:devel/libunwind \
		libidn.so:dns/libidn

USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
