# $FreeBSD: head/dns/rubygem-idn-ruby/Makefile 447386 2017-08-05 03:25:17Z jrm $

PORTNAME=	idn-ruby
PORTVERSION=	0.1.0
CATEGORIES=	dns rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	LibIDN Ruby Bindings

LICENSE=	APACHE20

LIB_DEPENDS=	libunwind.so:devel/libunwind \
		libidn.so:dns/libidn

USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
