# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/databases/pear-DBA/Makefile 441000 2017-05-16 13:37:51Z joneum $

PORTNAME=	DBA
PORTVERSION=	1.1.1
CATEGORIES=	databases www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Berkely-style database abstraction class

USES=		pear

.include <bsd.port.mk>
