# Created by: Greg Larkin <glarkin@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-childprocess/Makefile 444496 2017-06-27 16:15:11Z sunpoet $

PORTNAME=	childprocess
PORTVERSION=	0.7.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	External background process controller

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-ffi>=1.0.11:devel/rubygem-ffi

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
