# $FreeBSD: head/devel/hs-io-streams-haproxy/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	io-streams-haproxy
PORTVERSION=	1.0.0.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	HAProxy protocol version 1.5 support for I/O using streams

LICENSE=	BSD3CLAUSE

USE_CABAL=	attoparsec io-streams network

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
