# Created by: Tomoyuki Sakurai <cherry@trombik.org>
# $FreeBSD: head/devel/p5-Module-Recursive-Require/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	Module-Recursive-Require
PORTVERSION=	0.04
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Require module recursively

BUILD_DEPENDS=	p5-UNIVERSAL-require>=0:devel/p5-UNIVERSAL-require
RUN_DEPENDS=	p5-UNIVERSAL-require>=0:devel/p5-UNIVERSAL-require

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
