# Created by: chinsan
# $FreeBSD: head/devel/p5-Scalar-Listify/Makefile 480000 2018-09-18 09:08:25Z amdmi3 $

PORTNAME=	Scalar-Listify
PORTVERSION=	0.03
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Poduces an array(ref)? from a scalar value or array ref

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
