# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: head/net/rubygem-ruby-openid/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	ruby-openid
PORTVERSION=	2.7.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	OpenID library written in pure Ruby

LICENSE=	APACHE20 RUBY
LICENSE_COMB=	dual

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
