# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-mize/Makefile 461404 2018-02-10 16:21:26Z sunpoet $

PORTNAME=	mize
PORTVERSION=	0.3.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Memoziation for methods and functions for Ruby

LICENSE=	MIT

RUN_DEPENDS=	rubygem-protocol>=0:devel/rubygem-protocol

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
