# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-foreach/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	foreach
PORTVERSION=	1.4.3
PORTREVISION=	1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Foreach looping construct for R

LICENSE=	APACHE20

RUN_DEPENDS=	R-cran-iterators>=1.0.0:devel/R-cran-iterators

USES=	cran:auto-plist

.include <bsd.port.mk>
