# Created by: Martin Tournoij <martin@arp242.net>
# $FreeBSD: head/sysutils/battray/Makefile 470213 2018-05-17 09:56:55Z tz $

PORTNAME=	battray
DISTVERSION=	2.3
PORTREVISION=	1
CATEGORIES=	sysutils python
DISTVERSIONPREFIX=	version-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Display notebook battery status in tray

LICENSE=	MIT

USES=		python:3.3+
USE_GNOME=	pygobject3
USE_PYTHON=	autoplist distutils optsuffix

USE_GITHUB=	yes
GH_ACCOUNT=	Carpetsmoker

.include <bsd.port.mk>
