# $FreeBSD: head/devel/hs-data-default-instances-old-locale/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	data-default-instances-old-locale
PORTVERSION=	0.0.1
PORTREVISION=	12
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Default instances for types in old-locale

LICENSE=	BSD3CLAUSE

USE_CABAL=	data-default-class old-locale

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
