# $FreeBSD: head/devel/hs-data-default-instances-old-locale/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	data-default-instances-old-locale
PORTVERSION=	0.0.1
PORTREVISION=	13
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Default instances for types in old-locale

LICENSE=	BSD3CLAUSE

USE_CABAL=	data-default-class old-locale

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
