# $FreeBSD: head/www/rubygem-jquery-atwho-rails/Makefile 458332 2018-01-07 12:13:32Z sunpoet $

PORTNAME=	jquery-atwho-rails
PORTVERSION=	1.5.4
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	jQuery plugin that implements GitHub-like mentions

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE-MIT

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
