# $FreeBSD: head/multimedia/gstreamer1-plugins-kate/Makefile 405242 2016-01-04 14:21:56Z kwm $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	GStreamer kate codec plugin

GST_PLUGIN=	kate
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
