# $FreeBSD: head/devel/py-pyshp/Makefile 464818 2018-03-17 13:52:04Z dbaio $

PORTNAME=	pyshp
PORTVERSION=	1.2.12
CATEGORIES=	devel python geography
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dbaio@FreeBSD.org
COMMENT=	Pure Python read/write support for ESRI Shapefile format

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.TXT

USES=		python
USE_PYTHON=	autoplist concurrent distutils
NO_ARCH=	yes

.include <bsd.port.mk>
