# $FreeBSD: head/mail/rubygem-mini_mime/Makefile 447382 2017-08-05 02:48:54Z jrm $

PORTNAME=	mini_mime
PORTVERSION=	0.1.3
CATEGORIES=	mail rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Lightweight mime type lookup toy

LICENSE=	MIT

NO_ARCH=	yes

USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
