# $FreeBSD: head/mail/popa3d-before-sendmail/Makefile 409731 2016-02-28 09:32:43Z dinoex $

CATEGORIES=	mail

MAINTAINER=	ports@FreeBSD.org

WITH_SMTP_AFTER_POP3=	yes
MASTERDIR?=	${.CURDIR}/../popa3d

OPTIONS_DEFAULT=	SMTP_AFTER_POP3

.include "${MASTERDIR}/Makefile"
