# $FreeBSD: head/textproc/hs-blaze-markup/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	blaze-markup
PORTVERSION=	0.8.0.0
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Blazingly fast markup combinator library for Haskell

LICENSE=	BSD3CLAUSE

USE_CABAL=	blaze-builder>=0.2 text>=0.10

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
