# $FreeBSD: head/databases/php73-pgsql/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTREVISION=	1
CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php73

PKGNAMESUFFIX=	-pgsql

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
