# Created by: SimaMoto,RyoTa <liangtai.s4@gmail.com>
# $FreeBSD: head/chinese/gimp-help-zh_CN/Makefile 493763 2019-02-24 15:08:19Z tobik $

CATEGORIES=	chinese graphics

MAINTAINER=	liangtai.s16@gmail.com
COMMENT=	GIMP User Manual in Simplified Chinese

LICENSE=	GFDL

MASTERDIR=	${.CURDIR}/../../misc/gimp-help-en

DOCLANG=	zh_CN

.include "${MASTERDIR}/Makefile"
