# $FreeBSD: head/textproc/rubygem-pretty-xml/Makefile 441404 2017-05-21 14:57:08Z sunpoet $

PORTNAME=	pretty-xml
PORTVERSION=	0.2.2
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Print well formatted XML

LICENSE=	MIT

RUN_DEPENDS=	rubygem-nokogiri>=1.6.7.2:textproc/rubygem-nokogiri

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
