# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/pecl-protobuf/Makefile 494264 2019-03-01 11:19:03Z sunpoet $

PORTNAME=	protobuf
PORTVERSION=	3.7.0
CATEGORIES=	devel

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	PHP binding for Protocol buffers

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		localbase php:pecl

.include <bsd.port.mk>
