# $FreeBSD: head/devel/geany-plugin-scope/Makefile 416609 2016-06-09 15:24:55Z madpilot $

PORTNAME=	geany-plugin-scope
PORTVERSION=	${GEANY_VER}
CATEGORIES=	devel

MAINTAINER=	madpilot@FreeBSD.org
COMMENT=	Geany plugin: ${${GEANY_PLUGIN}_DESC}

USE_GNOME=	vte

.include "${.CURDIR}/../geany-plugins/files/Makefile.common"
.include <bsd.port.mk>
