# $FreeBSD: head/devel/hs-data-hash/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	data-hash
PORTVERSION=	0.2.0.1
PORTREVISION=	5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Combinators for building fast hashing functions

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
