# Created by: Alonso Cardenas Marquez <acm@FreeBSD.org>
# $FreeBSD: head/editors/lazarus-lcl-nogui/Makefile 435181 2017-03-01 17:50:48Z acm $

PKGNAMESUFFIX=	-lcl-nogui

COMMENT=	Lazarus components library - No gui backend

BUILD_DEPENDS=	${LCL_UNITS_DIR}/alllclunits.ppu:editors/lazarus-lcl-units

LCL_INTERFACE=	nogui

MASTERDIR=	${.CURDIR}/../../editors/lazarus

OPT=		#
.include "${MASTERDIR}/Makefile"
