# Created by: Michael Moll <kvedulv@kvedulv.de>
# $FreeBSD: head/www/rubygem-jekyll-watch/Makefile 456015 2017-12-11 10:44:43Z sunpoet $

PORTNAME=	jekyll-watch
PORTVERSION=	1.5.1
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Handles rebuilding of Jekyll sites when a file changes

LICENSE=	MIT

RUN_DEPENDS=	rubygem-listen>=3.0:devel/rubygem-listen

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
