# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-google-protobuf/Makefile 456057 2017-12-11 18:25:37Z sunpoet $

PORTNAME=	google-protobuf
PORTVERSION=	3.5.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Ruby extension to Google Protocol Buffers

LICENSE=	BSD3CLAUSE

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
