# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-google-protobuf/Makefile 494440 2019-03-02 17:47:38Z sunpoet $

PORTNAME=	google-protobuf
PORTVERSION=	3.7.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Ruby extension to Google Protocol Buffers

LICENSE=	BSD3CLAUSE

USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
