# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-google-protobuf/Makefile 448791 2017-08-27 00:36:28Z sunpoet $

PORTNAME=	google-protobuf
PORTVERSION=	3.4.0.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Ruby extension to Google Protocol Buffers

LICENSE=	BSD3CLAUSE

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
