# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/math/py-svgmath/Makefile 371328 2014-10-21 16:54:54Z mva $

PORTNAME=	svgmath
PORTVERSION=	0.3.3
CATEGORIES=	math python
MASTER_SITES=	SF
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	SVGMath-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	MathML to SVG Converter in Python

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
