# $FreeBSD: head/math/libxls/Makefile 432541 2017-01-27 00:14:31Z bapt $

PORTNAME=	libxls
PORTVERSION=	1.4.0
CATEGORIES=	math devel
MASTER_SITES=	SF/${PORTNAME}/

MAINTAINER=	bapt@FreeBSD.org
COMMENT=	Extract Cell Data From Excel xls files

LICENSE=	BSD2CLAUSE

USES=	zip libtool

GNU_CONFIGURE=	yes
INSTALL_TARGET=	install-strip
USE_LDCONFIG=	yes

WRKSRC=	${WRKDIR}/${PORTNAME}

.include <bsd.port.mk>
