# $FreeBSD: head/devel/rubygem-fast-stemmer/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	fast-stemmer
PORTVERSION=	1.0.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Fast Porter stemmer based on a C version of algorithm

LICENSE=	MIT

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
