# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/textproc/py-markdown2/Makefile 480856 2018-09-28 12:08:54Z wen $

PORTNAME=	markdown2
PORTVERSION=	2.3.6
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Fast and complete Python implementation of Markdown

LICENSE=	MIT

USES=		python zip
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
