# $FreeBSD: head/devel/rubygem-deep_merge/Makefile 454491 2017-11-19 14:13:30Z robak $

PORTNAME=	deep_merge
PORTVERSION=	1.2.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	robak@FreeBSD.org
COMMENT=	Recursive hash merger

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
