# Created by: Akinori MUSHA aka knu <knu@idaemons.org>
# $FreeBSD: head/databases/p5-Time-Piece-MySQL/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Time-Piece-MySQL
PORTVERSION=	0.06
PORTREVISION=	2
CATEGORIES=	databases devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Time::Piece::MySQL - Adds MySQL-specific methods to Time::Piece

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
