# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/textproc/p5-Text-Trim/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Text-Trim
PORTVERSION=	1.02
PORTREVISION=	2
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Extract the structure of a quoted mail message

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
