# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: head/textproc/nds-aspell/Makefile 438338 2017-04-12 09:09:47Z mat $

PORTNAME=	${DICT}-aspell
SPELLVERSION=	6-nds-0.01-0
PORTREVISION=	1
PORTEPOCH=	2
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Low Saxon dictionary

DICT=	 	nds

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
