# $FreeBSD: head/devel/elixir-gettext/Makefile 455930 2017-12-11 08:45:02Z olgeni $

PORTNAME=	gettext
PORTVERSION=	0.14.0
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Implementation of gettext for Elixir

LICENSE=	APACHE20

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	elixir-lang

MIX_REWRITE=	yes

.include <bsd.port.mk>
