# $FreeBSD: head/devel/elixir-gettext/Makefile 479406 2018-09-10 13:14:50Z mat $

PORTNAME=	gettext
PORTVERSION=	0.15.0
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	erlang@FreeBSD.org
COMMENT=	Implementation of gettext for Elixir

LICENSE=	APACHE20

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	elixir-lang

MIX_REWRITE=	yes

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
