# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: head/science/rubygem-ai4r/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	ai4r
PORTVERSION=	1.13
CATEGORIES=	science rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Various Ruby artificial intelligence algorithm implementations

LICENSE=	MPL

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
