# $FreeBSD: head/devel/erlang-getopt/Makefile 479406 2018-09-10 13:14:50Z mat $

PORTNAME=	getopt
PORTVERSION=	1.0.1
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	erlang@FreeBSD.org
COMMENT=	Command line parsing library for Erlang

LICENSE=	BSD3CLAUSE

USES=		erlang:rebar3
USE_GITHUB=	yes
GH_ACCOUNT=	jcomellas

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
