# Created by: SimaMoto,RyoTa <liangtai.s4@gmail.com>
# $FreeBSD: head/german/gimp-help/Makefile 493763 2019-02-24 15:08:19Z tobik $

CATEGORIES=	german graphics

MAINTAINER=	liangtai.s16@gmail.com
COMMENT=	GIMP User Manual in German

LICENSE=	GFDL

MASTERDIR=	${.CURDIR}/../../misc/gimp-help-en

DOCLANG=	de

.include "${MASTERDIR}/Makefile"
