# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/converters/R-cran-jsonlite/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	jsonlite
PORTVERSION=	1.5
PORTREVISION=	1
CATEGORIES=	converters
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Robust, High Performance JSON Parser and Generator for R

LICENSE=	MIT

USES=	cran:auto-plist,compiles

.include <bsd.port.mk>
