# $FreeBSD: head/arabic/kde4-l10n/Makefile 439367 2017-04-25 08:20:30Z riggs $

PORTNAME=	kde-l10n
PORTVERSION=	${KDE4_VERSION}
PORTREVISION=	1
CATEGORIES=	arabic kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Arabic messages and documentation for KDE SC 4

KDE4_L10N=	ar

.include "${.CURDIR:H:H}/misc/kde4-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
