# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: head/graphics/gstreamer-plugins-aalib/Makefile 428152 2016-12-08 19:52:19Z tijl $
#   $MCom: ports/graphics/gstreamer-plugins-aalib/Makefile,v 1.5 2008/03/19 14:05:33 ahze Exp $

PORTREVISION=	2
CATEGORIES=	graphics

COMMENT=	Gstreamer ASCII art plugin

GST_PLUGIN=	aalib

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
