# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: head/textproc/p5-Text-FixedLength/Makefile 479390 2018-09-10 11:16:59Z des $

PORTNAME=	Text-FixedLength
PORTVERSION=	0.12
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Parse and create fixed length field records

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
