# $FreeBSD: head/mail/rubygem-email_reply_parser/Makefile 459067 2018-01-15 15:18:31Z swills $

PORTNAME=	email_reply_parser
PORTVERSION=	0.5.9
CATEGORIES=	mail rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@michael-fausten.de
COMMENT=	Library to parse plain text email content

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
