# Created by: Dirk Froemberg <dirk@FreeBSD.org>
# $FreeBSD: head/textproc/expat2/Makefile 428144 2016-12-08 17:40:41Z tijl $

PORTNAME=	expat
PORTVERSION=	2.2.0
PORTREVISION=	1
CATEGORIES=	textproc
MASTER_SITES=	SF

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	XML 1.0 parser written in C

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

GNU_CONFIGURE=	yes
ALL_TARGET=	default
USES=		libtool pathfix tar:bz2
USE_LDCONFIG=	yes

.include <bsd.port.mk>
