# $FreeBSD: head/sysutils/powerdxx/Makefile 449918 2017-09-15 18:28:31Z adamw $

PORTNAME=	powerdxx
PORTVERSION=	0.2.5
PORTREVISION=	1
CATEGORIES=	sysutils

MAINTAINER=	kamikaze@bsdforen.de
COMMENT=	CPU clock speed/frequency daemon

LICENSE=	ISCL

USES=		compiler:c++11-lib

USE_GITHUB=	yes
GH_ACCOUNT=	lonkamikaze

MAKE_ARGS=	DOCSDIR="${DOCSDIR}"

.include <bsd.port.mk>
