# $FreeBSD: head/devel/hs-bloomfilter/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	bloomfilter
PORTVERSION=	2.0.1.0
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Pure and impure Bloom Filter implementations

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
