# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/databases/pear-DBA_Relational/Makefile 488102 2018-12-22 16:30:39Z joneum $

PORTNAME=	DBA_Relational
PORTVERSION=	0.2.0
CATEGORIES=	databases www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Berkely-style database abstraction class

LICENSE=	LGPL3

USES=		pear

PORTSCOUT=	skipv:0.19

.include <bsd.port.mk>
