# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: head/cad/gmsh-occ/Makefile 423896 2016-10-12 22:23:09Z jrm $

PKGNAMESUFFIX=	-occ

COMMENT=	Automatic 3D finite element mesh generator with OpenCascade support

MASTERDIR=	${.CURDIR}/../../cad/gmsh

OPTIONS_SLAVE=	OCC

.include "${MASTERDIR}/Makefile"
