# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-zoo/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	zoo
DISTVERSION=	1.8-0
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	S3 Infrastructure for Regular and Irregular Time Series

LICENSE=	GPLv2+

USES=	cran:auto-plist,compiles

.include <bsd.port.mk>
