# $FreeBSD: head/devel/hs-hashtables/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	hashtables
PORTVERSION=	1.2.3.0
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Mutable hash tables in the ST monad

LICENSE=	BSD3CLAUSE

USE_CABAL=	hashable>=1.1 primitive vector>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
