# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-rubygems-test/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	rubygems-test
PORTVERSION=	0.4.3
PORTREVISION=	1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Run automated tests

LICENSE=	MIT

RUN_DEPENDS=	rubygem-rake>=0.8.7:devel/rubygem-rake

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
