# $FreeBSD: head/multimedia/gstreamer1-plugins-rtmp/Makefile 411860 2016-03-25 15:47:45Z kwm $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	GStreamer RTMP stream source and sink plugin

GST_PLUGIN=	rtmp
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
