# Created by: Danilo G. Baio <dbaio@bsd.com.br>
# $FreeBSD: head/textproc/py3-docutils/Makefile 441859 2017-05-27 17:33:00Z sunpoet $

MASTERDIR=	${.CURDIR}/../py-docutils

PORTSCOUT=	ignore:1

USES=		python:3.3+

PYGMENTS_RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}pygments>=1.6:textproc/py3-pygments

.include "${MASTERDIR}/Makefile"
