# $FreeBSD: head/security/rubygem-rex-text/Makefile 441385 2017-05-21 11:53:54Z antoine $

PORTNAME=	rex-text
PORTVERSION=	0.2.15
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Ruby Exploitation(Rex) methods for text manipulation and generation

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
