# Created by: tobez
# $FreeBSD: head/math/p5-Math-BigInt/Makefile 481932 2018-10-12 19:59:42Z sunpoet $

PORTNAME=	Math-BigInt
PORTVERSION=	1.999814
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Arbitrary size integer math perl package

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

NO_ARCH=	yes

.include <bsd.port.mk>
