# Created by: tobez
# $FreeBSD: head/math/p5-Math-BigInt/Makefile 479390 2018-09-10 11:16:59Z des $

PORTNAME=	Math-BigInt
PORTVERSION=	1.999813
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Arbitrary size integer math perl package

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
