# Created by: tobez
# $FreeBSD: head/math/p5-Math-BigInt/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Math-BigInt
PORTVERSION=	1.999808
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:PJACKLAM
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Arbitrary size integer math perl package

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
