# $FreeBSD: head/devel/hs-syb/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	syb
PORTVERSION=	0.7
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Scrap Your Boilerplate

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
