# $FreeBSD: head/devel/hs-syb/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	syb
PORTVERSION=	0.7
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Scrap Your Boilerplate

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
