# $FreeBSD: head/textproc/libkomparediff2-kde4/Makefile 462619 2018-02-22 19:03:17Z tcberner $

PORTNAME=	libkomparediff2
PORTVERSION=	${KDE4_VERSION}
PORTREVISION=	4
CATEGORIES=	textproc kde kde-kde4

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Library to compare files and strings

USES=		cmake:outsource kde:4 tar:xz
USE_KDE=	kdelibs automoc4
USE_QT4=	qmake_build moc_build uic_build rcc_build
USE_LDCONFIG=	yes

.include <bsd.port.mk>
