# $FreeBSD: head/devel/i386-binutils/Makefile 475319 2018-07-25 17:46:55Z jhb $

COMMENT=	GNU binutils for i386 cross-development
PKGNAMEPREFIX=	i386-
PLIST=	${.CURDIR}/pkg-plist

MASTERDIR=	${.CURDIR}/../binutils

.include "${MASTERDIR}/Makefile"
