# Created by: renchap@cocoa-x.com
# $FreeBSD: head/devel/rubygem-systemu/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	systemu
PORTVERSION=	2.6.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	renchap@cocoa-x.com
COMMENT=	Portable replacement for popen4

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
