# Created by: renchap@cocoa-x.com
# $FreeBSD: head/devel/rubygem-systemu/Makefile 457533 2017-12-29 18:48:09Z sunpoet $

PORTNAME=	systemu
PORTVERSION=	2.6.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Portable replacement for popen4

LICENSE=	BSD2CLAUSE RUBY
LICENSE_COMB=	dual
LICENSE_FILE_BSD2CLAUSE=${WRKSRC}/BSDL
LICENSE_FILE_RUBY=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
