# Created by: Brad Hendrickse <bradh@uunet.co.za>
# $FreeBSD: head/net-mgmt/p5-Net-IPv4Addr/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Net-IPv4Addr
PORTVERSION=	0.10
PORTREVISION=	1
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension for manipulating IPv4 addresses

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
