# $FreeBSD: head/www/pear-Horde_Form/Makefile 447173 2017-08-02 19:23:51Z mm $

PORTNAME=	Horde_Form
PORTVERSION=	2.0.18
CATEGORIES=	www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Form API

USES=	horde
USE_HORDE_RUN=	Horde_Core \
		Horde_Date \
		Horde_Exception \
		Horde_Mail \
		Horde_Mime \
		Horde_Nls \
		Horde_Token \
		Horde_Translation \
		Horde_Util

.include <bsd.port.mk>
