# $FreeBSD: head/www/pear-Horde_Form/Makefile 437682 2017-04-04 06:41:38Z mm $

PORTNAME=	Horde_Form
PORTVERSION=	2.0.17
CATEGORIES=	www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Form API

USES=	horde
USE_HORDE_RUN=	Horde_Core \
		Horde_Date \
		Horde_Exception \
		Horde_Mail \
		Horde_Mime \
		Horde_Nls \
		Horde_Token \
		Horde_Translation \
		Horde_Util

.include <bsd.port.mk>
