# Created by: Li-Wen Hsu <lwhsu@FreeBSD.org>
# $FreeBSD: head/databases/py-pyhs/Makefile 455210 2017-11-30 15:50:30Z mat $

PORTNAME=	pyhs
PORTVERSION=	0.2.4
PORTREVISION=	1
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	python-handler-socket-${PORTVERSION}

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	HandlerSocket client for Python

USES=		python:2.7
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
