# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: head/converters/p5-Encode-Detect/Makefile 450501 2017-09-24 18:48:42Z sunpoet $

PORTNAME=	Encode-Detect
PORTVERSION=	1.01
PORTREVISION=	1
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Encode::Encoding subclass that detects the encoding of data

LICENSE=	MPL11
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
