# Created by: Dmitry Marakasov <amdmi3@FreeBSD.org>
# $FreeBSD: head/x11-toolkits/mygui-dummy/Makefile 406252 2016-01-16 17:48:12Z amdmi3 $

PORTREVISION=	0
PKGNAMESUFFIX=	-dummy

COMMENT=	Dummy renderer for MyGUI

MASTERDIR=	${.CURDIR}/../mygui

MYGUI_RENDERSYSTEM=	1
MYGUI_SUBDIR=		Platforms/Dummy/DummyPlatform

.include "${MASTERDIR}/Makefile"
