# Created by: Ion-Mihai "IOnut" Tetcu <itetcu@FreeBSD.org>
# $FreeBSD: head/mail/squirrelmail-user_special_mailboxes-plugin/Makefile 434992 2017-02-27 21:20:41Z rene $

PORTNAME=	user_special_mailboxes
PORTVERSION=	0.1
PORTREVISION=	3
CATEGORIES=	mail www
DISTNAME=	${PORTNAME:S/-/_/}.${PORTVERSION}-1.4

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Lets define folders to be displayed at the top of the folders list

USE_SM_COMPAT=	yes

SQUIRREL_PLUGIN_NAME=	${PORTNAME:S/-/_/}

.include "${.CURDIR}/../squirrelmail/bsd.squirrelmail.mk"
.include <bsd.port.mk>
