# Created by: Jordi Haarman
# $FreeBSD: head/devel/py-wsgiutils/Makefile 458932 2018-01-13 14:28:25Z sunpoet $

PORTNAME=	wsgiutils
PORTVERSION=	0.7
PORTREVISION=	3
CATEGORIES=	devel textproc www python
MASTER_SITES=	http://www.owlfish.com/software/wsgiutils/downloads/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	WSGIUtils-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Utility libraries for development of simple WSGI programs

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes
USES=		python:2.7
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
