# $FreeBSD: head/sysutils/u-boot-zedboard/Makefile 453381 2017-11-02 21:41:47Z olgeni $

MAINTAINER=	imp@FreeBSD.org
MASTERDIR=	${.CURDIR}/../u-boot-master

MODEL=		zedboard
BOARD_CONFIG=	zynq_zed_defconfig
FAMILY=		zynq_7000

.include "${MASTERDIR}/Makefile"
