# Created by: Mamoru Sakaue / MwGhennndo
# $FreeBSD: head/ports-mgmt/portsreinstall/Makefile 465484 2018-03-24 21:12:13Z sunpoet $

PORTNAME=	portsreinstall
PORTVERSION=	3.3.2
CATEGORIES=	ports-mgmt
MASTER_SITES=	OSDN/${PORTNAME}/67120/ \
		http://www.mwghennndo.com/software/${PORTNAME}/

MAINTAINER=	sakaue.mamoru@mwghennndo.com
COMMENT=	Ports upgrading utility for massive forced reinstall

LICENSE=	BSD2CLAUSE

MAKE_ARGS=	PREFIX=${STAGEDIR}${PREFIX}
NO_ARCH=	yes

.include <bsd.port.mk>
