# $FreeBSD: head/devel/pear-Date_Holidays_Denmark/Makefile 443179 2017-06-11 07:30:21Z sunpoet $

PORTNAME=	Date_Holidays_Denmark
PORTVERSION=	0.1.3
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Driver based class to calculate holidays in Denmark

BUILD_DEPENDS=	${PEARDIR}/Date/Holidays.php:devel/pear-Date_Holidays
RUN_DEPENDS=	${PEARDIR}/Date/Holidays.php:devel/pear-Date_Holidays

USES=		pear

.include <bsd.port.mk>
