# $FreeBSD: head/devel/hs-extra/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	extra
PORTVERSION=	1.6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Extra functions

LICENSE=	BSD3CLAUSE

USE_CABAL=	clock

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
