# $FreeBSD: head/textproc/hs-attoparsec-iso8601/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	attoparsec-iso8601
PORTVERSION=	1.0.0.0
PORTREVISION=	1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Parsing of ISO 8601 dates

LICENSE=	BSD3CLAUSE

USE_CABAL=	attoparsec base-compat text

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
