# $FreeBSD: head/devel/geany-plugin-projectorganizer/Makefile 479406 2018-09-10 13:14:50Z mat $

PORTNAME=	geany-plugin-projectorganizer
PORTVERSION=	${GEANY_VER}
CATEGORIES=	devel

MAINTAINER=	madpilot@FreeBSD.org
COMMENT=	Geany plugin: ${${GEANY_PLUGIN}_DESC}

OPTIONS_DEFINE=	DOCS

.include "${.CURDIR}/../geany-plugins/files/Makefile.common"
.include <bsd.port.mk>
