# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/devel/pear-Console_Color/Makefile 488107 2018-12-22 16:51:39Z joneum $

PORTNAME=	Console_Color
PORTVERSION=	1.0.3
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR use ANSI console colors

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		pear

.include <bsd.port.mk>
