# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/devel/pear-Console_Color/Makefile 443173 2017-06-11 07:29:51Z sunpoet $

PORTNAME=	Console_Color
PORTVERSION=	1.0.3
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR use ANSI console colors

USES=		pear

.include <bsd.port.mk>
