# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: head/sysutils/stepsync/Makefile 492056 2019-02-03 15:37:58Z theraven $

PORTNAME=	stepsync
PORTVERSION=	1.0
PORTREVISION=	1
CATEGORIES=	sysutils gnustep
MASTER_SITES=	SAVANNAH/gap
DISTNAME=	StepSync-${PORTVERSION}

MAINTAINER=	danfe@FreeBSD.org
COMMENT=	File and folder synchronization tool

LICENSE=	GPLv2+

USES=		gnustep
USE_GNUSTEP=	build base gui

.include <bsd.port.mk>
