# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: head/math/p5-Math-Base85/Makefile 481720 2018-10-10 10:24:00Z sunpoet $

PORTNAME=	Math-Base85
PORTVERSION=	0.4
CATEGORIES=	math perl5 converters net
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension for base 85 numbers, as referenced by RFC 1924

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

NO_ARCH=	yes

.include <bsd.port.mk>
