# $FreeBSD: head/devel/elixir-csv/Makefile 442029 2017-05-29 18:24:47Z olgeni $

PORTNAME=	csv
PORTVERSION=	2.0.0
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	CSV decoding and encoding for Elixir

LICENSE=	MIT

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	beatrichartz

.include <bsd.port.mk>
