# $FreeBSD: head/security/rubygem-rex-struct2/Makefile 441384 2017-05-21 11:52:08Z antoine $

PORTNAME=	rex-struct2
PORTVERSION=	0.1.2
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Ruby Exploitation(Rex) library for creating and using C-like structs

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
