# Created by: roam@FreeBSD.org
# $FreeBSD: head/dns/ares/Makefile 447034 2017-08-01 17:07:58Z zi $

PORTNAME=	ares
PORTVERSION=	1.1.1
PORTREVISION=	1
CATEGORIES=	dns
MASTER_SITES=	ZI \
		ftp://athena-dist.mit.edu/pub/ATHENA/ares/

MAINTAINER=	zi@FreeBSD.org
COMMENT=	Asynchronous DNS resolver library

CONFLICTS=	c-ares-1.* c-ares-config-1.*

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
