# Created by: Ion-Mihai "IOnut" Tetcu <itetcu@FreeBSD.org>
# $FreeBSD: head/devel/qgit/Makefile 490472 2019-01-16 11:13:44Z tijl $

PORTNAME=	qgit
DISTVERSIONPREFIX=	${PORTNAME}-
DISTVERSION=	2.8
PORTREVISION=	1
CATEGORIES=	devel

MAINTAINER=	adridg@FreeBSD.org
COMMENT=	Graphical interface to git repositories

LICENSE=	GPLv2

USES=		cmake qt:5
USE_QT=		core gui widgets \
		buildtools_build qmake_build

USE_GITHUB=	yes
GH_ACCOUNT=	tibirna

.include <bsd.port.mk>
