# Created by: Ion-Mihai "IOnut" Tetcu <itetcu@FreeBSD.org>
# $FreeBSD: head/devel/qgit/Makefile 488341 2018-12-25 20:25:39Z tcberner $

PORTNAME=	qgit
DISTVERSIONPREFIX=	${PORTNAME}-
DISTVERSION=	2.8
CATEGORIES=	devel

MAINTAINER=	adridg@FreeBSD.org
COMMENT=	Graphical interface to git repositories

LICENSE=	GPLv2

USES=		cmake qt:5
USE_QT=		core gui widgets \
		buildtools_build qmake_build

USE_GITHUB=	yes
GH_ACCOUNT=	tibirna

.include <bsd.port.mk>
