# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: head/devel/go-sql-driver/Makefile 446741 2017-07-27 13:57:30Z mat $

PORTNAME=	go-sql-driver
PORTVERSION=	1.1
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
MASTER_SITES=	GH \
		http://mirrors.rit.edu/zi/

MAINTAINER=	lattera@gmail.com
COMMENT=	Lightweight and fast MySQL driver for go

USES=		go
USE_GITHUB=	yes
GH_PROJECT=	mysql

GO_PKGNAME=	github.com/${PORTNAME}/${GH_PROJECT}

.include <bsd.port.mk>
