# $FreeBSD: head/databases/rubygem-arel7/Makefile 440136 2017-05-04 23:48:03Z sunpoet $

PORTNAME=	arel
PORTVERSION=	7.1.4
PORTEPOCH=	1
CATEGORIES=	databases rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	7

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Relational Algebra for Ruby

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE.txt

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
