# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: head/devel/p5-Hook-LexWrap/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Hook-LexWrap
PORTVERSION=	0.26
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Lexically scoped subroutine wrappers for Perl

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
