# Created by: ijliao
# $FreeBSD: head/finance/p5-Finance-TW-EmergingQuote/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	Finance-TW-EmergingQuote
PORTVERSION=	0.26
PORTREVISION=	1
CATEGORIES=	finance perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Check stock quotes from Taiwan Emerging Stock

BUILD_DEPENDS=	p5-libwww>=0:www/p5-libwww
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
