# $FreeBSD: head/devel/erlang-bear/Makefile 474635 2018-07-14 09:44:46Z olgeni $

PORTNAME=	bear
PORTVERSION=	0.8.5
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	erlang@FreeBSD.org
COMMENT=	Set of statistics functions for Erlang

LICENSE=	APACHE20

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	puzza007

.include <bsd.port.mk>
