# Created by: Dmitry Sivachenko <demon@FreeBSD.org>
# $FreeBSD: head/devel/py-phonenumbers/Makefile 438624 2017-04-16 10:18:34Z demon $

PORTNAME=	phonenumbers
PORTVERSION=	8.4.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Library for parsing, formatting, and validating intl phone numbers

LICENSE=	APACHE20

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
