# Created by: Gerrit Beine (<tux@pinguru.net>)
# $FreeBSD: head/net/pear-Net_LDAP/Makefile 443284 2017-06-11 07:41:46Z sunpoet $

PORTNAME=	Net_LDAP
DISTVERSION=	1.1.5
PORTREVISION=	1
CATEGORIES=	net pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	OO interface for searching and manipulating LDAP-entries

USES=		pear

.include <bsd.port.mk>
