# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/www/rubygem-crass/Makefile 454215 2017-11-14 22:51:28Z sunpoet $

PORTNAME=	crass
PORTVERSION=	1.0.3
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	CSS parser based on the CSS Syntax Level 3 draft

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
