# Created by: Kimo <kimor79@yahoo.com>
# $FreeBSD: head/databases/rubygem-mysql2/Makefile 445517 2017-07-11 17:00:16Z sunpoet $

PORTNAME=	mysql2
PORTVERSION=	0.4.8
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Simple, fast MySQL library for Ruby, binding to libmysql

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_RUBY=	yes
USES=		gem mysql ssl

.include <bsd.port.mk>
