# $FreeBSD: head/devel/elixir-combine/Makefile 446227 2017-07-19 19:15:55Z olgeni $

PORTNAME=	combine
PORTVERSION=	0.9.7
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Parser combinator library for Elixir

LICENSE=	MIT

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	bitwalker

MIX_REWRITE=	yes

.include <bsd.port.mk>
