# $FreeBSD: head/x11-fonts/gnu-unifont-ttf/Makefile 448889 2017-08-28 22:23:57Z jkim $

MASTERDIR=	${.CURDIR}/../gnu-unifont

PKGNAMESUFFIX=	-ttf

COMMENT=	GNU Unicode TrueType font

FONTFILES=	${PORTNAME} ${PORTNAME}_csur ${PORTNAME}_upper
FONTSUFFIX=	.ttf

DESCR=		${.CURDIR}/pkg-descr
DISTINFO_FILE=	${.CURDIR}/distinfo

.include "${MASTERDIR}/Makefile"
