# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/math/R-cran-rgenoud/Makefile 439361 2017-04-25 07:10:04Z wen $

PORTNAME=	rgenoud
DISTVERSION=	5.7-12.4
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	R Version of GENetic Optimization Using Derivatives

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=		cran:auto-plist

.include <bsd.port.mk>
