# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/math/R-cran-rgenoud/Makefile 469990 2018-05-15 02:55:48Z wen $

PORTNAME=	rgenoud
DISTVERSION=	5.8-2.0
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	R Version of GENetic Optimization Using Derivatives

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
