# $FreeBSD: head/devel/hs-microlens-th/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	microlens-th
PORTVERSION=	0.4.1.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	This package lets you automatically generate lenses for data types

LICENSE=	BSD3CLAUSE

USE_CABAL=	microlens

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
