# $FreeBSD: head/devel/hs-microlens-th/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	microlens-th
PORTVERSION=	0.4.2.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	This package lets you automatically generate lenses for data types

LICENSE=	BSD3CLAUSE

USE_CABAL=	microlens th-abstraction

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
