# Created by: Alexander Logvinov <ports@logvinov.com>
# $FreeBSD: head/devel/rubygem-fastthread/Makefile 456328 2017-12-14 18:09:09Z swills $

PORTNAME=	fastthread
PORTVERSION=	1.0.7
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Optimized replacement for thread.rb primitives

LICENSE=	LGPL21

BROKEN_RUBY24=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
