# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/net/p5-Net-IP-Minimal/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Net-IP-Minimal
PORTVERSION=	0.06
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Minimal functions from Net::IP

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
