# $FreeBSD: head/audio/gstreamer1-plugins-soundtouch/Makefile 411860 2016-03-25 15:47:45Z kwm $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	GStreamer soundtouch plugin

GST_PLUGIN=	soundtouch
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
