# Created by: chinsan
# $FreeBSD: head/devel/p5-File-Path/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	File-Path
PORTVERSION=	2.15
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Create or remove directory trees

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
