# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/devel/pear-Horde_Translation/Makefile 435605 2017-03-07 14:22:52Z mm $

PORTNAME=	Horde_Translation
PORTVERSION=	2.2.2
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde translation library

USES=	horde

.include <bsd.port.mk>
