# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: head/textproc/p5-Regexp-Common-net-CIDR/Makefile 437950 2017-04-07 18:50:22Z lth $

PORTNAME=	Regexp-Common-net-CIDR
PORTVERSION=	0.03
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Provide patterns for CIDR blocks

BUILD_DEPENDS=	p5-Regexp-Common>0:textproc/p5-Regexp-Common
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
