# Created by: Alexander Nusov <alexander.nusov@nfvexpress.com>
# $FreeBSD: head/devel/py-rtslib-fb/Makefile 432705 2017-01-29 09:20:24Z novel $

PORTNAME=	rtslib-fb
PORTVERSION=	2.1.62
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	alexander.nusov@nfvexpress.com
COMMENT=	API for Linux kernel SCSI target (aka lio)

LICENSE=	APACHE20

NO_ARCH=	yes

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
