# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/devel/py-traits/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	traits
PORTVERSION=	4.6.0
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Explicitly Typed Attributes for Python

LICENSE=	BSD3CLAUSE PSFL
LICENSE_COMB=	multi

BUILD_DEPENDS=	${PYNUMPY}

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
