# Created by: Pakhom Golynga <pg@pakhom.spb.ru>
# $FreeBSD: head/net-mgmt/zabbix4-proxy/Makefile 481218 2018-10-04 12:03:59Z dbaio $

PORTNAME=	zabbix4
CATEGORIES=	net-mgmt
PKGNAMESUFFIX=	-proxy

MASTERDIR=	${.CURDIR}/../zabbix4-server

OPTIONS_SINGLE_DB=	MYSQL PGSQL SQLITE ORACLE

.include "${MASTERDIR}/Makefile"
