# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-gsubfn/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	gsubfn
DISTVERSION=	0.6-5
PORTREVISION=	6
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	R package used for string matching, substitution and parsing

LICENSE=	GPLv2

RUN_DEPENDS=	R-cran-proto>=0.3.9.2_6:devel/R-cran-proto

USES=	cran:auto-plist

.include <bsd.port.mk>
