# $FreeBSD: head/devel/elixir-excoveralls/Makefile 447085 2017-08-02 02:29:27Z vanilla $

PORTNAME=	excoveralls
PORTVERSION=	0.7.2
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	vanilla@FreeBSD.org
COMMENT=	Coverage Reports for Elixir

LICENSE=	APACHE20

MIX_BUILD_DEPS=	devel/elixir-exjsx \
		www/erlang-hackney

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	parroty

.include <bsd.port.mk>
