# $FreeBSD: head/devel/elixir-excoveralls/Makefile 443101 2017-06-10 16:23:48Z vanilla $

PORTNAME=	excoveralls
PORTVERSION=	0.7.0
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	vanilla@FreeBSD.org
COMMENT=	Coverage Reports for Elixir

LICENSE=	APACHE20

MIX_BUILD_DEPS=	devel/elixir-exjsx \
		www/erlang-hackney

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	parroty

.include <bsd.port.mk>
