# $FreeBSD: head/www/hs-multipart/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	multipart
PORTVERSION=	0.1.2
PORTREVISION=	1
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	HTTP multipart split out of the cgi package

LICENSE=	BSD3CLAUSE

USE_CABAL=	parsec>=2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
