# Created by: Martin Matuska <martin@matuska.org>
# $FreeBSD: head/databases/luasql-firebird/Makefile 468288 2018-04-25 18:40:14Z acm $

PORTREVISION=	1

LUASQL_DRIVER=	firebird

MASTERDIR=	${.CURDIR}/../luasql-mysql

.include "${MASTERDIR}/Makefile"
