# Created by: Martin Matuska <martin@matuska.org>
# $FreeBSD: head/databases/luasql-firebird/Makefile 492711 2019-02-11 18:42:37Z swills $

LUASQL_DRIVER=	firebird

MASTERDIR=	${.CURDIR}/../luasql-mysql

.include "${MASTERDIR}/Makefile"
