# Created by: Martin Matuska <martin@matuska.org>
# $FreeBSD: head/databases/luasql-firebird/Makefile 416805 2016-06-12 15:05:44Z vanilla $

LUASQL_DRIVER=	firebird

MASTERDIR=	${.CURDIR}/../luasql-mysql

.include "${MASTERDIR}/Makefile"
