# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-fluent-logger/Makefile 458194 2018-01-06 04:33:10Z sunpoet $

PORTNAME=	fluent-logger
PORTVERSION=	0.7.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Structured event logger for Ruby

LICENSE=	APACHE20

RUN_DEPENDS=	rubygem-msgpack1>=1.0.0:devel/rubygem-msgpack1

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

PLIST_FILES=	bin/fluent-post

.include <bsd.port.mk>
