# $FreeBSD: head/devel/py-terminable_thread/Makefile 408646 2016-02-10 19:45:07Z truckman $

PORTNAME=	terminable_thread
PORTVERSION=	0.7.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	truckman@FreeBSD.org
COMMENT=	Thread subclass / raise exceptions or terminate from another thread

LICENSE=	PD
LICENSE_FILE=	${WRKSRC}/COPYING

NO_ARCH=	yes
USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
