# Created by: Artyom Mirgorodskiy <artyom.mirgorodsky@gmail.com>
# $FreeBSD: head/graphics/linux-c6-png/Makefile 432937 2017-01-31 16:54:21Z tijl $

PORTNAME=	libpng
PORTVERSION=	1.2.49
PORTREVISION=	5
CATEGORIES=	graphics linux

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	Library for manipulating PNG images (Linux CentOS ${LINUX_DIST_VER})

DESCR=		${.CURDIR}/../png/pkg-descr
RPMVERSION=	2.el6_7
USES=		linux:c6
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes

.include <bsd.port.mk>
