# $FreeBSD: head/textproc/py-sphinx_rtd_theme/Makefile 455210 2017-11-30 15:50:30Z mat $

PORTNAME=	sphinx_rtd_theme
PORTVERSION=	0.2.4
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	robak@FreeBSD.org
COMMENT=	Mobile-friendly py-sphinx theme

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
