# Created by: Frank Laszlo <laszlof@vonostingroup.com>
# $FreeBSD: head/security/md5deep/Makefile 457058 2017-12-23 15:00:27Z tijl $

PORTNAME=	md5deep
PORTVERSION=	4.4
CATEGORIES=	security

MAINTAINER=	nobutaka@FreeBSD.org
COMMENT=	Program to compute various message digests recursively

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/COPYING

GH_ACCOUNT=	jessek
GH_PROJECT=	hashdeep
GH_TAGNAME=	cd2ed74

USE_GITHUB=	yes
USES=		autoreconf gmake
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
