# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: head/devel/p5-Class-CodeStyler/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	Class-CodeStyler
PORTVERSION=	0.27
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Perl extension for code generation program formatting and execution

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Class-STL-Containers>=0:devel/p5-Class-STL-Containers

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
