# Created by: Dejan Lesjak <lesi@FreeBSD.org>
# $FreeBSD: head/x11/damageproto/Makefile 468334 2018-04-26 09:03:48Z amdmi3 $

PORTNAME=	damageproto
PORTVERSION=	1.2.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Damage extension headers

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

XORG_CAT=	proto

.include <bsd.port.mk>
