# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/graphics/p5-Graphics-GnuplotIF/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Graphics-GnuplotIF
PORTVERSION=	1.8
CATEGORIES=	graphics perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Dynamic Perl interface to gnuplot

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
