# Created by: Matthew Seaman <matthew@FreeBSD.org>
# $FreeBSD: head/sysutils/rubygem-hiera-file/Makefile 430230 2017-01-01 02:09:41Z sunpoet $

PORTNAME=	hiera-file
PORTVERSION=	1.1.1
PORTREVISION=	1
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	matthew@FreeBSD.org
COMMENT=	Data backend for Hiera that returns whole files

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

RUN_DEPENDS=	rubygem-hiera1>=0:sysutils/rubygem-hiera1

.include <bsd.port.mk>
