# $FreeBSD: head/textproc/hs-pretty-show/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	pretty-show
PORTVERSION=	1.7
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Library and an executable for working with derived Show instances

LICENSE=	BSD3CLAUSE

EXECUTABLE=	ppsh
USE_CABAL=	happy haskell-lexer

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
