# $FreeBSD: head/devel/R-cran-gbm/Makefile 443845 2017-06-18 18:09:16Z dbn $

PORTNAME=	gbm
DISTVERSION=	2.0-8
PORTREVISION=	7
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Extensions to AdaBoost algorithm

LICENSE=	GPLv2

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
