# $FreeBSD: head/misc/rubygem-dotenv/Makefile 493600 2019-02-22 19:55:10Z sunpoet $

PORTNAME=	dotenv
PORTVERSION=	2.7.0
CATEGORIES=	misc rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Loads environment variables from .env

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

PLIST_FILES=	bin/dotenv

.include <bsd.port.mk>
