# $FreeBSD: head/misc/rubygem-dotenv/Makefile 468466 2018-04-27 15:57:28Z sunpoet $

PORTNAME=	dotenv
PORTVERSION=	2.4.0
CATEGORIES=	misc rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Loads environment variables from `.env`

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

PLIST_FILES=	bin/dotenv

.include <bsd.port.mk>
