# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/finance/R-cran-strucchange/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	strucchange
DISTVERSION=	1.5-1
CATEGORIES=	finance
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Testing, Monitoring, and Dating Structural Changes

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

RUN_DEPENDS=	R-cran-zoo>0:math/R-cran-zoo \
		R-cran-sandwich>0:math/R-cran-sandwich

USES=	cran:auto-plist

.include <bsd.port.mk>
