# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/archivers/rubygem-bzip2-ruby/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	bzip2-ruby
PORTVERSION=	0.2.7
PORTREVISION=	2
CATEGORIES=	archivers rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby C bindings to libbzip2

LICENSE=	BSD2CLAUSE RUBY
LICENSE_COMB=	dual

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
