# Created by: Bill "I hate Perl" Fumerola
# $FreeBSD: head/textproc/p5-Text-Template/Makefile 461505 2018-02-11 14:38:11Z sunpoet $

PORTNAME=	Text-Template
PORTVERSION=	1.50
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Expand template text with embedded Perl

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
