# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/net/mtr-nox11/Makefile 442413 2017-06-02 18:12:17Z sunpoet $

PKGNAMESUFFIX=	-nox11

MASTERDIR=	${.CURDIR}/../mtr

CONFLICTS_INSTALL=	mtr

OPTIONS_EXCLUDE=	X11
OPTIONS_FILE_UNSET=	X11

PORTSCOUT=	ignore:1

.include "${MASTERDIR}/Makefile"
