# Created by: ijliao
# $FreeBSD: head/converters/dosunix/Makefile 484353 2018-11-06 21:13:54Z rene $

PORTNAME=	dosunix
PORTVERSION=	1.0.14
CATEGORIES=	converters
MASTER_SITES=	http://dosunix.sourceforge.net/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Manipulation of text files in a mixed DOS/Windows and Unix environment

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
