# Created by: Timur I. Bakeyev <bat@cpan.org>
# $FreeBSD: head/devel/p5-boolean/Makefile 435840 2017-03-10 20:10:43Z bofh $

PORTNAME=	boolean
PORTVERSION=	0.46
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:INGY
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Boolean support for Perl

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
