# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/py36-setuptools/Makefile 436290 2017-03-16 19:23:48Z antoine $

MASTERDIR=	${.CURDIR}/../py27-setuptools

USES=		python:3.6

.include "${MASTERDIR}/Makefile"
