# Created by: Jose Jachuf <jjachuf@gmail.com>
# $FreeBSD: head/databases/py-firebirdsql/Makefile 475047 2018-07-21 02:13:28Z wen $

PORTNAME=	firebirdsql
PORTVERSION=	1.1.0
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jjachuf@gmail.com
COMMENT=	Python DBAPI module for FirebirdSQL

LICENSE=	BSD2CLAUSE

NO_ARCH=	yes
USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
