# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/www/rubygem-haml-coderay/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	haml-coderay
PORTVERSION=	0.2.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Adds a CodeRay syntax highlighting filter to Haml

LICENSE=	ISCL
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-coderay>=0:textproc/rubygem-coderay \
		rubygem-haml>=0:www/rubygem-haml

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
