# Created by: Adam Weinberger <adamw@FreeBSD.org>
# $FreeBSD: head/devel/p5-Time-ParseDate/Makefile 423693 2016-10-10 20:01:29Z adamw $

PORTNAME=	Time-ParseDate
PORTVERSION=	2015.103
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Date parsing, both relative and absolute

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
