# $FreeBSD: head/devel/sparc64-binutils/Makefile 375610 2014-12-25 22:48:42Z bapt $

COMMENT=	GNU binutils for sparc64 cross-development
PKGNAMEPREFIX=	sparc64-
PLIST=	${.CURDIR}/pkg-plist

MASTERDIR=	${.CURDIR}/../binutils

.include "${MASTERDIR}/Makefile"
