# $FreeBSD: head/textproc/hs-polyparse/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	polyparse
PORTVERSION=	1.12
PORTREVISION=	3
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Variety of alternative parser combinator libraries

LICENSE=	LGPL21

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
