# $FreeBSD: head/security/php72-sodium/Makefile 454302 2017-11-16 10:48:48Z tz $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php72

PKGNAMESUFFIX=	-sodium

.include "${MASTERDIR}/Makefile"
