# $FreeBSD: head/x11/xrefresh/Makefile 469550 2018-05-10 14:28:26Z zeising $

PORTNAME=	xrefresh
PORTVERSION=	1.0.6
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Refresh all or part of an X screen

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	x11

PLIST_FILES=	bin/xrefresh man/man1/xrefresh.1.gz

.include <bsd.port.mk>
