# Created by: ijliao
# $FreeBSD: head/devel/rubygem-fastercsv/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	fastercsv
PORTVERSION=	1.5.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Complete replacement to the CSV standard library

LICENSE=	GPLv2 RUBY
LICENSE_COMB=	dual

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
