# Created by: Sergei Vyshenski <svysh.fbsd@gmail.com>
# $FreeBSD: head/textproc/p5-XML-Parser-Lite/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	XML-Parser-Lite
PORTVERSION=	0.721
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	svysh.fbsd@gmail.com
COMMENT=	Lightweight regexp-based XML parser

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-Requires>=0.06:devel/p5-Test-Requires \
		p5-XMLRPC-Lite>=0:net/p5-XMLRPC-Lite

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
