# Created by: Kubilay Kocak <koobs@FreeBSD.org>
# $FreeBSD: head/www/py-rfc3987/Makefile 445993 2017-07-16 10:14:21Z koobs $

PORTNAME=	rfc3987
PORTVERSION=	1.3.7
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	koobs@FreeBSD.org
COMMENT=	Parsing and validation of URIs (RFC 3986) and IRIs (RFC 3987)

LICENSE=	GPLv3+
LICENSE_FILE=	${WRKSRC}/COPYING.txt

USES=		python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
