# Created by: Kubilay Kocak <koobs@FreeBSD.org>
# $FreeBSD: head/www/py-rfc3987/Makefile 410503 2016-03-07 06:01:15Z koobs $

PORTNAME=	rfc3987
PORTVERSION=	1.3.5
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	koobs@FreeBSD.org
COMMENT=	Parsing and validation of URIs (RFC 3986) and IRIs (RFC 3987)

LICENSE=	GPLv3+

USES=		python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
