# Created by: Dejan Lesjak <lesi@FreeBSD.org>
# $FreeBSD: head/x11/printproto/Makefile 467132 2018-04-12 09:03:36Z amdmi3 $

PORTNAME=	printproto
PORTVERSION=	1.0.5
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Print extension headers

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

XORG_CAT=	proto

.include <bsd.port.mk>
