# Created by: Rui Lopes <rui@ruilopes.com>
# $FreeBSD: head/math/py-fpconst/Makefile 462307 2018-02-19 11:10:43Z antoine $

PORTNAME=	fpconst
PORTVERSION=	0.7.2
PORTREVISION=	1
CATEGORIES=	math python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Utilities for handling IEEE 754 floating point special values

USES=		python:2.7
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
