# $FreeBSD: head/devel/hs-clock/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	clock
PORTVERSION=	0.7.2
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A package for convenient access to high-resolution clock and timer functions

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
