# $FreeBSD: head/math/hs-contravariant/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	contravariant
PORTVERSION=	1.4
PORTREVISION=	2
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Contravariant functors

LICENSE=	BSD3CLAUSE

USE_CABAL=	semigroups StateVar transformers-compat void

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
