# $FreeBSD: head/math/hs-contravariant/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	contravariant
PORTVERSION=	1.4
PORTREVISION=	3
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Contravariant functors

LICENSE=	BSD3CLAUSE

USE_CABAL=	semigroups StateVar transformers-compat void

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
