# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/devel/pear-Pager/Makefile 445659 2017-07-13 16:00:04Z joneum $

PORTNAME=	Pager
PORTVERSION=	2.5.1
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR data paging class

LICENSE=	BSD2CLAUSE

USES=		pear

.include <bsd.port.mk>
