# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/devel/pear-Pager/Makefile 443229 2017-06-11 07:36:17Z sunpoet $

PORTNAME=	Pager
PORTVERSION=	2.4.9
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR data paging class

USES=		pear

.include <bsd.port.mk>
