# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-gtools/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	gtools
PORTVERSION=	3.5.0
PORTREVISION=	2
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Various R programming tools

LICENSE=	GPLv2

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
