# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: head/math/p5-Statistics-LTU/Makefile 479390 2018-09-10 11:16:59Z des $

PORTNAME=	Statistics-LTU
PORTVERSION=	2.8
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl implementation of Linear Threshold Units

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
