# Created by: William Grzybowski <wg@FreeBSD.org>
# $FreeBSD: head/databases/pear-DoctrineCommon/Makefile 484507 2018-11-09 09:30:21Z amdmi3 $

PORTNAME=	DoctrineCommon
PORTVERSION=	2.3.0
CATEGORIES=	databases pear
MASTER_SITES=	http://pear.doctrine-project.org/get/

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Shared code for Doctrine PHP object relational mapper

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		pear
PEAR_CHANNEL=	doctrine
NO_ARCH=	yes

.include <bsd.port.mk>
