# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-R6/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	R6
PORTVERSION=	2.2.2
PORTREVISION=	1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Classes with reference semantics

LICENSE=	MIT

USES=	cran:auto-plist

.include <bsd.port.mk>
