# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-R6/Makefile 440674 2017-05-12 02:54:11Z tota $

PORTNAME=	R6
PORTVERSION=	2.2.1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Classes with reference semantics

LICENSE=	MIT

USES=	cran:auto-plist

.include <bsd.port.mk>
