# Created by: Dmitry Marakasov <amdmi3@FreeBSD.org>
# $FreeBSD: head/devel/py3-flake8-import-order/Makefile 454942 2017-11-27 11:28:54Z amdmi3 $

MASTERDIR=	${.CURDIR}/../py-flake8-import-order

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}pycodestyle>=0:devel/py3-pycodestyle \
		${PYTHON_PKGNAMEPREFIX}asttokens>=0:devel/py3-asttokens

USES=		python:3

.include "${MASTERDIR}/Makefile"
