# $FreeBSD: head/security/rubygem-metasploit-payloads/Makefile 445712 2017-07-13 21:13:51Z antoine $

PORTNAME=	metasploit-payloads
PORTVERSION=	1.2.37
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Compiled binaries for Metasploit's Meterpreter

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
STRIP=

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
