# $FreeBSD: head/security/rubygem-metasploit-payloads/Makefile 447622 2017-08-09 11:59:21Z antoine $

PORTNAME=	metasploit-payloads
PORTVERSION=	1.2.46
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Compiled binaries for Metasploit's Meterpreter

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
STRIP=
USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
