# $FreeBSD: head/devel/rubygem-ruby-fogbugz/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	ruby-fogbugz
PORTVERSION=	0.2.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@michael-fausten.de
COMMENT=	Simple Ruby wrapper for the Fogbugz XML API

LICENSE=	MIT

RUN_DEPENDS=	rubygem-crack>=0.4:devel/rubygem-crack

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
