# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-SparseM/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	SparseM
PORTVERSION=	1.77
PORTREVISION=	2
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Sparse Linear Algebra

LICENSE=	GPLv2+

USES=	cran:auto-plist,compiles

.include <bsd.port.mk>
