# $FreeBSD: head/devel/hs-HUnit/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	HUnit
PORTVERSION=	1.6.0.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unit testing framework for Haskell

LICENSE=	BSD3CLAUSE

USE_CABAL=	call-stack

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
