# Created by: Loïc BARTOLETTI <lbartoletti@tuxfamily.org>
# $FreeBSD: head/devel/py-pyqtree/Makefile 448950 2017-08-30 00:25:10Z dbaio $

PORTNAME=	pyqtree
PORTVERSION=	0.24
CATEGORIES=	devel python geography
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Pyqtree-${PORTVERSION}

MAINTAINER=	lbartoletti@tuxfamily.org
COMMENT=	Pure Python quad tree spatial index for GIS or rendering usage

LICENSE=	MIT

NO_ARCH=	yes

USES=		python zip
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
