# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/devel/pear-Horde_Itip/Makefile 411757 2016-03-24 07:39:22Z mm $

PORTNAME=	Horde_Itip
PORTVERSION=	2.1.2
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde iTip invitation response handling

USES=		horde
USE_HORDE_RUN=	Horde_Icalendar \
		Horde_Mime

.include <bsd.port.mk>
