# Created by: Mark Felder <feld@FreeBSD.org>
# $FreeBSD: head/devel/py-inflect/Makefile 481127 2018-10-02 19:06:16Z feld $

PORTNAME=	inflect
PORTVERSION=	0.2.5
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Generate plurals, singular nouns, ordinals, indefinite articles

LICENSE=	AGPLv3+

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
