# $FreeBSD: head/textproc/py-mkdocs-nature/Makefile 472884 2018-06-20 17:05:41Z mat $

PORTNAME=	mkdocs-nature
DISTVERSION=	0.2.1
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	freebsd_ports@k-worx.org
COMMENT=	MkDocs theme, a clone of the "greenish" Sphinx theme of the same name

LICENSE=	BSD2CLAUSE

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}mkdocs>0:textproc/py-mkdocs@${PY_FLAVOR}

USES=		python
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
