# Created by: Yoshihiko Sarumaru <mistral@imasy.or.jp>
# $FreeBSD: head/x11-fonts/bdfresize/Makefile 405891 2016-01-12 16:20:31Z amdmi3 $

PORTNAME=	bdfresize
PORTVERSION=	1.5
PORTREVISION=	2
CATEGORIES=	x11-fonts
MASTER_SITES=	http://openlab.ring.gr.jp/efont/dist/tools/bdfresize/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Tool for resizing BDF format font

LICENSE=	GPLv2+
LICENSE_FILE=	${WRKSRC}/COPYING

GNU_CONFIGURE=	yes
PLIST_FILES=	bin/bdfresize \
		man/man1/bdfresize.1.gz

.include <bsd.port.mk>
