# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: head/math/p5-Math-BaseCalc/Makefile 451003 2017-09-30 19:01:43Z jadawin $

PORTNAME=	Math-BaseCalc
PORTVERSION=	1.019
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jadawin@FreeBSD.org
COMMENT=	Convert numbers between various bases

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
