# $FreeBSD: head/devel/py-pyqi/Makefile 422697 2016-09-23 21:42:02Z jrm $

PORTNAME=	pyqi
PORTVERSION=	0.3.2
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jrm@FreeBSD.org
COMMENT=	Tools for developing and testing command line interfaces in Python

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes

USE_PYTHON=	autoplist distutils
USES=		pgsql python

.include <bsd.port.mk>
