# Created by: Espen Volden aka voldern <voldern@hoeggen.net>
# $FreeBSD: head/databases/rubygem-data_objects/Makefile 459043 2018-01-15 14:01:40Z swills $

PORTNAME=	data_objects
PORTVERSION=	0.10.17
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	voldern@hoeggen.net
COMMENT=	Unified Ruby API for popular databases

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-addressable>=2.1:www/rubygem-addressable

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
