# Created by: chinsan <chinsan.tw@gmail.com>
# $FreeBSD: head/sysutils/p5-BSD-Sysctl/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	BSD-Sysctl
PORTVERSION=	0.11
PORTREVISION=	2
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	david@landgren.net
COMMENT=	Fetch sysctl values from BSD-like systems

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
