# $FreeBSD: head/x11-drivers/xf86-video-sis/Makefile 441503 2017-05-23 05:03:14Z rezny $

PORTNAME=	xf86-video-sis
PORTVERSION=	0.10.9
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org sis display driver

USE_GL=		gl

XORG_CAT=	driver
USE_XORG=	xf86dgaproto

.include <bsd.port.mk>
