# Created by: Douglas Thrift <douglas@douglasthrift.net>
# $FreeBSD: head/net/p5-Net-Ping-External/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Net-Ping-External
PORTVERSION=	0.15
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	douglas@douglasthrift.net
COMMENT=	Perl cross-platform interface to ICMP "ping" utilities

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
