# $FreeBSD: head/databases/php72-interbase/Makefile 454302 2017-11-16 10:48:48Z tz $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php72

PKGNAMESUFFIX=	-interbase

.include "${MASTERDIR}/Makefile"
