# Created by: Gabor Kovesdan
# $FreeBSD: head/security/p5-Crypt-HCE_MD5/Makefile 412895 2016-04-10 06:50:33Z ashish $

PORTNAME=	Crypt-HCE_MD5
PORTVERSION=	0.75
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Perl extension implementing one way hash chaining encryption using MD5

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
