# Created by: estith
# $FreeBSD: head/devel/p5-Devel-SimpleTrace/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Devel-SimpleTrace
PORTVERSION=	0.08
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Perl module for better stack traces on interpreter-generated warn/die

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual
LICENSE_FILE_ART10=	${WRKSRC}/LICENSE.Artistic

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
