# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-glue/Makefile 449305 2017-09-05 17:15:34Z tota $

PORTNAME=	glue
PORTVERSION=	1.1.1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Interpreted String Literals

LICENSE=	MIT

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
