# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-glue/Makefile 475140 2018-07-23 02:57:15Z tota $

PORTNAME=	glue
PORTVERSION=	1.3.0
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Interpreted String Literals

LICENSE=	MIT

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
