# Created by: Andreas Fehlner (fehlner@gmx.de)
# $FreeBSD: head/german/geonext/Makefile 412346 2016-04-01 14:00:51Z mat $

CATEGORIES=	german

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Interactive (dynamic) elementary Geometry Software

RUN_DEPENDS=	geonext>=0:math/geonext

WITH_LANG=	de
MASTERDIR=	${.CURDIR}/../../math/geonext

.include "${MASTERDIR}/Makefile"
