# Created by: Douglas Thrift <douglas@douglasthrift.net>
# $FreeBSD: head/dns/rubygem-simpleidn/Makefile 436526 2017-03-20 00:28:57Z sunpoet $

PORTNAME=	simpleidn
PORTVERSION=	0.0.7
CATEGORIES=	dns rubygems
MASTER_SITES=	RG

MAINTAINER=	douglas@douglasthrift.net
COMMENT=	Easy conversion from IDNA strings to unicode strings and vice-versa

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENCE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
