# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-jsmin2/Makefile 481545 2018-10-08 15:08:13Z antoine $

PORTNAME=	jsmin
PORTVERSION=	2.0.1
CATEGORIES=	devel

MAINTAINER=	pascal.christen@hostpoint.ch
COMMENT=	PHP extension for minifying JavaScript

LICENSE=	PHP301

USES=		php:pecl
IGNORE_WITH_PHP=70 71 72 73

.include <bsd.port.mk>
