# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: head/textproc/p5-XML-Handler-Trees/Makefile 425174 2016-11-02 22:45:14Z mat $

PORTNAME=	XML-Handler-Trees
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	PerlSAX handlers for building tree structures

USES=		perl5 dos2unix
USE_PERL5=	configure
DOS2UNIX_FILES=	Trees.pm

.include <bsd.port.mk>
