# Created by: Fernan Aguero <fernan@iib.unsam.edu.ar>
# $FreeBSD: head/devel/p5-Data-Stag/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	Data-Stag
PORTVERSION=	0.14
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Structured Tags datastructures

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

RUN_DEPENDS=	p5-IO-String>=0:devel/p5-IO-String
BUILD_DEPENDS:=	${RUN_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
