# Created by: Fernan Aguero <fernan@iib.unsam.edu.ar>
# $FreeBSD: head/devel/p5-Data-Stag/Makefile 474242 2018-07-09 08:40:17Z mat $

PORTNAME=	Data-Stag
PORTVERSION=	0.14
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Structured Tags datastructures

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-IO-String>=0:devel/p5-IO-String

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
