# $FreeBSD: head/devel/hs-unliftio/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	unliftio
PORTVERSION=	0.2.9.0
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	MonadUnliftIO typeclass for unlifting monads to IO

LICENSE=	BSD3CLAUSE

USE_CABAL=	async unliftio-core

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
