# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/math/R-cran-geepack/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	geepack
PORTREVISION=	2
DISTVERSION=	1.2-1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Generalized Estimating Equation Package

LICENSE=	GPLv3

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
