# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/math/R-cran-geepack/Makefile 443845 2017-06-18 18:09:16Z dbn $

PORTNAME=	geepack
PORTREVISION=	1
DISTVERSION=	1.2-1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Generalized Estimating Equation Package

LICENSE=	GPLv3

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
