# $FreeBSD: head/www/rubygem-oembed/Makefile 447386 2017-08-05 03:25:17Z jrm $

PORTNAME=	oembed
PORTVERSION=	0.2.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Slim library to work with oEmbed format

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
