# Created by: Li-Wen Hsu <lwhsu@FreeBSD.org>
# $FreeBSD: head/databases/py-pymysql/Makefile 457309 2017-12-26 18:59:10Z lwhsu $

PORTNAME=	pymysql
PORTVERSION=	0.8.0
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	PyMySQL-${PORTVERSION}

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	Pure Python MySQL Driver

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
