# Created by: brd@FreeBSD.org
# $FreeBSD: head/net/p5-Net-NTP/Makefile 437360 2017-03-31 14:32:02Z brd $

PORTNAME=	Net-NTP
PORTVERSION=	1.5
CATEGORIES=	net
MASTER_SITES=	CPAN

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension for decoding NTP server responses

NO_ARCH=	yes
USE_PERL5=	configure
USES=		perl5

PLIST_FILES=	%%SITE_PERL%%/Net/NTP.pm \
		%%PERL5_MAN3%%/Net::NTP.3.gz

.include <bsd.port.mk>
