# $FreeBSD: head/devel/kf5-kitemmodels/Makefile 473503 2018-06-28 17:39:53Z tcberner $

PORTNAME=	kitemmodels
DISTVERSION=	${KDE_FRAMEWORKS_VERSION}
CATEGORIES=	devel kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KF5 models for Qt Model/View system

USES=		cmake:outsource compiler:c++11-lib kde:5 qt:5 tar:xz
USE_KDE=	ecm
USE_QT=		buildtools_build core qmake_build testlib_build

.include <bsd.port.mk>
