# Created by: tcberner
# $FreeBSD: head/devel/kf5-kitemmodels/Makefile 438880 2017-04-19 14:59:40Z tcberner $

PORTNAME=	kitemmodels
PORTVERSION=	${KDE_FRAMEWORKS_VERSION}
CATEGORIES=	devel kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KF5 models for Qt Model/View system

USES=		cmake:outsource compiler:c++11-lib kde:5 tar:xz
USE_KDE=	ecm
USE_QT5=	buildtools_build core qmake_build testlib_build

.include <bsd.port.mk>
