# Created by: Carlo Strub <cs@FreeBSD.org>
# $FreeBSD: head/devel/go-gocode/Makefile 428636 2016-12-15 22:01:45Z cs $

PORTNAME=	gocode
PORTVERSION=	20161122
CATEGORIES=	devel
PKGNAMEPREFIX=	go-

MAINTAINER=	cs@FreeBSD.org
COMMENT=	Autocompletion daemon for golang

LICENSE=	MIT

USE_GITHUB=	yes
GH_ACCOUNT=	nsf
GH_TAGNAME=	5070dacabf2a80deeaf4ddb0be3761d06fce7be5
USES=		go
GO_PKGNAME=	github.com/nsf/gocode
PLIST_FILES=	bin/gocode

.include <bsd.port.mk>
