# $FreeBSD: head/math/R-cran-pls/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	pls
DISTVERSION=	2.7-0
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Partial Least Squares and Principal Component Regression

LICENSE=	GPLv2

USES=		cran:auto-plist

.include <bsd.port.mk>
