# $FreeBSD: head/www/rubygem-jquery-atwho-rails13/Makefile 461935 2018-02-15 16:59:19Z tz $

PORTNAME=	jquery-atwho-rails
PORTVERSION=	1.3.2
CATEGORIES=	www rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	13

MAINTAINER=	idefix@fechner.net
COMMENT=	jQuery plugin that implements GitHub-like mentions

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE-MIT

PORTSCOUT=	limit:^1\.3

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
