# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/net/p5-Net-Ifconfig-Wrapper/Makefile 408465 2016-02-08 08:54:55Z jadawin $

PORTNAME=	Net-Ifconfig-Wrapper
PORTVERSION=	0.14
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Provides a unified way to configure network interfaces

LICENSE=	ARTPERL10

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
