# Created by: will
# $FreeBSD: head/devel/p5-String-Random/Makefile 470737 2018-05-23 23:24:33Z sunpoet $

PORTNAME=	String-Random
PORTVERSION=	0.30
PORTEPOCH=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl interface to generate "random" strings

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
