# $FreeBSD: head/devel/hs-newtype/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	newtype
PORTVERSION=	0.2
PORTREVISION=	5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Typeclass and set of functions for working with newtypes

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
