# $FreeBSD: head/devel/hs-newtype/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	newtype
PORTVERSION=	0.2
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Typeclass and set of functions for working with newtypes

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
