# Created by: tobias.rehbein@web.de
# $FreeBSD: head/games/stonesoup-sdl/Makefile 418927 2016-07-22 19:22:02Z pawel $

PORT_OPTIONS+=	SDL
PKGNAMESUFFIX=	-sdl

MASTERDIR=	${.CURDIR}/../stonesoup

.include	"${MASTERDIR}/Makefile"
