# Created by: Danilo G. Baio <dbaio@FreeBSD.org>
# $FreeBSD: head/devel/py3-ply/Makefile 440442 2017-05-08 17:21:49Z dbaio $

MASTERDIR=	${.CURDIR}/../py-ply

USES=	python:3.3+

.include "${MASTERDIR}/Makefile"
