# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/math/R-cran-lazyeval/Makefile 417639 2016-06-27 08:09:30Z wen $

PORTNAME=	lazyeval
DISTVERSION=	0.2.0
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Disciplined approach to non-standard evaluation

LICENSE=	GPLv3

USES=	cran:auto-plist

.include <bsd.port.mk>
