# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/math/R-cran-lazyeval/Makefile 453793 2017-11-09 06:07:12Z wen $

PORTNAME=	lazyeval
DISTVERSION=	0.2.1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Disciplined approach to non-standard evaluation

LICENSE=	GPLv3

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
