# Created by: Jov <amutu@amutu.com>
# $FreeBSD: head/devel/bazel-clang38/Makefile 446943 2017-07-30 21:46:10Z lwhsu $

MASTERDIR=	${.CURDIR}/../bazel
PKGNAMESUFFIX=	-clang38

MAINTAINER=	amutu@amutu.com

OPTIONS_SLAVE=	CLANG38

CONFLICTS_INSTALL=	bazel

.include "${MASTERDIR}/Makefile"
