# Created by: Jov <amutu@amutu.com>
# $FreeBSD: head/devel/bazel-clang38/Makefile 473023 2018-06-22 08:28:00Z yuri $

MASTERDIR=	${.CURDIR}/../bazel
PKGNAMESUFFIX=	-clang38

MAINTAINER=	ports@FreeBSD.org

OPTIONS_SLAVE=	CLANG38

CONFLICTS_INSTALL=	bazel

.include "${MASTERDIR}/Makefile"
