# $FreeBSD: head/databases/php73-pdo_pgsql/Makefile 490239 2019-01-14 11:05:43Z tz $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php73

PKGNAMESUFFIX=	-pdo_pgsql

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
