# $FreeBSD: head/math/hs-integer-logarithms/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	integer-logarithms
PORTVERSION=	1.0.2.2
PORTREVISION=	1
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	The integer-logarithms package

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
