# $FreeBSD: head/math/hs-integer-logarithms/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	integer-logarithms
PORTVERSION=	1.0.2
PORTREVISION=	1
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	The integer-logarithms package

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
