# $FreeBSD: head/math/hs-integer-logarithms/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	integer-logarithms
PORTVERSION=	1.0.2.1
PORTREVISION=	1
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	The integer-logarithms package

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
