# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/www/pear-Horde_Service_Facebook/Makefile 455798 2017-12-08 20:21:01Z joneum $

PORTNAME=	Horde_Service_Facebook
DISTVERSION=	2.0.10
CATEGORIES=	www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Facebook client

USES=	horde php
USE_PHP=	json simplexml
USE_HORDE_RUN=	Horde_Exception \
		Horde_Http \
		Horde_Translation \
		Horde_Support \
		Horde_Util

.include <bsd.port.mk>
