# $FreeBSD: head/devel/hs-edit-distance/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	edit-distance
PORTVERSION=	0.2.2.1
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Levenshtein and restricted Damerau-Levenshtein edit distances

LICENSE=	BSD3CLAUSE

USE_CABAL=	random>=1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
