# Created by: Zhihao Yuan <lichray@gmail.com>
# $FreeBSD: head/graphics/py-png/Makefile 432149 2017-01-22 14:38:44Z sunpoet $

PORTNAME=	png
PORTVERSION=	0.0.17
CATEGORIES=	graphics python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	py${PORTNAME}-${PORTVERSION}

MAINTAINER=	lichray@gmail.com
COMMENT=	Python PNG encoder/decoder

LICENSE=	MIT

NO_ARCH=	yes
USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
