# Created by: Ditesh Shashikant Gathani <ditesh@gathani.org>
# $FreeBSD: head/www/pear-Services_W3C_CSSValidator/Makefile 463917 2018-03-08 19:48:41Z mat $

PORTNAME=	Services_W3C_CSSValidator
PORTVERSION=	0.2.3
CATEGORIES=	www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PHP interface to W3C CSS Validator API

BUILD_DEPENDS=	${PEARDIR}/HTTP/Request2.php:www/pear-HTTP_Request2@${PHP_FLAVOR}
RUN_DEPENDS=	${PEARDIR}/HTTP/Request2.php:www/pear-HTTP_Request2@${PHP_FLAVOR}

USES=		pear

.include <bsd.port.mk>
