# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-uopz/Makefile 481545 2018-10-08 15:08:13Z antoine $

PORTNAME=	uopz
PORTVERSION=	2.0.7
PORTREVISION=	1
CATEGORIES=	devel

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	User Operations for PHP Zend engine

LICENSE=	PHP301

USES=		php:pecl
IGNORE_WITH_PHP=	70 71 72 73

.include <bsd.port.mk>
