# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-rstudioapi/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	rstudioapi
PORTVERSION=	0.7
PORTREVISION=	1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Safely Access the RStudio API

LICENSE=	MIT

USES=	cran:auto-plist

.include <bsd.port.mk>
