# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/py35-setuptools/Makefile 446095 2017-07-17 18:42:18Z sunpoet $

MASTERDIR=	${.CURDIR}/../py27-setuptools

PORTSCOUT=	ignore:1

USES=		python:3.5

.include "${MASTERDIR}/Makefile"
