# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/www/R-cran-httpuv/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	httpuv
PORTVERSION=	1.3.5
PORTREVISION=	1
CATEGORIES=	www
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	HTTP and WebSocket server library for R

LICENSE=	GPLv3

RUN_DEPENDS=	R-cran-Rcpp>=0.11.0:devel/R-cran-Rcpp

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
