# Created by: lbr@FreeBSD.org
# $FreeBSD: head/www/p5-Catalyst-Plugin-Setenv/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	Catalyst-Plugin-Setenv
PORTVERSION=	0.03
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Set up the environment from Catalyst's config file

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Catalyst-Runtime>=5.7000:www/p5-Catalyst-Runtime

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
