# Created by: Pawel Worach
# $FreeBSD: head/x11-fonts/font-winitzki-cyrillic/Makefile 381876 2015-03-21 23:05:19Z bapt $

PORTNAME=	font-winitzki-cyrillic
PORTVERSION=	1.0.3
PORTREVISION=	3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Winitzki Cyrillic font

XORG_CAT=	font

.include <bsd.port.mk>
