# $FreeBSD: head/x11-drivers/xf86-video-geode/Makefile 433863 2017-02-11 14:17:58Z rezny $

PORTNAME=	xf86-video-geode
PORTVERSION=	2.11.19
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org geode display driver

XORG_CAT=	driver

ONLY_FOR_ARCHS=	i386
ONLY_FOR_ARCHES_REASON=	Geode processors are 32bit x86 only

.include <bsd.port.mk>
