# $FreeBSD: head/x11/dri3proto/Makefile 433894 2017-02-11 17:05:42Z bapt $

PORTNAME=	dri3proto
PORTVERSION=	1.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	DRI3 prototype headers

LICENSE=	MIT

XORG_CAT=	proto

.include <bsd.port.mk>
