# Created by: stas
# $FreeBSD: head/devel/boehm-gc-threaded/Makefile 458406 2018-01-08 12:52:49Z cpm $

COMMENT=	Garbage collection and memory leak detection for C and C++ with threading support

LICENSE=	MIT

MASTERDIR=	${.CURDIR}/../boehm-gc
DESCR=		${.CURDIR}/pkg-descr

GC_VARIANT=	threaded

.include "${MASTERDIR}/Makefile"
