# $FreeBSD: head/devel/hs-foundation/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	foundation
PORTVERSION=	0.0.13
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A custom prelude with no dependencies apart from base

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
