# $FreeBSD: head/devel/hs-foundation/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	foundation
PORTVERSION=	0.0.20
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A custom prelude with no dependencies apart from base

LICENSE=	BSD3CLAUSE

USE_CABAL=	basement

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
