# $FreeBSD: head/misc/kde4-l10n-eu/Makefile 439367 2017-04-25 08:20:30Z riggs $

PORTNAME=	kde-l10n
PORTVERSION=	${KDE4_VERSION}
PORTREVISION=	1
CATEGORIES=	misc kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Basque messages and documentation for KDE SC 4

KDE4_L10N=	eu

.include "${.CURDIR}/../kde4-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
