# Created by: Lars Balker Rasmussen <lbr@FreeBSD.org>
# $FreeBSD: head/textproc/p5-Text-SimpleTable/Makefile 475242 2018-07-24 12:29:32Z wen $

PORTNAME=	Text-SimpleTable
PORTVERSION=	2.07
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simple Eyecandy ASCII Tables

LICENSE=	ART20
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
