# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/devel/pear-Console_Getargs/Makefile 443174 2017-06-11 07:29:56Z sunpoet $

PORTNAME=	Console_Getargs
PORTVERSION=	1.3.5
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR command-line arguments parser

USES=		pear

.include <bsd.port.mk>
