# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/textproc/R-cran-formatR/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	formatR
DISTVERSION=	1.5
PORTREVISION=	2
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Format R Code Automatically

LICENSE=	GPLv2+

USES=	cran:auto-plist

.include <bsd.port.mk>
