# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/www/rubygem-rack-protection/Makefile 489042 2019-01-01 20:40:11Z sunpoet $

PORTNAME=	rack-protection
PORTVERSION=	2.0.5
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Collection of Rack middleware to protect against opportunistic attack

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/License

RUN_DEPENDS=	rubygem-rack>=0:www/rubygem-rack

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
