# $FreeBSD: head/security/rubygem-net-telnet/Makefile 438735 2017-04-17 16:50:32Z miwi $

PORTNAME=	net-telnet
PORTVERSION=	0.1.1
PORTREVISION=	1
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Provides telnet client functionality

LICENSE=	BSD2CLAUSE RUBY
LICENSE_COMB=	dual
LICENSE_FILE_RUBY=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem shebangfix
SHEBANG_FILES=	bin/setup

.include <bsd.port.mk>
