# $FreeBSD: head/devel/geany-plugins-l10n/Makefile 416609 2016-06-09 15:24:55Z madpilot $

PORTNAME=	geany-plugins-l10n
PORTVERSION=	${GEANY_VER}
CATEGORIES=	devel

MAINTAINER=	madpilot@FreeBSD.org
COMMENT=	Localization messages for Geany plugins

NO_ARCH=	yes

.include "${.CURDIR}/../geany-plugins/files/Makefile.common"
.include <bsd.port.mk>
