# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/sysutils/php70-fileinfo/Makefile 422569 2016-09-21 15:43:47Z tz $

CATEGORIES=	sysutils

MASTERDIR=	${.CURDIR}/../../lang/php70

PKGNAMESUFFIX=	-fileinfo

.include "${MASTERDIR}/Makefile"
