# Created by: Masafumi NAKANE <max@FreeBSD.org>
# $FreeBSD: head/www/p5-WWW-Shorten-isgd/Makefile 412351 2016-04-01 14:33:55Z mat $

PORTNAME=	WWW-Shorten-isgd
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Abstract interface to is.gd, one of URL shortening sites

BUILD_DEPENDS=	p5-WWW-Shorten>=1.97:www/p5-WWW-Shorten
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
