# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/mail/rubygem-email_reply_parser-discourse/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	email_reply_parser-discourse
PORTVERSION=	0.6
CATEGORIES=	mail rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Email Reply Parser

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
