# Created by: Andrew Pantyukhin <infofarmer@FreeBSD.org>
# $FreeBSD: head/textproc/supercat/Makefile 430357 2017-01-02 14:12:55Z rakuco $

PORTNAME=	supercat
PORTVERSION=	0.5.6
CATEGORIES=	textproc
MASTER_SITES=	http://supercat.nosredna.net/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Regexp-based text colorizer with ASCII/HTML output

CONFIGURE_ARGS=	--with-system-directory=${ETCDIR}
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
