# Created by: Shane Ambler <FreeBSD@Shaneware.biz>
# $FreeBSD: head/graphics/opencolorio-tools/Makefile 408830 2016-02-13 21:58:38Z pi $

PKGNAMESUFFIX=	-tools

COMMENT=	Tools to work with OpenColorIO profiles

MASTERDIR=	${.CURDIR}/../opencolorio
OCIO_SLAVE=	tools
OPTIONS_EXCLUDE=DOCS

.include "${MASTERDIR}/Makefile"
