# Created by: never@nevermind.kiev.ua
# $FreeBSD: head/devel/publib/Makefile 434587 2017-02-22 15:02:18Z bapt $

PORTNAME=	publib
PORTVERSION=	0.40
CATEGORIES=	devel
MASTER_SITES=	http://ftp.debian.org/debian/pool/main/p/publib/
DISTNAME=	publib_${PORTVERSION}.orig

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Library of C functions for various purposes

LICENSE=	BSD2CLAUSE

GNU_CONFIGURE=	yes

WRKSRC=		${WRKDIR}/${PORTNAME}-${PORTVERSION}

.include <bsd.port.mk>
