# $FreeBSD: head/devel/hs-hex/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	hex
PORTVERSION=	0.1.2
PORTREVISION=	5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Convert strings into hexadecimal and back

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
