# $FreeBSD: head/devel/hs-hex/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	hex
PORTVERSION=	0.1.2
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Convert strings into hexadecimal and back

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
