# Created by: Pedro Giffuni
# $FreeBSD: head/devel/R-cran-crayon/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	crayon
DISTVERSION=	1.3.4
PORTREVISION=	2
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Colored Terminal Output

LICENSE=	MIT

USES=		cran:auto-plist

.include <bsd.port.mk>
