# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/devel/py-shapely/Makefile 449172 2017-09-03 06:47:50Z wen $

PORTNAME=	Shapely
PORTVERSION=	1.6.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Python Package for Manipulation 2D Geospatial Geometry

LICENSE=	BSD3CLAUSE

LIB_DEPENDS=	libgeos_c.so:graphics/geos

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
