# Created by: Wei-chun Chao
# $FreeBSD: head/net-mgmt/p5-Net-Netmask/Makefile 471743 2018-06-05 05:34:49Z wen $

PORTNAME=	Net-Netmask
PORTVERSION=	1.9101
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module to parse, manipulate, and lookup IP network blocks

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
