# Created by: Joseph Scott <joseph@randomnetworks.com>
# $FreeBSD: head/devel/pear-Text_Diff/Makefile 443239 2017-06-11 07:37:07Z sunpoet $

PORTNAME=	Text_Diff
PORTVERSION=	1.1.1
CATEGORIES=	devel pear

MAINTAINER=	joseph@randomnetworks.com
COMMENT=	Engine for performing and rendering text diffs

USES=		pear

.include <bsd.port.mk>
