# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: head/textproc/rubygem-loofah/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	loofah
PORTVERSION=	2.0.3
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Library for manipulating HTML/XML documents and fragments

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE.txt

RUN_DEPENDS=	rubygem-nokogiri>=1.5.9:textproc/rubygem-nokogiri

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
