# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-expm/Makefile 480716 2018-09-26 06:19:44Z tota $

PORTNAME=	expm
DISTVERSION=	0.999-3
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Matrix Exponential, Log, 'etc'

LICENSE=	GPLv2+

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
