# $FreeBSD: head/x11/xkbutils/Makefile 479538 2018-09-11 18:34:27Z zeising $

PORTNAME=	xkbutils
PORTVERSION=	1.0.4
PORTREVISION=	2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XKB utility demos

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	xkbfile x11 xaw xorgproto

.include <bsd.port.mk>
