# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: head/textproc/R-cran-pystr/Makefile 443845 2017-06-18 18:09:16Z dbn $

PORTNAME=	pystr
PORTREVISION=	1
DISTVERSION=	2.0.0
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	String operations the Python way

RUN_DEPENDS=	R-cran-Rcpp>=0.11.4.6:devel/R-cran-Rcpp

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
