# Created by: Martin Matuska <martin@matuska.org>
# $FreeBSD: head/databases/luasql-sqlite3/Makefile 413574 2016-04-18 14:06:51Z mat $

LUASQL_DRIVER=	sqlite3

MASTERDIR=	${.CURDIR}/../luasql-mysql

.include "${MASTERDIR}/Makefile"
