# $FreeBSD: head/sysutils/firstboot-freebsd-update/Makefile 430932 2017-01-09 09:54:20Z amdmi3 $

PORTNAME=	firstboot-freebsd-update
PORTVERSION=	1.2
CATEGORIES=	sysutils
MASTER_SITES=	# none
DISTFILES=	# none
EXTRACT_ONLY=	# none

MAINTAINER=	cperciva@FreeBSD.org
COMMENT=	Update the system using freebsd-update when it first boots

NO_WRKSUBDIR=	yes
NO_BUILD=	yes
NO_INSTALL=	yes
NO_ARCH=	yes

USE_RC_SUBR=	firstboot_freebsd_update

.include <bsd.port.mk>
