# $FreeBSD: head/audio/rtaudio/Makefile 453464 2017-11-04 13:53:23Z yuri $

PORTNAME=	rtaudio
DISTVERSIONPREFIX=	v
DISTVERSION=	5.0.0
CATEGORIES=	audio

MAINTAINER=	yuri@FreeBSD.org
COMMENT=	C++ classes that provide a common API for realtime audio input/output

LICENSE=	MIT

USES=		autoreconf libtool pkgconfig
USE_GITHUB=	yes
GH_ACCOUNT=	thestk
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
