# $FreeBSD: head/sysutils/syslog-ng/Makefile 450628 2017-09-25 18:51:17Z cy $

VERSIONS=		36 37 39 310 311 312
SYSLOG_NG_VERSION?=	311

MASTERDIR=		${.CURDIR}/../syslog-ng${SYSLOG_NG_VERSION}

.include "${MASTERDIR}/Makefile"
