# $FreeBSD: head/sysutils/syslog-ng/Makefile 444618 2017-06-29 01:11:52Z cy $

VERSIONS=		36 37 39 310
SYSLOG_NG_VERSION?=	37

MASTERDIR=		${.CURDIR}/../syslog-ng${SYSLOG_NG_VERSION}

.include "${MASTERDIR}/Makefile"
