# Created by: Zach Thompson <hideo@lastamericanempire.com>
# $FreeBSD: head/devel/p5-Rose-Object/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Rose-Object
PORTVERSION=	0.860
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simple object base class

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Class-XSAccessor>=0:devel/p5-Class-XSAccessor

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
