# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/security/rubygem-ed25519/Makefile 495162 2019-03-09 14:38:16Z sunpoet $

PORTNAME=	ed25519
PORTVERSION=	1.2.4
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Ruby binding to the Ed25519 (RFC 8032)

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
