# Created by: Samy Al Bahra <sbahra@kerneled.org>
# $FreeBSD: head/textproc/hs-stringsearch/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	stringsearch
PORTVERSION=	0.3.6.6
PORTREVISION=	4
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast searching, splitting and replacing of ByteStrings

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
