# Created by: Christer Edwards <christer.edwards@gmail.com>
# $FreeBSD: head/devel/py-ioflo/Makefile 462307 2018-02-19 11:10:43Z antoine $

PORTNAME=	ioflo
PORTVERSION=	1.5.0
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	christer.edwards@gmail.com
COMMENT=	Automated Reasoning Engine and Flow Based Programming Framework

LICENSE=	APACHE20

USES=		python:2.7 shebangfix
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

SHEBANG_FILES=	scripts/ioflo

.include <bsd.port.mk>
