# Created by: Emanuel Haupt <ehaupt@FreeBSD.org>
# $FreeBSD: head/textproc/py-QDarkStyle/Makefile 491737 2019-01-31 15:29:58Z ehaupt $

PORTNAME=	QDarkStyle
PORTVERSION=	2.6.5
CATEGORIES=	textproc devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ehaupt@FreeBSD.org
COMMENT=	Dark stylesheet for Python and Qt applications

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.md

USES=		python
USE_PYTHON=	autoplist concurrent distutils

NO_ARCH=	yes

.include <bsd.port.mk>
