# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: head/mail/p5-Email-Address/Makefile 463752 2018-03-06 20:31:51Z sunpoet $

PORTNAME=	Email-Address
PORTVERSION=	1.909
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	RFC 2822 Address Parsing and Creation

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

# This port is still used by many ports
DEPRECATED=	Deprecated by upstream
EXPIRATION_DATE=2018-12-31

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
