# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: head/mail/p5-Email-Address/Makefile 435027 2017-02-28 09:47:13Z sunpoet $

PORTNAME=	Email-Address
PORTVERSION=	1.908
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	RFC 2822 Address Parsing and Creation

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
