# $FreeBSD: head/textproc/hs-appar/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	appar
PORTVERSION=	0.1.4
PORTREVISION=	6
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple applicative parser

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
