# $FreeBSD: head/textproc/hs-appar/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	appar
PORTVERSION=	0.1.4
PORTREVISION=	5
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple applicative parser

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
