# Created by: Leo Kim <leo@florida.sarang.net>
# $FreeBSD: head/audio/p5-MP3-Info/Makefile 478112 2018-08-26 09:38:36Z amdmi3 $

PORTNAME=	MP3-Info
PORTVERSION=	1.24
PORTREVISION=	1
CATEGORIES=	audio perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Manipulate / fetch info from MP3 audio files

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
