# Created by: Danilo G. Baio <dbaio@bsd.com.br>
# $FreeBSD: head/devel/py3-colorama/Makefile 437659 2017-04-03 13:20:36Z skreuzer $

MASTERDIR=	${.CURDIR}/../py-colorama

USES=	python:3.3+

.include "${MASTERDIR}/Makefile"
