# Created by: renchap@cocoa-x.com
# $FreeBSD: head/devel/rubygem-moneta06/Makefile 457530 2017-12-29 18:47:53Z sunpoet $

PORTNAME=	moneta
PORTVERSION=	0.6.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	06

MAINTAINER=	renchap@cocoa-x.com
COMMENT=	Unified interface to key/value stores

DEPRECATED=	Use devel/rubygem-moneta instead
EXPIRATION_DATE=2018-01-31

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
