# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: head/textproc/rubygem-rchardet/Makefile 458449 2018-01-08 16:52:30Z sunpoet $

PORTNAME=	rchardet
PORTVERSION=	1.7.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Character encoding auto-detection in Ruby

LICENSE=	LGPL21

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
