# Created by: Ying-Chieh Liao <ijliao@FreeBSD.org>
# $FreeBSD: head/devel/p5-Perl-Tidy/Makefile 462301 2018-02-19 10:30:50Z sunpoet $

PORTNAME=	Perl-Tidy
PORTVERSION=	20180219
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Indents and reformats Perl scripts to make them easier to read

LICENSE=	GPLv2

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
