# Created by: Antoine Brodin <antoine@FreeBSD.org>
# $FreeBSD: head/textproc/py-xlsxwriter/Makefile 445341 2017-07-08 16:57:36Z antoine $

PORTNAME=	XlsxWriter
PORTVERSION=	0.9.8
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Python module for creating Excel XLSX files

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes
USES=		python
USE_PYTHON=	concurrent distutils autoplist

.include <bsd.port.mk>
