# Created by: Antoine Brodin <antoine@FreeBSD.org>
# $FreeBSD: head/textproc/py-xlsxwriter/Makefile 470773 2018-05-24 12:18:54Z antoine $

PORTNAME=	XlsxWriter
PORTVERSION=	1.0.5
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Python module for creating Excel XLSX files

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes
USES=		python
USE_PYTHON=	concurrent distutils autoplist

.include <bsd.port.mk>
