# $FreeBSD: head/devel/hs-unicode-show/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	unicode-show
PORTVERSION=	0.1.0.2
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Print and show in unicode

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
