# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/math/py-vincenty/Makefile 486341 2018-12-01 13:05:31Z sunpoet $

PORTNAME=	vincenty
PORTVERSION=	0.1.4
CATEGORIES=	math python geography
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Calculate the geographical distance between 2 points

LICENSE=	UNLICENSE

USES=		python
USE_PYTHON=	autoplist concurrent distutils

NO_ARCH=	yes

.include <bsd.port.mk>
