# Created by: alexander smishlajev
# $FreeBSD: head/devel/py-decoratortools/Makefile 455441 2017-12-03 20:35:07Z sunpoet $

PORTNAME=	DecoratorTools
PORTVERSION=	1.8
PORTREVISION=	3
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Class, function, and metaclass decorators

LICENSE=	PSFL ZPL21
LICENSE_COMB=	dual

NO_ARCH=	yes
USE_PYTHON=	autoplist distutils
USES=		python:2.7 zip

.include <bsd.port.mk>
