# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/math/R-cran-miscTools/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	miscTools
DISTVERSION=	0.6-22
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Miscellaneous small tools and utilities for R

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=		cran:auto-plist

.include <bsd.port.mk>
