# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: head/textproc/p5-Text-Truncate/Makefile 437950 2017-04-07 18:50:22Z lth $

PORTNAME=	Text-Truncate
PORTVERSION=	1.06
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module with simple string truncating routine

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
