# Created by: Dan Rench <citric@cubicone.tmetic.com>
# $FreeBSD: head/converters/p5-MIME-Base64-URLSafe/Makefile 492552 2019-02-10 00:06:48Z sunpoet $

PORTNAME=	MIME-Base64-URLSafe
PORTVERSION=	0.01
PORTREVISION=	2
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	citric@cubicone.tmetic.com
COMMENT=	Perl version of Python's URL-safe base64 codec

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
