# Created by: Nick Hilliard <nick@foobar.org>
# $FreeBSD: head/devel/pear-Structures_DataGrid/Makefile 443232 2017-06-11 07:36:32Z sunpoet $

PORTNAME=	Structures_DataGrid
PORTVERSION=	0.9.3
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Full-featured tabular structured data management package

RUN_DEPENDS=	${PEARDIR}/Console/Table.php:devel/pear-Console_Table

USES=		pear

.include <bsd.port.mk>
