# Created by: Li-Wen Hsu <lwhsu@lwhsu.org>
# $FreeBSD: head/www/trac-privatetickets/Makefile 451328 2017-10-05 18:05:36Z joneum $

PORTNAME=	privatetickets
PORTVERSION=	2.2.0
CATEGORIES=	www devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	trac-
DISTNAME=	TracPrivateTickets-${PORTVERSION}

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Modified ticket security for Trac

LICENSE=	BSD2CLAUSE

RUN_DEPENDS=	tracd:www/trac

USES=		python
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
