# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: head/devel/rubygem-deprecated2/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	deprecated
PORTVERSION=	2.0.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	2

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Version 2 of this library intended to aid working with deprecated code

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

PORTSCOUT=	limit:^2\.[0-9]*

.include <bsd.port.mk>
