# $FreeBSD: head/devel/hs-parallel/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	parallel
PORTVERSION=	3.2.1.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Parallel programming library

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
