# $FreeBSD: head/devel/pear-Date_Holidays_PHPdotNet/Makefile 488140 2018-12-22 22:43:18Z joneum $

PORTNAME=	Date_Holidays_PHPdotNet
PORTVERSION=	0.1.2
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Driver based class to calculate birthdays of members of PHP.net

LICENSE=	PHP301

BUILD_DEPENDS=	${PEARDIR}/Date/Holidays.php:devel/pear-Date_Holidays@${PHP_FLAVOR}
RUN_DEPENDS=	${PEARDIR}/Date/Holidays.php:devel/pear-Date_Holidays@${PHP_FLAVOR}

USES=		pear

.include <bsd.port.mk>
