# $FreeBSD: head/devel/pear-Date_Holidays_PHPdotNet/Makefile 443189 2017-06-11 07:31:11Z sunpoet $

PORTNAME=	Date_Holidays_PHPdotNet
PORTVERSION=	0.1.2
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Driver based class to calculate birthdays of members of PHP.net

BUILD_DEPENDS=	${PEARDIR}/Date/Holidays.php:devel/pear-Date_Holidays
RUN_DEPENDS=	${PEARDIR}/Date/Holidays.php:devel/pear-Date_Holidays

USES=		pear

.include <bsd.port.mk>
