# Created by: Yuri Victorovich <yuri@rawbw.com>
# $FreeBSD: head/misc/py-python-geohash/Makefile 462887 2018-02-25 00:40:37Z yuri $

PORTNAME=	python-geohash
PORTVERSION=	0.8.5
PORTREVISION=	1
CATEGORIES=	misc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	yuri@FreeBSD.org
COMMENT=	Fast, accurate python geohashing library

LICENSE=	APACHE20 MIT BSD3CLAUSE
LICENSE_COMB=	multi

USES=		python:2.7
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
