# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-deldir/Makefile 440295 2017-05-06 23:07:40Z tota $

PORTNAME=	deldir
DISTVERSION=	0.1-14
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Delaunay Triangulation and Dirichlet (Voronoi) Tessellation

LICENSE=	GPLv2+

USES=	cran:auto-plist,compiles

.include <bsd.port.mk>
