# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-deldir/Makefile 467033 2018-04-11 08:02:45Z tota $

PORTNAME=	deldir
DISTVERSION=	0.1-15
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Delaunay Triangulation and Dirichlet (Voronoi) Tessellation

LICENSE=	GPLv2+

USES=	cran:auto-plist,compiles

.include <bsd.port.mk>
