# Created by: Bill Brinzer <bill.brinzer@gmail.com>
# $FreeBSD: head/devel/p5-Capture-Tiny/Makefile 437985 2017-04-08 07:29:06Z wen $

PORTNAME=	Capture-Tiny
PORTVERSION=	0.46
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:DAGOLDEN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bill.brinzer@gmail.com
COMMENT=	Capture STDOUT and STDERR from Perl, XS, or external programs

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

TEST_DEPENDS=	p5-Inline>=0.50:devel/p5-Inline

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
