# $FreeBSD: head/devel/hs-generic-deriving/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	generic-deriving
PORTVERSION=	1.12.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Generic programming library for generalised deriving

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
