# $FreeBSD: head/devel/hs-generic-deriving/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	generic-deriving
PORTVERSION=	1.11.2
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Generic programming library for generalised deriving

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
