# Created by: Dmitry Marakasov <amdmi3@FreeBSD.org>
# $FreeBSD: head/www/rubygem-net-http-pipeline/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	net-http-pipeline
PORTVERSION=	1.0.1
CATEGORIES=	www net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	HTTP/1.1 pipelining implementation atop Net::HTTP

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
