# Created by: Shin-ya MURAKAMI <murashin@gfd-dennou.org>
# $FreeBSD: head/math/rubygem-narray/Makefile 414148 2016-04-27 23:30:19Z swills $

PORTNAME=	narray
PORTVERSION=	${NARRAY_VERSION}
CATEGORIES=	math rubygems
MASTER_SITES=	RG

MAINTAINER=	murashin@gfd-dennou.org
COMMENT=	Numerical N-dimensional array library for Ruby

USE_RUBY=	yes
USES=		gem

.include "${.CURDIR}/Makefile.version"

.include <bsd.port.mk>
