# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/www/pear-Services_Blogging/Makefile 443353 2017-06-11 07:47:36Z sunpoet $

PORTNAME=	Services_Blogging
PORTVERSION=	0.2.4
CATEGORIES=	www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PHP interface to Blog

BUILD_DEPENDS=	${PEARDIR}/XML/RPC.php:net/pear-XML_RPC
RUN_DEPENDS=	${PEARDIR}/XML/RPC.php:net/pear-XML_RPC

USES=		pear

.include <bsd.port.mk>
