# $FreeBSD: head/x11-drivers/xf86-video-s3virge/Makefile 433863 2017-02-11 14:17:58Z rezny $

PORTNAME=	xf86-video-s3virge
PORTVERSION=	1.10.7
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org s3virge display driver

XORG_CAT=	driver

.include <bsd.port.mk>
