# Created by: David Naylor <naylor.b.david@gmail.com>
# $FreeBSD: head/math/R-cran-quadprog/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	quadprog
DISTVERSION=	1.5-5
PORTREVISION=	7
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	Functions to solve Quadratic Programming Problems

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
