# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-MSwM/Makefile 475009 2018-07-20 12:18:37Z tota $

PORTNAME=	MSwM
PORTVERSION=	1.4
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Fitting Markov Switching Models

LICENSE=	GPLv2+

USES=	cran:auto-plist

.include <bsd.port.mk>
