# $FreeBSD: head/devel/rubygem-graphql/Makefile 492909 2019-02-14 08:59:13Z mfechner $

PORTNAME=	graphql
PORTVERSION=	1.8.15
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	mfechner@FreeBSD.org
COMMENT=	Plain-Ruby implementation of GraphQL

LICENSE=	MIT

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
