# $FreeBSD: head/devel/erlang-rebar3_hex/Makefile 472000 2018-06-08 13:43:25Z olgeni $

PORTNAME=	rebar3_hex
PORTVERSION=	2.5.0
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	erlang@FreeBSD.org
COMMENT=	Rebar3 Hex library

LICENSE=	BSD3CLAUSE

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	hexpm

.include <bsd.port.mk>
