# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/graphics/R-cran-colorspace/Makefile 428619 2016-12-15 14:48:41Z tota $

PORTNAME=	colorspace
DISTVERSION=	1.3-2
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Color Space Manipulation

LICENSE=	BSD3CLAUSE

USES=	cran:auto-plist,compiles

.include <bsd.port.mk>
