# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/graphics/R-cran-colorspace/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	colorspace
DISTVERSION=	1.3-2
PORTREVISION=	1
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Color Space Manipulation

LICENSE=	BSD3CLAUSE

USES=	cran:auto-plist,compiles

.include <bsd.port.mk>
