# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: head/mail/p5-URI-imap/Makefile 437950 2017-04-07 18:50:22Z lth $

PORTNAME=	URI-imap
PORTVERSION=	1.01
PORTREVISION=	1
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	URI::imap - Support IMAP URI

BUILD_DEPENDS=	p5-URI>=0:net/p5-URI
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
