# $FreeBSD: head/textproc/hs-html/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	html
PORTVERSION=	1.0.1.2
PORTREVISION=	16
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	HTML combinator library

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
