# $FreeBSD: head/devel/sparc64-gcc/Makefile 469834 2018-05-13 21:46:05Z kan $

PKGNAMEPREFIX=	sparc64-
PLIST=	${.CURDIR}/pkg-plist

BROKEN_aarch64=		fails to package

MASTERDIR=	${.CURDIR}/../powerpc64-gcc

.include "${MASTERDIR}/Makefile"
