# $FreeBSD: head/devel/erlang-ssl_verify_fun/Makefile 472000 2018-06-08 13:43:25Z olgeni $

PORTNAME=	ssl_verify_fun
PORTVERSION=	1.1.3
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	erlang@FreeBSD.org
COMMENT=	Erlang library for certificate hostname validation

LICENSE=	MIT

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	deadtrickster
GH_PROJECT=	ssl_verify_fun.erl

.include <bsd.port.mk>
