# Created by: Pedro Giffuni
# $FreeBSD: head/math/R-cran-combinat/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	combinat
DISTVERSION=	0.0-8
PORTREVISION=	2
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	pfg@FreeBSD.org
COMMENT=	Routines for combinatorics

LICENSE=	GPLv2

USES=		cran:auto-plist

.include <bsd.port.mk>
