# Created by: Pedro Giffuni
# $FreeBSD: head/math/R-cran-combinat/Makefile 446648 2017-07-26 08:44:49Z wen $

PORTNAME=	combinat
DISTVERSION=	0.0-8
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	pfg@FreeBSD.org
COMMENT=	Routines for combinatorics

LICENSE=	GPLv2

USES=		cran:auto-plist

.include <bsd.port.mk>
