# $FreeBSD: head/devel/hs-abstract-par/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	abstract-par
PORTVERSION=	0.3.3
PORTREVISION=	6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Type classes generalizing the functionality of the 'monad-par' library

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
