# $FreeBSD: head/devel/hs-abstract-par/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	abstract-par
PORTVERSION=	0.3.3
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Type classes generalizing the functionality of the 'monad-par' library

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
