# $FreeBSD: head/devel/hs-hourglass/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	hourglass
PORTVERSION=	0.2.10
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple performant time related library

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
