# $FreeBSD: head/devel/hs-hourglass/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	hourglass
PORTVERSION=	0.2.10
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple performant time related library

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
