# $FreeBSD: head/devel/hs-hourglass/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	hourglass
PORTVERSION=	0.2.11
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple performant time related library

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
