# Created by: Shane Ambler
# $FreeBSD: head/graphics/py-openimageio/Makefile 486968 2018-12-08 17:39:17Z pi $

CATEGORIES=	graphics multimedia python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

COMMENT=	OpenImageIO python bindings

MASTERDIR=	${.CURDIR}/../openimageio
OPTIONS_EXCLUDE=${OPTIONS_DEFINE}

.include "${MASTERDIR}/Makefile"
