# Created by: Johannes Meixner <johannes@perceivon.net>
# $FreeBSD: head/www/rubygem-ace-rails-ap/Makefile 485623 2018-11-22 20:48:20Z sunpoet $

PORTNAME=	ace-rails-ap
PORTVERSION=	4.1.5
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ajax.org Cloud9 Editor (Ace) for the Rails 3.1 asset pipeline

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem shebangfix
USE_RUBY=	yes

NO_ARCH=	yes

SHEBANG_FILES=	update.sh

.include <bsd.port.mk>
