# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-allison/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	allison
PORTVERSION=	2.0.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Modern, pretty RDoc template

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

PLIST_FILES=	bin/allison

.include <bsd.port.mk>
