# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: head/devel/p5-Set-Scalar/Makefile 479390 2018-09-10 11:16:59Z des $

PORTNAME=	Set-Scalar
PORTVERSION=	1.29
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module containing a set of scalars, including references

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

NO_ARCH=	yes

.include <bsd.port.mk>
