# Created by: chinsan
# $FreeBSD: head/security/p5-HTML-Email-Obfuscate/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	HTML-Email-Obfuscate
PORTVERSION=	1.00
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Obfuscates HTML email addresses that look normal

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-HTML-Parser>=0:www/p5-HTML-Parser

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
