# $FreeBSD: head/devel/hs-murmur-hash/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	murmur-hash
PORTVERSION=	0.1.0.9
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	MurmurHash2 implementation for Haskell

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
