# $FreeBSD: head/devel/hs-murmur-hash/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	murmur-hash
PORTVERSION=	0.1.0.9
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	MurmurHash2 implementation for Haskell

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
