# Created by: Bruce M Simpson <bms@FreeBSD.org>
# $FreeBSD: head/astro/gpstk/Makefile 447064 2017-08-01 18:03:36Z tcberner $

PORTNAME=	gpstk
PORTVERSION=	2.9
DISTVERSIONPREFIX=	v
CATEGORIES=	astro devel

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Toolkit for developing GPS applications

LICENSE=	LGPL3

USES=		cmake:outsource python:run
USE_GCC=	yes
USE_LDCONFIG=	yes

USE_GITHUB=	yes
GH_ACCOUNT=	SGL-UT
GH_PROJECT=	GPSTk

.include <bsd.port.mk>
