# Created by: Bruce M Simpson <bms@FreeBSD.org>
# $FreeBSD: head/astro/gpstk/Makefile 453450 2017-11-04 11:33:25Z vanilla $

PORTNAME=	gpstk
PORTVERSION=	2.10
DISTVERSIONPREFIX=	v
CATEGORIES=	astro devel

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Toolkit for developing GPS applications

LICENSE=	LGPL3

USES=		cmake:outsource
USE_LDCONFIG=	yes

USE_GITHUB=	yes
GH_ACCOUNT=	SGL-UT
GH_PROJECT=	GPSTk

.include <bsd.port.mk>
