# Created by: Tom Judge <tom@tomjudge.com>
# $FreeBSD: head/sysutils/p5-File-Log/Makefile 484353 2018-11-06 21:13:54Z rene $

PORTNAME=		File-Log
PORTVERSION=		1.05
PORTREVISION=	1
CATEGORIES=		sysutils perl5
MASTER_SITES=		CPAN
PKGNAMEPREFIX=		p5-

MAINTAINER=		perl@FreeBSD.org
COMMENT=		Simple Object Orientated Logger

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
