# $FreeBSD: head/devel/hs-transformers-base/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	transformers-base
PORTVERSION=	0.4.4
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Lift computations from the bottom of a transformer stack

LICENSE=	BSD3CLAUSE

USE_CABAL=	transformers-compat>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
