# $FreeBSD: head/devel/hs-transformers-base/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	transformers-base
PORTVERSION=	0.4.4
PORTREVISION=	5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Lift computations from the bottom of a transformer stack

LICENSE=	BSD3CLAUSE

USE_CABAL=	transformers-compat>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
