# $FreeBSD: head/textproc/rubygem-asciidoctor-diagram/Makefile 487083 2018-12-09 20:26:13Z swills $

PORTNAME=	asciidoctor-diagram
PORTVERSION=	1.5.10
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	numisemis@yahoo.com
COMMENT=	Asciidoctor diagramming extension

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

RUN_DEPENDS=	rubygem-asciidoctor>=1.5:textproc/rubygem-asciidoctor

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
