# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: head/net-mgmt/p5-Net-IP-Match-XS/Makefile 479390 2018-09-10 11:16:59Z des $

PORTNAME=	Net-IP-Match-XS
PORTVERSION=	0.03
PORTREVISION=	1
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Efficiently match IP addresses against IP ranges

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
