# $FreeBSD: head/x11-drivers/xf86-video-rendition/Makefile 479538 2018-09-11 18:34:27Z zeising $

PORTNAME=	xf86-video-rendition
PORTVERSION=	4.2.7
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org rendition display driver

XORG_CAT=	driver

.include <bsd.port.mk>
