# $FreeBSD: head/x11-drivers/xf86-video-rendition/Makefile 433863 2017-02-11 14:17:58Z rezny $

PORTNAME=	xf86-video-rendition
PORTVERSION=	4.2.6
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org rendition display driver

XORG_CAT=	driver

.include <bsd.port.mk>
