# $FreeBSD: head/x11-drivers/xf86-video-mach64/Makefile 479538 2018-09-11 18:34:27Z zeising $

PORTNAME=	xf86-video-mach64
PORTVERSION=	6.9.6
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org mach64 display driver

USE_GL=		gl
XORG_CAT=	driver

.include <bsd.port.mk>
