# $FreeBSD: head/multimedia/gstreamer1-plugins-mpeg2dec/Makefile 405242 2016-01-04 14:21:56Z kwm $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	GStreamer mpeg decode plugin

GST_PLUGIN=	mpeg2dec
DIST=		ugly

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
