# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libXinerama/Makefile 474036 2018-07-06 19:57:19Z zeising $

PORTNAME=	libXinerama
PORTVERSION=	1.1.4
PORTEPOCH=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X11 Xinerama library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 xext xextproto xineramaproto:both
USES+=	cpe
CPE_PRODUCT=	libxinerama
CPE_VENDOR=	x

.include <bsd.port.mk>
