# Created by: Muhammad Moinur Rahman<bofh@FreeBSD.org>
# $FreeBSD: head/devel/pecl-raphf2/Makefile 489349 2019-01-05 15:47:56Z rene $

PORTNAME=	raphf
PORTVERSION=	2.0.0
PORTREVISION=	1
CATEGORIES=	devel

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Resource and persistent handles factory

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

PORTSCOUT=	limit:^2.*

USES=		gmake php:pecl
CONFLICTS=	pecl-raphf-1*

.include <bsd.port.mk>
