# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/xf86dgaproto/Makefile 469439 2018-05-09 09:04:01Z amdmi3 $

PORTNAME=	xf86dgaproto
PORTVERSION=	2.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XFree86-DGA extension headers

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

XORG_CAT=	proto

.include <bsd.port.mk>
