# Created by: chinsan
# $FreeBSD: head/finance/p5-Business-TW-Invoice-U420/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	Business-TW-Invoice-U420
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	finance perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Print Taiwan Unified Invoice with U420 printer

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Class-Accessor>=0:devel/p5-Class-Accessor

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
