# Created by: chinsan
# $FreeBSD: head/finance/p5-Business-TW-Invoice-U420/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	Business-TW-Invoice-U420
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	finance perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Print Taiwan Unified Invoice with U420 printer

BUILD_DEPENDS=	p5-Class-Accessor>=0:devel/p5-Class-Accessor
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
