# $FreeBSD: head/www/hs-shakespeare/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	shakespeare
PORTVERSION=	2.0.15
PORTREVISION=	2
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Toolkit for making compile-time interpolated templates

LICENSE=	MIT

USE_CABAL=	aeson blaze-html blaze-markup exceptions

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
