# Created by: R Joseph Wright <rjoseph@mammalia.org>
# $FreeBSD: head/graphics/nurbs++/Makefile 449591 2017-09-10 20:55:38Z gerald $

PORTNAME=	nurbs++
PORTVERSION=	3.0.11
PORTREVISION=	5
CATEGORIES=	graphics
MASTER_SITES=	SF/libnurbs/nurbs%2B%2B/${PORTVERSION}

MAINTAINER=	gahr@FreeBSD.org
COMMENT=	C++ library to manipulate and create NURBS curves and surfaces

USES=		libtool tar:bzip2
GNU_CONFIGURE=	yes
USE_GCC=	any
USE_LDCONFIG=	yes

INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
