# $FreeBSD: head/devel/rubygem-octopress-hooks/Makefile 427722 2016-12-03 19:35:42Z sunpoet $

PORTNAME=	octopress-hooks
PORTVERSION=	2.6.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Allows access to Jekyll data at different internal processing stages

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

RUN_DEPENDS=	rubygem-jekyll>=2.0:www/rubygem-jekyll

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
