# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/net/rubygem-dropbox-sdk/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	dropbox-sdk
PORTVERSION=	1.6.5
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Library of the Dropbox API web endpoints

LICENSE=	MIT

RUN_DEPENDS=	rubygem-json>=0:devel/rubygem-json

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
