# Created by: Stephen Montgomery-Smith <stephen@math.missouri.edu>
# $FreeBSD: head/math/octave-forge-special-matrix/Makefile 490472 2019-01-16 11:13:44Z tijl $

PORTNAME=	octave-forge-special-matrix
PORTVERSION=	1.0.7
PORTREVISION=	22
CATEGORIES=	math

MAINTAINER=	stephen@FreeBSD.org
COMMENT=	Octave-forge package ${OCTAVE_PKGNAME}

GNU_CONFIGURE=	yes

.include "${.CURDIR}/../../Mk/bsd.octave.mk"
.include <bsd.port.mk>
