# Created by: Stephen Montgomery-Smith <stephen@math.missouri.edu>
# $FreeBSD: head/math/octave-forge-special-matrix/Makefile 475857 2018-07-29 22:18:44Z gerald $

PORTNAME=	octave-forge-special-matrix
PORTVERSION=	1.0.7
PORTREVISION=	19
CATEGORIES=	math

MAINTAINER=	stephen@FreeBSD.org
COMMENT=	Octave-forge package ${OCTAVE_PKGNAME}

GNU_CONFIGURE=	yes

.include "${.CURDIR}/../../Mk/bsd.octave.mk"
.include <bsd.port.mk>
