# $FreeBSD: head/devel/hs-hspec-expectations/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	hspec-expectations
PORTVERSION=	0.8.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Catchy combinators for HUnit

LICENSE=	MIT

USE_CABAL=	call-stack HUnit

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
