# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-microbenchmark/Makefile 443845 2017-06-18 18:09:16Z dbn $

PORTNAME=	microbenchmark
PORTREVISION=	1
DISTVERSION=	1.4-2
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Infrastructure to measure the execution time of R expressions

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	R-cran-ggplot2>0:graphics/R-cran-ggplot2

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
