# $FreeBSD: head/www/p5-CGI-Struct/Makefile 429026 2016-12-20 18:36:06Z sunpoet $

PORTNAME=	CGI-Struct
PORTVERSION=	1.21
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	fullermd@over-yonder.net
COMMENT=	Build data structures from CGI request parameters

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

TEST_DEPENDS=	p5-Test-Deep>=0:devel/p5-Test-Deep

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
