# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/p5-CPAN-Perl-Releases/Makefile 456926 2017-12-21 17:41:26Z sunpoet $

PORTNAME=	CPAN-Perl-Releases
PORTVERSION=	3.44
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Map Perl releases to the location of the tarballs

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
