# $FreeBSD: head/www/hs-path-pieces/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	path-pieces
PORTVERSION=	0.2.1
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Components of paths

LICENSE=	BSD3CLAUSE

USE_CABAL=	text>=0.5

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
