# $FreeBSD: head/www/hs-path-pieces/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	path-pieces
PORTVERSION=	0.2.1
PORTREVISION=	4
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Components of paths

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
