# Created by: IWATSUKI Hiroyuki <don@na.rim.or.jp>
# $FreeBSD: head/textproc/rubygem-tidy/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	tidy
PORTVERSION=	1.1.2
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	don@na.rim.or.jp
COMMENT=	Ruby interface to HTML Tidy Library Project

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
