# Created by: Carlo Strub <cs@FreeBSD.org>
# $FreeBSD: head/devel/go-logrus/Makefile 418703 2016-07-18 13:39:17Z mat $

PORTNAME=	logrus
PORTVERSION=	0.10.0
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	go-

MAINTAINER=	cs@FreeBSD.org
COMMENT=	Structured, pluggable logging for Go

LICENSE=	MIT

USE_GITHUB=	yes
GH_ACCOUNT=	Sirupsen
USES=		go
GO_PKGNAME=	github.com/Sirupsen/logrus

.include <bsd.port.mk>
