# $FreeBSD: head/net/hs-network-uri/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	network-uri
PORTVERSION=	2.6.1.0
PORTREVISION=	4
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	URI manipulation

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
