# $FreeBSD: head/net/hs-network-uri/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	network-uri
PORTVERSION=	2.6.1.0
PORTREVISION=	1
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	URI manipulation

LICENSE=	BSD3CLAUSE

USE_CABAL=	parsec>=3.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
