# Created by: Kozlov Sergey <kozlov.sergey.404@gmail.com>
# $FreeBSD: head/textproc/py-pdfminer/Makefile 480460 2018-09-23 08:13:44Z skozlov $

PORTNAME=	pdfminer
PORTVERSION=	20140328
PORTREVISION=	1
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	skozlov@FreeBSD.org
COMMENT=	PDF parser and analyzer

LICENSE=	MIT

USES=		python:2.7
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
