# $FreeBSD: head/textproc/jo/Makefile 488583 2018-12-28 03:14:06Z swills $

PORTNAME=	jo
PORTVERSION=	1.2
CATEGORIES=	textproc
MASTER_SITES=	https://github.com/jpmens/${PORTNAME}/releases/download/${PORTVERSION}/

MAINTAINER=	swills@FreeBSD.org
COMMENT=	Small utility to create JSON objects

LICENSE=	GPLv2+
LICENSE_FILE=	${WRKSRC}/COPYING

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/jo man/man1/jo.1.gz

.include <bsd.port.mk>
