# Created by: Vladimir Kondratiev <wulf@mail.mipt.ru>
# $FreeBSD: head/devel/rubygem-debugger-linecache/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	debugger-linecache
PORTVERSION=	1.2.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby module for reading and caching lines

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
