# $FreeBSD: head/devel/geany-plugin-geniuspaste/Makefile 416609 2016-06-09 15:24:55Z madpilot $

PORTNAME=	geany-plugin-geniuspaste
PORTVERSION=	${GEANY_VER}
CATEGORIES=	devel

MAINTAINER=	madpilot@FreeBSD.org
COMMENT=	Geany plugin: ${${GEANY_PLUGIN}_DESC}

LIB_DEPENDS=	libsoup-2.4.so:devel/libsoup

.include "${.CURDIR}/../geany-plugins/files/Makefile.common"
.include <bsd.port.mk>
