# $FreeBSD: head/devel/hs-gio/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	gio
PORTVERSION=	0.13.3.1
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Binding to the GIO

LICENSE=	LGPL21

USES=		pkgconfig
USE_CABAL=	glib>=0.13.0.0 mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
