# Created by: Cezary Morga <cm@therek.net>
# $FreeBSD: head/devel/p5-ExtUtils-XSpp/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	ExtUtils-XSpp
PORTVERSION=	0.18
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	XS for C++ in Perl

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-Base>=0:devel/p5-Test-Base \
		p5-Test-Differences>=0:devel/p5-Test-Differences

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
