# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/science/R-cran-snow/Makefile 479977 2018-09-18 06:51:54Z tota $

PORTNAME=	snow
DISTVERSION=	0.4-3
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Support for simple parallel computing in R

LICENSE=	GPLv2+

USES=	cran:auto-plist

.include <bsd.port.mk>
