# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/science/R-cran-snow/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	snow
DISTVERSION=	0.4-2
PORTREVISION=	1
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Support for simple parallel computing in R

LICENSE=	GPLv2+

USES=	cran:auto-plist

.include <bsd.port.mk>
