# Created by: Palle Girgensohn <girgen@FreeBSD.org>
# $FreeBSD: head/net/rubygem-serverengine/Makefile 491101 2019-01-24 17:10:32Z girgen $

PORTNAME=	serverengine
PORTVERSION=	2.1.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	girgen@FreeBSD.org
COMMENT=	Framework to implement robust multiprocess servers

LICENSE=	APACHE20

RUN_DEPENDS=	rubygem-sigdump>=0.2.2:devel/rubygem-sigdump

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
