# $FreeBSD: head/net/hs-sendfile/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	sendfile
PORTVERSION=	0.7.9
PORTREVISION=	13
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Portable sendfile library

LICENSE=	BSD3CLAUSE

USE_CABAL=	network>=2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
