# $FreeBSD: head/devel/rubygem-paint1/Makefile 476736 2018-08-09 11:07:45Z sunpoet $

PORTNAME=	paint
PORTVERSION=	1.0.1
CATEGORIES=	devel
MASTER_SITES=	RG
PKGNAMESUFFIX=	1

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Terminal painter

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE.txt

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
