# Created by: Jesse McConnell <jesse@gallup.com>
# $FreeBSD: head/devel/p5-Log-Agent/Makefile 453068 2017-10-28 17:32:52Z sunpoet $

PORTNAME=	Log-Agent
PORTVERSION=	1.002
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Set of Perl modules that allows you to enhance logging capabilities

LICENSE=	ART20

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
