# Created by: Ryan Steinmetz (<rpsfa@rit.edu>)
# $FreeBSD: head/devel/rubygem-configuration/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	configuration
PORTVERSION=	1.3.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Mechanism to parse ruby configuration files

LICENSE=	BSD2CLAUSE RUBY
LICENSE_COMB=	dual

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
