# $FreeBSD: head/devel/hs-ansi-terminal/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	ansi-terminal
PORTVERSION=	0.6.3.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple ANSI terminal support, with Windows compatibility

LICENSE=	BSD3CLAUSE

FLAGS_DISABLE=	Example

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
