# Created by: bsam
# $FreeBSD: head/multimedia/linux-c6-libv4l/Makefile 432937 2017-01-31 16:54:21Z tijl $

PORTNAME=	libv4l
PORTVERSION=	0.6.3
PORTREVISION=	3
CATEGORIES=	multimedia linux

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	Video4Linux library (Linux CentOS ${LINUX_DIST_VER})

DESCR=		${.CURDIR}/../${PORTNAME}/pkg-descr
RPMVERSION=	2.el6
USES=		linux:c6
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes

.include <bsd.port.mk>
