# $FreeBSD: head/sysutils/cfengine-masterfiles/Makefile 482115 2018-10-14 20:59:30Z cy $

VERSIONS=		36 37 38 39 310 311 312
CFENGINE_VERSION?=	312

MASTERDIR=		${.CURDIR}/../cfengine-masterfiles${CFENGINE_VERSION}

.include "${MASTERDIR}/Makefile"
