# $FreeBSD: head/sysutils/cfengine-masterfiles/Makefile 485710 2018-11-23 22:07:04Z cy $

VERSIONS=		36 37 38 39 310 311 312 313
CFENGINE_VERSION?=	312

MASTERDIR=		${.CURDIR}/../cfengine-masterfiles${CFENGINE_VERSION}

.include "${MASTERDIR}/Makefile"
