# Created by: Peter van Heusden <pvh@egenetics.com>
# $FreeBSD: head/lang/p5-Error/Makefile 470745 2018-05-23 23:43:20Z wen $

PORTNAME=	Error
PORTVERSION=	0.17026
CATEGORIES=	lang perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Error/exception handling in object-oriented programming style

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
