# $FreeBSD: head/devel/hs-js-jquery/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	js-jquery
PORTVERSION=	3.2.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Obtain minified jQuery code

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
