# $FreeBSD: head/devel/hs-js-jquery/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	js-jquery
PORTVERSION=	3.2.1
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Obtain minified jQuery code

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
