# $FreeBSD: head/devel/hs-js-jquery/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	js-jquery
PORTVERSION=	3.2.1
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Obtain minified jQuery code

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
