# Created by: Cezary Morga <cm@therek.net>
# $FreeBSD: head/devel/p5-Module-Math-Depends/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	Module-Math-Depends
PORTVERSION=	0.02
PORTREVISION=	3
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Convenience object for manipulating module dependencies

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Params-Util>=0:devel/p5-Params-Util

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
