# $FreeBSD: head/devel/rubygem-googleapis-common-protos-types/Makefile 457711 2017-12-31 17:57:55Z swills $

PORTNAME=	googleapis-common-protos-types
PORTVERSION=	1.0.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Common protocol buffer types used by Google APIs

RUN_DEPENDS=	rubygem-google-protobuf>=3.0:devel/rubygem-google-protobuf

USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
