# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-uri_template/Makefile 486473 2018-12-02 17:43:33Z antoine $

PORTNAME=	uri_template
PORTVERSION=	1.0
PORTREVISION=	1
CATEGORIES=	devel

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	URI Template(RFC6570) library for PHP

DEPRECATED=	Works only with EOL php 5.6
EXPIRATION_DATE=	2018-12-30

LICENSE=	PHP301

USES=		php:pecl
IGNORE_WITH_PHP=	70 71 72 73

.include <bsd.port.mk>
