# Created by: Dan Langille <dvl@FreeBSD.org>
# $FreeBSD: head/devel/py-apache_conf_parser/Makefile 455619 2017-12-05 20:27:27Z dvl $

PORTNAME=	apache_conf_parser
PORTVERSION=	1.0.1
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dvl@FreeBSD.org
COMMENT=	Parse and manipulate apache conf files

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
