# Created by: Chris D. Faulhaber <jedgar@fxp.org>
# $FreeBSD: head/editors/bvi/Makefile 408249 2016-02-05 18:19:14Z marino $

PORTNAME=	bvi
PORTVERSION=	1.4.0
CATEGORIES=	editors
MASTER_SITES=	SF
EXTRACT_SUFX=	.src.tar.gz

MAINTAINER=	naddy@FreeBSD.org
COMMENT=	Vi-like binary file (hex)editor

USES=		ncurses
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
