# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/security/pear-Crypt_RC4/Makefile 443312 2017-06-11 07:44:14Z sunpoet $

PORTNAME=	Crypt_RC4
PORTVERSION=	1.0.3
CATEGORIES=	security www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR encryption class for RC4 encryption

USES=		pear

.include <bsd.port.mk>
