# $FreeBSD: head/devel/pear-channel-geshi/Makefile 479875 2018-09-16 00:23:01Z jmd $

PORTNAME=	geshi
PORTVERSION=	20180906
CATEGORIES=	devel www pear

MAINTAINER=	michael.osipov@siemens.com
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	pear.geshi.org

.include "${.CURDIR}/../../devel/pear/bsd.pear.channel.mk"
.include <bsd.port.mk>
