# Created by: Anish Mistry <amistry@am-productions.biz>
# $FreeBSD: head/print/pear-File_PDF/Makefile 443302 2017-06-11 07:43:26Z sunpoet $

PORTNAME=	File_PDF
PORTVERSION=	0.3.3
CATEGORIES=	print pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR class to generate PDFs

USES=		pear

.include <bsd.port.mk>
