# Created by: Johannes Meixner <johannes@perceivon.net>
# $FreeBSD: head/www/rubygem-dropzonejs-rails/Makefile 440056 2017-05-03 21:53:55Z sunpoet $

PORTNAME=	dropzonejs-rails
PORTVERSION=	0.7.4
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	JS File upload by Matias Meno

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-rails4>=3.1:www/rubygem-rails4

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
