# Created by: Jose Jachuf <jjachuf@gmail.com>
# $FreeBSD: head/devel/py-rope/Makefile 462228 2018-02-18 13:25:24Z wen $

PORTNAME=	rope
PORTVERSION=	0.10.7
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jjachuf@gmail.com
COMMENT=	Python refactoring library

LICENSE=	GPLv2

NO_ARCH=	yes
USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
