# Created by: Muhammad Moinur Rahman <bofh@FreeBSD.org>
# $FreeBSD: head/devel/libfastjson/Makefile 441294 2017-05-20 08:54:20Z bofh $

PORTNAME=	libfastjson
PORTVERSION=	0.99.5
DISTVERSIONPREFIX=	v
CATEGORIES=	devel

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	libfastjson is a fork from json-c

LICENSE=	MIT

USE_GITHUB=	yes
GH_ACCOUNT=	rsyslog

GNU_CONFIGURE=	yes
USES=		autoreconf libtool pathfix pkgconfig
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
