# $FreeBSD: head/devel/hs-newtype-generics/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	newtype-generics
PORTVERSION=	0.5.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Full replacement for the original newtype package

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
