# $FreeBSD: head/devel/hs-newtype-generics/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	newtype-generics
PORTVERSION=	0.5.3
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Full replacement for the original newtype package

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
