# $FreeBSD: head/x11-drivers/xf86-video-voodoo/Makefile 479538 2018-09-11 18:34:27Z zeising $

PORTNAME=	xf86-video-voodoo
PORTVERSION=	1.2.5
PORTREVISION=	10
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org voodoo display driver

XORG_CAT=	driver

.include <bsd.port.mk>
