# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/math/p5-Math-VecStat/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Math-VecStat
PORTVERSION=	0.08
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Basic statistics on vectors

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
