# Created by: Andrey Kostenko <andrey@kostenko.name>
# $FreeBSD: head/devel/p5-IO-Interactive/Makefile 423521 2016-10-08 16:58:13Z adamw $

PORTNAME=	IO-Interactive
PORTVERSION=	1.022
PORTEPOCH=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Utilities for interactive I/O

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
