# $FreeBSD: head/devel/hs-deepseq-generics/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=      deepseq-generics
PORTVERSION=   0.2.0.0
PORTREVISION=  2
CATEGORIES=    devel haskell

MAINTAINER=    haskell@FreeBSD.org
COMMENT=       GHC.Generics-based Control.DeepSeq.rnf implementation

LICENSE=       BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
