# Created by: Pedro Giffuni
# $FreeBSD: head/devel/R-cran-praise/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	praise
DISTVERSION=	1.0.0
PORTREVISION=	1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	pfg@FreeBSD.org
COMMENT=	Praise Users

LICENSE=	MIT

USES=	cran:auto-plist

.include <bsd.port.mk>
