# Created by: torstenb
# $FreeBSD: head/x11-wm/ctwm/Makefile 445226 2017-07-07 09:36:28Z bhughes $

PORTNAME=	ctwm
PORTVERSION=	4.0.1
PORTEPOCH=	1
CATEGORIES=	x11-wm
MASTER_SITES=	https://www.ctwm.org/dist/ \
		https://distfiles.over-yonder.net/ctwm/

MAINTAINER=	fullermd@over-yonder.net
COMMENT=	Extension to twm, with support for multiple virtual screens

LICENSE=	MIT

USES=		cmake:outsource jpeg tar:xz
USE_XORG=	x11 xext xt ice sm xpm xmu

.include <bsd.port.mk>
