# $FreeBSD: head/devel/rubygem-rabl-rails50/Makefile 483726 2018-11-01 19:17:28Z sunpoet $

PORTNAME=	rabl
PORTVERSION=	0.14.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	-rails50

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	General ruby templating with json, bson, xml and msgpack support

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

RUN_DEPENDS=	rubygem-activesupport50>=2.3.14:devel/rubygem-activesupport50

USE_RUBY=	yes
USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
