# $FreeBSD: head/devel/rubygem-rabl-rails50/Makefile 447386 2017-08-05 03:25:17Z jrm $

PORTNAME=	rabl
PORTVERSION=	0.13.1
PORTREVISION=	1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	-rails50

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	General ruby templating with json, bson, xml and msgpack support

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

RUN_DEPENDS=	rubygem-activesupport50>0:devel/rubygem-activesupport50

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
