# $FreeBSD: head/databases/pecl-mongodb/Makefile 487586 2018-12-16 13:02:35Z pi $

PORTNAME=	mongodb
PORTVERSION=	1.5.3
CATEGORIES=	databases pear

MAINTAINER=	pi@FreeBSD.org
COMMENT=	PECL classes for MongoDB

LICENSE=	APACHE20

USES=		php:pecl ssl
USE_PHP=	spl:build
CFLAGS+=	-I${LOCALBASE}/include

.include <bsd.port.mk>
