# $FreeBSD: head/databases/pecl-mongodb/Makefile 472715 2018-06-18 20:52:32Z pi $

PORTNAME=	mongodb
PORTVERSION=	1.4.4
CATEGORIES=	databases pear

MAINTAINER=	pi@FreeBSD.org
COMMENT=	PECL classes for MongoDB

LICENSE=	APACHE20

USES=		php:pecl ssl
USE_PHP=	spl:build
CFLAGS+=	-I${LOCALBASE}/include

.include <bsd.port.mk>
