# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: head/audio/gstreamer-plugins-lame/Makefile 428152 2016-12-08 19:52:19Z tijl $
#   $MCom: ports/audio/gstreamer-plugins-lame/Makefile,v 1.5 2008/03/19 14:05:30 ahze Exp $

PORTREVISION=	2
CATEGORIES=	audio

COMMENT=	Gstreamer mp3 encode plugin

GST_PLUGIN=	lame

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
