# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/textproc/p5-Text-Lorem/Makefile 432932 2017-01-31 16:21:45Z mat $

PORTNAME=	Text-Lorem
PORTVERSION=	0.3
PORTREVISION=	2
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Generate random Latin looking text

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
