# $FreeBSD: head/sysutils/py-pkginfo/Makefile 453903 2017-11-10 15:43:15Z swills $

PORTNAME=	pkginfo
DISTVERSION=	1.4.1
CATEGORIES=	sysutils python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	che@bein.link
COMMENT=	Query metadatdata from sdists / bdists / installed packages

LICENSE=	MIT

NO_ARCH=	yes
USES?=		python
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
