# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-sexp_processor/Makefile 462038 2018-02-16 15:43:10Z sunpoet $

PORTNAME=	sexp_processor
PORTVERSION=	4.10.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Generic sexp processing tools

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
