# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: head/devel/p5-Class-STL-Containers/Makefile 475310 2018-07-25 12:46:30Z bofh $

PORTNAME=	Class-STL-Containers
PORTVERSION=	0.37
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Perl extension for STL-like object management

LICENSE=	GPLv2

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
