# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-mutter/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	mutter
PORTVERSION=	0.5.3
#PORTREVISION=	0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	This Ruby gem is a tiny command-line interface library

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
