# $FreeBSD: head/devel/rubygem-aws-sdk-resources/Makefile 458772 2018-01-11 18:35:50Z sunpoet $

PORTNAME=	aws-sdk-resources
DISTVERSION=	2.10.115
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	AWS SDK for Ruby Resources

LICENSE=	APACHE20

RUN_DEPENDS=	rubygem-aws-sdk-core>=${PORTVERSION}:devel/rubygem-aws-sdk-core

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
