# $FreeBSD: head/devel/rubygem-aws-sdk-resources/Makefile 492951 2019-02-14 22:41:39Z sunpoet $

PORTNAME=	aws-sdk-resources
DISTVERSION=	2.11.220
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	AWS SDK for Ruby Resources

LICENSE=	APACHE20

RUN_DEPENDS=	rubygem-aws-sdk-core>=${PORTVERSION}:devel/rubygem-aws-sdk-core

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
