# $FreeBSD: head/security/hs-crypto-api/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	crypto-api
PORTVERSION=	0.13.2
PORTREVISION=	5
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Generic interface for cryptographic operations

LICENSE=	BSD3CLAUSE

USE_CABAL=	cereal>=0.2 entropy tagged>=0.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
