# Created by: James FitzGibbon <jfitz@FreeBSD.org>
# $FreeBSD: head/devel/p5-Date-Manip/Makefile 472814 2018-06-19 18:25:04Z swills $

PORTNAME=	Date-Manip
PORTVERSION=	6.72
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:SBECK
PKGNAMEPREFIX=	p5-

MAINTAINER=	swills@FreeBSD.org
COMMENT=	Perl5 module containing date manipulation routines

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-Inter>=0:devel/p5-Test-Inter

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
