# Created by: Jov <amutu@amutu.com>
# $FreeBSD: head/sysutils/u-boot-orangepi-plus-2e/Makefile 474536 2018-07-12 21:05:37Z linimon $

MASTERDIR=	${.CURDIR}/../u-boot-master

MODEL=		orangepi-plus-2e
BOARD_CONFIG=	orangepi_plus2e_defconfig
FAMILY=		allwinner

.include "${MASTERDIR}/Makefile"
