# Created by: Jov <amutu@amutu.com>
# $FreeBSD: head/sysutils/u-boot-orangepi-plus-2e/Makefile 447121 2017-08-02 16:17:19Z imp $

MAINTAINER=	amutu@amutu.com
MASTERDIR=	${.CURDIR}/../u-boot-master

MODEL=		orangepi-plus-2e
BOARD_CONFIG=	orangepi_plus2e_defconfig
FAMILY=		allwinner

.include "${MASTERDIR}/Makefile"
