# $FreeBSD: head/devel/hs-prettyclass/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	prettyclass
PORTVERSION=	1.0.0.0
PORTREVISION=	6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Pretty printing class similar to Show

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
