# $FreeBSD: head/devel/hs-prettyclass/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	prettyclass
PORTVERSION=	1.0.0.0
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Pretty printing class similar to Show

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
