# Created by: Lauri Watts <lauri@kde.org>
# $FreeBSD: head/databases/qt4-pgsql-plugin/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTREVISION=	4

COMMENT=	Qt PostgreSQL database plugin
DB=		psql
USES=		pgsql

.include "${.CURDIR:H:H}/devel/qt4/Makefile.sqldrivers"
