# $FreeBSD: head/sysutils/u-boot-olimex-a20-som-evb/Makefile 472714 2018-06-18 20:22:13Z linimon $

MASTERDIR=	${.CURDIR}/../u-boot-master

MODEL=		olimex-a20-som-evb
BOARD_CONFIG=	A20-Olimex-SOM-EVB_defconfig
FAMILY=		allwinner

.include "${MASTERDIR}/Makefile"
