# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/textproc/rubygem-ruby-xslt/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	ruby-xslt
PORTVERSION=	0.9.9
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	XSLT processor in pure Ruby

LICENSE=	GPLv2

USE_GNOME=	libxslt
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
