# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/textproc/rubygem-ruby-xslt/Makefile 451209 2017-10-04 10:56:01Z sunpoet $

PORTNAME=	ruby-xslt
PORTVERSION=	0.9.10
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	XSLT processor in pure Ruby

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/COPYING

USE_GNOME=	libxslt
USE_RUBY=	yes
USES=		gem gnome

.include <bsd.port.mk>
