# Created by: Ju Pengfei <jupengfei@gmail.com>
# $FreeBSD: head/devel/hs-bsd-sysctl/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	bsd-sysctl
PORTVERSION=	1.0.7
PORTREVISION=	12
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Access to the BSD sysctl(3) interface

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
