# Created by: Ju Pengfei <jupengfei@gmail.com>
# $FreeBSD: head/devel/hs-bsd-sysctl/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	bsd-sysctl
PORTVERSION=	1.0.7
PORTREVISION=	14
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Access to the BSD sysctl(3) interface

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
