# Created by: Cheng-Lung Sung <clsung@dragon2.net>
# $FreeBSD: head/devel/p5-FileHandle-Unget/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	FileHandle-Unget
PORTVERSION=	0.1628
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	FileHandle which supports ungetting of multiple bytes

LICENSE=	GPLv2

BUILD_DEPENDS=	p5-URI>=0:net/p5-URI
TEST_DEPENDS=	p5-File-Slurp>=0:devel/p5-File-Slurp

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
