# $FreeBSD: head/security/rubygem-rex-random_identifier/Makefile 449187 2017-09-03 09:19:18Z antoine $

PORTNAME=	rex-random_identifier
PORTVERSION=	0.1.3
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Ruby Exploitation(Rex) library for generating Random identifier

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-rex-text>=0:security/rubygem-rex-text

NO_ARCH=	yes
USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
