# Created by: kevit
# $FreeBSD: head/devel/p5-Class-Declare/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	Class-Declare
PORTVERSION=	0.19
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	simarg@gmail.com
COMMENT=	Perl module for declare classes

TEST_DEPENDS=	p5-Test-Exception>=0.15:devel/p5-Test-Exception

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
