# Created by: Kevin Lo <kevlo@FreeBSD.org>
# $FreeBSD: head/devel/p5-String-Similarity/Makefile 458825 2018-01-12 13:20:45Z adamw $

PORTNAME=	String-Similarity
PORTVERSION=	1.04
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module that calculates the similarity of two strings

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
