# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/www/webpy/Makefile 467669 2018-04-18 03:15:07Z wen $

PORTNAME=	webpy
PORTVERSION=	0.39
CATEGORIES=	www python
MASTER_SITES=	http://webpy.org/static/ \
		CHEESESHOP
DISTNAME=	web.py-${PORTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Web Framework For Python

LICENSE=	PD

USES=		python:2.7
USE_PYTHON=	autoplist distutils
PYDISTUTILS_PKGNAME=	web.py

.include <bsd.port.mk>
