# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: head/net/rubygem-ruby-yadis/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	ruby-yadis
PORTVERSION=	0.3.4
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Yadis Service discovery library written in pure Ruby

LICENSE=	APACHE20

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
