# Created by: Michael Nottebrock <lofi@FreeBSD.org>
# $FreeBSD: head/databases/qt4-ibase-plugin/Makefile 463394 2018-03-02 13:07:57Z adridg $

PORTREVISION=	2

COMMENT=	Qt InterBase/Firebird database plugin
DB=		ibase
USES=		firebird

ONLY_FOR_ARCHS=	i386 amd64

.include "${.CURDIR:H:H}/devel/qt4/Makefile.sqldrivers"
