# Created by: gahr
# $FreeBSD: head/x11-themes/e16-themes/Makefile 446812 2017-07-28 09:01:09Z amdmi3 $

PORTNAME=	e16-themes
PORTVERSION=	1.0.1
CATEGORIES=	x11-themes enlightenment
MASTER_SITES=	SF/enlightenment/${PORTNAME}/${PORTVERSION}

MAINTAINER=	enlightenment@FreeBSD.org
COMMENT=	Set of themes for the e16 window manager

DATADIR=	${PREFIX}/share/e16
GNU_CONFIGURE=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
