# $FreeBSD: head/multimedia/gstreamer1-plugins-dv/Makefile 405242 2016-01-04 14:21:56Z kwm $

PORTREVISION=	0
CATEGORIES=	multimedia
PKGNAMESUFFIX=	1-plugins-dv

COMMENT=	GStreamer dv demux and decoder plugin based on libdv

GST_PLUGIN=	libdv
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
