# Created by: Yen-Ming Lee <leeym@FreeBSD.org>
# $FreeBSD: head/devel/p5-IPC-Shareable/Makefile 430405 2017-01-02 20:13:16Z adamw $

PORTNAME=	IPC-Shareable
PORTVERSION=	0.61
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Share Perl variables between processes

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
