# $FreeBSD: head/math/hs-NumInstances/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	NumInstances
PORTVERSION=	1.4
PORTREVISION=	2
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Instances of numeric classes for functions and tuples

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
