# $FreeBSD: head/math/hs-NumInstances/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	NumInstances
PORTVERSION=	1.4
PORTREVISION=	4
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Instances of numeric classes for functions and tuples

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
