# Created by: lx
# $FreeBSD: head/devel/lua51-bitop/Makefile 458803 2018-01-12 00:19:21Z lx $

COMMENT=	lua-bitop for Lua 5.1

SLAVE_PORT=	lua-bitop

USES=	gmake lua:51

MASTERDIR=	${.CURDIR}/../lua-bitop
PLIST=	${MASTERDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
