# Created by: wen@FreeBSD.org
# $FreeBSD: head/net-im/pecl-stomp/Makefile 440442 2017-05-08 17:21:49Z dbaio $

PORTNAME=	stomp
PORTVERSION=	1.0.9
PORTREVISION=	1
CATEGORIES=	net-im pear

MAINTAINER=	dbaio@FreeBSD.org
COMMENT=	PECL extension of stomp client

LICENSE=	PHP301
LICENSE_FILE=	${WRKSRC}/LICENSE

PORTSCOUT=	limit:^1.*

USES=		php:pecl
IGNORE_WITH_PHP=	70 71

.include <bsd.port.mk>
