# Created by: Pawel Pekala <pawel@FreeBSD.org>
# $FreeBSD: head/ports-mgmt/ports-tools/Makefile 455620 2017-12-05 20:35:45Z pawel $

PORTNAME=	ports-tools
PORTVERSION=	1.5
CATEGORIES=	ports-mgmt

MAINTAINER=	pawel@FreeBSD.org
COMMENT=	Collection of ports tree related scripts

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

CONFLICTS_INSTALL=	popular # bin/pcheck

USE_GITHUB=	yes
GH_ACCOUNT=	ppekala

NO_BUILD=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
