# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/textproc/pear-Horde_Text_Diff/Makefile 436664 2017-03-21 23:38:47Z mm $

PORTNAME=	Horde_Text_Diff
PORTVERSION=	2.2.0
CATEGORIES=	textproc www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde engine for performing and rendering text diffs

USES=	horde
USE_HORDE_RUN=	Horde_Exception \
		Horde_Util

.include <bsd.port.mk>
