# $FreeBSD: head/devel/hs-gitrev/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	gitrev
PORTVERSION=	1.3.1
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Compile git revision info into Haskell projects

LICENSE=	BSD3CLAUSE

USE_CABAL=	base-compat

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
