# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-jsmin/Makefile 456296 2017-12-14 13:57:28Z tz $

PORTNAME=	jsmin
PORTVERSION=	2.0.1
PORTREVISION=	1
CATEGORIES=	devel

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	PHP extension for minifying JavaScript

LICENSE=	PHP301

USES=		php:pecl
IGNORE_WITH_PHP=	70 71 72

.include <bsd.port.mk>
