# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-jsmin/Makefile 489349 2019-01-05 15:47:56Z rene $

PORTNAME=	jsmin
PORTVERSION=	3.0.0
CATEGORIES=	devel

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	PHP extension for minifying JavaScript

LICENSE=	PHP301

USES=		php:pecl

.include <bsd.port.mk>
