# $FreeBSD: head/devel/hs-safe-exceptions/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	safe-exceptions
PORTVERSION=	0.1.6.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	The safe-exceptions package

LICENSE=	BSD3CLAUSE

USE_CABAL=	exceptions

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
