# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: head/multimedia/gstreamer-plugins-theora/Makefile 428129 2016-12-08 15:38:24Z tijl $
#   $MCom: ports/multimedia/gstreamer-plugins-theora/Makefile,v 1.4 2008/03/21 04:01:32 ahze Exp $

PORTREVISION=	2
CATEGORIES=	multimedia

COMMENT=	Gstreamer theora plugin

GST_PLUGIN=	theora

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
