# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/devel/php70-tokenizer/Makefile 422569 2016-09-21 15:43:47Z tz $

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php70

PKGNAMESUFFIX=	-tokenizer

.include "${MASTERDIR}/Makefile"
