# Created by: Scott Sanders <scott@jssjr.com>
# $FreeBSD: head/textproc/rubygem-fast_xs073/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	fast_xs
PORTVERSION=	0.7.3
PORTEPOCH=	1
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	073

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Systems integration framework. Expander

LICENSE=	MIT

RUN_DEPENDS=	rubygem-hoe>=2.3.2:devel/rubygem-hoe

PORTSCOUT=	limit:^0.7

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
