# Created by: Michael Moll <kvedulv at kvedulv.de>
# $FreeBSD: head/devel/rubygem-hitimes/Makefile 476058 2018-07-31 23:48:13Z sunpoet $

PORTNAME=	hitimes
PORTVERSION=	1.3.0
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	High resolution timer library for Ruby

LICENSE=	ISCL
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
