# Created by: Michael Moll <kvedulv at kvedulv.de>
# $FreeBSD: head/devel/rubygem-hitimes/Makefile 447423 2017-08-05 23:11:23Z sunpoet $

PORTNAME=	hitimes
PORTVERSION=	1.2.6
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	High resolution timer library for Ruby

LICENSE=	ISCL
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
