# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: head/textproc/sr-aspell/Makefile 453284 2017-11-01 13:10:35Z olgeni $

PORTNAME=	${DICT}-aspell
SPELLVERSION=	6-sr-0.02
PORTREVISION=	1
PORTEPOCH=	2
CATEGORIES=	textproc

MAINTAINER=	nikola.lecic@anthesphoria.net
COMMENT=	Aspell Serbian dictionary

DICT=		sr

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
