# Created by: Christer Edwards <christer.edwards@gmail.com>
# $FreeBSD: head/security/py-python-gnupg/Makefile 483069 2018-10-27 00:47:37Z swills $

PORTNAME=	python-gnupg
PORTVERSION=	0.4.3
CATEGORIES=	security python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	christer.edwards@gmail.com
COMMENT=	Python wrapper for the GNU Privacy Guard (GPG or GnuPG)

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		python

NO_ARCH=	yes
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
