# $FreeBSD: head/mail/hs-mime-types/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	mime-types
PORTVERSION=	0.1.0.7
CATEGORIES=	mail haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Basic mime-type handling types and functions

LICENSE=	MIT

USE_CABAL=	text

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
