# Created by: Yuri Victorovich <yuri@rawbw.com>
# $FreeBSD: head/www/py-rfc3986/Makefile 440745 2017-05-13 01:44:11Z dbaio $

PORTNAME=	rfc3986
PORTVERSION=	1.0.0
CATEGORIES=	www python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	yuri@rawbw.com
COMMENT=	Python implementation of RFC 3986

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	sigmavirus24

USES=		python
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
