# $FreeBSD: head/textproc/rubygem-jekyll-sitemap/Makefile 438379 2017-04-12 16:25:11Z sunpoet $

PORTNAME=	jekyll-sitemap
PORTVERSION=	1.1.1
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Automatically generate a sitemap.xml for Jekyll sites

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.md

RUN_DEPENDS=	rubygem-jekyll>=3.3:www/rubygem-jekyll

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
