# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pear-channel-phpdoc/Makefile 441000 2017-05-16 13:37:51Z joneum $

PORTNAME=	phpdoc
PORTVERSION=	20120214
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	pear.phpdoc.org

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.channel.mk"
.include <bsd.port.post.mk>
