# $FreeBSD: head/net/rubygem-omniauth-authentiq/Makefile 436535 2017-03-20 09:57:41Z tz $

PORTNAME=	omniauth-authentiq
PORTVERSION=	0.3.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Authentiq OAuth2 Strategy for OmniAuth

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-omniauth-oauth2>=1.3.1:net/rubygem-omniauth-oauth2

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
