# $FreeBSD: head/databases/sqlrelay/Makefile.common 442515 2017-06-03 19:26:05Z pi $

SQLRELAY_PORTNAME=	sqlrelay
SQLRELAY_PORTVERSION=	1.1.0

SQLRELAY_PORTDIR=	databases/${SQLRELAY_PORTNAME}
SQLRELAY_WRKSRC_CMD=	cd ${PORTSDIR}/${SQLRELAY_PORTDIR} && ${MAKE} -V WRKSRC

SQLRELAY_CONFIGURE_ARGS=	\
		--localstatedir=/var \
		--with-rudiments-prefix="${LOCALBASE}"
