# $FreeBSD: head/devel/rubygem-readwritesettings/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	readwritesettings
PORTVERSION=	3.0.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Simple settings solution that uses an ERB enabled YAML file

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
