# Created by: marius@alchemy.franken.de
# $FreeBSD: head/sysutils/gcdmaster/Makefile 426578 2016-11-20 12:41:44Z bapt $

PORTNAME=	gcdmaster
PORTREVISION=	8

COMMENT=	GNOME frontend for cdrdao

MASTERDIR=	${.CURDIR}/../cdrdao
DESCR=		${.CURDIR}/pkg-descr
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
