# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: head/math/R-cran-nnls/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	nnls
PORTVERSION=	1.4
PORTREVISION=	9
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	R implementation of an algorithm for non-negative least squares

LICENSE=	GPLv2

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
