# $FreeBSD: head/x11/libXTrap/Makefile 476013 2018-07-31 18:41:30Z zeising $

PORTNAME=	libXTrap
PORTVERSION=	1.0.1
PORTREVISION=	4
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	The XTrap library

XORG_CAT=	lib
USE_XORG=	x11 xext xorgproto xt

.include <bsd.port.mk>
