# Created by: chinsan
# $FreeBSD: head/textproc/vbindiff/Makefile 408215 2016-02-05 16:11:16Z marino $

PORTNAME=	vbindiff
DISTVERSION=	3.0_beta4
CATEGORIES=	textproc
MASTER_SITES=	http://www.cjmweb.net/vbindiff/

MAINTAINER=	cyberbotx@cyberbotx.com
COMMENT=	Visual binary diff, visually compare binary files

USES=		ncurses
GNU_CONFIGURE=	yes

PLIST_FILES=	bin/vbindiff \
		man/man1/vbindiff.1.gz

.include <bsd.port.mk>
