# Created by: Ruben van Staveren
# $FreeBSD: head/devel/p5-Thread-Suspend/Makefile 438370 2017-04-12 16:24:25Z sunpoet $

PORTNAME=	Thread-Suspend
PORTVERSION=	1.23
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Suspend and resume operations for threads

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
