# Created by: Dirk Froemberg <dirk@FreeBSD.org>
# $FreeBSD: head/polish/php_doc/Makefile 353996 2014-05-13 21:13:31Z edwin $

CATEGORIES=	polish lang
PKGNAMEPREFIX=
PHP_LANG=	pl
MASTERDIR=	${.CURDIR}/../../lang/php_doc

.include "${MASTERDIR}/Makefile"
