# Created by: Denis Podolskiy <bytestore@yandex.ru>
# $FreeBSD: head/graphics/libjpeg-turbo/Makefile 477110 2018-08-13 20:22:38Z antoine $

PKGNAMEPREFIX=	lib
PORTREVISION=	0

COMMENT=	SIMD-accelerated JPEG codec library, provides libTurboJPEG

MASTERDIR=	${.CURDIR:H}/jpeg-turbo
SLAVE_PORT=	yes
OPTIONS_EXCLUDE=DOCS

.include "${MASTERDIR}/Makefile"
