# $FreeBSD: head/devel/hs-atomic-primops/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	atomic-primops
PORTVERSION=	0.8.0.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Safe approach to CAS and other atomic operations

LICENSE=	BSD3CLAUSE

USE_CABAL=	primitive

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
