# $FreeBSD: head/audio/gstreamer1-plugins-musepack/Makefile 446388 2017-07-22 11:35:44Z kwm $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer musepack mpc encoder/decoder plugin

GST_PLUGIN=	musepack
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
