# Created by: Alonso Cardenas Marquez <acm@FreeBSD.org>
# $FreeBSD: head/converters/fpc-iconvenc/Makefile 447304 2017-08-03 23:40:28Z acm $

CATEGORIES=	converters lang
PKGNAMESUFFIX=	-iconvenc

COMMENT=	Free Pascal unit to iconv library

USE_FPC=	yes

MASTERDIR=	${.CURDIR}/../../lang/fpc
WRKUNITDIR=	${FPCSRCDIR}/packages/${PKGNAMESUFFIX:S/-//}
EXTRACTUNITDIR=	${WRKUNITDIR}

.include "${MASTERDIR}/Makefile"
