# Created by: Shane Ambler <FreeBSD@Shaneware.biz>
# $FreeBSD: head/devel/godot2-tools/Makefile 464714 2018-03-16 17:27:57Z amdmi3 $

PKGNAMESUFFIX=	2-tools

COMMENT=	Game integrated development environment

OPTIONS_EXCLUDE=	#
OPTIONS_SLAVE=	TOOLS

MASTERDIR=	${.CURDIR}/../godot2

.include "${MASTERDIR}/Makefile"
