# Created by: Samy Al Bahra <sbahra@kerneled.org>
# $FreeBSD: head/devel/hs-dlist/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	dlist
PORTVERSION=	0.8.0.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Difference lists

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
