# Created by: Samy Al Bahra <sbahra@kerneled.org>
# $FreeBSD: head/devel/hs-dlist/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	dlist
PORTVERSION=	0.8.0.3
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Difference lists

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
