# Created by: Samy Al Bahra <sbahra@kerneled.org>
# $FreeBSD: head/devel/hs-dlist/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	dlist
PORTVERSION=	0.8.0.5
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Difference lists

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
