# $FreeBSD: head/lang/nyan/Makefile 484673 2018-11-11 09:32:27Z sunpoet $

PORTNAME=	nyan
PORTVERSION=	g20180708
CATEGORIES=	lang
PKGNAMESUFFIX=	-lang

MAINTAINER=	freebsd@sysctl.cz
COMMENT=	Data description language designed for openage

LICENSE=	LGPL3
LICENSE_FILE=	${WRKSRC}/legal/LGPLv3

USES=		cmake:outsource compiler:c++17-lang
USE_GITHUB=	yes
GH_ACCOUNT=	SFTtech
GH_TAGNAME=	3c263e2
USE_LDCONFIG=	yes

.include <bsd.port.mk>
