# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: head/finance/rubygem-money/Makefile 469149 2018-05-05 17:22:31Z sunpoet $

PORTNAME=	money
PORTVERSION=	6.11.2
CATEGORIES=	finance rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Library for handling money and different currencies

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-i18n>=0.6.4:devel/rubygem-i18n

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
