# $FreeBSD: head/www/p5-Mozilla-CA/Makefile 446795 2017-07-28 01:25:01Z dbaio $

PORTNAME=	Mozilla-CA
PORTVERSION=	20160104
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for Mozilla CA cert bundle in PEM format

LICENSE=	MPL20

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
