# $FreeBSD: head/www/p5-Mozilla-CA/Makefile 410928 2016-03-12 19:09:36Z adamw $

PORTNAME=	Mozilla-CA
PORTVERSION=	20160104
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for Mozilla CA cert bundle in PEM format

LICENSE=	MPL

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
