# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-aws-sigv4/Makefile 449065 2017-09-01 10:50:37Z sunpoet $

PORTNAME=	aws-sigv4
PORTVERSION=	1.0.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Amazon Web Services Signature Version 4 signing library

LICENSE=	APACHE20

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
