# Created by: Maxim Maximov (mcsi@agava.com)
# $FreeBSD: head/devel/p5-enum/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	enum
PORTVERSION=	1.110
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:NEILB
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:C/0$//}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Defines symbolic constants with ordered numeric values, like C enums

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
