# $FreeBSD: head/x11/libXevie/Makefile 479538 2018-09-11 18:34:27Z zeising $

PORTNAME=	libXevie
PORTVERSION=	1.0.3
PORTREVISION=	5
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	The Xevie library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 xext xorgproto

.include <bsd.port.mk>
