# $FreeBSD: head/devel/hs-echo/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	echo
PORTVERSION=	0.1.3
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cross-platform and cross-console library to handle echoing terminal input

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
