# Created by: Roderick van Domburg <r.s.a.vandomburg@student.utwente.nl>
# $FreeBSD: head/devel/rubygem-needle/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	needle
PORTVERSION=	1.3.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Dependency-injection/inversion-of-control container

LICENSE=	BSD3CLAUSE GPLv2 RUBY
LICENSE_COMB=	dual

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
