# $FreeBSD: head/misc/py-tqdm/Makefile 451978 2017-10-13 10:47:24Z culot $

PORTNAME=	tqdm
PORTVERSION=	4.19.2
DISTVERSIONPREFIX=	v
CATEGORIES=	misc
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	neel@neelc.org
COMMENT=	Fast, extensible progress bar for Python

LICENSE=	MIT MPL20
LICENSE_COMB=	multi

USES?=		python
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

USE_GITHUB=	yes

.include <bsd.port.mk>
