# $FreeBSD: head/misc/py-tqdm/Makefile 459680 2018-01-22 18:10:06Z rm $

PORTNAME=	tqdm
PORTVERSION=	4.19.5
DISTVERSIONPREFIX=	v
CATEGORIES=	misc
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	neel@neelc.org
COMMENT=	Fast, extensible progress bar for Python

LICENSE=	MIT MPL20
LICENSE_COMB=	multi

USES=		python
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

USE_GITHUB=	yes

.include <bsd.port.mk>
