# $FreeBSD: head/misc/py-tqdm/Makefile 455210 2017-11-30 15:50:30Z mat $

PORTNAME=	tqdm
PORTVERSION=	4.19.4
DISTVERSIONPREFIX=	v
CATEGORIES=	misc
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	neel@neelc.org
COMMENT=	Fast, extensible progress bar for Python

LICENSE=	MIT MPL20
LICENSE_COMB=	multi

USES=		python
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

USE_GITHUB=	yes

.include <bsd.port.mk>
