# $FreeBSD: head/www/p5-HTML-Template/Makefile 463880 2018-03-08 09:03:08Z amdmi3 $

PORTNAME=	HTML-Template
PORTVERSION=	2.95
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl module to use HTML Templates from CGI scripts

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
