# $FreeBSD: head/sysutils/ansible25/Makefile 477614 2018-08-20 00:38:40Z lifanov $

PORTVERSION=	2.5.8
PKGNAMESUFFIX=	25

CONFLICTS=	ansible-* ansible1-* ansible23-* ansible24-*

MASTERDIR=	${.CURDIR}/../ansible
DISTINFO_FILE=	${.CURDIR}/distinfo

EXTRA_PATCHES=

.include "${MASTERDIR}/Makefile"
