# $FreeBSD: head/sysutils/ansible25/Makefile 480543 2018-09-24 03:18:49Z lifanov $

PORTVERSION=	2.5.9
PKGNAMESUFFIX=	25

CONFLICTS=	ansible-* ansible1-* ansible23-* ansible24-*

MASTERDIR=	${.CURDIR}/../ansible
DISTINFO_FILE=	${.CURDIR}/distinfo

EXTRA_PATCHES=

.include "${MASTERDIR}/Makefile"
