# $FreeBSD: head/sysutils/ansible25/Makefile 475222 2018-07-24 03:16:31Z lifanov $

PORTVERSION=	2.5.6
PORTREVISION=	1
PKGNAMESUFFIX=	25

CONFLICTS=	ansible-* ansible1-* ansible23-* ansible24-*

MASTERDIR=	${.CURDIR}/../ansible
DISTINFO_FILE=	${.CURDIR}/distinfo

EXTRA_PATCHES=

.include "${MASTERDIR}/Makefile"
