# $FreeBSD: head/security/hs-crypto-random/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	crypto-random
PORTVERSION=	0.0.9
PORTREVISION=	4
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple cryptographic random related types

LICENSE=	BSD3CLAUSE

USE_CABAL=	securemem vector

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
