# Created by: Michael Gmelin <grembo@FreeBSD.org>
# $FreeBSD: head/devel/py-buildbot-pkg/Makefile 484380 2018-11-07 03:24:59Z koobs $

PORTNAME=	buildbot-pkg
PORTVERSION=	1.5.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	koobs@FreeBSD.org
COMMENT=	Buildbot packaging tools

LICENSE=	GPLv2
#LICENSE_FILE=	Not packaged in sdist

USES=		python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
