# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-metaclass/Makefile 433842 2017-02-11 08:37:54Z sunpoet $

PORTNAME=	metaclass
PORTVERSION=	0.0.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Adds a metaclass method to all Ruby objects

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING.txt

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
