# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-Formula/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	Formula
DISTVERSION=	1.2-3
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Extended Model Formulas

LICENSE=	GPLv2+

USES=	cran:auto-plist

.include <bsd.port.mk>
