# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-Formula/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	Formula
DISTVERSION=	1.2-2
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Extended Model Formulas

LICENSE=	GPLv2+

USES=	cran:auto-plist

.include <bsd.port.mk>
