# $FreeBSD: head/graphics/gstreamer1-plugins-kms/Makefile 446388 2017-07-22 11:35:44Z kwm $

PORTREVISION=	0
CATEGORIES=	graphics

COMMENT=	GStreamer video sink via KMS plugin

GST_PLUGIN=	kms
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
