# Created by: Veniamin Gvozdikov <vg@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-bin_utils/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	bin_utils
PORTVERSION=	0.0.7
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	vg@FreeBSD.org
COMMENT=	Extracting binary integers from binary string and packing back

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
