# Created by: Veniamin Gvozdikov <vg@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-bin_utils/Makefile 462745 2018-02-23 21:09:47Z rene $

PORTNAME=	bin_utils
PORTVERSION=	0.0.7
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Extracting binary integers from binary string and packing back

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
