# Created by: Li-Wen Hsu <lwhsu@FreeBSD.org>
# $FreeBSD: head/databases/py-pgxnclient/Makefile 455210 2017-11-30 15:50:30Z mat $

PORTNAME=	pgxnclient
PORTVERSION=	1.2.1
PORTREVISION=	1
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	Command line tool to interact with the PostgreSQL Extension Network

USES=		python
USE_PYTHON=	distutils autoplist concurrent optsuffix

.include <bsd.port.mk>
