# $FreeBSD: head/devel/rubygem-will_paginate/Makefile 447386 2017-08-05 03:25:17Z jrm $

PORTNAME=	will_paginate
PORTVERSION=	3.1.6
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Pagination plugin for web frameworks and other apps

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_RUBY=	yes
USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
