# $FreeBSD: head/databases/postgresql10-pgtcl/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTREVISION=	2
PKGNAMESUFFIX=	-postgresql10

CONFLICTS=	pgtcl-[0-9]* pgtcl-postgresql9[0123456]-[0-9]*

PGTCL_SLAVE=	10
MASTERDIR=	${.CURDIR}/../pgtcl

.include "${MASTERDIR}/Makefile"
