# $FreeBSD: head/databases/postgresql10-pgtcl/Makefile 492989 2019-02-15 11:02:22Z girgen $

PORTREVISION=	0
PKGNAMESUFFIX=	-postgresql10

CONFLICTS=	pgtcl-[0-9]* pgtcl-postgresql9[0123456]-[0-9]*

PGTCL_SLAVE=	10
MASTERDIR=	${.CURDIR}/../pgtcl

.include "${MASTERDIR}/Makefile"
