# Created by: Pawel Pekala <c0rn@o2.pl>
# $FreeBSD: head/mail/claws-mail-fancy/Makefile 449036 2017-08-31 14:35:32Z pawel $

PORTNAME=	fancy
PORTREVISION=	0

COMMENT=	Webkit based HTML renderer plugin for Claws Mail

LIB_DEPENDS=	libsoup-gnome-2.4.so:devel/libsoup-gnome \
		libwebkitgtk-1.0.so:www/webkit-gtk2

CLAWS_PLUGINS_BUILD=	fancy

.include "../claws-mail/Makefile.claws"
.include <bsd.port.mk>
