# Created by: Cezary Morga <cm@therek.net>
# $FreeBSD: head/devel/p5-Locale-Msgfmt/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Locale-Msgfmt
PORTVERSION=	0.15
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Compile .po files to .mo files

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
