# $FreeBSD: head/sysutils/ansible24/Makefile 473687 2018-07-01 23:27:22Z lifanov $

PORTVERSION=	2.4.4.0
PORTREVISION=	1
PKGNAMESUFFIX=	24

CONFLICTS=	ansible-* ansible1-* ansible23-* ansible25-*

MASTERDIR=	${.CURDIR}/../ansible
DISTINFO_FILE=	${.CURDIR}/distinfo

EXTRA_PATCHES=

.include "${MASTERDIR}/Makefile"
