# $FreeBSD: head/sysutils/ansible24/Makefile 465604 2018-03-26 15:18:36Z lifanov $

PORTVERSION=	2.4.3.0
PKGNAMESUFFIX=	24

CONFLICTS=	ansible-* ansible1-* ansible23-*

MASTERDIR=	${.CURDIR}/../ansible
DISTINFO_FILE=	${.CURDIR}/distinfo

.include "${MASTERDIR}/Makefile"
