# $FreeBSD: head/textproc/hs-hxt-charproperties/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	hxt-charproperties
PORTVERSION=	9.2.0.1
PORTREVISION=	5
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Character properties and classes for XML and Unicode

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
