# $FreeBSD: head/textproc/hs-hxt-charproperties/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	hxt-charproperties
PORTVERSION=	9.2.0.1
PORTREVISION=	4
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Character properties and classes for XML and Unicode

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
