# $FreeBSD: head/textproc/hs-hxt-charproperties/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	hxt-charproperties
PORTVERSION=	9.2.0.1
PORTREVISION=	1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Character properties and classes for XML and Unicode

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
