# Created by: Tobias C. Berner <tcberner@FreeBSD.org>
# $FreeBSD: head/databases/sqlitebrowser-qt5/Makefile 423026 2016-09-30 21:57:26Z rm $

PORTNAME=	sqlitebrowser
PORTREVISION=	0
PKGNAMESUFFIX=	-qt5

CONFLICTS_INSTALL=	${PORTNAME}-3.*

MASTERDIR=	${.CURDIR:H}/sqlitebrowser

.include "${MASTERDIR}/Makefile"
