# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/security/pear-Horde_Oauth/Makefile 425775 2016-11-08 23:53:53Z mm $

PORTNAME=	Horde_Oauth
PORTVERSION=	2.0.3
CATEGORIES=	security www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde OAuth client/server

USES=	horde
USE_HORDE_RUN=	Horde_Exception \
		Horde_Http \
		Horde_Util
USE_PHP=	hash openssl

.include <bsd.port.mk>
