# $FreeBSD: head/net/rubygem-net-ping/Makefile 457846 2018-01-02 10:55:11Z romain $

PORTNAME=	net-ping
PORTVERSION=	2.0.2
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Collection of classes that provide different ways to ping computers

LICENSE=	APACHE20

USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
