# $FreeBSD: head/archivers/R-cran-zip/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	zip
DISTVERSION=	1.0.0
PORTREVISION=	1
CATEGORIES=	archivers
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	Cross-Platform 'zip' Compression

LICENSE=	CC0-1.0

TEST_DEPENDS=	R-cran-withr>0:devel/R-cran-withr

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
