# $FreeBSD: head/devel/hs-call-stack/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	call-stack
PORTVERSION=	0.1.0
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	The call-stack package

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
