# Created by: Richard Gallamore <ultima@FreeBSD.org>
# $FreeBSD: head/archivers/py-rjsmin/Makefile 444980 2017-07-03 19:06:08Z ultima $

PORTNAME=	rjsmin
PORTVERSION=	1.0.12
PORTREVISION=	1
CATEGORIES=	archivers python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ultima@FreeBSD.org
COMMENT=	Fast javascript minifier for Python

LICENSE=	APACHE20

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
