# $FreeBSD: head/x11/libXprintAppUtil/Makefile 479538 2018-09-11 18:34:27Z zeising $

PORTNAME=	libXprintAppUtil
PORTVERSION=	1.0.1
PORTREVISION=	5
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	The XprintAppUtil library

XORG_CAT=	lib
USE_XORG=	x11 xau xp xprintutil xorgproto

.include <bsd.port.mk>
