# Created by: Scott Sanders <scott@jssjr.com>
# $FreeBSD: head/www/rubygem-url_escape/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	url_escape
PORTVERSION=	2009.06.24
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Fast replacement for CGI.escape and Rack::Utils.escape

LICENSE=	MIT

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
