# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/www/py-apachelog/Makefile 487070 2018-12-09 18:30:32Z joneum $

PORTNAME=	apachelog
PORTVERSION=	1.1
PORTREVISION=	2
CATEGORIES=	www python
MASTER_SITES=	https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/apachelog/ \
		http://freebsd.unixfreunde.de/sources/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Python access log parser

LICENSE=	ART10 GPLv1+ # same as Perl
LICENSE_COMB=	dual

USES=		python:2.7
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
