# $FreeBSD: head/net-mgmt/zabbix2-java/Makefile 476352 2018-08-04 12:37:18Z dbaio $

PORTNAME=	zabbix2
CATEGORIES=	net-mgmt
PKGNAMESUFFIX=	-java

MASTERDIR=	${.CURDIR}/../zabbix2-server
PLIST=		${PKGDIR}/pkg-plist.java

OPTIONS_DEFINE=		IPV6

USE_JAVA=	yes

.include "${MASTERDIR}/Makefile"
