# Created by: Adam Weinberger <adamw@FreeBSD.org>
# $FreeBSD: head/www/rubygem-roda/Makefile 472222 2018-06-12 00:17:15Z adamw $

PORTNAME=	roda
PORTVERSION=	3.9.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	adamw@FreeBSD.org
COMMENT=	Routing tree web toolkit

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

RUN_DEPENDS=	rubygem-rack>=2.0:www/rubygem-rack

USES=		gem
USE_RUBY=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
