# $FreeBSD: head/devel/rubygem-simple-navigation/Makefile 439691 2017-04-28 21:40:51Z jrm $

PORTNAME=	simple-navigation
PORTVERSION=	4.0.5
PORTREVISION=	1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	jrm@FreeBSD.org
COMMENT=	Create navigations for Rails, Sinatra or Padrino applications

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-activesupport5>0:devel/rubygem-activesupport5

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
