# Created by: Philip Paeps <philip@FreeBSD.org>
# $FreeBSD: head/devel/py3-pylru-cache/Makefile 422508 2016-09-20 15:29:54Z philip $

MASTERDIR=	${.CURDIR}/../py-pylru-cache

USES=		python:3.2+

.include "${MASTERDIR}/Makefile"
