# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/mail/claws-mail-python/Makefile 489278 2019-01-04 20:59:10Z antoine $

PORTNAME=	python
PORTREVISION=	0

COMMENT=	Python scripting plugin for Claws Mail

BROKEN=		fails to stage

USE_GNOME=	pygtk2

CLAWS_PLUGINS_BUILD=	python

.include "../claws-mail/Makefile.claws"
.include <bsd.port.mk>
