# $FreeBSD: head/x11/gstreamer1-plugins-x/Makefile 405242 2016-01-04 14:21:56Z kwm $

PORTREVISION=	0
CATEGORIES=	x11

COMMENT=	GStreamer X and Xvideo output plugins

GST_PLUGIN=	x
DIST=		base

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
