# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/databases/pear-Horde_Imsp/Makefile 455798 2017-12-08 20:21:01Z joneum $

PORTNAME=	Horde_Imsp
DISTVERSION=	2.0.10
CATEGORIES=	databases www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde IMSP API

USES=	horde
USE_HORDE_RUN=	Horde_Translation

.include <bsd.port.mk>
