# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: head/multimedia/gstreamer-plugins-annodex/Makefile 428152 2016-12-08 19:52:19Z tijl $
#    $MCom: ports/multimedia/gstreamer-plugins-annodex/Makefile,v 1.1 2006/07/06 19:48:44 ahze Exp $

PORTREVISION=	2
CATEGORIES=	multimedia

COMMENT=	Gstreamer annodex CMML plugin

GST_PLUGIN=	annodex

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
