# Created by: renchap@cocoa-x.com
# $FreeBSD: head/devel/rubygem-mixlib-authentication/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	mixlib-authentication
PORTVERSION=	1.3.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	renchap@cocoa-x.com
COMMENT=	Mixes in simple per-request authentication

RUN_DEPENDS=	rubygem-mixlib-log>=0:devel/rubygem-mixlib-log

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
