# $FreeBSD: head/devel/hs-th-lift/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	th-lift
PORTVERSION=	0.7.8
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Derive Template Haskell's Lift class for datatypes.

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
