# $FreeBSD: head/devel/hs-th-lift/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	th-lift
PORTVERSION=	0.7.11
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Derive Template Haskell's Lift class for datatypes.

LICENSE=	BSD3CLAUSE

USE_CABAL=	th-abstraction

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
