# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/databases/py-pg8000/Makefile 477874 2018-08-23 14:28:01Z wen $

PORTNAME=	pg8000
PORTVERSION=	1.12.3
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Pure-Python Interface to the PostgreSQL Database

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
