# Created by: Dmitry Marakasov <amdmi3@FreeBSD.org>
# $FreeBSD: head/devel/py3-hgtools/Makefile 432226 2017-01-23 14:20:49Z amdmi3 $

MASTERDIR=	${.CURDIR}/../py-hgtools

USES=		python:3 zip

.include "${MASTERDIR}/Makefile"
