# $FreeBSD: head/devel/cpputest/Makefile 427288 2016-11-28 08:40:29Z wen $

PORTNAME=	cpputest
PORTVERSION=	3.8
DISTVERSIONPREFIX=	v
CATEGORIES=	devel

MAINTAINER=	akos.somfai@gmail.com
COMMENT=	Unit testing and mocking framework for C/C++

LICENSE=	BSD3CLAUSE

USE_GITHUB=	yes

USES=		autoreconf libtool pathfix
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
