# $FreeBSD: head/devel/rubygem-recursive-open-struct/Makefile 444203 2017-06-23 21:19:38Z sunpoet $

PORTNAME=	recursive-open-struct
PORTVERSION=	1.0.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Allows nested hashes to be treated in a recursive fashion

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
