# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/math/p5-Math-Evol/Makefile 443580 2017-06-14 16:10:11Z sunpoet $

PORTNAME=	Math-Evol
PORTVERSION=	1.13
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module implements the evolution search strategy

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
