# $FreeBSD: head/textproc/py-CommonMark/Makefile 465794 2018-03-28 11:07:59Z romain $

PORTNAME=	CommonMark
PORTVERSION=	0.7.5
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Python parser for the CommonMark Markdown spec

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
