# $FreeBSD: head/devel/rubygem-mmap2/Makefile 457897 2018-01-02 15:44:46Z swills $

PORTNAME=	mmap2
PORTVERSION=	2.2.9
PORTREVISION=	1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	idefix@fechner.net
COMMENT=	Implement memory-mapped file objects for Ruby 2.x

LICENSE=	RUBY

USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
