# $FreeBSD: head/devel/rubygem-mmap2/Makefile 451476 2017-10-07 19:01:09Z antoine $

PORTNAME=	mmap2
PORTVERSION=	2.2.7
PORTREVISION=	1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	tz@FreeBSD.org
COMMENT=	Implement memory-mapped file objects for Ruby 2.x

LICENSE=	RUBY

USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
