# $FreeBSD: head/devel/hs-uuagc-cabal/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	uuagc-cabal
PORTVERSION=	1.0.6.0
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cabal plugin for the Universiteit Utrecht Attribute Grammar System

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl>=2.0.1.0 uulib>=0.9.14

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
