# Created by: TERAMOTO Masahiro <markun@onohara.to>
# $FreeBSD: head/irc/p5-IRC-Utils/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	IRC-Utils
PORTVERSION=	0.12
PORTREVISION=	1
CATEGORIES=	irc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:HINRIK
PKGNAMEPREFIX=	p5-

MAINTAINER=	markun@onohara.to
COMMENT=	Common utilities for IRC-related tasks

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
