# Created by: chinsan
# $FreeBSD: head/devel/pecl-htscanner/Makefile 486751 2018-12-06 11:22:12Z rene $

PORTNAME=	htscanner
PORTVERSION=	1.0.1
PORTREVISION=	1
CATEGORIES=	devel pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Support htaccess for PHP

DEPRECATED=	Works only with EOL php 5.6
EXPIRATION_DATE=	2018-12-30

LICENSE=	PHP30

USES=		php:pecl
IGNORE_WITH_PHP=	71 72 73

CONFIGURE_ARGS=	--enable-htscanner

.include <bsd.port.mk>
