# Created by: Stephen Montgomery-Smith <stephen@math.missouri.edu>
# $FreeBSD: head/math/octave-forge-missing-functions/Makefile 495225 2019-03-10 04:56:17Z stephen $

PORTNAME=	octave-forge-missing-functions
PORTVERSION=	1.0.2
PORTREVISION=	23
CATEGORIES=	math

MAINTAINER=	stephen@FreeBSD.org
COMMENT=	Octave-forge package ${OCTAVE_PKGNAME}

GNU_CONFIGURE=	yes

.include "${.CURDIR}/../../Mk/bsd.octave.mk"
.include <bsd.port.mk>
