# $FreeBSD: head/devel/hs-vector-binary-instances/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	vector-binary-instances
PORTVERSION=	0.2.3.5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Instances of Data.Binary and Data.Serialize for vector

LICENSE=	BSD3CLAUSE

USE_CABAL=	cereal vector>=0.6

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
