# $FreeBSD: head/net-p2p/namecoin-daemon/Makefile 424861 2016-10-28 16:00:45Z danfe $

PKGNAMESUFFIX=	-daemon

MASTERDIR=	${.CURDIR}/../namecoin

DESCR=		${MASTERDIR}/pkg-descr

SLAVE_PORT=	yes

OPTIONS_EXCLUDE=	X11 DBUS QRCODES

.include "${MASTERDIR}/Makefile"
