# Created by: Jesper Schmitz Mouridsen
# $FreeBSD: head/x11-themes/lxqt-themes/Makefile 490472 2019-01-16 11:13:44Z tijl $

PORTNAME=	lxqt-themes
PORTVERSION=	0.13.0
PORTREVISION=	1
CATEGORIES=	x11-themes
MASTER_SITES=	LXQT

MAINTAINER=	jsm@FreeBSD.org
COMMENT=	Themes for the LXQt desktop

LICENSE=	LGPL21+

USES=		lxqt cmake tar:xz
USE_LXQT=	buildtools

.include <bsd.port.mk>
