# Created by: Danilo G. Baio <dbaio@FreeBSD.org>
# $FreeBSD: head/textproc/pear-Validate_ISPN/Makefile 463917 2018-03-08 19:48:41Z mat $

PORTNAME=	Validate_ISPN
PORTVERSION=	0.6.1
CATEGORIES=	textproc pear

MAINTAINER=	dbaio@FreeBSD.org
COMMENT=	Validation class for ISPN (International Standard Product Numbers)

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	${PEARDIR}/Validate.php:devel/pear-Validate@${PHP_FLAVOR}

USES=		pear
NO_ARCH=	yes

.include <bsd.port.mk>
