# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-bit/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	bit
DISTVERSION=	1.1-14
PORTREVISION=	1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Class for vectors of 1-bit booleans

LICENSE=	GPLv2

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
