# Created by: Ben Woods <woodsb02@FreeBSD.org>
# $FreeBSD: head/net/remmina-plugin-exec/Makefile 463551 2018-03-04 05:21:09Z woodsb02 $

PKGNAMESUFFIX=	-exec

COMMENT=	Remmina plugin to execute a command

USE_GNOME+=	cairo

MASTERDIR=	${.CURDIR}/../remmina-plugins

.include "${MASTERDIR}/Makefile"
