# Created by: Ben Woods <woodsb02@FreeBSD.org>
# $FreeBSD: head/net/remmina-plugin-exec/Makefile 478203 2018-08-27 13:05:13Z woodsb02 $

PKGNAMESUFFIX=	-exec

COMMENT=	Remmina plugin to execute a command

USE_GNOME+=	cairo

MASTERDIR=	${.CURDIR}/../remmina-plugins

.include "${MASTERDIR}/Makefile"
