# $FreeBSD: head/devel/rubygem-i18n/Makefile 434617 2017-02-22 17:15:00Z sunpoet $

PORTNAME=	i18n
PORTVERSION=	0.8.1
PORTEPOCH=	2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	New wave Internationalization support for Ruby

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
