# $FreeBSD: head/devel/rubygem-i18n/Makefile 445031 2017-07-04 18:37:33Z sunpoet $

PORTNAME=	i18n
PORTVERSION=	0.8.4
PORTEPOCH=	2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	New wave Internationalization support for Ruby

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
