# $FreeBSD: head/devel/rubygem-i18n/Makefile 461902 2018-02-15 12:46:50Z sunpoet $

PORTNAME=	i18n
PORTVERSION=	1.0.0
PORTEPOCH=	2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	New wave Internationalization support for Ruby

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

RUN_DEPENDS=	rubygem-concurrent-ruby>=1.0:devel/rubygem-concurrent-ruby

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
