# $FreeBSD: head/devel/gwenhywfar-qt5/Makefile 479538 2018-09-11 18:34:27Z zeising $

PORTREVISION=	1
PKGNAMESUFFIX=	-${SLAVEPORT}

MAINTAINER=	jhale@FreeBSD.org
COMMENT=	Gwenhywfar Qt5 support library

MASTERDIR=	${.CURDIR}/../../devel/gwenhywfar
SLAVEPORT=	qt5
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
