# $FreeBSD: head/devel/gwenhywfar-gtk3/Makefile 462080 2018-02-17 01:26:35Z jhale $

PORTREVISION=	0
PKGNAMESUFFIX=	-${SLAVEPORT}

MAINTAINER=	jhale@FreeBSD.org
COMMENT=	Gwenhywfar GTK3+ support library

MASTERDIR=	${.CURDIR}/../../devel/gwenhywfar
SLAVEPORT=	gtk3
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
