# Created by: TAKAHASHI Kaoru <kaoru@kaisei.org>
# $FreeBSD: head/devel/p5-Tie-Array-Pack/Makefile 458558 2018-01-09 18:44:07Z danfe $

PORTNAME=	Tie-Array-Pack
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Array implemented as a packed string

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
