# $FreeBSD: head/databases/php71-pgsql/Makefile 475229 2018-07-24 08:44:32Z tz $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php71

PKGNAMESUFFIX=	-pgsql

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
