# $FreeBSD: head/databases/php71-pgsql/Makefile 490236 2019-01-14 11:00:50Z tz $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php71

PKGNAMESUFFIX=	-pgsql

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
