# $FreeBSD: head/net-im/pecl-stomp2/Makefile 489349 2019-01-05 15:47:56Z rene $

PORTNAME=	stomp
PORTVERSION=	2.0.2
CATEGORIES=	net-im pear

MAINTAINER=	dbaio@FreeBSD.org
COMMENT=	PECL extension of stomp client

LICENSE=	PHP301
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		php:pecl
CONFLICTS=	pecl-stomp-1*

PORTSCOUT=	limit:^2.*

.include <bsd.port.mk>
