# $FreeBSD: head/textproc/php72-simplexml/Makefile 454302 2017-11-16 10:48:48Z tz $

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php72

PKGNAMESUFFIX=	-simplexml

.include "${MASTERDIR}/Makefile"
