# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: head/textproc/py-hypua2jamo/Makefile 455210 2017-11-30 15:50:30Z mat $

PORTNAME=	hypua2jamo
PORTVERSION=	0.3
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	zi@FreeBSD.org
COMMENT=	Convert Hanyang-PUA code to unicode Hangul Jamo

USES=		python:2.7
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
