# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-mcmc/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	mcmc
DISTVERSION=	0.9-5
PORTREVISION=	2
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Markov Chain Monte Carlo

LICENSE=	MIT

USES=	cran:compiles,auto-plist

.include <bsd.port.mk>
