# $FreeBSD: head/devel/elixir-msgpax/Makefile 441564 2017-05-24 04:41:25Z olgeni $

PORTNAME=	msgpax
PORTVERSION=	2.0.0
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	MessagePack implementation for Elixir

LICENSE=	ISCL

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	lexmag

MIX_REWRITE=	yes

.include <bsd.port.mk>
