# Created by: rpsfa@rit.edu
# $FreeBSD: head/dns/rubygem-net-dns/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	net-dns
PORTVERSION=	0.8.0
PORTREVISION=	1
CATEGORIES=	dns rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Pure Ruby DNS library

LICENSE=	BSD2CLAUSE RUBY
LICENSE_COMB=	dual

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
