# $FreeBSD: head/math/hs-fixed/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	fixed
PORTVERSION=	0.2.1.1
PORTREVISION=	3
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Signed 15.16 precision fixed point arithmetic

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
