# $FreeBSD: head/x11-fonts/libXfontcache/Makefile 479538 2018-09-11 18:34:27Z zeising $

PORTNAME=	libXfontcache
PORTVERSION=	1.0.5
PORTREVISION=	5
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	The Xfontcache library

XORG_CAT=	lib
USE_XORG=	x11 xext xorgproto

.include <bsd.port.mk>
