# $FreeBSD: head/textproc/hs-xmlhtml/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	xmlhtml
PORTVERSION=	0.2.5.2
PORTREVISION=	1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	XML parser and renderer with HTML 5 quirks mode

LICENSE=	BSD3CLAUSE

USE_CABAL=	blaze-builder blaze-html blaze-markup unordered-containers

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
