# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pear-channel-pdepend/Makefile 463917 2018-03-08 19:48:41Z mat $

PORTNAME=	pdepend
PORTVERSION=	20100520
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	pear.pdepend.org

.include "${PORTSDIR}/devel/pear/bsd.pear.channel.mk"
.include <bsd.port.mk>
