# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/science/R-cran-bayesm/Makefile 443845 2017-06-18 18:09:16Z dbn $

PORTNAME=	bayesm
PORTREVISION=	1
DISTVERSION=	3.0-2
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Bayesian Inference for Marketing/Micro-econometrics

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

RUN_DEPENDS=	R-cran-RcppArmadillo>=0:math/R-cran-RcppArmadillo

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
