# $FreeBSD: head/multimedia/gstreamer1-plugins-aom/Makefile 487820 2018-12-20 00:46:32Z jbeich $

PORTREVISION=	1
CATEGORIES=	multimedia

COMMENT=	GStreamer (libaom) plugin

GST_PLUGIN=	aom
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
