# $FreeBSD: head/math/py-algopy/Makefile 467660 2018-04-17 22:24:52Z yuri $

PORTNAME=	algopy
DISTVERSION=	0.5.7
CATEGORIES=	math python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	yuri@FreeBSD.org
COMMENT=	Algorithmic Differentiation (AD) and Taylor polynomial approximations

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	${PYNUMPY}

USES=		python zip
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
