# $FreeBSD: head/devel/py-shellingham/Makefile 495021 2019-03-08 07:01:05Z matthew $

PORTNAME=	shellingham
PORTVERSION=	1.3.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	matthew@FreeBSD.org
COMMENT=	Detect what shell the current Python executable is running in

LICENSE=	ISCL
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		python
USE_PYTHON=	autoplist concurrent distutils

# No tests implemented for this module.

.include <bsd.port.mk>
