# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: head/www/p5-Template-Plugin-Subst/Makefile 437950 2017-04-07 18:50:22Z lth $

PORTNAME=	Template-Plugin-Subst
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	TT plugin for s/// functionality in templates

BUILD_DEPENDS=	p5-Template-Toolkit>=0:www/p5-Template-Toolkit
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
