# Created by: jeffhung
# $FreeBSD: head/devel/p5-File-Util/Makefile 438848 2017-04-19 14:38:49Z sunpoet $

PORTNAME=	File-Util
PORTVERSION=	4.161950
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jeffhung@mail2000.com.tw
COMMENT=	Perl5 module for easy, versatile, portable file handling

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

TEST_DEPENDS=	p5-Test-NoWarnings>=0:devel/p5-Test-NoWarnings

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
