# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: head/x11/nvidia-driver-304/Makefile 437618 2017-04-03 12:08:32Z danfe $

DISTVERSION=	304.135
# Explicitly set PORTREVISION as it can be overridden by the master port
PORTREVISION=	0

MASTERDIR=	${.CURDIR}/../nvidia-driver
PKGNAMESUFFIX=	-304

.include "${MASTERDIR}/Makefile"
