# Created by: Mark Felder <feld@FreeBSD.org>
# $FreeBSD: head/devel/py-fabric3/Makefile 425178 2016-11-03 00:18:13Z feld $

PORTNAME=	fabric3
DISTVERSION=	1.12.post1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Fabric3-${DISTVERSION}

MAINTAINER=	feld@FreeBSD.org
COMMENT=	Python tool for remote execution and deployment

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
