# $FreeBSD: head/devel/rubygem-statsd-instrument/Makefile 470933 2018-05-26 17:49:34Z sunpoet $

PORTNAME=	statsd-instrument
PORTVERSION=	2.2.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	StatsD client for Ruby applications

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
