# $FreeBSD: head/devel/rubygem-statsd-instrument/Makefile 486193 2018-11-29 16:45:56Z sunpoet $

PORTNAME=	statsd-instrument
PORTVERSION=	2.3.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	StatsD client for Ruby applications

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
