# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-mocha/Makefile 476060 2018-07-31 23:48:24Z sunpoet $

PORTNAME=	mocha
PORTVERSION=	1.6.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Library for mocking and stubbing syntax like JMock and SchMock

LICENSE=	BSD2CLAUSE RUBY MIT
LICENSE_COMB=	dual
LICENSE_FILE_MIT=	${WRKSRC}/MIT-LICENSE.md

RUN_DEPENDS=	rubygem-metaclass>=0.0.1:devel/rubygem-metaclass

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
