# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/mail/hs-mime/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	mime
PORTVERSION=	0.4.0.2
PORTREVISION=	1
CATEGORIES=	mail haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Working with MIME types

LICENSE=	BSD3CLAUSE

USE_CABAL=	text>=0.9

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
