# $FreeBSD: head/devel/hs-say/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	say
PORTVERSION=	0.1.0.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	The say packagae

LICENSE=	BSD3CLAUSE

USE_CABAL=	text

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
