# $FreeBSD: head/www/rubygem-gollum-lib-gitlab/Makefile 434702 2017-02-24 09:43:48Z tz $

CATEGORIES=	www

MASTERDIR=	${.CURDIR}/../rubygem-gollum-lib

PKGNAMESUFFIX=	-gitlab

DEPRECATED=	Obsoleted by update of www/gitlab-ce. Please use www/rubygem-gitlab-gollum-lib instead.
EXPIRATION_DATE=	2018-07-31

OPTIONS_DEFAULT=	GITLAB

.include "${MASTERDIR}/Makefile"
