# Created by: Dmitry Liakh <dliakh@ukr.net>
# $FreeBSD: head/www/p5-Mobile-UserAgent/Makefile 412351 2016-04-01 14:33:55Z mat $

PORTNAME=	Mobile-UserAgent
PORTVERSION=	1.05
PORTREVISION=	1
CATEGORIES=	www
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	dliakh@ukr.net
COMMENT=	Parses a mobile user agent string into its basic constituent parts

RUN_DEPENDS=	p5-Class-Singleton>=0:devel/p5-Class-Singleton

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
