# $FreeBSD: head/biology/py-pysam/Makefile 479938 2018-09-17 17:40:28Z yuri $

PORTNAME=	pysam
DISTVERSION=	0.15.1
CATEGORIES=	biology python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	yuri@FreeBSD.org
COMMENT=	Python module for reading, manipulating and writing genomic data sets

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		gmake python
USE_PYTHON=	autoplist distutils cython cython_run

.include <bsd.port.mk>
