# $FreeBSD: head/devel/hs-microstache/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	microstache
PORTVERSION=	1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Mustache templates for Haskell

LICENSE=	BSD3CLAUSE

USE_CABAL=	aeson parsec semigroups text unordered-containers vector

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
