# $FreeBSD: head/net/nats-top/Makefile 420800 2016-08-24 15:13:39Z olgeni $

PORTNAME=	nats-top
PORTVERSION=	0.3.2
DISTVERSIONPREFIX=	v
CATEGORIES=	net

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Top like program monitor for NATS

LICENSE=	MIT

USES=		go
GO_PKGNAME=	github.com/nats-io/nats-top
USE_GITHUB=	yes
GH_ACCOUNT=	nats-io
GH_PROJECT=	nats-top
PLIST_FILES=	bin/nats-top

.include <bsd.port.mk>
