# $FreeBSD: head/devel/p5-BSD-devstat/Makefile 451816 2017-10-12 08:09:55Z sunpoet $

PORTNAME=	BSD-devstat
PORTVERSION=	0.02
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension of devstat(3) API

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
