# Created by: renchap@cocoa-x.com
# $FreeBSD: head/devel/rubygem-mixlib-cli/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	mixlib-cli
PORTVERSION=	1.4.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	renchap@cocoa-x.com
COMMENT=	Simple mixin for CLI interfaces, including option parsing

LICENSE=	APACHE20

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
