# Created by: Matthew X. Economou <xenophon+fbsdports@irtnog.org>
# $FreeBSD: head/graphics/py-django-easy-thumbnails/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	easy-thumbnails
PORTVERSION=	2.3
CATEGORIES=	graphics python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}django-

MAINTAINER=	xenophon+fbsdports@irtnog.org
COMMENT=	Easy thumbnails for Django

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}django18>=0:www/py-django18

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
