# $FreeBSD: head/devel/npth/Makefile 445580 2017-07-12 10:12:15Z jhale $

PORTNAME=	npth
PORTVERSION=	1.5
CATEGORIES=	devel
MASTER_SITES=	GNUPG

MAINTAINER=	jhale@FreeBSD.org
COMMENT=	New GNU Portable Threads

LICENSE=	LGPL21+
LICENSE_FILE=	${WRKSRC}/COPYING.LIB

USES=		tar:bzip2 libtool
USE_LDCONFIG=	yes
GNU_CONFIGURE=	yes
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
