# $FreeBSD: head/sysutils/rcm/Makefile 476222 2018-08-02 07:04:01Z tobik $

PORTNAME=	rcm
PORTVERSION=	1.3.3
CATEGORIES=	sysutils
MASTER_SITES=	https://thoughtbot.github.io/rcm/dist/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	RC file (dotfile) management

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
