# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: head/www/p5-HTML-TableContentParser/Makefile 468776 2018-05-01 17:57:47Z skreuzer $

PORTNAME=	HTML-TableContentParser
PORTVERSION=	0.300
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Do interesting things with the contents of tables

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

RUN_DEPENDS=	p5-HTML-Parser>=3.68:www/p5-HTML-Parser

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
