# Created by: Samy Al Bahra <sbahra@kerneled.org>
# $FreeBSD: head/ports-mgmt/hs-porte/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	porte
PORTVERSION=	0.0.4
PORTREVISION=	18
CATEGORIES=	ports-mgmt haskell

MAINTAINER=	sbahra@repnop.org
COMMENT=	FreeBSD ports index search and statistical analysis tool

LICENSE=	BSD3CLAUSE

USE_CABAL=	extensible-exceptions stringsearch

EXECUTABLE=	porte

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
