# $FreeBSD: head/databases/postgresql95-pgtcl/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTREVISION=	1
PKGNAMESUFFIX=	-postgresql95

CONFLICTS=	pgtcl-[0-9]* pgtcl-postgresql9[01234]-[0-9]*

PGTCL_SLAVE=	9.5
MASTERDIR=	${.CURDIR}/../pgtcl

.include "${MASTERDIR}/Makefile"
