# $FreeBSD: head/databases/qt5-sqldrivers-odbc/Makefile 492793 2019-02-12 17:43:00Z tcberner $


COMMENT=	Qt ${DB_DESC} plugin

DB=		ODBC
DB_DESC=	Open Database Connectivity

LIB_DEPENDS=	libodbc.so:databases/unixODBC

.include "${.CURDIR:H:H}/devel/qt5/Makefile.sqldrivers"
