# $FreeBSD: head/databases/qt5-sqldrivers-odbc/Makefile 490472 2019-01-16 11:13:44Z tijl $

PORTREVISION=	1

COMMENT=	Qt ${DB_DESC} plugin

DB=		ODBC
DB_DESC=	Open Database Connectivity

LIB_DEPENDS=	libodbc.so:databases/unixODBC

.include "${.CURDIR:H:H}/devel/qt5/Makefile.sqldrivers"
