# Created by: Alexander Logvinov <ports@logvinov.com>
# $FreeBSD: head/www/rubygem-maruku/Makefile 431564 2017-01-15 14:32:00Z swills $

PORTNAME=	maruku
PORTVERSION=	0.7.3
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Markdown and PHP Markdown extra interpreter for Ruby

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

PLIST_FILES=	bin/maruku bin/marutex

.include <bsd.port.mk>
