# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/devel/pear-Horde_Autoloader/Makefile 407900 2016-02-02 22:56:26Z mm $

PORTNAME=	Horde_Autoloader
PORTVERSION=	2.1.2
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Autoloader

USES=	horde

.include <bsd.port.mk>
