# $FreeBSD: head/devel/rubygem-algebrick/Makefile 450983 2017-09-30 11:47:25Z sunpoet $

PORTNAME=	algebrick
PORTVERSION=	0.7.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Typed structs based on algebraic type definitions

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
