# $FreeBSD: head/www/rubygem-browser/Makefile 449076 2017-09-01 10:51:34Z sunpoet $

PORTNAME=	browser
PORTVERSION=	2.5.1
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Web browser detection for Ruby

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
