# Created by: Mons Anderson <mons@cpan.org>
# $FreeBSD: head/devel/p5-common-sense/Makefile 410927 2016-03-12 19:04:34Z adamw $

PORTNAME=	common-sense
PORTVERSION=	3.74
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:MLEHMANN
PKGNAMEPREFIX=	p5-

MAINTAINER=	mons@cpan.org
COMMENT=	Perl common defaults with lower memory usage

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
