# $FreeBSD: head/graphics/qt5-graphicaleffects/Makefile 473503 2018-06-28 17:39:53Z tcberner $

PORTNAME=	graphicaleffects
DISTVERSION=	${QT5_VERSION}
CATEGORIES=	graphics
PKGNAMEPREFIX=	qt5-

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Qt Quick graphical effects

USES=		qmake qt-dist:5,graphicaleffects
USE_QT=		buildtools_build core gui quick qml

.include <bsd.port.mk>
