# Created by: Peter Johnson <johnson.peter@gmail.com>
# $FreeBSD: head/security/zzuf/Makefile 418981 2016-07-23 23:04:10Z bapt $

PORTNAME=	zzuf
PORTVERSION=	0.13
PORTREVISION=	1
CATEGORIES=	security
MASTER_SITES=	http://caca.zoy.org/raw-attachment/wiki/zzuf/

MAINTAINER=	johnson.peter@gmail.com
COMMENT=	Transparent application input fuzzer

USES=		libtool
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

.include <bsd.port.mk>
