# Created by: ijliao
# $FreeBSD: head/graphics/p5-GD-Arrow/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	GD-Arrow
PORTVERSION=	0.01
PORTREVISION=	5
CATEGORIES=	graphics perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Draw arrows using GD

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

BUILD_DEPENDS=	p5-GD>=0:graphics/p5-GD
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
