# Created by: Veniamin Gvozdikov <vg@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-murmurhash3/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	murmurhash3
PORTVERSION=	0.1.6
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	vg@FreeBSD.org
COMMENT=	Implementation of murmur3 hashing function

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
