# Created by: Maxim Sobolev <sobomax@FreeBSD.org>
# $FreeBSD: head/devel/p5-Class-Generate/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	Class-Generate
PORTVERSION=	1.15
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simplify the creation of class hierarchies

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Text-Soundex>=0:textproc/p5-Text-Soundex

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
