# Created by: Yarema <yds@CoolRat.org>
# $FreeBSD: head/net/courier-authlib-ldap/Makefile 450857 2017-09-28 18:46:27Z madpilot $

PORTREVISION=	1
PKGNAMESUFFIX=	-ldap

COMMENT=	LDAP support for the Courier authentication library
CATEGORIES=	net mail

MASTERDIR=	${.CURDIR}/../../security/courier-authlib

.include "${MASTERDIR}/Makefile"
