# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/www/pear-Horde_Service_Weather/Makefile 435605 2017-03-07 14:22:52Z mm $

PORTNAME=	Horde_Service_Weather
PORTVERSION=	2.5.4
CATEGORIES=	www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Weather Provider

USES=	horde
USE_HORDE_BUILD=	Horde_Role
USE_HORDE_RUN=	Horde_Role \
		Horde_Date \
		Horde_Exception \
		Horde_Http \
		Horde_Translation \
		Horde_Url

.include <bsd.port.mk>
