# Created by: Pawel Pekala <pawel@FreeBSD.org>
# $FreeBSD: head/mail/claws-mail-bogofilter/Makefile 412348 2016-04-01 14:16:16Z mat $

PORTNAME=	bogofilter
PORTREVISION=	0

COMMENT=	Spam filtering plugin for Claws Mail

RUN_DEPENDS=	bogofilter:mail/bogofilter

CLAWS_PLUGINS_BUILD=	bogofilter

.include "../claws-mail/Makefile.claws"
.include <bsd.port.mk>
