# Created by: Wen heping <wenheping@gmail.com>)
# $FreeBSD: head/www/pear-Services_Facebook/Makefile 443357 2017-06-11 07:47:55Z sunpoet $

PORTNAME=	Services_Facebook
PORTVERSION=	0.2.14
CATEGORIES=	www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PHP interface to Facebook's API

BUILD_DEPENDS=	${PEARDIR}/Validate.php:devel/pear-Validate
RUN_DEPENDS=	${PEARDIR}/Validate.php:devel/pear-Validate

USES=		pear php
USE_PHP=	curl

.include <bsd.port.mk>
