# $FreeBSD: head/graphics/gstreamer1-plugins-openjpeg/Makefile 451711 2017-10-10 17:45:57Z sunpoet $

PORTREVISION=	0
CATEGORIES=	graphics

COMMENT=	GStreamer jpeg2000 decoder plugin

GST_PLUGIN=	openjpeg
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

EXTRA_PATCHES=	${.CURDIR}/files/patch-openjpeg23

.include "${MASTERDIR}/Makefile"
