# $FreeBSD: head/graphics/gstreamer1-plugins-openjpeg/Makefile 448363 2017-08-20 09:48:39Z sunpoet $

PORTREVISION=	0
CATEGORIES=	graphics

COMMENT=	GStreamer jpeg2000 decoder plugin

GST_PLUGIN=	openjpeg
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

EXTRA_PATCHES=	${.CURDIR}/files/patch-openjpeg22

.include "${MASTERDIR}/Makefile"
