# Created by: Dirk Froemberg <dirk@FreeBSD.org>
# $FreeBSD: head/japanese/php_doc/Makefile 353996 2014-05-13 21:13:31Z edwin $

CATEGORIES=	japanese lang
PKGNAMEPREFIX=
PHP_LANG=	ja
MASTERDIR=	${.CURDIR}/../../lang/php_doc

.include "${MASTERDIR}/Makefile"
