# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/textproc/rubygem-yard/Makefile 439310 2017-04-24 15:17:23Z sunpoet $

PORTNAME=	yard
PORTVERSION=	0.9.9
CATEGORIES=	textproc devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Documentation generation tool for Ruby

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

PLIST_FILES=	bin/yard \
		bin/yardoc \
		bin/yri

.include <bsd.port.mk>
