# $FreeBSD: head/devel/hs-unix-time/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	unix-time
PORTVERSION=	0.3.7
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unix time parser/formatter and utilities

LICENSE=	BSD3CLAUSE

USE_CABAL=	old-time

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
