# $FreeBSD: head/x11/dsbautostart/Makefile 490472 2019-01-16 11:13:44Z tijl $

PORTNAME=	dsbautostart
PORTVERSION=	1.1
PORTREVISION=	1
CATEGORIES=	x11
MASTER_SITES=	http://freeshell.de/~mk/download/

MAINTAINER=	mk@nic-nac-project.org
COMMENT=	Manage commands to be executed at X session start

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		qt:5 tar:tgz qmake

USE_GL=		gl
USE_QT=		buildtools_build core gui linguisttools_build widgets

.include <bsd.port.mk>
