# $FreeBSD: head/math/hs-dense-linear-algebra/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	dense-linear-algebra
PORTVERSION=	0.1.0.0
PORTREVISION=	1
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple and incomplete pure haskell implementation of linear algebra

LICENSE=	BSD3CLAUSE

USE_CABAL=	math-functions vector-algorithms vector-binary-instances

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
