# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-atomic/Makefile 469666 2018-05-11 16:54:11Z sunpoet $

PORTNAME=	atomic
PORTVERSION=	1.1.101
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Atomic reference implementation

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
