# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-BH/Makefile 465176 2018-03-21 14:03:11Z tota $

PORTNAME=	BH
DISTVERSION=	1.66.0-1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Boost C++ Header Files

LICENSE=	BSL

USES=	cran:auto-plist

.include <bsd.port.mk>
