# $FreeBSD: head/irc/rubygem-cinch/Makefile 450220 2017-09-20 16:32:27Z sunpoet $

PORTNAME=	cinch
PORTVERSION=	2.3.4
CATEGORIES=	irc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	IRC Bot Building Framework

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
