# Created by: Alfred Perlstein <alfred@freebsd.org>
# $FreeBSD: head/www/py-djangorestframework/Makefile 411537 2016-03-21 05:03:30Z alfred $

PORTNAME=	djangorestframework
PORTVERSION=	3.3.3
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	alfred@FreeBSD.org
COMMENT=	Django REST framework

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
