# Created by: Alfred Perlstein <alfred@freebsd.org>
# $FreeBSD: head/www/py-djangorestframework/Makefile 457543 2017-12-29 20:53:29Z antoine $

PORTNAME=	djangorestframework
PORTVERSION=	3.6.4
PORTEPOCH=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	alfred@FreeBSD.org
COMMENT=	Django REST framework

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
