# $FreeBSD: head/devel/hs-timezone-series/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	timezone-series
PORTVERSION=	0.1.8
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Enhanced timezone handling for Data.Time

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
