# $FreeBSD: head/devel/hs-Glob/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	Glob
PORTVERSION=	0.8.0
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Globbing library

LICENSE=	BSD3CLAUSE

USE_CABAL=	dlist>=0.4 transformers-compat

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
