# $FreeBSD: head/devel/hs-Glob/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	Glob
PORTVERSION=	0.8.0
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Globbing library

LICENSE=	BSD3CLAUSE

USE_CABAL=	dlist>=0.4 transformers-compat

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
