# $FreeBSD: head/multimedia/gstreamer1-plugins-smoothstreaming/Makefile 446388 2017-07-22 11:35:44Z kwm $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	GStreamer parse and demuliplex a Smooth Streaming manifest into audio/video streams plugin

GST_PLUGIN=	smoothstreaming
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
