# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: head/www/twiki-LdapContrib/Makefile 412351 2016-04-01 14:33:55Z mat $

PORTNAME=	LdapContrib
SVNREV=		16840
PORTREVISION=	1
MASTER_SITES=	http://protey.ru/freebsd/distfiles/ \
		LOCAL/skv

COMMENT=	LDAP services for TWiki

RUN_DEPENDS=	p5-perl-ldap>=0:net/p5-perl-ldap

.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
