# $FreeBSD: head/devel/py-python-socketio/Makefile 445317 2017-07-08 11:01:31Z mmokhi $

PORTNAME=	python-socketio
PORTVERSION=	1.7.6
CATEGORIES=	devel python net
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	mmokhi@FreeBSD.org
COMMENT=	Python implementation of the SocketIO realtime server

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
