# $FreeBSD: head/net-p2p/hs-torrent/Makefile 442133 2017-05-31 02:23:36Z danfe $

PORTNAME=	torrent
PORTVERSION=	10000.0.0
CATEGORIES=	net-p2p haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	BitTorrent file parser and generator

LICENSE=	BSD3CLAUSE

USE_CABAL=	bencode>=0.2 syb

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
