# $FreeBSD: head/net-p2p/hs-torrent/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	torrent
PORTVERSION=	10000.1.1
PORTREVISION=	1
CATEGORIES=	net-p2p haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	BitTorrent file parser and generator

LICENSE=	BSD3CLAUSE

USE_CABAL=	bencode>=0.2 syb

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
