# Created by: Alonso Cardenas Marquez <acm@FreeBSD.org>
# $FreeBSD: head/devel/dcd-client/Makefile 446442 2017-07-23 02:53:47Z acm $

PORTREVISION=	0
CATEGORIES=	devel
PKGNAMESUFFIX=	-client

COMMENT=	Auto-complete program for the D programming language (client)

MASTERDIR=	${.CURDIR}/../../devel/dcd-server

PLIST=		${.CURDIR}/pkg-plist

DUB_CONFIG=	client

.include "${MASTERDIR}/Makefile"
