# $FreeBSD: head/devel/py-pyinotify/Makefile 416469 2016-06-06 15:25:42Z mat $

PORTNAME=	pyinotify
PORTVERSION=	0.9.6
CATEGORIES=	devel
MASTER_SITES=	CHEESESHOP/source/p/pyinotify
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jpaetzel@FreeBSD.org
COMMENT=	Python interface to (lib)inotify

LICENSE=	MIT

LIB_DEPENDS=	libinotify.so:devel/libinotify

USES=		python
USE_PYTHON=	distutils

.include <bsd.port.mk>
