# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/py-whistle/Makefile 465537 2018-03-25 18:05:45Z sunpoet $

PORTNAME=	whistle
PORTVERSION=	1.0.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Event dispatcher

LICENSE=	APACHE20

NO_ARCH=	yes
USE_PYTHON=	autoplist distutils
USES=		python:3.5+

.include <bsd.port.mk>
