# $FreeBSD: head/devel/hs-extensible-exceptions/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	extensible-exceptions
PORTVERSION=	0.1.1.4
PORTREVISION=	10
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Extensible exceptions

LICENSE=	BSD3CLAUSE

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
