# $FreeBSD: head/devel/hs-extensible-exceptions/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	extensible-exceptions
PORTVERSION=	0.1.1.4
PORTREVISION=	8
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Extensible exceptions

LICENSE=	BSD3CLAUSE

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
