# $FreeBSD: head/print/harfbuzz-icu/Makefile 450872 2017-09-28 20:52:07Z jbeich $

PORTREVISION=	2
PKGNAMESUFFIX=	-icu

COMMENT=	Harfbuzz ICU support

MASTERDIR=	${.CURDIR}/../../print/harfbuzz
PLIST=		pkg-plist
HARFBUZZ_SLAVE=	icu

.include "${MASTERDIR}/Makefile"
