# $FreeBSD: head/print/harfbuzz-icu/Makefile 482830 2018-10-23 11:35:03Z jbeich $

PORTREVISION=	1
PKGNAMESUFFIX=	-icu

COMMENT=	Harfbuzz ICU support

MASTERDIR=	${.CURDIR}/../../print/harfbuzz
PLIST=		${.CURDIR}/pkg-plist
HARFBUZZ_SLAVE=	icu

.include "${MASTERDIR}/Makefile"
