# $FreeBSD: head/print/harfbuzz-icu/Makefile 476207 2018-08-01 22:32:04Z jbeich $

PORTREVISION=	0
PKGNAMESUFFIX=	-icu

COMMENT=	Harfbuzz ICU support

MASTERDIR=	${.CURDIR}/../../print/harfbuzz
PLIST=		${.CURDIR}/pkg-plist
HARFBUZZ_SLAVE=	icu

.include "${MASTERDIR}/Makefile"
