# $FreeBSD: head/devel/rubygem-uuidtools/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	uuidtools
PORTVERSION=	2.1.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Simple universally unique ID generation library

LICENSE=	APACHE20

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
