# $FreeBSD: head/www/py-multidict/Makefile 476643 2018-08-08 13:53:09Z wg $

PORTNAME=	multidict
PORTVERSION=	4.3.1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Multidict implementation

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python:3.4+
USE_PYTHON=	autoplist distutils cython

.include <bsd.port.mk>
