# $FreeBSD: head/devel/hs-reflection/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	reflection
PORTVERSION=	2.1.4
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Reifies arbitrary terms into types that can be reflected back into terms

LICENSE=	BSD3CLAUSE

USE_CABAL=	tagged>=0.4.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
