# $FreeBSD: head/devel/hs-reflection/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	reflection
PORTVERSION=	2.1.3
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Reifies arbitrary terms into types that can be reflected back into terms

LICENSE=	BSD3CLAUSE

USE_CABAL=	tagged>=0.4.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
