# $FreeBSD: head/devel/py-pydevd/Makefile 461934 2018-02-15 16:53:33Z amdmi3 $

PORTNAME=	pydevd
PORTVERSION=	1.1.1
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Debugger used in PyDev and PyCharm

USES=		python
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
