# $FreeBSD: head/devel/py-pydevd/Makefile 449092 2017-09-01 18:10:09Z wg $

PORTNAME=	pydevd
PORTVERSION=	1.1.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Debugger used in PyDev and PyCharm

USES=		python
USE_PYTHON=	autoplist concurrent distutils
NO_ARCH=	yes

.include <bsd.port.mk>
