# $FreeBSD: head/textproc/hs-scanner/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	scanner
PORTVERSION=	0.2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Parser combinator library designed to be fast

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
