# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-coffee-script-source/Makefile 430383 2017-01-02 17:45:51Z swills $

PORTNAME=	coffee-script-source
PORTVERSION=	1.12.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	CoffeeScript is a little language that compiles into JavaScript

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
