# Created by: renchap@cocoa-x.com
# $FreeBSD: head/devel/rubygem-mixlib-config/Makefile 446975 2017-07-31 15:50:13Z sunpoet $

PORTNAME=	mixlib-config
PORTVERSION=	2.2.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	renchap@cocoa-x.com
COMMENT=	Class based config mixin, similar to the one found in Chef

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
