# Created by: renchap@cocoa-x.com
# $FreeBSD: head/devel/rubygem-mixlib-config/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	mixlib-config
PORTVERSION=	2.1.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	renchap@cocoa-x.com
COMMENT=	Class based config mixin, similar to the one found in Chef

LICENSE=	APACHE20

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
