# Created by: Yen-Ming Lee <leeym@leeym.com>
# $FreeBSD: head/net/udptunnel/Makefile 430409 2017-01-02 21:00:18Z hrs $

PORTNAME=	udptunnel
PORTVERSION=	1.1
PORTREVISION=	1
CATEGORIES=	net
MASTER_SITES=	http://www.cs.columbia.edu/~lennox/udptunnel/

MAINTAINER=	hrs@FreeBSD.org
COMMENT=	Tunnel UDP packets over a TCP connection

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/COPYRIGHT

GNU_CONFIGURE=	yes
PLIST_FILES=	bin/udptunnel

.include <bsd.port.mk>
