# Created by: Mark Felder <feld@FreeBSD.org>
# $FreeBSD: head/devel/py-bluelet/Makefile 481127 2018-10-02 19:06:16Z feld $

PORTNAME=	bluelet
PORTVERSION=	0.2.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Pure-Python asynchronous I/O using coroutines

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
