# Created by: Greg Larkin <glarkin@FreeBSD.org>
# $FreeBSD: head/math/pecl-bitset/Makefile 438175 2017-04-10 15:08:47Z mat $

PORTNAME=	bitset
PORTVERSION=	3.0.0
PORTREVISION=	1
CATEGORIES=	math

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	PECL extension for manipulating bitsets

LICENSE=	PHP301
LICENSE_FILE=	${WRKSRC}/LICENSE

IGNORE_WITH_PHP=56
USES=		php:pecl

.include <bsd.port.mk>
