# Created by: clsung@dragon2.net
# $FreeBSD: head/chinese/p5-Lingua-ZH-Toke/Makefile 412344 2016-04-01 13:29:15Z mat $

PORTNAME=	Lingua-ZH-Toke
PORTVERSION=	0.02
PORTREVISION=	2
CATEGORIES=	chinese perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Chinese Tokenizer on steroids

BUILD_DEPENDS=	p5-Lingua-ZH-TaBE>=0:chinese/p5-Lingua-ZH-TaBE
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
