# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-bdsmatrix/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	bdsmatrix
DISTVERSION=	1.3-3
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Routines for Block Diagonal Symmetric matrices

LICENSE=	LGPL20

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
