# Created by: clsung@dragon2.net
# $FreeBSD: head/net/p5-Net-MovableType/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	Net-MovableType
PORTVERSION=	1.74
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Lightweight MovableType client Perl module

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-SOAP-Lite>=0:net/p5-SOAP-Lite

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
