# Created by: mat
# $FreeBSD: head/databases/p5-DBIx-Ease/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	DBIx-Ease
PORTVERSION=	0.07
PORTREVISION=	1
CATEGORIES=	databases perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Less-code DBI interactions for all drivers

BUILD_DEPENDS=	p5-DBI>=0:databases/p5-DBI
RUN_DEPENDS=	p5-DBI>=0:databases/p5-DBI

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
