# Created by: Daichi GOTO <daichi@FreeBSD.org>
# $FreeBSD: head/devel/open-usp-tukubai/Makefile 471288 2018-06-01 20:21:37Z rene $

PORTNAME=	open-usp-tukubai
PORTVERSION=	2014061402
CATEGORIES=	devel
MASTER_SITES=	https://uec.usp-lab.com/TUKUBAI/DOWNLOAD/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Open usp Tukubai is OSS version of Tukubai commands set

USES=		gmake python tar:bzip2

NO_BUILD=	yes
MAKE_ENV+=	STAGEDIR=${STAGEDIR}

.include <bsd.port.mk>
