# $FreeBSD: head/www/rubygem-rails-settings-cached-rails50/Makefile 447386 2017-08-05 03:25:17Z jrm $

PORTNAME=	rails-settings-cached
PORTVERSION=	0.6.6
CATEGORIES=	www rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	-rails50

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Rails settings plugin for easily managing key-value pairs table

LICENSE=	MIT

RUN_DEPENDS=	rubygem-rails50>=0:www/rubygem-rails50

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
