# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: head/devel/p5-Carp-Assert/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	Carp-Assert
PORTVERSION=	0.21
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Executable comments like the ANSI C library assert.h

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

TEST_DEPENDS=	pod2test:devel/p5-Pod-Tests

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
