# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/finance/R-cran-TTR/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	TTR
DISTVERSION=	0.23-1
CATEGORIES=	finance
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Technical Trading Rules

LICENSE=	GPLv2

RUN_DEPENDS=	R-cran-xts>=0.9.3:math/R-cran-xts

USES=	cran:auto-plist

.include <bsd.port.mk>
