# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/finance/R-cran-TTR/Makefile 443845 2017-06-18 18:09:16Z dbn $

PORTNAME=	TTR
PORTREVISION=	1
DISTVERSION=	0.23-1
CATEGORIES=	finance
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Technical Trading Rules

LICENSE=	GPLv2

RUN_DEPENDS=	R-cran-xts>=0.9.3:math/R-cran-xts

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
