# Created by: Timur I. Bakeyev <bat@cpan.org>
# $FreeBSD: head/databases/p5-Relations-Query/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	Relations-Query
PORTVERSION=	0.93
PORTREVISION=	1
CATEGORIES=	databases perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Object for building queries with DBI/DBD::mysql

BUILD_DEPENDS=	p5-Relations>=0:databases/p5-Relations
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
