# Created by: joerg
# $FreeBSD: head/deskutils/sliderule/Makefile 437439 2017-04-01 15:23:30Z gerald $

PORTNAME=	sliderule
PORTVERSION=	1.0
PORTREVISION=	4
CATEGORIES=	deskutils
MASTER_SITES=	LOCAL/joerg
DISTNAME=	${PORTNAME}

MAINTAINER=	joerg@FreeBSD.org
COMMENT=	The part of X11R3's xcalc featuring a slide rule

USES=		imake
USE_XORG=	x11 xext
USE_GCC=	any
PLIST_FILES=	bin/sliderule man/man1/sliderule.1.gz

.include <bsd.port.mk>
