# $FreeBSD: head/www/rubygem-acts-as-taggable-on5/Makefile 441546 2017-05-23 18:52:24Z sunpoet $

PORTNAME=	acts-as-taggable-on
PORTVERSION=	5.0.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	5

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Tag a single model on several contexts

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.md

RUN_DEPENDS=	rubygem-activerecord4>=4.2.8:databases/rubygem-activerecord4

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
