# $FreeBSD: head/lang/tcbasic/Makefile 449572 2017-09-10 13:43:09Z tobik $

PORTNAME=	tcbasic
PORTVERSION=	2.2.0
CATEGORIES=	lang
MASTER_SITES=	https://github.com/tcort/${PORTNAME}/releases/download/v${PORTVERSION}/

MAINTAINER=	linuxgeek@gmail.com
COMMENT=	Small BASIC Interpreter written in C

LICENSE=	GPLv3

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/tcbasic man/man1/tcbasic.1.gz

.include <bsd.port.mk>
