# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-RUnit/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	RUnit
PORTVERSION=	0.4.28
PORTREVISION=	1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	R functions implementing a Unit Testing framework

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
