# Created by: Joseph Benden <joe@thrallingpenguin.com>
# $FreeBSD: head/www/rubygem-hashicorp-checkpoint/Makefile 450530 2017-09-24 18:51:03Z sunpoet $

PORTNAME=	hashicorp-checkpoint
PORTVERSION=	0.1.4
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	joe@thrallingpenguin.com
COMMENT=	Internal HashiCorp service to check version information

LICENSE=	MPL20
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
