# Created by: Christopher Key <cjk32@cam.ac.uk>
# $FreeBSD: head/devel/p5-UUID-Tiny/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	UUID-Tiny
PORTVERSION=	1.04
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Pure Perl UUID Support With Functional Interface

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Digest-SHA1>=0:security/p5-Digest-SHA1

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
