# $FreeBSD: head/sysutils/sbase/Makefile 460461 2018-01-31 06:25:40Z yuri $

PORTNAME=	sbase
DISTVERSION=	g20171110
CATEGORIES=	sysutils
MASTER_SITES=	https://git.suckless.org/sbase/snapshot/
DISTNAME=	${PORTNAME}-4b9c664

MAINTAINER=	pkubaj@anongoth.pl
COMMENT=	Collection of UNIX tools that are portable across UNIX-like systems

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

.include <bsd.port.mk>
