# Created by: Chris St Denis (<chris@ctgameinfo.com>)
# $FreeBSD: head/dns/pear-File_DNS/Makefile 443252 2017-06-11 07:39:12Z sunpoet $

PORTNAME=	File_DNS
PORTVERSION=	0.1.0
CATEGORIES=	dns devel pear

MAINTAINER=	chris@ctgameinfo.com
COMMENT=	PEAR class to read and write RFC1033-style DNS Zonefiles

BUILD_DEPENDS=	${PEARDIR}/File.php:sysutils/pear-File
RUN_DEPENDS=	${PEARDIR}/File.php:sysutils/pear-File

USES=		pear

.include <bsd.port.mk>
