# Created by: Pav Lucistnik <pav@FreeBSD.org>
# $FreeBSD: head/textproc/pear-Spreadsheet_Excel_Writer/Makefile 463917 2018-03-08 19:48:41Z mat $

PORTNAME=	Spreadsheet_Excel_Writer
PORTVERSION=	0.9.4
CATEGORIES=	textproc www pear

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	PEAR class for writing Microsoft Excel files

LICENSE=	LGPL3

BUILD_DEPENDS=	${PEARDIR}/OLE.php:devel/pear-OLE@${PHP_FLAVOR}
RUN_DEPENDS=	${PEARDIR}/OLE.php:devel/pear-OLE@${PHP_FLAVOR}

USES=	pear
NO_ARCH=	yes

.include <bsd.port.mk>
