# Created by: Emanuel Haupt <ehaupt@FreeBSD.org>
# $FreeBSD: head/shells/bash-static/Makefile 486080 2018-11-28 07:28:41Z ehaupt $

MASTERDIR=	${.CURDIR}/../../shells/bash

OPTIONS_SLAVE=	STATIC

PKGNAMESUFFIX=	-static

.include "${MASTERDIR}/Makefile"
