# Created by: Oleg Pudeyev <oleg@bsdpower.com>
# $FreeBSD: head/x11/gtk-theme-switch2/Makefile 428152 2016-12-08 19:52:19Z tijl $

PORTNAME=	gtk-theme-switch
DISTVERSION=	2.0.0rc2
PORTREVISION=	6
CATEGORIES=	x11
MASTER_SITES=	http://www.muhri.net/

MAINTAINER=	oleg@bsdpower.com
COMMENT=	Command line tool for switching GTK+ 2.0 themes

USES=		gmake pkgconfig
USE_XORG=	x11
USE_GNOME=	gtk20

PLIST_FILES=	bin/switch2 man/man1/switch2.1.gz

.include <bsd.port.mk>
