# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: head/textproc/hil-aspell/Makefile 438338 2017-04-12 09:09:47Z mat $

PORTNAME=	${DICT}-aspell
SPELLVERSION=	5-hil-0.11-0
PORTREVISION=	1
PORTEPOCH=	2
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Hiligaynon dictionary

DICT=	 	hil

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
