# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: head/devel/p5-Set-NestedGroups/Makefile 479390 2018-09-10 11:16:59Z des $

PORTNAME=	Set-NestedGroups
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module for grouped data eg ACL's, city/state/country etc

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
