# Created by: Dirk Froemberg <dirk@FreeBSD.org>
# $FreeBSD: head/german/php_doc/Makefile 353996 2014-05-13 21:13:31Z edwin $

CATEGORIES=	german lang
PKGNAMEPREFIX=
PHP_LANG=	de
MASTERDIR=	${.CURDIR}/../../lang/php_doc

.include "${MASTERDIR}/Makefile"
