# $FreeBSD: head/sysutils/u-boot-nanopi-neo/Makefile 447113 2017-08-02 15:36:30Z linimon $

MAINTAINER=	manu@FreeBSD.org
MASTERDIR=	${.CURDIR}/../u-boot-master

MODEL=		nanopi_neo
BOARD_CONFIG=	nanopi_neo_defconfig
FAMILY=		allwinner

.include "${MASTERDIR}/Makefile"
