# Created by: Wen Heping<wenheping@gmail.com>
# $FreeBSD: head/devel/rubygem-sequel/Makefile 447161 2017-08-02 18:36:25Z sunpoet $

PORTNAME=	sequel
PORTVERSION=	4.49.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Database Toolkit for Ruby

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

PLIST_FILES=	bin/sequel

.include <bsd.port.mk>
