# Created by: Frederic Culot <culot@FreeBSD.org>
# $FreeBSD: head/devel/p5-Future/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	Future
PORTVERSION=	0.33
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:PEVANS
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Build objects representing outstanding operations

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-Fatal>0:devel/p5-Test-Fatal \
		p5-Test-Identity>0:devel/p5-Test-Identity \
		p5-Test-Refcount>0:devel/p5-Test-Refcount

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
