# Created by: stas
# $FreeBSD: head/www/xpi-vimperator/Makefile 409749 2016-02-28 15:51:41Z rakuco $

PORTNAME=	vimperator
PORTVERSION=	3.8.3
DISTVERSIONSUFFIX=	-fx
CATEGORIES=	www

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Vim look and feel for Firefox

LICENSE=MIT
LICENSE_FILE=${WRKSRC}/License.txt

XPI_ID=		vimperator@mozdev.org
XPI_NUM=	4891

.include "${.CURDIR}/../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
