# $FreeBSD: head/www/py-django-bulk-update/Makefile 448350 2017-08-19 20:26:44Z rene $

PORTNAME=	django-bulk-update
PORTVERSION=	2.2.0
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	rene@FreeBSD.org
COMMENT=	Bulk update using a single query over Django ORM

LICENSE=	MIT

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}django110>0:www/py-django110

NO_ARCH=	yes
USES=		python:2.7-3.4
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
