# Created by: Carlo Strub <cs@FreeBSD.org>
# $FreeBSD: head/www/py-django-otp/Makefile 468732 2018-04-30 18:26:25Z cs $

PORTNAME=	django-otp
PORTVERSION=	0.4.3
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	cs@FreeBSD.org
COMMENT=	Adding two-factor authentication to Django

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
