# Created by: Carlo Strub <cs@FreeBSD.org>
# $FreeBSD: head/www/py-django-otp/Makefile 437227 2017-03-29 19:55:22Z cs $

PORTNAME=	django-otp
PORTVERSION=	0.3.11
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	cs@FreeBSD.org
COMMENT=	Adding two-factor authentication to Django

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
