# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/devel/php70-readline/Makefile 444463 2017-06-27 13:46:53Z sunpoet $

PORTREVISION=	1
CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php70

PKGNAMESUFFIX=	-readline

.include "${MASTERDIR}/Makefile"
