# Created by: Joe Horn <joehorn@gmail.com>
# $FreeBSD: head/www/pecl-twig/Makefile 470132 2018-05-16 17:10:17Z joneum $

PORTNAME=	twig
PORTVERSION=	1.29.0
CATEGORIES=	www
MASTER_SITES=	http://pear.twig-project.org/get/
PKGNAMEPREFIX=	pecl-
DISTNAME=	CTwig-${PORTVERSION}

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Twig C extension to improve performance of the Twig template language

LICENSE=	BSD3CLAUSE

USES=		php:ext tar:tgz
IGNORE_WITH_PHP=	70 71 72

.include <bsd.port.mk>
