# $FreeBSD: head/sysutils/py-filelock/Makefile 453338 2017-11-02 06:09:42Z yuri $

PORTNAME=	filelock
PORTVERSION=	2.0.12
CATEGORIES=	sysutils python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	yuri@FreeBSD.org
COMMENT=	Platform independent file lock

LICENSE=	PD
LICENSE_FILE=	${WRKSRC}/LICENSE.rst

USES=		python
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
