# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/math/R-cran-sm/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	sm
DISTVERSION=	2.2-5.6
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Smoothing methods for nonparametric regression and density estimation

BROKEN_amd64=	Does not build

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
