# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/math/R-cran-sm/Makefile 452060 2017-10-14 12:25:57Z wen $

PORTNAME=	sm
DISTVERSION=	2.2-5.4
PORTREVISION=	2
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Smoothing methods for nonparametric regression and density estimation

BROKEN_amd64=	Does not build

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
