# $FreeBSD: head/mail/p5-Email-MIME-RFC2047/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Email-MIME-RFC2047
PORTVERSION=	0.97
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	hvo.pm@xs4all.nl
COMMENT=	Correct handling of non-ASCII MIME headers

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
