# Created by: Marc Fournier <scrappy@FreeBSD.org>
# $FreeBSD: head/converters/p5-Convert-ASN1/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Convert-ASN1
PORTVERSION=	0.27
PORTREVISION=	2
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module to encode and decode ASN.1 data structures

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
