# Created by: Thierry Thomas (<thierry@pompo.net>)
# $FreeBSD: head/mail/pecl-mailparse/Makefile 440442 2017-05-08 17:21:49Z dbaio $

PORTNAME=	mailparse
PORTVERSION=	3.0.2
CATEGORIES=	mail www

MAINTAINER=	dbaio@FreeBSD.org
COMMENT=	PECL extension to create and decode MIME messages

LICENSE=	PHP301
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		php:pecl
USE_PHP=	mbstring:build
IGNORE_WITH_PHP=	56

.include <bsd.port.mk>
