# $FreeBSD: head/devel/py-itypes/Makefile 465632 2018-03-26 19:42:16Z yuri $

PORTNAME=	itypes
DISTVERSION=	1.1.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	freebsd_ports@k-worx.org
COMMENT=	Simple immutable types for Python

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
