# Created by: Chris St Denis <chris@smartt.com>
# $FreeBSD: head/devel/pear-HTML_QuickForm_Renderer_Tableless/Makefile 463917 2018-03-08 19:48:41Z mat $

PORTNAME=	HTML_QuickForm_Renderer_Tableless
PORTVERSION=	0.6.1
CATEGORIES=	devel www pear

MAINTAINER=	chris@smartt.com
COMMENT=	Implementation of Tableless Renderer for HTML_QuickForm

BUILD_DEPENDS=	${PEARDIR}/HTML/QuickForm.php:devel/pear-HTML_QuickForm@${PHP_FLAVOR}
RUN_DEPENDS=	${PEARDIR}/HTML/QuickForm.php:devel/pear-HTML_QuickForm@${PHP_FLAVOR}

USES=		pear

.include <bsd.port.mk>
