# Created by: Muhammad Moinur Rahman <bofh@FreeBSD.org>
# $FreeBSD: head/textproc/py3-chardet/Makefile 442754 2017-06-06 09:56:50Z koobs $

MASTERDIR=	${.CURDIR}/../py-chardet

BUILD_DEPENDS=  ${PYTHON_PKGNAMEPREFIX}pytest-runner>0:devel/py3-pytest-runner

USES=		python:3.3+

.include "${MASTERDIR}/Makefile"
