# $FreeBSD: head/x11-fonts/xfsinfo/Makefile 494069 2019-02-27 16:41:18Z zeising $

PORTNAME=	xfsinfo
PORTVERSION=	1.0.6
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X font server information utility

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

XORG_CAT=	app
USE_XORG=	x11 libfs

PLIST_FILES=	bin/xfsinfo man/man1/xfsinfo.1.gz

.include <bsd.port.mk>
