# $FreeBSD: head/net/hs-socks/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	socks
PORTVERSION=	0.5.5
PORTREVISION=	2
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Socks proxy (version 5) implementation

LICENSE=	BSD3CLAUSE

USE_CABAL=	cereal>=0.3.1 network>=2.3

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
