# $FreeBSD: head/net/hs-socks/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	socks
PORTVERSION=	0.5.5
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Socks proxy (version 5) implementation

LICENSE=	BSD3CLAUSE

USE_CABAL=	cereal>=0.3.1 network>=2.3

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
