# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/www/p5-Any-Template/Makefile 412351 2016-04-01 14:33:55Z mat $

PORTNAME=	Any-Template
PORTVERSION=	1.015
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Provide a consistent interface to a wide array of templating languages

BUILD_DEPENDS=	p5-Log-Trace>0:devel/p5-Log-Trace
RUN_DEPENDS=	p5-Log-Trace>0:devel/p5-Log-Trace
TEST_DEPENDS=	p5-Test-Assertions>0:devel/p5-Test-Assertions

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
