# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: head/devel/rubygem-holidays/Makefile 482073 2018-10-14 16:30:40Z sunpoet $

PORTNAME=	holidays
PORTVERSION=	6.6.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Collection of Ruby methods to deal with statutory and other holidays

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem shebangfix
USE_RUBY=	yes

NO_ARCH=	yes

SHEBANG_FILES=	bin/setup

.include <bsd.port.mk>
