# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: head/devel/rubygem-holidays/Makefile 451672 2017-10-10 11:17:08Z sunpoet $

PORTNAME=	holidays
PORTVERSION=	6.2.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Collection of Ruby methods to deal with statutory and other holidays

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
