# $FreeBSD: head/net/rubygem-network_interface/Makefile 449186 2017-09-03 09:14:32Z antoine $

PORTNAME=	network_interface
PORTVERSION=	0.0.2
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Get network interface information from Ruby

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem
USE_RUBY=	yes

PLIST_FILES=	bin/list_interfaces.rb

.include <bsd.port.mk>
