# $FreeBSD: head/devel/hs-map-syntax/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	map-syntax
PORTVERSION=	0.3
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Syntax sugar for defining maps

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl>=2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
