# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-ghc-paths/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	ghc-paths
PORTVERSION=	0.1.0.9
PORTREVISION=	11
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Knowledge of GHC's installation directories

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
