# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-ghc-paths/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	ghc-paths
PORTVERSION=	0.1.0.9
PORTREVISION=	12
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Knowledge of GHC's installation directories

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
