# Created by: Babak Farrokhi <farrokhi@FreeBSD.org>
# $FreeBSD: head/net/py-cymruwhois/Makefile 439955 2017-05-02 15:39:31Z farrokhi $

PORTNAME=	cymruwhois
PORTVERSION=	1.6
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	farrokhi@FreeBSD.org
COMMENT=	Python client for the whois.cymru.com service

LICENSE=	MIT

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
