# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: head/textproc/rubygem-redcarpet/Makefile 429860 2016-12-29 03:18:07Z swills $

PORTNAME=	redcarpet
PORTVERSION=	3.4.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Fast, safe and extensible Markdown to (X)HTML parser

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

USE_RUBY=	yes
USES=		gem

PLIST_FILES=	bin/redcarpet

.include <bsd.port.mk>
