# $FreeBSD: head/mail/php73-imap/Makefile 485597 2018-11-22 11:53:53Z joneum $

CATEGORIES=	mail
PORTREVISION=	1

MASTERDIR=	${.CURDIR}/../../lang/php73

PKGNAMESUFFIX=	-imap

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
