# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-withr/Makefile 449576 2017-09-10 14:45:29Z tota $

PORTNAME=	withr
PORTVERSION=	2.0.0
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Run Code 'With' Temporarily Modified Global State

LICENSE=	GPLv2+

USES=		cran:auto-plist

.include <bsd.port.mk>
