# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-withr/Makefile 464336 2018-03-13 02:18:12Z tota $

PORTNAME=	withr
PORTVERSION=	2.1.1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Run Code 'With' Temporarily Modified Global State

LICENSE=	GPLv2+

USES=		cran:auto-plist

.include <bsd.port.mk>
