# $FreeBSD: head/net/pecl-zmq/Makefile 481624 2018-10-09 11:51:18Z garga $

PORTNAME=	zmq
PORTVERSION=	1.1.3
PORTREVISION=	3
CATEGORIES=	net pear

MAINTAINER=	garga@FreeBSD.org
COMMENT=	PHP bindings for ZeroMQ

LICENSE=	BSD3CLAUSE

LIB_DEPENDS=	libzmq.so:net/libzmq4

USES=		php:pecl pkgconfig

.include <bsd.port.mk>
