# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: head/audio/gstreamer-plugins-nas/Makefile 428152 2016-12-08 19:52:19Z tijl $
#   $MCom: ports/audio/gstreamer-plugins-nas/Makefile,v 1.5 2008/03/19 14:05:31 ahze Exp $

PORTREVISION=	2
CATEGORIES=	audio

COMMENT=	GStreamer NAS (Network Audio System) plugin

GST_PLUGIN=	nas

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
