# $FreeBSD: head/converters/php72-mbstring/Makefile 454302 2017-11-16 10:48:48Z tz $

CATEGORIES=	converters

MASTERDIR=	${.CURDIR}/../../lang/php72

PKGNAMESUFFIX=	-mbstring

.include "${MASTERDIR}/Makefile"
