# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pear-channel-pirum/Makefile 441000 2017-05-16 13:37:51Z joneum $

PORTNAME=	pirum
PORTVERSION=	20110921
PORTREVISION=	1
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	pear.pirum-project.org

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.channel.mk"
.include <bsd.port.post.mk>
