# $FreeBSD: head/devel/erlang-unicode_util_compat/Makefile 441974 2017-05-29 08:18:31Z olgeni $

PORTNAME=	unicode_util_compat
PORTVERSION=	0.2.0
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Compatibility library for unicode_util from Erlang R20

LICENSE=	BSD3CLAUSE

USES=		gmake erlang:rebar3
USE_GITHUB=	yes
GH_ACCOUNT=	benoitc

.include <bsd.port.mk>
