# $FreeBSD: head/devel/erlang-unicode_util_compat/Makefile 447617 2017-08-09 10:25:07Z olgeni $

PORTNAME=	unicode_util_compat
PORTVERSION=	0.3.1
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Compatibility library for unicode_util from Erlang R20

LICENSE=	BSD3CLAUSE

USES=		gmake erlang:rebar3
USE_GITHUB=	yes
GH_ACCOUNT=	benoitc

.include <bsd.port.mk>
