# $FreeBSD: head/textproc/rubygem-gemoji/Makefile 433221 2017-02-03 11:31:26Z antoine $

PORTNAME=	gemoji
PORTVERSION=	3.0.0
PORTREVISION=	1
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Emoji assets

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem
PLIST_FILES=	bin/gemoji

.include <bsd.port.mk>
