# Created by: Dmitry Karasik (<dk@catpipe.net>)
# $FreeBSD: head/devel/pear-HTML_QuickForm_Controller/Makefile 463917 2018-03-08 19:48:41Z mat $

PORTNAME=	HTML_QuickForm_Controller
PORTVERSION=	1.0.10
CATEGORIES=	devel www pear

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	The add-on to HTML_QuickForm that allows building of multipage forms

LICENSE=	PHP301

BUILD_DEPENDS=	${PEARDIR}/HTML/QuickForm.php:devel/pear-HTML_QuickForm@${PHP_FLAVOR}
RUN_DEPENDS=	${PEARDIR}/HTML/QuickForm.php:devel/pear-HTML_QuickForm@${PHP_FLAVOR}

USES=		pear

.include <bsd.port.mk>
