# $FreeBSD: head/databases/postgresql96-pgtcl/Makefile 421360 2016-09-05 11:15:29Z girgen $

PKGNAMESUFFIX=	-postgresql96

CONFLICTS=	pgtcl-[0-9]* pgtcl-postgresql9[01234]-[0-9]*

PGTCL_SLAVE=	9.6
MASTERDIR=	${.CURDIR}/../pgtcl

.include "${MASTERDIR}/Makefile"
