# $FreeBSD: head/devel/hs-constraints/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	constraints
PORTVERSION=	0.10
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Constraint manipulation

LICENSE=	BSD3CLAUSE

USE_CABAL=	hashable mtl semigroups transformers-compat

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
