# $FreeBSD: head/devel/hs-constraints/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	constraints
PORTVERSION=	0.10.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Constraint manipulation

LICENSE=	BSD3CLAUSE

USE_CABAL=	hashable mtl semigroups transformers-compat

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
