# $FreeBSD: head/devel/hs-kqueue/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	kqueue
PORTVERSION=	0.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Binding to the kqueue event library

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl>=1.1
USE_C2HS=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
