# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/devel/py-setuptools-git/Makefile 434429 2017-02-20 03:04:23Z vanilla $

PORTNAME=	setuptools-git
PORTVERSION=	1.2
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Setuptools plugin for git

LICENSE=	BSD4CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
