# Created by: iblis <iblis@hs.ntnu.edu.tw>
# $FreeBSD: head/devel/unittest-cpp/Makefile 431472 2017-01-14 15:39:16Z vanilla $

PORTNAME=	unittest-cpp
PORTVERSION=	2.0.0
DISTVERSIONPREFIX=	v
CATEGORIES=	devel

MAINTAINER=	iblis@hs.ntnu.edu.tw
COMMENT=	Lightweight unit testing framework for C++

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes

USES=		cmake

.include <bsd.port.mk>
