# $FreeBSD: head/mail/php71-imap/Makefile 475229 2018-07-24 08:44:32Z tz $

CATEGORIES=	mail

MASTERDIR=	${.CURDIR}/../../lang/php71

PKGNAMESUFFIX=	-imap

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
