# $FreeBSD: head/devel/hs-data-default-class/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	data-default-class
PORTVERSION=	0.1.2.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Class for types with a default value

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
