# $FreeBSD: head/www/rubygem-rails-settings-cached/Makefile 447022 2017-08-01 15:51:54Z jrm $

PORTNAME=	rails-settings-cached
PORTVERSION=	0.6.6
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	jrm@FreeBSD.org
COMMENT=	Rails settings plugin for easily managing key-value pairs table

LICENSE=	MIT

RUN_DEPENDS=	rubygem-rails4>=4.2.0:www/rubygem-rails4

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
