# Created by: David O'Brien (obrien@NUXI.com)
# $FreeBSD: head/editors/vim-console/Makefile 458784 2018-01-11 20:29:52Z adamw $

PKGNAMESUFFIX=	-console

COMMENT=	Improved version of the vi editor (console only)

CONFLICTS_INSTALL=	vim vim-tiny

CONSOLE=	yes
MASTERDIR=	${.CURDIR}/../vim

.include "${MASTERDIR}/Makefile"
