# Created by: Alex Miller (<asm@asm.kiev.ua>)
# $FreeBSD: head/www/pear-HTTP/Makefile 443340 2017-06-11 07:46:30Z sunpoet $

PORTNAME=	HTTP
PORTVERSION=	1.4.1
CATEGORIES=	www devel pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR miscellaneous HTTP utilities

USES=		pear

.include <bsd.port.mk>
