# $FreeBSD: head/devel/hs-colour/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	colour
PORTVERSION=	2.3.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	This package provides a data type for colours and transparency

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
