# $FreeBSD: head/devel/hs-colour/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	colour
PORTVERSION=	2.3.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	This package provides a data type for colours and transparency

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
