# Created by: Adam Weinberger <adamw@FreeBSD.org>
# $FreeBSD: head/devel/p5-Brannigan/Makefile 433588 2017-02-07 20:31:36Z sunpoet $

PORTNAME=	Brannigan
PORTVERSION=	1.1.00001
CATEGORIES=	devel www perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:IDOPEREL
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:R}${PORTVERSION:E}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Comprehensive, flexible system for validating and parsing input

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
