# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/misc/teseq/Makefile 484628 2018-11-10 18:12:57Z bapt $

PORTNAME=	teseq
PORTVERSION=	1.1.1
PORTREVISION=	1
CATEGORIES=	misc
MASTER_SITES=	GNU

MAINTAINER=	danilo@FreeBSD.org
COMMENT=	Terminal control sequence analyzer

GNU_CONFIGURE=	yes
USES=	gmake perl5

INFO=	teseq

PLIST_FILES=	bin/reseq bin/teseq \
		man/man1/reseq.1.gz \
		man/man1/teseq.1.gz

.include <bsd.port.mk>
