# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/biology/python-nexus/Makefile 466142 2018-04-01 11:52:08Z wen $

PORTNAME=	python-nexus
PORTVERSION=	1.61
CATEGORIES=	biology python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Generic nexus file format reader for python

LICENSE=	BSD3CLAUSE
#LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python shebangfix
SHEBANG_FILES=	nexus/bin/*.py
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
