# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/biology/python-nexus/Makefile 480370 2018-09-22 08:54:58Z wen $

PORTNAME=	python-nexus
PORTVERSION=	1.63
CATEGORIES=	biology python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Generic nexus file format reader for python

LICENSE=	BSD3CLAUSE
#LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python shebangfix
SHEBANG_FILES=	nexus/bin/*.py
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
