# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-TypeCompose/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	TypeCompose
PORTVERSION=	0.9.12
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Type composition classes and instances

LICENSE=	BSD3CLAUSE

USE_CABAL=	base-orphans

IGNORE=		Doesn't build with recent GHC version

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
