# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-TypeCompose/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	TypeCompose
PORTVERSION=	0.9.12
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Type composition classes and instances

LICENSE=	BSD3CLAUSE

USE_CABAL=	base-orphans

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
