# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-TypeCompose/Makefile 480361 2018-09-22 08:13:53Z antoine $

PORTNAME=	TypeCompose
PORTVERSION=	0.9.12
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Type composition classes and instances

LICENSE=	BSD3CLAUSE

USE_CABAL=	base-orphans

IGNORE=		Doesn't build with recent GHC version
DEPRECATED=	Doesn't build with recent GHC version
EXPIRATION_DATE=	2018-10-22

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
