# Created by: tcberner
# $FreeBSD: head/x11-themes/kf5-breeze-icons/Makefile 426118 2016-11-14 16:12:56Z tcberner $

PORTNAME=	breeze-icons
PORTVERSION=	${KDE_FRAMEWORKS_VERSION}
CATEGORIES=	x11-themes kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	The Breeze icon theme for KDE

USES=		cmake:outsource kde:5 tar:xz
USE_KDE=	ecm
USE_QT5=	buildtools_build core qmake_build testlib

NO_ARCH=	yes

.include <bsd.port.mk>
