# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/security/rubygem-bcrypt/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	bcrypt
PORTVERSION=	3.1.11
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	OpenBSD bcrypt password hashing algorithm

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
