# Created by: Jov <amutu@amutu.com>
# $FreeBSD: head/devel/py-backports.weakref/Makefile 445590 2017-07-12 15:55:52Z lwhsu $

PORTNAME=	backports.weakref
DISTVERSION=	1.0rc1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	amutu@amutu.com
COMMENT=	Backport of the weakref module from Python 3.4

LICENSE=	PSFL

BUILD_DEPENDS=	${PYTHON_PKGNAMEPREFIX}setuptools_scm>0:devel/py-setuptools_scm

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
