# $FreeBSD: head/lang/fpc-rtl-extra/Makefile 447304 2017-08-03 23:40:28Z acm $

CATEGORIES=	lang
PKGNAMESUFFIX=	-rtl-extra

COMMENT=	Free Pascal rtl-extra unit

USE_FPC=	yes

MASTERDIR=	${.CURDIR}/../../lang/fpc
WRKUNITDIR=	${FPCSRCDIR}/packages/${PKGNAMESUFFIX:S/-//}
EXTRACTUNITDIR=	${WRKUNITDIR}

.include "${MASTERDIR}/Makefile"
