# $FreeBSD: head/lang/fpc-rtl-extra/Makefile 434894 2017-02-26 17:38:04Z acm $

CATEGORIES=	lang
PKGNAMESUFFIX=	-rtl-extra

MAINTAINER=	freebsd-fpc@FreeBSD.org
COMMENT=	Free Pascal rtl-extra unit

USE_FPC=	yes

MASTERDIR=	${.CURDIR}/../../lang/fpc
WRKUNITDIR=	${FPCSRCDIR}/packages/${PKGNAMESUFFIX:S/-//}
EXTRACTUNITDIR=	${WRKUNITDIR}

.include "${MASTERDIR}/Makefile"
