# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-graf/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	graf
PORTVERSION=	0.0.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Simple git log analyzer gem

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem
PLIST_FILES=	bin/graf

.include <bsd.port.mk>
