# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/textproc/R-cran-XML/Makefile 477712 2018-08-21 09:24:48Z tota $

PORTNAME=	XML
DISTVERSION=	3.98-1.16
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Tools for parsing and generating XML

LICENSE=	BSD2CLAUSE

USES=	cran:auto-plist,compiles
USE_GNOME=	libxml2

.include <bsd.port.mk>
