# $FreeBSD: head/net/rubygem-connection_pool/Makefile 470934 2018-05-26 17:49:39Z sunpoet $

PORTNAME=	connection_pool
PORTVERSION=	2.2.2
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Generic connection pool for Ruby

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
