# Created by: chinsan
# $FreeBSD: head/devel/pecl-vld/Makefile 489349 2019-01-05 15:47:56Z rene $

PORTNAME=	vld
PORTVERSION=	0.15.0
CATEGORIES=	devel pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Dump the internal representation of PHP scripts

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		php:pecl

CONFIGURE_ARGS=	--enable-vld

.include <bsd.port.mk>
