# Created by: UMENO Takashi <umeno@rr.iij4u.or.jp>
# $FreeBSD: head/shells/klish/Makefile 469037 2018-05-04 17:33:47Z krion $

PORTNAME=	klish
PORTVERSION=	2.1.4
CATEGORIES=	shells
MASTER_SITES=	http://libcode.org/attachments/download/70/

MAINTAINER=	umeno@rr.iij4u.or.jp
COMMENT=	Klish - Kommand Line Interface Shell

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENCE

USES=		libtool tar:xz
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
