# Created by: will
# $FreeBSD: head/archivers/p5-Mac-Macbinary/Makefile 451681 2017-10-10 11:20:11Z sunpoet $

PORTNAME=	Mac-Macbinary
PORTVERSION=	0.06
PORTREVISION=	1
CATEGORIES=	archivers perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module that can extract info from Macbinary files

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
