# $FreeBSD: head/devel/hs-EdisonCore/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	EdisonCore
PORTVERSION=	1.3.1.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A library of efficent, purely-functional data structures (Core Implementations)

USE_CABAL=	EdisonAPI mtl QuickCheck

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
