# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/graphics/R-cran-dichromat/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	dichromat
DISTVERSION=	2.0-0
PORTREVISION=	7
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Color schemes for dichromats

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
