# Created by: Florian Smeets <flo@smeets.im>
# $FreeBSD: head/sysutils/pecl-proctitle/Makefile 438175 2017-04-10 15:08:47Z mat $

PORTNAME=	proctitle
PORTVERSION=	0.1.2
PORTREVISION=	1
CATEGORIES=	sysutils pear

MAINTAINER=	flo@FreeBSD.org
COMMENT=	PECL extension that allows changing the current process' name

USES=		php:pecl

.include <bsd.port.mk>
