# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: head/sysutils/rubygem-sys-cpu/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	sys-cpu
PORTVERSION=	0.7.2
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Interface for getting information about the CPU

LICENSE=	ART20

RUN_DEPENDS=	rubygem-ffi>=1.0.0:devel/rubygem-ffi

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
