# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-sprockets-helpers/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	sprockets-helpers
PORTVERSION=	1.2.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Asset path helpers for Sprockets 2.x applications

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-sprockets3>=2.2:devel/rubygem-sprockets3

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
