# Created by: Veniamin Gvozdikov <vg@FreeBSD.org>
# $FreeBSD: head/net/rubygem-iproto/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	iproto
PORTVERSION=	0.3.17
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	vg@FreeBSD.org
COMMENT=	Ruby implementation of Mail.Ru iproto protocol

RUN_DEPENDS=	rubygem-bin_utils>=0.0.3:devel/rubygem-bin_utils

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
