# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: head/www/google-sitemapgen/Makefile 432275 2017-01-23 18:51:29Z sunpoet $

PORTNAME=	google-sitemapgen
PORTVERSION=	1.5
CATEGORIES=	www devel
MASTER_SITES=	https://fossies.org/linux/www/old/
DISTNAME=	sitemap_gen_${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Script to analyze web server and generate Google Sitemap files

NO_ARCH=	yes
NO_WRKSUBDIR=	yes
USES=		python:2
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
