# Created by: Dmitry Marakasov <amdmi3@FreeBSD.org>
# $FreeBSD: head/devel/cppcheck-gui/Makefile 492703 2019-02-11 17:37:53Z amdmi3 $

PORTREVISION=	0

MASTERDIR=	${.CURDIR}/../cppcheck

GUI_ONLY=	yes

.include "${MASTERDIR}/Makefile"
