# $FreeBSD: head/x11-themes/kf5-kemoticons/Makefile 492794 2019-02-12 17:48:25Z tcberner $

PORTNAME=	kemoticons
DISTVERSION=	${KDE_FRAMEWORKS_VERSION}
CATEGORIES=	x11-themes kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KF5 library to convert emoticons

USES=		cmake compiler:c++11-lib kde:5 qt:5 tar:xz
USE_KDE=	archive config coreaddons ecm service
USE_QT=		buildtools_build core gui qmake_build widgets xml

.include <bsd.port.mk>
