# Created by: buganini@gmail.com
# $FreeBSD: head/mail/pecl-pop3/Makefile 456296 2017-12-14 13:57:28Z tz $

PORTNAME=	pop3
PORTVERSION=	1.0.2
PORTREVISION=	1
CATEGORIES=	mail

MAINTAINER=	buganini@gmail.com
COMMENT=	POP3 Client Library for PHP

USES=		php:pecl
IGNORE_WITH_PHP=	70 71 72

.include <bsd.port.mk>
