# Created by: petef@FreeBSD.org
# $FreeBSD: head/devel/p5-Curses-Widgets/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	Curses-Widgets
PORTVERSION=	1.997
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	CursesWidgets-${PORTVERSION}

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Curses-based widgets and functions

LICENSE=	GPLv2

BUILD_DEPENDS=	p5-Curses>=0:devel/p5-Curses
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
