# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-cri/Makefile 478747 2018-09-01 22:52:09Z sunpoet $

PORTNAME=	cri
PORTVERSION=	2.15.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Allows building easy-to-use commandline interfaces

LICENSE=	MIT

RUN_DEPENDS=	rubygem-colored>=1.2:textproc/rubygem-colored

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
