# Created by: John Chen <johnpupu@gmail.com>
# $FreeBSD: head/devel/pecl-ev/Makefile 485511 2018-11-21 12:41:57Z joneum $

PORTNAME=	ev
PORTVERSION=	1.0.4
CATEGORIES=	devel

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Libev extension for PHP

LICENSE=	PHP301
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		php:pecl

.include <bsd.port.mk>
