# $FreeBSD: head/devel/hs-PSQueue/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	PSQueue
PORTVERSION=	1.1
PORTREVISION=	16
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Priority Search Queue

LICENSE=	BSD3CLAUSE

IGNORE=		Doesn't build with recent GHC version

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
