# $FreeBSD: head/devel/hs-PSQueue/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	PSQueue
PORTVERSION=	1.1
PORTREVISION=	15
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Priority Search Queue

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
