# $FreeBSD: head/devel/hs-code-page/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	code-page
PORTVERSION=	0.1.3
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A cross-platform module that exports functions which adjust code pages on Windows

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
