# $FreeBSD: head/devel/hs-code-page/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	code-page
PORTVERSION=	0.1.3
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A cross-platform module that exports functions which adjust code pages on Windows

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
