# Created by: Pawel Worach
# $FreeBSD: head/x11-fonts/font-isas-misc/Makefile 495395 2019-03-11 21:25:57Z zeising $

PORTNAME=	font-isas-misc
PORTVERSION=	1.0.3
PORTREVISION=	4
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org miscellaneous ISAS fonts

XORG_CAT=	font

.include <bsd.port.mk>
