# Created by: Joseph Benden <joe@thrallingpenguin.com>
# $FreeBSD: head/www/rubygem-httpi/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	httpi
PORTVERSION=	0.9.7
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	joe@thrallingpenguin.com
COMMENT=	Library for common HTTP client API

LICENSE=	MIT

RUN_DEPENDS=	rubygem-rack>=1.4.5:www/rubygem-rack

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

PORTSCOUT=	limit:^0\.9\.

.include <bsd.port.mk>
