# Created by: Gabor Kovesdan
# $FreeBSD: head/security/p5-Digest-JHash/Makefile 433453 2017-02-05 20:59:27Z ashish $

PORTNAME=	Digest-JHash
PORTVERSION=	0.10
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Perl extension for JHash hash algorithm

LICENSE=	ART20

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
