# Created by: Piotr Rybicki <meritus@innervision.pl>
# $FreeBSD: head/math/pear-Math_BigInteger/Makefile 417904 2016-07-01 22:05:48Z mm $

PORTNAME=	Math_BigInteger
PORTVERSION=	1.0.3
CATEGORIES=	math pear

MAINTAINER=	meritus@innervision.pl
COMMENT=	Pure-PHP arbitrary precision integer arithmetic library

USE_PHP=	pcre
USES=	pear

.include <bsd.port.mk>
