# Created by: arved
# $FreeBSD: head/net-mgmt/p5-SNMP-Info/Makefile 431619 2017-01-16 09:07:50Z jadawin $

PORTNAME=	SNMP-Info
PORTVERSION=	3.34
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jadawin@FreeBSD.org
COMMENT=	Perl5 module for gathering information from network devices

LICENSE=	BSD3CLAUSE

LIB_DEPENDS=	libnetsnmp.so:net-mgmt/net-snmp

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
