# Created by: arved
# $FreeBSD: head/net-mgmt/p5-SNMP-Info/Makefile 461638 2018-02-12 19:28:33Z riggs $

PORTNAME=	SNMP-Info
PORTVERSION=	3.39
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jadawin@FreeBSD.org
COMMENT=	Perl5 module for gathering information from network devices

LICENSE=	BSD3CLAUSE

LIB_DEPENDS=	libnetsnmp.so:net-mgmt/net-snmp

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
