# Created by: arved
# $FreeBSD: head/net-mgmt/p5-SNMP-Info/Makefile 451333 2017-10-05 18:54:26Z jadawin $

PORTNAME=	SNMP-Info
PORTVERSION=	3.37
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jadawin@FreeBSD.org
COMMENT=	Perl5 module for gathering information from network devices

LICENSE=	BSD3CLAUSE

LIB_DEPENDS=	libnetsnmp.so:net-mgmt/net-snmp

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
