# $FreeBSD: head/x11-toolkits/gstreamer1-plugins-gtk/Makefile 483887 2018-11-03 11:58:10Z tijl $

PORTREVISION=	0
CATEGORIES=	x11-toolkits
GST_PLUGIN_SUFFIX=	-gtk

COMMENT=	GStreamer gtksink plugin

GST_PLUGIN=	gtk3
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
