# $FreeBSD: head/www/sogo2-activesync/Makefile 492056 2019-02-03 15:37:58Z theraven $

PORTREVISION=	4
PKGNAMESUFFIX=		-activesync

MAINTAINER=		acm@FreeBSD.org

CONFLICTS=		sogo[2-4]-[0-9]* sogo[3-4]-activesync-[0-9]*

OPTIONS_SLAVE=		ACTIVESYNC

MASTERDIR=		${.CURDIR}/../sogo2

.include "${MASTERDIR}/Makefile"
