# Created by: chinsan
# $FreeBSD: head/devel/p5-List-Rotation-Cycle/Makefile 480092 2018-09-19 09:08:25Z amdmi3 $

PORTNAME=	List-Rotation-Cycle
PORTVERSION=	1.009
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN LOCAL/chinsan/CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Cycle through a list of values

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

PORTSCOUT=	limitw:1,even

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
