# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-MemoTrie/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	MemoTrie
PORTVERSION=	0.6.9
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Trie-based memo functions

LICENSE=	BSD3CLAUSE

USE_CABAL=	newtype-generics void

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
