# Created by: Greg Larkin <glarkin@FreeBSD.org>
# $FreeBSD: head/math/pecl-bitset2/Makefile 486751 2018-12-06 11:22:12Z rene $

PORTNAME=	bitset
PORTVERSION=	2.0.4
CATEGORIES=	math

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	PECL extension for manipulating bitsets

DEPRECATED=	Works only with EOL php 5.6
EXPIRATION_DATE=	2018-12-30

LICENSE=	PHP301
LICENSE_FILE=	${WRKSRC}/LICENSE

PORTSCOUT=	limit:^2\.

IGNORE_WITH_PHP=71 72 73
USES=		php:pecl

.include <bsd.port.mk>
