# $FreeBSD: head/editors/calligra-l10n-fi/Makefile 439367 2017-04-25 08:20:30Z riggs $

PORTNAME=	calligra-l10n
PORTVERSION=	${CALLIGRA_VERSION}
PORTREVISION=	2
CATEGORIES=	editors kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Finnish messages and documentation for Calligra

CALLIGRA_L10N=	fi

.include "${.CURDIR:H:H}/editors/calligra-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
