# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/net/pear-Net_Ping/Makefile 443289 2017-06-11 07:42:10Z sunpoet $

PORTNAME=	Net_Ping
PORTVERSION=	2.4.5
CATEGORIES=	net pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR class to execute ping

USES=		pear

.include <bsd.port.mk>
