# $FreeBSD: head/security/hs-crypto-random-api/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	crypto-random-api
PORTVERSION=	0.2.0
PORTREVISION=	13
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple random generators API for cryptography related code

LICENSE=	BSD3CLAUSE

USE_CABAL=	entropy

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
