# $FreeBSD: head/archivers/php71-phar/Makefile 455586 2017-12-05 15:56:04Z tz $

CATEGORIES=	archivers

PORTREVISION=	2
MASTERDIR=	${.CURDIR}/../../lang/php71

PKGNAMESUFFIX=	-phar

.include "${MASTERDIR}/Makefile"
