# Created by: Pawel Worach
# $FreeBSD: head/x11-fonts/font-adobe-100dpi/Makefile 495395 2019-03-11 21:25:57Z zeising $

PORTNAME=	font-adobe-100dpi
PORTVERSION=	1.0.3
PORTREVISION=	4
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Adobe 100dpi font

XORG_CAT=	font
USE_XORG=	fontutil

.include <bsd.port.mk>
