# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: head/mail/rubygem-rmail/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	rmail
PORTVERSION=	1.1.2
CATEGORIES=	mail rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Lightweight mail library

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
