# Created by: Kozlov Sergey <kozlov.sergey.404@gmail.com>
# $FreeBSD: head/print/py-preppy/Makefile 480460 2018-09-23 08:13:44Z skozlov $

PORTNAME=	preppy
PORTVERSION=	2.3.4
CATEGORIES=	print python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	skozlov@FreeBSD.org
COMMENT=	ReportLab's templating system

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
