# $FreeBSD: head/lang/fpc-rtl-console/Makefile 447304 2017-08-03 23:40:28Z acm $

CATEGORIES=	lang
PKGNAMESUFFIX=	-rtl-console

COMMENT=	Free Pascal console abstraction unit (RTL)

USE_FPC=	rtl-extra

MASTERDIR=	${.CURDIR}/../../lang/fpc
WRKUNITDIR=	${FPCSRCDIR}/packages/${PKGNAMESUFFIX:S/-//}
EXTRACTUNITDIR=	${WRKUNITDIR}

.include "${MASTERDIR}/Makefile"
