# Created by: John Marino <marino@FreeBSD.org>
# $FreeBSD: head/devel/libspark2012/Makefile 439129 2017-04-21 20:25:00Z rene $

PORTNAME=	libspark2012
PORTVERSION=	2012
PORTREVISION=	2
CATEGORIES=	devel
MASTER_SITES=	http://downloads.dragonlace.net/src/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	SPARK 2012 Spark.Ada library

LICENSE=	GPLv3

USES=		ada tar:bzip2

.include <bsd.port.mk>
