# Created by: Andrej Zverev <az@inec.ru>
# $FreeBSD: head/sysutils/mdf2iso/Makefile 405891 2016-01-12 16:20:31Z amdmi3 $

PORTNAME=	mdf2iso
PORTVERSION=	0.3.0
PORTREVISION=	1
CATEGORIES=	sysutils
MASTER_SITES=	http://BSDforge.com/projects/source/sysutils/mdf2iso/

MAINTAINER=	portmaster@BSDforge.com
COMMENT=	Alcohol 120% to ISO converter

LICENSE=	GPLv2+

USES=		tar:xz

WRKSRC=		${WRKDIR}/${PORTNAME}

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/mdf2iso

INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
