# $FreeBSD: head/textproc/py-python-bidi/Makefile 461737 2018-02-13 19:39:51Z yuri $

PORTNAME=	python-bidi
DISTVERSION=	0.4.0
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	yuri@FreeBSD.org
COMMENT=	Pure python implementation of the BiDi layout algorithm

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		python
USE_PYTHON=	distutils autoplist concurrent
NO_ARCH=	yes

.include <bsd.port.mk>
