# Created by: Kyle Evans <kevans@FreeBSD.org>
# $FreeBSD: head/devel/py-chainmap/Makefile 445117 2017-07-06 01:39:08Z ultima $

PORTNAME=	chainmap
PORTVERSION=	1.0.2
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	kevans@FreeBSD.org
COMMENT=	Backport/clone of chainmap for py26, py32, and pypy3

LICENSE=	PSFL

USES=		python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
