# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-fracdiff/Makefile 443845 2017-06-18 18:09:16Z dbn $

PORTNAME=	fracdiff
DISTVERSION=	1.4-2
PORTREVISION=	6
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Fractionally differenced ARIMA aka ARFIMA(p,d,q) models

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
