# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-fracdiff/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	fracdiff
DISTVERSION=	1.4-2
PORTREVISION=	7
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Fractionally differenced ARIMA aka ARFIMA(p,d,q) models

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
