# $FreeBSD: head/devel/geany-plugin-ctags/Makefile 416609 2016-06-09 15:24:55Z madpilot $

PORTNAME=	geany-plugin-ctags
PORTVERSION=	${GEANY_VER}
CATEGORIES=	devel

MAINTAINER=	madpilot@FreeBSD.org
COMMENT=	Geany plugin: ${${GEANY_PLUGIN}_DESC}

RUN_DEPENDS=	exctags:devel/ctags

.include "${.CURDIR}/../geany-plugins/files/Makefile.common"
.include <bsd.port.mk>
