# $FreeBSD: head/devel/go-nuid/Makefile 422810 2016-09-27 08:58:23Z olgeni $

PORTNAME=	nuid
DISTVERSIONPREFIX=	v
DISTVERSION=	1.0.0
CATEGORIES=	devel
PKGNAMEPREFIX=	go-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	NATS unique identifier generator library

LICENSE=	MIT

USES=		go
USE_GITHUB=	yes
GH_ACCOUNT=	nats-io

GO_PKGNAME=	github.com/${GH_ACCOUNT}/${PORTNAME}

.include <bsd.port.mk>
