# $FreeBSD: head/devel/hs-hslua/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	hslua
PORTVERSION=	0.9.5.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Lua language interpreter embedding in Haskell

LICENSE=	MIT

USE_CABAL=	exceptions

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
