# $FreeBSD: head/editors/libreoffice/Makefile.common 441257 2017-05-19 18:42:01Z jkim $

PORTNAME=	libreoffice
PORTVERSION=	5.3.3
CATEGORIES+=	editors

MAINTAINER=	office@FreeBSD.org

LICENSE=	LGPL3+ MPL
LICENSE_COMB=	dual

LOVERSION=	${PORTVERSION}.${RCVER}
RCVER=		2
