# $FreeBSD: head/editors/libreoffice/Makefile.common 484482 2018-11-08 21:44:09Z jkim $

PORTNAME=	libreoffice
PORTVERSION=	6.0.7
CATEGORIES+=	editors

MAINTAINER=	office@FreeBSD.org

LICENSE=	LGPL3+ MPL20
LICENSE_COMB=	dual

LOVERSION=	${PORTVERSION}.${RCVER}
RCVER=		3
