# Created by: William Grzybowski <wg@FreeBSD.org>
# $FreeBSD: head/devel/py-pycparser/Makefile 442431 2017-06-02 18:14:00Z sunpoet $

PORTNAME=	pycparser
PORTVERSION=	2.10
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	C parser in Python

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes
USES?=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
