# $FreeBSD: head/devel/rubygem-http_accept_language/Makefile 447386 2017-08-05 03:25:17Z jrm $

PORTNAME=	http_accept_language
PORTVERSION=	2.1.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Rails plugin to extract Accept-Language HTTP header into array

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
