# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: head/converters/p5-Number-RecordLocator/Makefile 479390 2018-09-10 11:16:59Z des $

PORTNAME=	Number-RecordLocator
PORTVERSION=	0.005
PORTREVISION=	1
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Encodes integers into a short locator string

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
