# $FreeBSD: head/sysutils/gstreamer1-plugins-cdio/Makefile 414276 2016-04-29 15:20:28Z arved $

PORTREVISION=	1
CATEGORIES=	sysutils

COMMENT=	GStreamer compact disc input and control library

GST_PLUGIN=	cdio
DIST=		ugly

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
