# $FreeBSD: head/sysutils/gstreamer1-plugins-cdio/Makefile 466597 2018-04-05 20:13:33Z jhale $

PORTREVISION=	1
CATEGORIES=	sysutils

COMMENT=	GStreamer compact disc input and control library

GST_PLUGIN=	cdio
DIST=		ugly

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
