# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/textproc/rubygem-css_parser/Makefile 492809 2019-02-12 21:03:59Z sunpoet $

PORTNAME=	css_parser
PORTVERSION=	1.7.0
CATEGORIES=	textproc www rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Set of classes for parsing CSS in Ruby

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

RUN_DEPENDS=	rubygem-addressable>=0:www/rubygem-addressable

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
