# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/textproc/rubygem-css_parser/Makefile 439308 2017-04-24 15:17:08Z sunpoet $

PORTNAME=	css_parser
PORTVERSION=	1.5.0
CATEGORIES=	textproc www rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Set of classes for parsing CSS in Ruby

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

RUN_DEPENDS=	rubygem-addressable>=0:www/rubygem-addressable

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
