# $FreeBSD: head/lang/fpc-rtl-unicode/Makefile 466532 2018-04-05 04:52:36Z acm $

CATEGORIES=	lang
PKGNAMESUFFIX=	-rtl-unicode

COMMENT=	Free Pascal compatibility unit with Delphi

USES=		fpc

MASTERDIR=	${.CURDIR}/../../lang/fpc
WRKUNITDIR=	${FPCSRCDIR}/packages/${PKGNAMESUFFIX:S/-//}
EXTRACTUNITDIR=	${WRKUNITDIR}

.include "${MASTERDIR}/Makefile"
