# Created by: Phil Phillips <pphillips@experts-exchange.com>
# $FreeBSD: head/graphics/rubygem-chunky_png/Makefile 485622 2018-11-22 20:48:12Z sunpoet $

PORTNAME=	chunky_png
PORTVERSION=	1.3.11
CATEGORIES=	graphics rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby library to read and write PNG images

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
