# Created by: Emanuel Haupt <ehaupt@FreeBSD.org>
# $FreeBSD: head/dns/py-ldns/Makefile 343142 2014-02-06 19:17:51Z danilo $

MASTERDIR=	${.CURDIR}/../../dns/ldns

BUILD_PYLDNS=yes

PLIST=	${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
