# Created by: Pawel Worach
# $FreeBSD: head/x11-fonts/font-adobe-utopia-75dpi/Makefile 381876 2015-03-21 23:05:19Z bapt $

PORTNAME=	font-adobe-utopia-75dpi
PORTVERSION=	1.0.4
PORTREVISION=	3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Adobe Utopia 75dpi font

XORG_CAT=	font
USE_XORG=	fontutil

.include <bsd.port.mk>
