# $FreeBSD: head/devel/hs-threads/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	threads
PORTVERSION=	0.5.1.6
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fork threads and wait for their result

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
