# $FreeBSD: head/devel/hs-threads/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	threads
PORTVERSION=	0.5.1.6
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fork threads and wait for their result

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
