# $FreeBSD: head/textproc/rubygem-compass-blueprint/Makefile 490462 2019-01-16 10:28:27Z tz $

PORTNAME=	compass-blueprint
PORTVERSION=	1.0.0
CATEGORIES=	textproc ruby
MASTER_SITES=	RG

MAINTAINER=	t.zuehlsdorff@anymotion.de
COMMENT=	Compass extension for blueprint css framework

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-compass>=0:textproc/rubygem-compass

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
