# Created by: Olivier Duchateau <duchateau.olivier@gmail.com>
# $FreeBSD: head/security/py3-certifi/Makefile 446827 2017-07-28 13:07:40Z sunpoet $

MASTERDIR=      ${.CURDIR}/../py-certifi

PORTSCOUT=	ignore:1

USES=   	python:3.3+

.include "${MASTERDIR}/Makefile"
