# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: head/textproc/p5-String-Tokenizer/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	String-Tokenizer
PORTVERSION=	0.06
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Simple string tokenizer

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
