# Created by: Veniamin Gvozdikov <vg@FreeBSD.org>
# $FreeBSD: head/x11-themes/cursor-chameleon-darkskyblue/Makefile 462745 2018-02-23 21:09:47Z rene $

PORTNAME=	chameleon
PORTVERSION=	0.5
PORTREVISION=	1
CATEGORIES=	x11-themes
MASTER_SITES=	LOCAL/vg
PKGNAMEPREFIX=	cursor-
PKGNAMESUFFIX=	-darkskyblue
DISTNAME=	Chameleon-DarkSkyBlue-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Chameleon Xcursors theme

LICENSE=	GPLv2

THEME=		DarkSkyBlue

.include "${.CURDIR}/../cursor-chameleon-white/files/Makefile.common"
.include <bsd.port.mk>
