# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/textproc/R-cran-xtable/Makefile 478523 2018-08-31 07:11:00Z tota $

PORTNAME=	xtable
DISTVERSION=	1.8-3
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Export tables to LaTeX or HTML

LICENSE=	GPLv2+

USES=	cran:auto-plist

.include <bsd.port.mk>
