# $FreeBSD: head/multimedia/gstreamer1-plugins-v4l2/Makefile 405242 2016-01-04 14:21:56Z kwm $

PORTREVISION=	0
CATEGORIES=	multimedia
PKGNAMESUFFIX=	1-plugins-v4l2

COMMENT=	GStreamer Video 4 Linux 2 source plugin

GST_PLUGIN=	gst_v4l2
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
