# Created by: Johannes Meixner <johannes@perceivon.net>
# $FreeBSD: head/multimedia/linux-c6-libtheora/Makefile 479406 2018-09-10 13:14:50Z mat $

PORTNAME=	libtheora
PORTVERSION=	1.1.0
PORTREVISION=	3
CATEGORIES=	multimedia linux

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	Theora Video Compression Codec (Linux CentOS ${LINUX_DIST_VER})

DESCR=		${.CURDIR}/../${PORTNAME}/pkg-descr
RPMVERSION=	2.el6
USES=		linux:c6
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
