# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-backports/Makefile 441664 2017-05-25 03:15:54Z tota $

PORTNAME=	backports
PORTVERSION=	1.1.0
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Reimplementations of Functions Introduced Since R-3.0.0

LICENSE=	GPLv2

USES=		cran:auto-plist

.include <bsd.port.mk>
