# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-backports/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	backports
PORTVERSION=	1.1.2
PORTREVISION=	2
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Reimplementations of Functions Introduced Since R-3.0.0

LICENSE=	GPLv2

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
