# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-flipper010/Makefile 462170 2018-02-17 16:40:30Z sunpoet $

PORTNAME=	flipper
PORTVERSION=	0.10.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	010

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Act of enabling/disabling features in your application

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

DEPRECATED=	Use devel/rubygem-flipper instead
EXPIRATION_DATE=2018-02-28

CONFLICTS_INSTALL=	rubygem-flipper

PORTSCOUT=	limit:^0\.10\.

NO_ARCH=	yes
USES=		gem
USE_RUBY=	yes

DEPRECATED=	yes
EXPIRATION_DATE=	2018-08-01

.include <bsd.port.mk>
