# Created by: nwhitehorn
# $FreeBSD: head/astro/py-astropy/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	astropy
PORTVERSION=	1.1.2
PORTREVISION=	1
CATEGORIES=	astro
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nwhitehorn@FreeBSD.org
COMMENT=	Community-developed python astronomy tools

LICENSE=	BSD3CLAUSE

BUILD_DEPENDS=	${PYNUMPY}
RUN_DEPENDS=	${PYNUMPY}

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
