# Created by: nwhitehorn
# $FreeBSD: head/astro/py-astropy/Makefile 490909 2019-01-21 22:50:27Z antoine $

PORTNAME=	astropy
PORTVERSION=	1.1.2
PORTREVISION=	2
PORTEPOCH=	1
CATEGORIES=	astro
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nwhitehorn@FreeBSD.org
COMMENT=	Community-developed python astronomy tools

LICENSE=	BSD3CLAUSE

BUILD_DEPENDS=	${PYNUMPY}
RUN_DEPENDS=	${PYNUMPY}

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
