# Created by: nwhitehorn
# $FreeBSD: head/astro/py-astropy/Makefile 417939 2016-07-02 19:31:16Z swills $

PORTNAME=	astropy
PORTVERSION=	1.1.2
CATEGORIES=	astro
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nwhitehorn@FreeBSD.org
COMMENT=	Community-developed python astronomy tools

LICENSE=	BSD3CLAUSE

BUILD_DEPENDS=	${PYNUMPY}
RUN_DEPENDS=	${PYNUMPY}

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
