# $FreeBSD: head/devel/rubygem-peek-performance_bar/Makefile 455591 2017-12-05 16:44:09Z tz $

PORTNAME=	peek-performance_bar
PORTVERSION=	1.3.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	idefix@fechner.net
COMMENT=	Take a peek into the window.performance timing behind your app

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

RUN_DEPENDS=	rubygem-peek>=0.1.0:devel/rubygem-peek

NO_ARCH=	yes
USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
