# Created by: Pedro Giffuni
# $FreeBSD: head/math/R-cran-scatterplot3d/Makefile 493236 2019-02-18 02:28:52Z wen $

PORTNAME=	scatterplot3d
DISTVERSION=	0.3-41
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	pfg@FreeBSD.org
COMMENT=	3D Scatter Plot

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
