# $FreeBSD: head/x11/xwininfo/Makefile 479538 2018-09-11 18:34:27Z zeising $

PORTNAME=	xwininfo
PORTVERSION=	1.1.4
PORTREVISION=	2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Window information utility for X

XORG_CAT=	app
USES=		iconv
USE_XORG=	x11 xcb xorgproto xorg-macros

PLIST_FILES=	bin/xwininfo man/man1/xwininfo.1.gz

.include <bsd.port.mk>
