# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/devel/pear-PHP_Parser/Makefile 443226 2017-06-11 07:36:01Z sunpoet $

PORTNAME=	PHP_Parser
PORTVERSION=	0.2.2
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PHP Grammar Parser

USES=		pear

.include <bsd.port.mk>
