# Created by: Pakhom Golynga <pg@pakhom.spb.ru>
# $FreeBSD: head/net-mgmt/zabbix3-proxy/Makefile 451872 2017-10-12 12:38:23Z dbaio $

PORTNAME=	zabbix3
CATEGORIES=	net-mgmt
PKGNAMESUFFIX=	-proxy

MASTERDIR=	${.CURDIR}/../zabbix3-server

.include "${MASTERDIR}/Makefile"
