# Created by: stas
# $FreeBSD: head/graphics/rubygem-exifr/Makefile 449732 2017-09-12 20:57:18Z sunpoet $

PORTNAME=	exifr
PORTVERSION=	1.3.2
CATEGORIES=	graphics rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Pure-ruby EXIF reader

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

PLIST_FILES=	bin/exifr

.include <bsd.port.mk>
