# Created by: Zhen REN <bg1tpt@gmail.com>
# $FreeBSD: head/textproc/pear-File_Fortune/Makefile 443329 2017-06-11 07:45:37Z sunpoet $

PORTNAME=	File_Fortune
PORTVERSION=	1.0.0
PORTREVISION=	1
CATEGORIES=	textproc pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Interface for reading from and writing to fortune files

USES=		pear

.include <bsd.port.mk>
