# Created by: Pierre David <pdagog@gmail.com>, Jean Benoit <jean@unistra.fr>
# $FreeBSD: head/net-mgmt/netmagis-utils/Makefile 412348 2016-04-01 14:16:16Z mat $

PORTNAME=	netmagis
PKGNAMESUFFIX=	-utils

COMMENT=	Netmagis command-line utilities

RUN_DEPENDS=	netmagis-config:net-mgmt/netmagis-common

MASTERDIR=	${.CURDIR}/../netmagis-common

PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
