# $FreeBSD: head/devel/py-atpublic/Makefile 448942 2017-08-30 00:02:43Z acm $

PORTNAME=	atpublic
PORTVERSION=	0.5
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	acm@FreeBSD.org
COMMENT=	Very simple decorator and function of module's all

LICENSE=	APACHE20

USES=		python:3
USE_PYTHON=	autoplist distutils

MAKE_ENV=	ATPUBLIC_BUILD_EXTENSION=1

.include <bsd.port.mk>
