# $FreeBSD: head/devel/p5-Log-Any/Makefile 477566 2018-08-19 10:46:37Z wen $

PORTNAME=	Log-Any
PORTVERSION=	1.707
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:PREACTION
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to bring loggers and listeners together

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

CONFLICTS_INSTALL=	p5-Log-Any-Adapter-Syslog

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	YES

.include <bsd.port.mk>
