# Created by: Palle Girgensohn <girgen@partitur.se>
# $FreeBSD: head/databases/postgresql96-plperl/Makefile 421360 2016-09-05 11:15:29Z girgen $

WANT_PGSQL_VER=	9.6

.include "${.CURDIR}/../postgresql95-plperl/Makefile"
