# $FreeBSD: head/textproc/php71-xmlwriter/Makefile 475229 2018-07-24 08:44:32Z tz $

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php71

PKGNAMESUFFIX=	-xmlwriter

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
