# $FreeBSD: head/devel/hs-base-orphans/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	base-orphans
PORTVERSION=	0.6
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Backwards-compatible orphan instances for base

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
