# $FreeBSD: head/devel/hs-base-orphans/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	base-orphans
PORTVERSION=	0.6
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Backwards-compatible orphan instances for base

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
