# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/mail/pear-Contact_Vcard_Build/Makefile 443263 2017-06-11 07:40:06Z sunpoet $

PORTNAME=	Contact_Vcard_Build
PORTVERSION=	1.1.2
CATEGORIES=	mail www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR class to build (create) and fetch vCard 2.1 and 3.0 text blocks

USES=		pear

.include <bsd.port.mk>
