# Created by: kftseng@iyard.org
# $FreeBSD: head/www/p5-HTML-StripScripts/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	HTML-StripScripts
PORTVERSION=	1.06
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Strip scripting constructs out of HTML

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
