# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: head/www/rubygem-redmine_acts_as_taggable_on/Makefile 489411 2019-01-05 22:46:44Z sunpoet $

PORTNAME=	redmine_acts_as_taggable_on
PORTVERSION=	1.1.0
CATEGORIES=	www rubygems
MASTER_SITES=	LOCAL/feld/rubygems

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Allows multiple Redmine plugins to use tags safely

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

RUN_DEPENDS=	rubygem-acts-as-taggable-on3>=3.4:www/rubygem-acts-as-taggable-on3

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
