# Created by: Muhammad Moinur Rahman<bofh@FreeBSD.org>
# $FreeBSD: head/devel/pecl-propro2/Makefile 489349 2019-01-05 15:47:56Z rene $

PORTNAME=	propro
PORTVERSION=	2.1.0
CATEGORIES=	devel

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Facility to manage extension object properties

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

PORTSCOUT=	limit:^2.*

USES=		gmake php:pecl
CONFLICTS=	pecl-propro-1*

.include <bsd.port.mk>
