# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-labeling/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	labeling
PORTVERSION=	0.3
PORTREVISION=	2
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Provides a range of axis labeling algorithms

LICENSE=	MIT

USES=	cran:auto-plist

.include <bsd.port.mk>
