# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-labeling/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	labeling
PORTVERSION=	0.3
PORTREVISION=	3
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Provides a range of axis labeling algorithms

LICENSE=	MIT

USES=	cran:auto-plist

.include <bsd.port.mk>
