# $FreeBSD: head/devel/elixir-estree/Makefile 479406 2018-09-10 13:14:50Z mat $

PORTNAME=	elixir-estree
PORTVERSION=	2.6.1
DISTVERSIONPREFIX=	v
CATEGORIES=	devel

MAINTAINER=	erlang@FreeBSD.org
COMMENT=	JavaScript AST to JavaScript code generator in Elixir

LICENSE=	MIT

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	bryanjos

ELIXIR_APP_NAME=estree

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
