# Created by: Kevin Lo <kevlo@FreeBSD.org>
# $FreeBSD: head/math/p5-Math-RPN/Makefile 412348 2016-04-01 14:16:16Z mat $

PORTNAME=	Math-RPN
PORTVERSION=	1.11
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kevlo@FreeBSD.org
COMMENT=	Reverse polish math expression evaluation

TEST_DEPENDS=	p5-Test-Warn>=0:devel/p5-Test-Warn

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
