# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-memoizable/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	memoizable
PORTVERSION=	0.4.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Memoize method return values

LICENSE=	MIT

RUN_DEPENDS=	rubygem-thread_safe>=0.3.1:devel/rubygem-thread_safe

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
