# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-yajl-ruby/Makefile 453699 2017-11-07 21:03:05Z sunpoet $

PORTNAME=	yajl-ruby
PORTVERSION=	1.3.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Streaming JSON parsing and encoding library for Ruby

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
