# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-yajl-ruby/Makefile 427692 2016-12-03 19:33:27Z sunpoet $

PORTNAME=	yajl-ruby
PORTVERSION=	1.3.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Streaming JSON parsing and encoding library for Ruby

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
