# Created by: tobez
# $FreeBSD: head/math/p5-Bit-Vector-Minimal/Makefile 495695 2019-03-14 09:00:59Z amdmi3 $

PORTNAME=	Bit-Vector-Minimal
PORTVERSION=	1.3
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Object-oriented wrapper around Perl's vec()

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
