# Created by: Jui-Nan Lin <jnlin@freebsd.cs.nctu.edu.tw>
# $FreeBSD: head/net/pecl-amqp/Makefile 441497 2017-05-23 00:45:36Z dbaio $

PORTNAME=	amqp
PORTVERSION=	1.9.0
CATEGORIES=	net pear

MAINTAINER=	jnlin@freebsd.cs.nctu.edu.tw
COMMENT=	PHP extension for AMQP API

LICENSE=	PHP301
LICENSE_FILE=	${WRKSRC}/LICENSE

LIB_DEPENDS=	librabbitmq.so:net/rabbitmq-c-devel

USES=		php:pecl

.include <bsd.port.mk>
