# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/finance/R-cran-urca/Makefile 421669 2016-09-10 07:17:15Z tota $

PORTNAME=	urca
DISTVERSION=	1.3-0
CATEGORIES=	finance
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Unit root and cointegration tests for time series data

LICENSE=	GPLv2+

USES=	cran:auto-plist

.include <bsd.port.mk>
