# $FreeBSD: head/www/rubygem-rack-timeout/Makefile 438505 2017-04-14 12:18:18Z jrm $

PORTNAME=	rack-timeout
PORTVERSION=	0.4.2
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	jrm@FreeBSD.org
COMMENT=	Abort requests that are taking too long

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
