# $FreeBSD: head/www/rubygem-rack-timeout/Makefile 447386 2017-08-05 03:25:17Z jrm $

PORTNAME=	rack-timeout
PORTVERSION=	0.4.2
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Abort requests that are taking too long

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
