# $FreeBSD: head/graphics/poppler-qt5/Makefile 490472 2019-01-16 11:13:44Z tijl $

PORTREVISION=	1
PKGNAMESUFFIX=	-qt5

COMMENT=	Qt 5 bindings to poppler

MASTERDIR=	${.CURDIR}/../../graphics/poppler
_SLAVE_PORT=	qt5
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
