# Created by: Stephen Roznowski (sjr@home.com)
# $FreeBSD: head/textproc/p5-Parse-Syslog/Makefile 412349 2016-04-01 14:25:16Z mat $

PORTNAME=	Parse-Syslog
PORTVERSION=	1.10
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 routines that present a simple interface to parse syslog files

BUILD_DEPENDS=	p5-IO-stringy>=0:devel/p5-IO-stringy

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
