# $FreeBSD: head/converters/py-text-unidecode/Makefile 491837 2019-02-01 18:55:18Z kai $

PORTNAME=	text-unidecode
DISTVERSION=	1.2
CATEGORIES=	converters python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	kai@FreeBSD.org
COMMENT=	Most basic port of Perl's Text::Unidecode module

LICENSE=	ART10
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	distutils autoplist

NO_ARCH=	yes

.include <bsd.port.mk>
