# $FreeBSD: head/x11/xmh/Makefile 412351 2016-04-01 14:33:55Z mat $

PORTNAME=	xmh
PORTVERSION=	1.0.3
CATEGORIES=	x11 mail

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Send and read mail with an X interface to MH

RUN_DEPENDS+=	repl:mail/nmh

XORG_CAT=	app
USE_XORG=	xaw xmu xt xbitmaps

.include <bsd.port.mk>
