# Created by: jupengfei <jupengfei@gmail.com>
# $FreeBSD: head/devel/p5-Parse-CPAN-Packages-Fast/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	Parse-CPAN-Packages-Fast
PORTVERSION=	0.09
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Parse CPAN package index

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-CPAN-DistnameInfo>=0:devel/p5-CPAN-DistnameInfo

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
