# $FreeBSD: head/textproc/rubygem-asciidoctor/Makefile 465225 2018-03-21 19:04:01Z sunpoet $

PORTNAME=	asciidoctor
PORTVERSION=	1.5.6.2
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Fast, open source text processor and publishing toolchain

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

PLIST_FILES+=	bin/asciidoctor bin/asciidoctor-safe

.include <bsd.port.mk>
