# Created by: Danilo G. Baio <dbaio@bsd.com.br>
# $FreeBSD: head/devel/py3-six/Makefile 435252 2017-03-02 16:55:16Z skreuzer $

MASTERDIR=	${.CURDIR}/../py-six

TEST_DEPENDS=	${PYTHON_PKGNAMEPREFIX}pytest>0:devel/py3-pytest

USES=	python:3.3+

.include "${MASTERDIR}/Makefile"
