# $FreeBSD: head/devel/hs-data-default-instances-dlist/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	data-default-instances-dlist
PORTVERSION=	0.0.1
PORTREVISION=	12
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Default instances for types in dlist

LICENSE=	BSD3CLAUSE

USE_CABAL=	data-default-class dlist

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
