# $FreeBSD: head/devel/hs-data-default-instances-dlist/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	data-default-instances-dlist
PORTVERSION=	0.0.1
PORTREVISION=	9
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Default instances for types in dlist

LICENSE=	BSD3CLAUSE

USE_CABAL=	data-default-class dlist

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
