# $FreeBSD: head/devel/rubygem-stud/Makefile 433255 2017-02-03 18:23:14Z swills $

PORTNAME=	stud
PORTVERSION=	0.0.22
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Common code techniques

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
