# Created by: Mikle Davidkin <skylord@vt.net.ru>
# $FreeBSD: head/net-p2p/verlihub-plugins-chatroom/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	chatroom
PORTVERSION=	1.1
PORTREVISION=	6
CATEGORIES=	net-p2p
MASTER_SITES=	SF/verlihub/VH_Chatroom/${DISTVERSION}

MAINTAINER=	me@skylord.ru

PLUGIN_DESC=	Chatroom

.include "../verlihub-plugins/Makefile.plugins"
.include <bsd.port.mk>
