# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: head/textproc/p5-Data-Phrasebook/Makefile 435401 2017-03-04 13:48:49Z sunpoet $

PORTNAME=	Data-Phrasebook
PORTVERSION=	0.35
PORTREVISION=	2
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Accessing phrasebooks from various data sources

LICENSE=	ART20

BUILD_DEPENDS=	p5-Module-Pluggable>=2.7:devel/p5-Module-Pluggable
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
