# $FreeBSD: head/www/rubygem-cal-heatmap-rails/Makefile 416406 2016-06-05 17:44:01Z pi $

PORTNAME=	cal-heatmap-rails
PORTVERSION=	3.6.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Calendar heatmap assets for Rails

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.md

RUN_DEPENDS=	rubygem-d3_rails>=3.4.6:www/rubygem-d3_rails

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
