# Created by: Sergey Skvortsov <skv@FreeBSD.org>
# $FreeBSD: head/textproc/p5-XML-Filter-DetectWS/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	XML-Filter-DetectWS
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	PerlSAX filter that detects ignorable whitespace

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-XML-Filter-SAXT>=0:textproc/p5-XML-Filter-SAXT

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
