# $FreeBSD: head/devel/rubygem-peek-rails4/Makefile 448666 2017-08-24 13:05:43Z tz $

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../rubygem-peek

RUN_DEPENDS=	rubygem-concurrent-ruby>=0.9.0:devel/rubygem-concurrent-ruby \
		rubygem-concurrent-ruby-ext>=0.9.0:devel/rubygem-concurrent-ruby-ext \
		rubygem-railties4>=4.0.0:www/rubygem-railties4

.include "${MASTERDIR}/Makefile"
