# $FreeBSD: head/sysutils/dsbbatmon/Makefile 466173 2018-04-01 17:32:15Z tobik $

PORTNAME=	dsbbatmon
DISTVERSION=	1.0.2
CATEGORIES=	sysutils
MASTER_SITES=	http://freeshell.de/~mk/download/

MAINTAINER=	mk@nic-nac-project.org
COMMENT=	Qt battery monitor

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		tar:tgz qmake

USE_GL=		gl
USE_QT5=	buildtools_build core gui linguisttools_build widgets

.include <bsd.port.mk>
