# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/devel/pear-Horde_Nls/Makefile 490211 2019-01-13 20:58:36Z adamw $

PORTNAME=	Horde_Nls
PORTVERSION=	2.2.1
PORTREVISION=	1
CATEGORIES=	devel www pear
MASTER_SITES=	http://pear.horde.org/get/

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Native Language Support

USES=		horde
USE_HORDE_RUN=	Horde_Translation \
		Horde_Util

.include <bsd.port.mk>
