# $FreeBSD: head/devel/hs-silently/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	silently
PORTVERSION=	1.2.5
PORTREVISION=	5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Prevent or capture writing to stdout and other handles

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
