# $FreeBSD: head/textproc/py-parsimonious/Makefile 440442 2017-05-08 17:21:49Z dbaio $

PORTNAME=	parsimonious
PORTVERSION=	0.7.0
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dbaio@FreeBSD.org
COMMENT=	PEGs based parser in Python

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
