# Created by: Adam Weinberger <adamw@FreeBSD.org>
# $FreeBSD: head/graphics/atril-lite/Makefile 430778 2017-01-07 10:42:51Z olivierd $

PORTREVISION=	2
PKGNAMESUFFIX=	-lite

COMMENT=	MATE multi-format document viewer

OPTIONS_EXCLUDE=	CAJA

MASTERDIR=      ${.CURDIR}/../../graphics/atril
SLAVEPORT=      lite
DESCR=		${.CURDIR}/pkg-descr
PLIST=          ${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
