# Created by: Adam Weinberger <adamw@FreeBSD.org>
# $FreeBSD: head/graphics/atril-lite/Makefile 449354 2017-09-06 18:34:45Z truckman $

PORTREVISION?=	0
PKGNAMESUFFIX=	-lite

COMMENT=	MATE multi-format document viewer

OPTIONS_EXCLUDE=	CAJA DBUS

MASTERDIR=	${.CURDIR}/../../graphics/atril
SLAVEPORT=	lite
DESCR=		${.CURDIR}/pkg-descr
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
