# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-mixlib-archive/Makefile 470083 2018-05-16 00:00:10Z sunpoet $

PORTNAME=	mixlib-archive
PORTVERSION=	0.4.6
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Simple interface to various archive formats

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-mixlib-log>=0:devel/rubygem-mixlib-log

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
