# Created by: Aaron Straup Cope <ascope@cpan.org>
# $FreeBSD: head/textproc/p5-Bloom-Filter/Makefile 435036 2017-02-28 09:47:57Z sunpoet $

PORTNAME=	Bloom-Filter
PORTVERSION=	1.2
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:XAERXESS
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Probabilistic algorithm for doing existence tests

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
