# Created by: Dikshie
# $FreeBSD: head/sysutils/py-filelike/Makefile 455210 2017-11-30 15:50:30Z mat $

PORTNAME=	filelike
PORTVERSION=	0.4.1
PORTREVISION=	1
CATEGORIES=	sysutils python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dikshie@sfc.wide.ad.jp
COMMENT=	Python module for building and manipulating file-like object

USES=		python
USE_PYTHON=	distutils autoplist concurrent

.include <bsd.port.mk>
