# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/graphics/hs-HGL/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	HGL
PORTVERSION=	3.2.0.5
PORTREVISION=	4
CATEGORIES=	graphics haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple Haskell graphics library based on X11 or Win32

LICENSE=	BSD3CLAUSE

USE_CABAL=	X11

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
