# $FreeBSD: head/archivers/pear-Horde_Pack/Makefile 463917 2018-03-08 19:48:41Z mat $

PORTNAME=	Horde_Pack
PORTVERSION=	1.0.7
CATEGORIES=	archivers www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Pack Utility

USES=		horde
USE_HORDE_RUN=	Horde_Compress_Fast \
		Horde_Exception

.include <bsd.port.mk>
