# Created by: Brian Gaeke <brg@dgate.org>
# $FreeBSD: head/emulators/vmips/Makefile 477789 2018-08-22 14:32:04Z swills $

PORTNAME=	vmips
PORTVERSION=	1.5.1
CATEGORIES=	emulators
MASTER_SITES=	SF \
		http://www.dgate.org/vmips/releases/${DISTNAME}/

MAINTAINER=	brg@dgate.org
COMMENT=	MIPS R3000 simulator

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		gmake
GNU_CONFIGURE=	yes

INFO=		vmips

.include <bsd.port.mk>
