# Created by: renchap@cocoa-x.com
# $FreeBSD: head/net/rubygem-bunny/Makefile 446798 2017-07-28 02:41:09Z sunpoet $

PORTNAME=	bunny
PORTVERSION=	2.7.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	renchap@cocoa-x.com
COMMENT=	Another synchronous Ruby AMQP client

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-amq-protocol>=2.2.0:net/rubygem-amq-protocol

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
