# $FreeBSD: head/textproc/erlang-yamerl/Makefile 455123 2017-11-29 16:24:37Z olgeni $

PORTNAME=	yamerl
PORTVERSION=	0.6.0
DISTVERSIONPREFIX=	v
CATEGORIES=	textproc
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	YAML 1.2 parser in pure Erlang

LICENSE=	BSD2CLAUSE

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	yakaz

ERL_DOCS=	README.md doc

.include <bsd.port.mk>
