# $FreeBSD: head/devel/hs-simple-reflect/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	simple-reflect
PORTVERSION=	0.3.2
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple reflection of expressions containing variables

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
