# $FreeBSD: head/devel/hs-simple-reflect/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	simple-reflect
PORTVERSION=	0.3.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple reflection of expressions containing variables

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
