# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/textproc/rubygem-jekyll-sass-converter/Makefile 455466 2017-12-03 20:37:12Z sunpoet $

PORTNAME=	jekyll-sass-converter
PORTVERSION=	1.5.1
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Basic Sass converter for Jekyll

LICENSE=	MIT

RUN_DEPENDS=	rubygem-sass>=3.4:textproc/rubygem-sass

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
