# $FreeBSD: head/emulators/ppsspp-qt5-devel/Makefile 452750 2017-10-23 23:06:24Z jbeich $

PORTREVISION=	0
PKGNAMESUFFIX=	-qt5-devel

MASTERDIR=	${.CURDIR}/../ppsspp-devel

OPTIONS_SLAVE=	QT5

.include "${MASTERDIR}/Makefile"
