# $FreeBSD: head/emulators/ppsspp-qt5-devel/Makefile 452570 2017-10-21 06:50:49Z jbeich $

PORTREVISION=	1
PKGNAMESUFFIX=	-qt5-devel

MASTERDIR=	${.CURDIR}/../ppsspp-devel

OPTIONS_SLAVE=	QT5

.include "${MASTERDIR}/Makefile"
