# $FreeBSD: head/emulators/ppsspp-qt5/Makefile 468844 2018-05-02 15:07:27Z jbeich $

PORTREVISION=	1
PKGNAMESUFFIX=	-qt5

MASTERDIR=	${.CURDIR}/../ppsspp

OPTIONS_SLAVE=	QT5

.include "${MASTERDIR}/Makefile"
