# $FreeBSD: head/emulators/ppsspp-qt5/Makefile 452570 2017-10-21 06:50:49Z jbeich $

PORTREVISION=	3
PKGNAMESUFFIX=	-qt5

MASTERDIR=	${.CURDIR}/../ppsspp

OPTIONS_SLAVE=	QT5

.include "${MASTERDIR}/Makefile"
