# $FreeBSD: head/emulators/ppsspp-qt5/Makefile 470890 2018-05-26 14:33:07Z jbeich $

PORTREVISION=	0
PKGNAMESUFFIX=	-qt5

MASTERDIR=	${.CURDIR}/../ppsspp

OPTIONS_SLAVE=	QT5

.include "${MASTERDIR}/Makefile"
