# Created by: Yuri Victorovich <yuri@rawbw.com>
# $FreeBSD: head/devel/py-constantly/Makefile 462887 2018-02-25 00:40:37Z yuri $

PORTNAME=	constantly
PORTVERSION=	15.1.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	yuri@FreeBSD.org
COMMENT=	Provides symbolic constant support to Python projects

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
