# $FreeBSD: head/deskutils/kdepim/Makefile 478003 2018-08-25 05:15:02Z tcberner $

PORTNAME=	kdepim
DISTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	deskutils kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KDE PIM applications metaport

USES=		kde:5 metaport
USE_KDE=	${_USE_KDEPIM5_ALL}

.include <bsd.port.mk>
