# $FreeBSD: head/deskutils/kdepim/Makefile 467009 2018-04-10 19:31:53Z tcberner $

PORTNAME=	kdepim
DISTVERSION=	${KDE_APPLICATIONS_VERSION}
PORTREVISION=	2
CATEGORIES=	deskutils kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KDE PIM applications metaport

USES=		kde:5 metaport
USE_KDE=	${_USE_KDEPIM5_ALL}

.include <bsd.port.mk>
