# Created by: Yuri Victorovich <yuri@rawbw.com>
# $FreeBSD: head/devel/py-opster/Makefile 420765 2016-08-24 06:17:24Z vanilla $

PORTNAME=	opster
PORTVERSION=	4.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	yuri@rawbw.com
COMMENT=	Command line parsing speedster

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
