# Created by: Cyrille Szymanski <cnszym@gmail.com>
# $FreeBSD: head/math/R-cran-dlmodeler/Makefile 477564 2018-08-19 10:13:05Z wen $

PORTNAME=	dlmodeler
DISTVERSION=	1.4-2
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	cnszym@gmail.com
COMMENT=	Generalized Dynamic Linear Modeler

LICENSE=	GPLv2 GPLv3 BSD2CLAUSE
LICENSE_COMB=	dual

BUILD_DEPENDS=	R-cran-KFAS>0:math/R-cran-KFAS

USES=	cran:auto-plist

.include <bsd.port.mk>
