# $FreeBSD: head/devel/hs-haddock-library/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	haddock-library
PORTVERSION=	1.7.0
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Library exposing some functionality of Haddock

LICENSE=	BSD3CLAUSE

USE_CABAL=	attoparsec

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
