# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-sandwich/Makefile 448849 2017-08-28 06:26:27Z tota $

PORTNAME=	sandwich
DISTVERSION=	2.4-0
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Robust Covariance Matrix Estimators

LICENSE=	GPLv2+

RUN_DEPENDS=	R-cran-zoo>0:math/R-cran-zoo

USES=	cran:auto-plist

.include <bsd.port.mk>
