# Created by: TERAMOTO Masahiro <markun@onohara.to>
# $FreeBSD: head/textproc/rubygem-opml/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	opml
PORTVERSION=	1.0.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	markun@onohara.to
COMMENT=	Simple wrapper for parsing OPML files

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
