# $FreeBSD: head/russian/stardict-mueller7accent/Makefile 424339 2016-10-20 15:58:12Z rakuco $

PORTNAME=	stardict-mueller7accent
PORTVERSION=	2.4.2
CATEGORIES=	russian
MASTER_SITES=	http://abloz.com/huzheng/stardict-dic/ru/
DISTNAME=	stardict-Mueller7accentGPL-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Mueller English-Russian dictionary with accents

USES=		tar:bzip2

.include "${.CURDIR}/../stardict-mueller7/files/Makefile.common"
.include <bsd.port.mk>
