# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: head/astro/p5-Astro-Constants/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Astro-Constants
PORTVERSION=	0.1100
CATEGORIES=	astro perl5 science
MASTER_SITES=	CPAN/Astro
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Physical constants for use in astronomy

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

TEST_DEPENDS=	p5-Test-Number-Delta>=0:devel/p5-Test-Number-Delta

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
