# Created by: TAKATSU Tomonari <tota@rtfm.jp>
# $FreeBSD: head/devel/rubygem-ptreloaded/Makefile 432064 2017-01-21 17:29:23Z sunpoet $

PORTNAME=	ptreloaded
PORTVERSION=	0.0.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
DISTNAME=	ParseTreeReloaded-${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Reimplementation of ParseTree using RubyInlineAcceleration

RUN_DEPENDS=	rubygem-rubyinlineaccel>=0.0.1:devel/rubygem-rubyinlineaccel

LICENSE=	GPLv2

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
