# Created by: Timur I. Bakeyev <bat@cpan.org>
# $FreeBSD: head/devel/p5-Test-MockTime/Makefile 468148 2018-04-23 23:31:26Z bofh $

PORTNAME=	Test-MockTime
PORTVERSION=	0.17
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Replaces actual time with simulated time

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
