# $FreeBSD: head/devel/rubygem-micromachine/Makefile 455894 2017-12-10 13:22:10Z sunpoet $

PORTNAME=	micromachine
PORTVERSION=	3.0.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Minimal Finite State Machine

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
