# Created by: Alex Miller (<asm@asm.kiev.ua>)
# $FreeBSD: head/devel/pear-XML_Util/Makefile 441000 2017-05-16 13:37:51Z joneum $

PORTNAME=	XML_Util
PORTVERSION=	1.4.2
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR XML utility class

LICENSE=	BSD2CLAUSE

NO_ARCH=	yes
USES=		pear

.include <bsd.port.mk>
