# Created by: Ian Vaudrey <i.vaudrey@bigfoot.com>
# $FreeBSD: head/devel/makedepend/Makefile 431710 2017-01-16 23:20:40Z bapt $

PORTNAME=	makedepend
PORTVERSION=	1.0.5
PORTEPOCH=	1
CATEGORIES=	devel

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Dependency generator for makefiles

LICENSE=	MIT

XORG_CAT=	util
USE_XORG=	xproto

PLIST_FILES=	bin/makedepend man/man1/makedepend.1.gz

.include <bsd.port.mk>
