# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/chinese/kde4-l10n-zh_TW/Makefile 439367 2017-04-25 08:20:30Z riggs $

PORTNAME=	kde-l10n
PORTVERSION=	${KDE4_VERSION}
PORTREVISION=	1
CATEGORIES=	chinese kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Traditional Chinese messages and documentation for KDE SC 4

KDE4_L10N=	zh_TW

.include "${.CURDIR:H:H}/misc/kde4-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
