# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: head/multimedia/gstreamer-plugins-mpeg2dec/Makefile 428152 2016-12-08 19:52:19Z tijl $
#   $MCom: ports/multimedia/gstreamer-plugins-mpeg2dec/Makefile,v 1.5 2008/03/19 14:05:36 ahze Exp $

PORTREVISION=	2
CATEGORIES=	multimedia

COMMENT=	Gstreamer mpeg decode plugin

GST_PLUGIN=	mpeg2dec

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
