# Created by: Alfred Perlstein <alfred@freebsd.org>
# $FreeBSD: head/www/py-djangorestframework-csv/Makefile 408427 2016-02-07 16:41:12Z alfred $

PORTNAME=	djangorestframework-csv
PORTVERSION=	1.4.1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	alfred@FreeBSD.org
COMMENT=	Django REST framework

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
