# Created by: Mark Felder <feld@FreeBSD.org>
# $FreeBSD: head/www/py-pySmartDL/Makefile 461428 2018-02-10 19:59:26Z sunpoet $

PORTNAME=	pySmartDL
PORTVERSION=	1.2.4
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	feld@FreeBSD.org
COMMENT=	Smart download manager for Python

RUN_DEPENDS=	${PY_FUTURES}

USES=		python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
