# Created by: William Grzybowski <wg@FreeBSD.org>
# $FreeBSD: head/www/py-tmdb3/Makefile 462307 2018-02-19 11:10:43Z antoine $

PORTNAME=	tmdb3
PORTVERSION=	0.7.2
PORTREVISION=	1
CATEGORIES=	www devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	TheMovieDB.org APIv3 interface

USES=		python:2.7
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
