# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: head/textproc/pa-aspell/Makefile 438338 2017-04-12 09:09:47Z mat $

PORTNAME=	${DICT}-aspell
SPELLVERSION=	6-pa-0.01-1
PORTREVISION=	1
PORTEPOCH=	2
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Punjabi dictionary

DICT=	 	pa

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
