# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-concurrent-ruby-ext/Makefile 444191 2017-06-23 21:17:17Z sunpoet $

PORTNAME=	concurrent-ruby-ext
PORTVERSION=	1.0.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	C extensions to optimize the concurrent-ruby

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

RUN_DEPENDS=	rubygem-concurrent-ruby>=${PORTVERSION}:devel/rubygem-concurrent-ruby

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
