# $FreeBSD: head/net/rubygem-pcaprub/Makefile 415215 2016-05-15 07:13:28Z antoine $

PORTNAME=	pcaprub
PORTVERSION=	0.12.4
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Libpcap bindings for ruby

LICENSE=	LGPL21

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
