# Created by: Joseph Benden <joe@thrallingpenguin.com>
# $FreeBSD: head/devel/rubygem-wdm/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	wdm
PORTVERSION=	0.1.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	joe@thrallingpenguin.com
COMMENT=	Library for monitoring directories for changes

LICENSE=	MIT

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
