# $FreeBSD: head/devel/hs-vector-th-unbox/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	vector-th-unbox
PORTVERSION=	0.2.1.6
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Deriver for Data.Vector.Unboxed using Template Haskell

LICENSE=	BSD3CLAUSE

USE_CABAL=	vector

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
