# $FreeBSD: head/devel/hs-vector-th-unbox/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	vector-th-unbox
PORTVERSION=	0.2.1.6
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Deriver for Data.Vector.Unboxed using Template Haskell

LICENSE=	BSD3CLAUSE

USE_CABAL=	vector

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
