# $FreeBSD: head/devel/hs-vector-th-unbox/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	vector-th-unbox
PORTVERSION=	0.2.1.6
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Deriver for Data.Vector.Unboxed using Template Haskell

LICENSE=	BSD3CLAUSE

USE_CABAL=	vector

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
