# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-smallcheck/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	smallcheck
PORTVERSION=	1.1.1
PORTREVISION=	5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Property-based testing library

LICENSE=	BSD3CLAUSE

USE_CABAL=	logict mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
