# $FreeBSD: head/databases/rubygem-arel8/Makefile 456541 2017-12-17 15:53:48Z sunpoet $

PORTNAME=	arel
PORTVERSION=	8.0.0
PORTEPOCH=	1
CATEGORIES=	databases rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	8

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Relational Algebra for Ruby

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE.txt

PORTSCOUT=	limit:^8\.

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
