# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/devel/pear-HTML_CSS/Makefile 443198 2017-06-11 07:31:58Z sunpoet $

PORTNAME=	HTML_CSS
PORTVERSION=	1.5.4
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR class for generating CSS declarations

BUILD_DEPENDS=	${PEARDIR}/HTML/Common.php:devel/pear-HTML_Common
RUN_DEPENDS=	${PEARDIR}/HTML/Common.php:devel/pear-HTML_Common

USES=		pear

.include <bsd.port.mk>
