# Created by: Valery Komarov <komarov@valerka.net>
# $FreeBSD: head/devel/php5-blitz/Makefile 461158 2018-02-07 17:46:10Z mat $

PORTNAME=	blitz
PORTVERSION=	0.8.2
PORTREVISION=	1
CATEGORIES=	devel
MASTER_SITES=	http://alexeyrybak.com/blitz/
PKGNAMEPREFIX=	php5-

MAINTAINER=	komarov@valerka.net
COMMENT=	PHP templating engine

CONFLICTS=	php5-blitz-devel-[0-9]*

USES=		php:ext
IGNORE_WITH_PHP=	70 71 72

.include <bsd.port.mk>
