# $FreeBSD: head/security/hs-pem/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	pem
PORTVERSION=	0.2.2
PORTREVISION=	5
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Privacy Enhanced Mail (PEM) format reader and writer

LICENSE=	BSD3CLAUSE

USE_CABAL=	base64-bytestring>=1.0.0 mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
