# $FreeBSD: head/security/hs-pem/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	pem
PORTVERSION=	0.2.2
PORTREVISION=	4
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Privacy Enhanced Mail (PEM) format reader and writer

LICENSE=	BSD3CLAUSE

USE_CABAL=	base64-bytestring>=1.0.0 mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
