# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/net/pear-Services_Pingback/Makefile 443300 2017-06-11 07:43:16Z sunpoet $

PORTNAME=	Services_Pingback
PORTVERSION=	0.2.2
CATEGORIES=	net www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Pingback user-agent class

USES=		pear

.include <bsd.port.mk>
