# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: head/russian/aspell/Makefile 438338 2017-04-12 09:09:47Z mat $

PORTNAME=	aspell
SPELLVERSION=	6-ru-0.99f7-1
PORTREVISION=	1
PORTEPOCH=	2
CATEGORIES=	russian textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Russian dictionary

DICT=	 	ru

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
