# Created by: ache
# $FreeBSD: head/converters/mpack/Makefile 415839 2016-05-25 15:43:34Z mat $

PORTNAME=	mpack
PORTVERSION=	1.6
PORTREVISION=	3
CATEGORIES=	converters mail news
MASTER_SITES=	ftp://ftp.andrew.cmu.edu/pub/mpack/

MAINTAINER=	dinoex@FreeBSD.org
COMMENT=	External MIME packer/unpacker

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/mpack bin/munpack \
		man/man1/mpack.1.gz man/man1/munpack.1.gz

.include <bsd.port.mk>
