# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/devel/pear-HTML_Javascript/Makefile 489872 2019-01-10 17:03:29Z joneum $

PORTNAME=	HTML_Javascript
PORTVERSION=	1.1.2
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Provides an interface for creating simple JS scripts

LICENSE=	PHP30

USES=		pear

.include <bsd.port.mk>
