# Created by: Pedro Giffuni
# $FreeBSD: head/math/R-cran-qualityTools/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	qualityTools
DISTVERSION=	1.55
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	pfg@FreeBSD.org
COMMENT=	Statistical Methods for Quality Science

LICENSE=	GPLv2

BUILD_DEPENDS=	${CRAN_DEPENDS}
RUN_DEPENDS=	${CRAN_DEPENDS}

CRAN_DEPENDS=	R-cran-Rsolnp>0:math/R-cran-Rsolnp

USES=	cran:auto-plist

.include <bsd.port.mk>
