# Created by: Pedro Giffuni
# $FreeBSD: head/math/R-cran-qualityTools/Makefile 440270 2017-05-06 15:12:57Z miwi $

PORTNAME=	qualityTools
DISTVERSION=	1.55
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	pfg@FreeBSD.org
COMMENT=	Statistical Methods for Quality Science

LICENSE=	GPLv2

BUILD_DEPENDS=	${CRAN_DEPENDS}
RUN_DEPENDS=	${CRAN_DEPENDS}

CRAN_DEPENDS=	R-cran-Rsolnp>0:math/R-cran-Rsolnp

USES=	cran:auto-plist

.include <bsd.port.mk>
