# $FreeBSD: head/www/py-cssmin/Makefile 464784 2018-03-17 10:44:23Z sunpoet $

PORTNAME=	cssmin
PORTVERSION=	0.2.0
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Python port of the YUI CSS compression algorithm

LICENSE=	MIT

NO_ARCH=	yes
USES=		python
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
