# $FreeBSD: head/security/rubygem-nexpose/Makefile 460871 2018-02-04 08:04:33Z antoine $

PORTNAME=	nexpose
PORTVERSION=	7.2.0
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Ruby API to Rapid7 Nexpose vulnerability management

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/COPYING

NO_ARCH=	yes
USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
