# Created by: Zhihao Yuan <lichray@gmail.com>
# $FreeBSD: head/chinese/fcitx-table-extra/Makefile 412344 2016-04-01 13:29:15Z mat $

PORTNAME=	fcitx-table-extra
PORTVERSION=	0.3.7
CATEGORIES=	chinese
MASTER_SITES=	http://download.fcitx-im.org/${PORTNAME}/
DIST_SUBDIR=	fcitx

MAINTAINER=	lichray@gmail.com
COMMENT=	Table-based input methods for Fcitx

LICENSE=	GPLv2

LIB_DEPENDS=	libfcitx-config.so:chinese/fcitx

USES=		tar:xz cmake gettext
INSTALLS_ICONS=	yes
STRIP=

.include <bsd.port.mk>
