# Created by: ndewing@experts-exchange.com
# $FreeBSD: head/devel/rubygem-mixlib-shellout/Makefile 459061 2018-01-15 15:04:59Z swills $

PORTNAME=	mixlib-shellout
PORTVERSION=	2.3.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	nickdewing@gmail.com
COMMENT=	Shell interface that also collects stdout and stderr

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
