# $FreeBSD: head/www/sogo4-activesync/Makefile 471448 2018-06-03 05:59:04Z acm $

PKGNAMESUFFIX=		-activesync

MAINTAINER=		acm@FreeBSD.org

CONFLICTS=		sogo[2-4]-[0-9]* sogo[2-3]-activesync-[0-9]*

OPTIONS_SLAVE=		ACTIVESYNC

MASTERDIR=		${.CURDIR}/../sogo4

.include "${MASTERDIR}/Makefile"
