# Created by: Mark Felder <feld@FreeBSD.org>
# $FreeBSD: head/databases/py-zodbpickle/Makefile 451925 2017-10-12 19:00:13Z feld $

PORTNAME=	zodbpickle
PORTVERSION=	0.7.0
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	feld@FreeBSD.org
COMMENT=	Python pickling interface for ZODB

LICENSE=	PSFL ZPL21
LICENSE_COMB=	multi

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
