# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/textproc/R-cran-stringi/Makefile 464450 2018-03-14 03:06:49Z tota $

PORTNAME=	stringi
DISTVERSION=	1.1.7
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Character String Processing Facilities

LICENSE=	BSD3CLAUSE

LIB_DEPENDS=	libicui18n.so:devel/icu

USES=	cran:auto-plist,compiles pkgconfig:build

.include <bsd.port.mk>
