# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/textproc/R-cran-stringi/Makefile 475300 2018-07-25 05:30:04Z tota $

PORTNAME=	stringi
DISTVERSION=	1.2.4
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Character String Processing Facilities

LICENSE=	BSD3CLAUSE

LIB_DEPENDS=	libicui18n.so:devel/icu

USES=	cran:auto-plist,compiles pkgconfig:build

.include <bsd.port.mk>
