# $FreeBSD: head/sysutils/u-boot-nanopi-m1plus/Makefile 447381 2017-08-05 01:46:09Z linimon $

MAINTAINER=    manu@FreeBSD.org
MASTERDIR=     ${.CURDIR}/../u-boot-master

MODEL=         nanopi_m1plus
BOARD_CONFIG=  nanopi_m1_plus_defconfig
FAMILY=                allwinner

.include "${MASTERDIR}/Makefile"
