# $FreeBSD: head/databases/rubygem-dbd-mysql/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	dbd-mysql
PORTVERSION=	0.4.4
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	MySQL driver for DBI-for-Ruby

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	rubygem-dbi>=0:databases/rubygem-dbi \
		rubygem-mysql>=0:databases/rubygem-mysql

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
