# $FreeBSD: head/devel/aarch64-none-elf-binutils/Makefile 405261 2016-01-04 18:30:53Z andrew $

COMMENT=	GNU binutils for bare metal AArch64 cross-development
PKGNAMEPREFIX=	aarch64-none-elf-
BUTARGET=	aarch64-none-elf
PLIST=	${.CURDIR}/pkg-plist

MASTERDIR=	${.CURDIR}/../binutils

.include "${MASTERDIR}/Makefile"
