# $FreeBSD: head/devel/websocketpp/Makefile 423868 2016-10-12 15:35:41Z arved $

PORTNAME=	websocketpp
PORTVERSION=	0.7.0
CATEGORIES=	devel

MAINTAINER=	arved@FreeBSD.org
COMMENT=	Header only implementation of the WebSocket protocol

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

USE_GITHUB=	yes
GH_ACCOUNT=	zaphoyd
USES=		cmake
NO_ARCH=	yes

.include <bsd.port.mk>
