# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: head/devel/p5-Date-Calc-Iterator/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	Date-Calc-Iterator
PORTVERSION=	1.00
PORTREVISION=	1
CATEGORIES=	devel net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Iterate over a range of dates

BUILD_DEPENDS=	p5-Date-Calc>=0:devel/p5-Date-Calc
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
