# $FreeBSD: head/devel/hs-basement/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	basement
PORTVERSION=	0.0.7
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Foundation most basic primitives without any dependencies

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
