# $FreeBSD: head/emulators/citra-qt5/Makefile 491069 2019-01-24 00:14:20Z jbeich $

PORTREVISION=	0
PKGNAMESUFFIX=	-qt5

MASTERDIR=	${.CURDIR}/../citra

OPTIONS_SLAVE=	QT5

.include "${MASTERDIR}/Makefile"
