# $FreeBSD: head/emulators/citra-qt5/Makefile 459487 2018-01-20 00:22:37Z jbeich $

PORTREVISION=	0
PKGNAMESUFFIX=	-qt5

MASTERDIR=	${.CURDIR}/../citra

OPTIONS_SLAVE=	QT5

.include "${MASTERDIR}/Makefile"
