# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: head/x11-themes/gtk-aluminumalloy-toxic-theme/Makefile 443503 2017-06-13 14:40:17Z mat $

PORTREVISION=	5

THEME_FLAVOR=	toxic

MASTERDIR=	${.CURDIR}/../gtk-aluminumalloy-volcanic-theme

DISTINFO_FILE=	${.CURDIR}/../gtk-aluminumalloy-toxic-theme/distinfo
PLIST=		${.CURDIR}/../gtk-aluminumalloy-toxic-theme/pkg-plist

.include "${MASTERDIR}/Makefile"
