# Created by: ijliao
# $FreeBSD: head/www/py-mechanize/Makefile 455224 2017-11-30 20:28:15Z antoine $

PORTNAME=	mechanize
PORTVERSION=	0.3.6
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP \
		http://wwwsearch.sourceforge.net/mechanize/src/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	Stateful programmatic web browsing in Python

LICENSE=	BSD3CLAUSE

USES=		python:2.7
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
