# $FreeBSD: head/devel/php72-intl/Makefile 463395 2018-03-02 13:11:59Z tz $

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php72

PKGNAMESUFFIX=	-intl

USES=		compiler:c++11-lib
USE_CXXSTD=	gnu++11

.include "${MASTERDIR}/Makefile"
