# $FreeBSD: head/devel/php72-intl/Makefile 461290 2018-02-09 09:12:48Z jbeich $

PORTREVISION=	1
CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php72

PKGNAMESUFFIX=	-intl

USES=		compiler:c++11-lib
USE_CXXSTD=	gnu++11

.include "${MASTERDIR}/Makefile"
