# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-cloudfiles/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	cloudfiles
PORTVERSION=	1.5.0.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby version of the Rackspace Cloud Files API

LICENSE=	MIT

RUN_DEPENDS=	rubygem-json>=0:devel/rubygem-json

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
