# $FreeBSD: head/sysutils/u-boot-nanopi-neo-air/Makefile 447381 2017-08-05 01:46:09Z linimon $

MAINTAINER=    manu@FreeBSD.org
MASTERDIR=     ${.CURDIR}/../u-boot-master

MODEL=         nanopi_neo_air
BOARD_CONFIG=  nanopi_neo_air_defconfig
FAMILY=                allwinner

.include "${MASTERDIR}/Makefile"
