# Created by: ijliao
# $FreeBSD: head/misc/p5-Chatbot-Eliza/Makefile 450750 2017-09-27 13:44:09Z culot $

PORTNAME=	Chatbot-Eliza
PORTVERSION=	1.08
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Clone of the classic Eliza program

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
