# Created by: Alexey V. Degtyarev <alexey@renatasystems.org>
# $FreeBSD$

PORTNAME=	jmespath
PORTVERSION=	0.9.3
PORTREVISION=	0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	alexey@renatasystems.org
COMMENT=	JSON Matching Expressions

LICENSE=	MIT

USES=		python
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
