# $FreeBSD: head/misc/elixir-mime/Makefile 479406 2018-09-10 13:14:50Z mat $

PORTNAME=	mime
PORTVERSION=	1.3.0
DISTVERSIONPREFIX=	v
CATEGORIES=	misc
PKGNAMEPREFIX=	elixir-

MAINTAINER=	erlang@FreeBSD.org
COMMENT=	MIME type module for Elixir

LICENSE=	APACHE20

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	elixir-lang

MIX_REWRITE=	yes

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
