# Created by: Greg Larkin <glarkin@FreeBSD.org>
# $FreeBSD: head/devel/pear-VersionControl_SVN/Makefile 443247 2017-06-11 07:37:47Z sunpoet $

PORTNAME=	VersionControl_SVN
PORTVERSION=	0.5.2
CATEGORIES=	devel pear

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Wrapper interface for the Subversion command-line client

LICENSE=	BSD2CLAUSE

BUILD_DEPENDS=	pear-XML_Parser>=1.3.4:devel/pear-XML_Parser
RUN_DEPENDS=	pear-XML_Parser>=1.3.4:devel/pear-XML_Parser

USES=		pear

.include <bsd.port.mk>
