# $FreeBSD: head/security/goptlib/Makefile 413776 2016-04-22 12:40:04Z mat $

PORTNAME=	goptlib
PORTVERSION=	0.5
CATEGORIES=	security
MASTER_SITES=	http://c-s.li/ports/

MAINTAINER=	cs@FreeBSD.org
COMMENT=	Go pluggable transports library

USES=		go
GO_PKGNAME=	git.torproject.org/pluggable-transports/${PORTNAME}.git
GO_TARGET=	${GO_PKGNAME}

.include <bsd.port.mk>
