# $FreeBSD: head/devel/hs-hslua-module-text/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	hslua-module-text
PORTVERSION=	0.1.2.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Lua module for text

LICENSE=	MIT

USE_CABAL=	hslua

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
