# $FreeBSD: head/devel/hs-hslua-module-text/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	hslua-module-text
PORTVERSION=	0.2.0
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Lua module for text

LICENSE=	MIT

USE_CABAL=	hslua

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
