# $FreeBSD: head/math/hs-categories/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	categories
PORTVERSION=	1.0.7
PORTREVISION=	2
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Categories

LICENSE=	BSD3CLAUSE

USE_CABAL=	void>=0.5.4.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
