# Created by: Pav Lucistnik <pav@FreeBSD.org>
# $FreeBSD: head/devel/pear-OLE/Makefile 450163 2017-09-19 20:20:10Z bofh $

PORTNAME=	OLE
DISTVERSION=	1.0.0RC3
CATEGORIES=	devel www pear

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	PEAR class for reading and writing OLE containers

USES=		pear

.include <bsd.port.mk>
