# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: head/textproc/p5-HTML-Entities-Numbered/Makefile 479390 2018-09-10 11:16:59Z des $

PORTNAME=	HTML-Entities-Numbered
PORTVERSION=	0.04
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	HTML::Entities::Numbered - Conversion of numbered HTML entities

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
