# $FreeBSD: head/audio/gstreamer1-plugins-mpg123/Makefile 483887 2018-11-03 11:58:10Z tijl $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	GStreamer MPEG Layer 1, 2, and 3 plugin

GST_PLUGIN=	mpg123
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
