# $FreeBSD: head/www/twiki-MailerContrib/Makefile 412351 2016-04-01 14:33:55Z mat $

PORTNAME=	MailerContrib
SVNREV=		17641

COMMENT=	E-mail notification of changes

RUN_DEPENDS=	p5-URI>=1.35:net/p5-URI

.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
