# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/security/php56-openssl/Makefile 481804 2018-10-11 09:42:02Z antoine $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php56

PORTREVISION=	1
PKGNAMESUFFIX=	-openssl

.include "${MASTERDIR}/Makefile"
