# Created by: Michael Nottebrock <lofi@FreeBSD.org>
# $FreeBSD: head/databases/qt4-sqlite-plugin/Makefile 442740 2017-06-06 05:00:56Z tcberner $

PORTREVISION=	3

COMMENT=	Qt SQLite 2 database plugin
DB=		sqlite2
USES=		sqlite:2

.include "${.CURDIR:H:H}/devel/qt4/Makefile.sqldrivers"
