# $FreeBSD: head/textproc/py-dbfread/Makefile 427181 2016-11-26 18:18:37Z matthew $

PORTNAME=	dbfread
PORTVERSION=	2.0.7
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	matthew@FreeBSD.org
COMMENT=	Read DBF files, returning data as native Python objects

LICENSE=	MIT

NO_ARCH=	yes

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
