# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-rake-contrib/Makefile 430224 2017-01-01 01:47:16Z sunpoet $

PORTNAME=	rake-contrib
PORTVERSION=	1.0.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Additional libraries for Rake

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

RUN_DEPENDS=	rubygem-rake>=0:devel/rubygem-rake

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
