# $FreeBSD: head/multimedia/gstreamer1-plugins-ttml/Makefile 446388 2017-07-22 11:35:44Z kwm $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	GStreamer ttml subtitle plugin

GST_PLUGIN=	ttml
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
