# $FreeBSD: head/devel/hs-asn1-types/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	asn1-types
PORTVERSION=	0.3.2
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	ASN.1 types

LICENSE=	BSD3CLAUSE

USE_CABAL=	hourglass memory

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
