# Created by: wen@FreeBSD.org
# $FreeBSD: head/textproc/p5-PDF-Tiny/Makefile 446453 2017-07-23 06:46:04Z wen $

PORTNAME=	PDF-Tiny
DISTVERSION=	0.09
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Minimal Lightweight PDF Library

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
