# Created by: Veniamin Gvozdikov <vg@FreeBSD.org>
# $FreeBSD: head/audio/rubygem-librmpd/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	librmpd
PORTVERSION=	0.1.1
CATEGORIES=	audio rubygems
MASTER_SITES=	RG

MAINTAINER=	vg@FreeBSD.org
COMMENT=	Is a simple yet powerful Music Player Daemon library

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
