# Created by: Veniamin Gvozdikov <vg@FreeBSD.org>
# $FreeBSD: head/audio/rubygem-librmpd/Makefile 462745 2018-02-23 21:09:47Z rene $

PORTNAME=	librmpd
PORTVERSION=	0.1.1
CATEGORIES=	audio rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Is a simple yet powerful Music Player Daemon library

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
