# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-lumberjack/Makefile 440725 2017-05-12 21:51:18Z sunpoet $

PORTNAME=	lumberjack
PORTVERSION=	1.0.12
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Simple, powerful, and fast logging utility

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT_LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
