# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/math/hs-math-functions/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	math-functions
PORTVERSION=	0.2.1.0
PORTREVISION=	2
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Special functions and Chebyshev polynomials

LICENSE=	BSD3CLAUSE

USE_CABAL=	primitive vector vector-th-unbox

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
