# $FreeBSD: head/devel/hs-bytestring-nums/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	bytestring-nums
PORTVERSION=	0.3.6
PORTREVISION=	14
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Parse numeric literals from ByteStrings

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
