# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/textproc/p5-Kwalify/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Kwalify
PORTVERSION=	1.22
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:SREZIC
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Implementation of Kwalify parser, validator and data binding tool

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
