# $FreeBSD: head/textproc/hs-doctemplates/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	doctemplates
PORTVERSION=	0.2.2.1
PORTREVISION=	2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	The doctemplates package

LICENSE=	BSD3CLAUSE

USE_CABAL=	aeson blaze-html blaze-markup scientific unordered-containers \
		vector

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
