# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/science/pybrain/Makefile 412349 2016-04-01 14:25:16Z mat $

PORTNAME=	pybrain
PORTVERSION=	0.3.3
CATEGORIES=	science python

MAINTAINER=	wen@FreeBSD.org
COMMENT=	PyBrain is the swiss army knife for neural networking

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}scipy>=0.7.1:science/py-scipy

USE_GITHUB=	yes

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
