# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/polish/kde4-l10n/Makefile 461375 2018-02-10 10:29:51Z tcberner $

PORTNAME=	kde-l10n
PORTVERSION=	${KDE4_VERSION}
PORTREVISION=	3
CATEGORIES=	polish kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Polish messages and documentation for KDE SC 4

KDE4_L10N=	pl

.include "${.CURDIR:H:H}/misc/kde4-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
