# Created by: Lars Thegler <lars@thegler.dk>
# $FreeBSD: head/sysutils/p5-Sys-CpuLoad/Makefile 437950 2017-04-07 18:50:22Z lth $

PORTNAME=	Sys-CpuLoad
PORTVERSION=	0.03
PORTREVISION=	1
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module to retrieve CPU load averages

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
