# $FreeBSD: head/misc/erlang-mimerl/Makefile 479406 2018-09-10 13:14:50Z mat $

PORTNAME=	mimerl
PORTVERSION=	1.1.1
CATEGORIES=	misc
PKGNAMEPREFIX=	erlang-

MAINTAINER=	erlang@FreeBSD.org
COMMENT=	Erlang library to handle mimetypes

LICENSE=	MIT

USES=		erlang:rebar3
USE_GITHUB=	yes
GH_ACCOUNT=	benoitc

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
