# Created by: Tsung-Han Yeh <snowfly@yuntech.edu.tw>
# $FreeBSD: head/www/p5-WWW-OpenSVN/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	WWW-OpenSVN
PORTVERSION=	0.1.3
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	snowfly@yuntech.edu.tw
COMMENT=	Automated interface for OpenSVN.csie.org

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-libwww>=0:www/p5-libwww

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
