# Created by: Bruce M Simpson <bms@FreeBSD.org>
# $FreeBSD: head/x11-fonts/gfe/Makefile 481888 2018-10-12 09:19:04Z antoine $

PORTNAME=	gfe
PORTVERSION=	0.0.4
PORTREVISION=	7
CATEGORIES=	x11-fonts
MASTER_SITES=	SUNSITE/X11/fonts

MAINTAINER=	ports@FreeBSD.org
COMMENT=	GTK+-based .bdf font editor for X

DEPRECATED=	Uses obsolete glib12
EXPIRATION_DATE=	2018-12-20

GNU_CONFIGURE=	yes
PLIST_FILES=	bin/gfe

USE_GNOME=	gtk12
USE_XORG=	xpm

.include <bsd.port.mk>
