# $FreeBSD: head/net/p5-Net-LDAP-FilterBuilder/Makefile 422279 2016-09-16 22:50:48Z amdmi3 $

PORTNAME=	Net-LDAP-FilterBuilder
PORTVERSION=	1.200000
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jeremybbaggs@gmail.com
COMMENT=	Perl module to construct LDAP filter statments

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
