# $FreeBSD: head/devel/hs-primitive/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	primitive
PORTVERSION=	0.6.3.0
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Primitive memory-related operations

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
