# $FreeBSD: head/devel/elixir-make/Makefile 463719 2018-03-06 12:05:10Z olgeni $

PORTNAME=	make
DISTVERSIONPREFIX=	v
DISTVERSION=	0.4.1
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Make compiler for Mix

LICENSE=	APACHE20

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	elixir-lang
GH_PROJECT=	elixir_make

ELIXIR_APP_NAME=elixir_make

.include <bsd.port.mk>
