# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/german/kde4-l10n/Makefile 449969 2017-09-16 16:52:48Z tcberner $

PORTNAME=	kde-l10n
PORTVERSION=	${KDE4_VERSION}
PORTREVISION=	2
CATEGORIES=	german kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	German messages and documentation for KDE SC 4

KDE4_L10N=	de

.include "${.CURDIR:H:H}/misc/kde4-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
