# $FreeBSD: head/devel/rubygem-mkrf/Makefile 414144 2016-04-27 22:29:01Z swills $

PORTNAME=	mkrf
PORTVERSION=	0.2.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Replacement to mkmf generates Rakefiles to build C Extensions

LICENSE=	MIT

USE_RUBY=	yes
USES=		gem python

.include <bsd.port.mk>
