# Created by: Yarema <yds@CoolRat.org>
# $FreeBSD: head/databases/courier-authlib-mysql/Makefile 481732 2018-10-10 11:54:58Z madpilot $

PORTREVISION=	0
PKGNAMESUFFIX=	-mysql

COMMENT=	MySQL support for the Courier authentication library
CATEGORIES=	databases mail

MASTERDIR=	${.CURDIR}/../../security/courier-authlib

.include "${MASTERDIR}/Makefile"
