# Created by: mat
# $FreeBSD: head/devel/p5-NEXT/Makefile 423527 2016-10-08 17:06:52Z adamw $

PORTNAME=	NEXT
PORTVERSION=	0.67
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Provide a pseudo-class NEXT (et al) that allows method redispatch

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
