# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: head/sysutils/p5-Schedule-Match/Makefile 479390 2018-09-10 11:16:59Z des $

PORTNAME=	Schedule-Match
PORTVERSION=	0.07
PORTREVISION=	1
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Handles and detects clash between pattern-based schedules

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
