# Created by: Steve Wills <steve@meatwad.mouf.net>
# $FreeBSD: head/graphics/rubygem-opengl/Makefile 444274 2017-06-25 15:02:29Z sunpoet $

PORTNAME=	opengl
PORTVERSION=	0.10.0
PORTEPOCH=	1
CATEGORIES=	graphics ruby
MASTER_SITES=	RG
DIST_SUBDIR=	ruby

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	OpenGL wrapper for Ruby

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

USE_GL=		glut
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
