# Created by: Ryan Steinmetz <rpsfa@rit.edu>
# $FreeBSD: head/devel/rubygem-delayed_job/Makefile 467355 2018-04-14 23:59:11Z sunpoet $

PORTNAME=	delayed_job
PORTVERSION=	4.1.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Asynchronously executing longer tasks in the background

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.md

RUN_DEPENDS=	rubygem-activesupport4>=3.0:devel/rubygem-activesupport4

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
