# $FreeBSD: head/devel/p5-Log-Any-Adapter-Callback/Makefile 484353 2018-11-06 21:13:54Z rene $

PORTNAME=	Log-Any-Adapter-Callback
PORTVERSION=	0.09
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension adapter for Log::Any with callbacks

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS:=	p5-Log-Any>0:devel/p5-Log-Any

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
