# $FreeBSD: head/net/hs-network-multicast/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	network-multicast
PORTVERSION=	0.2.0
PORTREVISION=	4
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple multicast library

USE_CABAL=	network

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
