# $FreeBSD: head/x11-drivers/xf86-input-joystick/Makefile 431440 2017-01-13 23:25:56Z bapt $

PORTNAME=	xf86-input-joystick
PORTVERSION=	1.6.3
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org joystick input driver

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

XORG_CAT=	driver

USES=		pathfix

.include <bsd.port.mk>
