# $FreeBSD: head/x11-drivers/xf86-input-joystick/Makefile 479538 2018-09-11 18:34:27Z zeising $

PORTNAME=	xf86-input-joystick
PORTVERSION=	1.6.3
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org joystick input driver

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

XORG_CAT=	driver

USES=		pathfix

.include <bsd.port.mk>
