# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/graphics/R-cran-shape/Makefile 465671 2018-03-27 08:49:59Z tota $

PORTNAME=	shape
PORTVERSION=	1.4.4
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Functions for plotting graphical shapes, colors

LICENSE=	GPLv3

USES=	cran:auto-plist

.include <bsd.port.mk>
