# Created by: markm@FreeBSD.org
# $FreeBSD: head/textproc/p5-Text-CSV/Makefile 477475 2018-08-18 03:38:05Z wen $

PORTNAME=	Text-CSV
PORTVERSION=	1.97
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Composition and decomposition of comma-separated values

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
