# Created by: markm@FreeBSD.org
# $FreeBSD: head/textproc/p5-Text-CSV/Makefile 489801 2019-01-09 14:53:09Z sunpoet $

PORTNAME=	Text-CSV
PORTVERSION=	1.99
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Composition and decomposition of comma-separated values

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

NO_ARCH=	yes

.include <bsd.port.mk>
