# $FreeBSD: head/devel/hs-lifted-base/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	lifted-base
PORTVERSION=	0.2.3.11
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Lifted IO operations from the base library

LICENSE=	BSD3CLAUSE

USE_CABAL=	monad-control>=0.3 transformers-base>=0.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
