# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/p5-Devel-Caller-IgnoreNamespaces/Makefile 451889 2017-10-12 15:09:23Z sunpoet $

PORTNAME=	Devel-Caller-IgnoreNamespaces
PORTVERSION=	1.1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Make available a magic caller which can ignore namespaces

LICENSE=	ART10 GPLv2
LICENSE_COMB=	dual
LICENSE_FILE_ART10=	${WRKSRC}/ARTISTIC.txt
LICENSE_FILE_GPLv2=	${WRKSRC}/GPL2.txt

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
