# Created by: Jin-Sih, Lin <linpct@gmail.com>
# $FreeBSD: head/devel/rubygem-rodzilla/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	rodzilla
PORTVERSION=	0.3.6
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	linpct@gmail.com
COMMENT=	Bugzilla API Client

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

RUN_DEPENDS=	rubygem-httparty>=0.12.0:www/rubygem-httparty

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
