# Created by: Ilya A. Arkhipov <rum1cro@yandex.ru>
# $FreeBSD: head/www/py-django-subdomains/Makefile 455210 2017-11-30 15:50:30Z mat $

PORTNAME=	django-subdomains
PORTVERSION=	2.1.0
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	rum1cro@yandex.ru
COMMENT=	Subdomains helpers for the Django framework

LICENSE=	MIT

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}django18>0:www/py-django18@${FLAVOR}

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
