# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-fast_stack/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	fast_stack
PORTVERSION=	0.2.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Fast method for collecting stack traces

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
