# Created by: Gabor Kovesdan
# $FreeBSD: head/security/p5-Digest-Elf/Makefile 412897 2016-04-10 07:01:20Z ashish $

PORTNAME=	Digest-Elf
PORTVERSION=	1.42
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Perl extension for ElfHash hash algorithm

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
