# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/mail/claws-mail-tnef/Makefile 438695 2017-04-17 14:07:47Z pawel $

PORTNAME=	tnef
PORTREVISION=	0

COMMENT=	TNEF attachment format parser plugin for Claws Mail

LIB_DEPENDS=	libytnef.so:converters/ytnef

CLAWS_PLUGINS_BUILD=	tnef_parse

.include "../claws-mail/Makefile.claws"
.include <bsd.port.mk>
