# $FreeBSD: head/devel/pear-Horde_Cli/Makefile 444450 2017-06-27 10:02:04Z mm $

PORTNAME=	Horde_Cli
PORTVERSION=	2.2.4
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Command Line Interface API

USES=	horde
USE_HORDE_RUN=	Horde_Support Horde_Translation

.include <bsd.port.mk>
