# Created by: Alexander Logvinov <avl@FreeBSD.org>
# $FreeBSD: head/net/remmina-plugin-xdmcp/Makefile 478203 2018-08-27 13:05:13Z woodsb02 $

PKGNAMESUFFIX=	-xdmcp

COMMENT=	Remmina plugin for XDMCP protocol

RUN_DEPENDS=	Xephyr:x11-servers/xephyr

USE_GNOME+=	cairo

MASTERDIR=	${.CURDIR}/../remmina-plugins

.include "${MASTERDIR}/Makefile"
