# $FreeBSD: head/x11-themes/qtcurve-kde4/Makefile 439367 2017-04-25 08:20:30Z riggs $

PORTNAME=	qtcurve
PORTREVISION=	1

COMMENT=	QtCurve KDE 4 widget style and window decoration

QTCURVE_SLAVE=	kde4

MASTERDIR=	${.CURDIR}/../qtcurve

.include "${MASTERDIR}/Makefile"
