# Created by: mat
# $FreeBSD: head/www/p5-Template-Alloy/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Template-Alloy
PORTVERSION=	1.020
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:RHANDOM
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Mixing of all of the major template systems

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
