# Created by: Johannes Meixner <johannes@perceivon.net>
# $FreeBSD: head/textproc/rubygem-version_sorter/Makefile 461630 2018-02-12 19:04:38Z sunpoet $

PORTNAME=	version_sorter
PORTVERSION=	2.2.4
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Fast sorting of version strings

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
