# Created by: vanilla
# $FreeBSD: head/devel/mq4cpp/Makefile 459156 2018-01-16 06:14:58Z vanilla $

PORTNAME=	mq4cpp
PORTVERSION=	1.16
PORTREVISION=	3
CATEGORIES=	devel
MASTER_SITES=	http://www.sixtyfourbit.org/Download/

MAINTAINER=	vanilla@FreeBSD.org
COMMENT=	Message Queuing for C++

OPTIONS_DEFINE=	DOCS

USE_LDCONFIG=	yes
USES=		dos2unix libtool pathfix pkgconfig tar:bzip2
GNU_CONFIGURE=	yes
USE_CXXSTD=	c++98

.include <bsd.port.mk>
