# $FreeBSD: head/textproc/hs-uri-bytestring/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	uri-bytestring
PORTVERSION=	0.3.1.1
PORTREVISION=	1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell URI parsing as ByteStrings

LICENSE=	BSD3CLAUSE

USE_CABAL=	attoparsec blaze-builder th-lift th-lift-instances

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
