# $FreeBSD: head/textproc/hs-uri-bytestring/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	uri-bytestring
PORTVERSION=	0.3.1.1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell URI parsing as ByteStrings

LICENSE=	BSD3CLAUSE

USE_CABAL=	attoparsec blaze-builder th-lift th-lift-instances

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
