# Created by: Robert Gogolok <gogo@cs.uni-sb.de>
# $FreeBSD: head/sysutils/rubygem-bundler/Makefile 480297 2018-09-21 18:08:34Z sunpoet $

PORTNAME=	bundler
PORTVERSION=	1.16.5
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Tool that manages gem dependencies for ruby applications

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.md

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

PLIST_FILES=	bin/bundle bin/bundler

.include <bsd.port.mk>
