# $FreeBSD: head/x11-drivers/xf86-video-i740/Makefile 476013 2018-07-31 18:41:30Z zeising $

PORTNAME=	xf86-video-i740
PORTVERSION=	1.3.6
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org i740 display driver

XORG_CAT=	driver

.include <bsd.port.mk>
