# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/math/p5-Text-AsciiTeX/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Text-AsciiTeX
PORTVERSION=	0.05
PORTREVISION=	2
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Convert (La)TeX formulas to ASCII art

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
