# $FreeBSD: head/devel/hs-test-framework-hunit/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	test-framework-hunit
PORTVERSION=	0.3.0.2
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	HUnit support for the test-framework package

LICENSE=	BSD3CLAUSE

USE_CABAL=	extensible-exceptions HUnit test-framework

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
