# Created by: Martin Matuska <martin@matuska.org>
# $FreeBSD: head/devel/pth-hard/Makefile 342606 2014-02-04 20:45:48Z antoine $

PKGNAMESUFFIX=	-hard

CONFLICTS=	pth-2.*

MASTERDIR=	${.CURDIR}/../pth

.include "${MASTERDIR}/Makefile"
