# $FreeBSD: head/textproc/hs-cmark-gfm/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	cmark-gfm
PORTVERSION=	0.1.3
PORTREVISION=	2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast, accurate GitHub Flavored Markdown parser and renderer

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
