# $FreeBSD: head/textproc/hs-magic/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	magic
PORTVERSION=	1.1
PORTREVISION=	3
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Interface to C file/magic library

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
