# $FreeBSD: head/devel/rubygem-powerpack/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	powerpack
PORTVERSION=	0.1.1
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Extensions to core Ruby classes

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
