# Created by: Mark Felder <feld@FreeBSD.org>
# $FreeBSD: head/math/py-intspan/Makefile 483103 2018-10-27 02:52:14Z swills $

PORTNAME=	intspan
PORTVERSION=	1.5.14
CATEGORIES=	math python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	FInite element Automatic Tabulator

LICENSE=	APACHE20

USES=		python zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
