# Created by: Mark Felder <feld@FreeBSD.org>
# $FreeBSD: head/math/py-intspan/Makefile 483523 2018-10-30 19:54:04Z sunpoet $

PORTNAME=	intspan
PORTVERSION=	1.5.14
CATEGORIES=	math python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Finite element automatic tabulator

LICENSE=	APACHE20

USES=		python zip
USE_PYTHON=	autoplist concurrent distutils

NO_ARCH=	yes

.include <bsd.port.mk>
