# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: head/math/p5-Statistics-Basic/Makefile 481603 2018-10-09 06:13:08Z wen $

PORTNAME=	Statistics-Basic
PORTVERSION=	1.6611
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Collection of basic statistics modules

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Number-Format>=1.61:textproc/p5-Number-Format

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
