# Created by: mat
# $FreeBSD: head/devel/p5-Class-Accessor-Chained/Makefile 463191 2018-02-28 09:03:02Z amdmi3 $

PORTNAME=	Class-Accessor-Chained
PORTVERSION=	0.01
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Make chained accessors

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

RUN_DEPENDS=	p5-Class-Accessor>=0:devel/p5-Class-Accessor
BUILD_DEPENDS=	${RUN_DEPENDS}

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
