# Created by: Martin Matuska <martin@matuska.org>
# $FreeBSD: head/databases/luasql-odbc/Makefile 416804 2016-06-12 15:05:12Z vanilla $

LUASQL_DRIVER=	odbc

MASTERDIR=	${.CURDIR}/../luasql-mysql

.include "${MASTERDIR}/Makefile"
