# Created by: Chin-San Huang <chinsan.tw@gmail.com>
# $FreeBSD: head/archivers/pecl-rar/Makefile 460318 2018-01-29 18:07:03Z joneum $

PORTNAME=	rar
PORTVERSION=	4.0.0
CATEGORIES=	archivers pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PECL extension to create and read RAR files

LICENSE=	PHP301

USES=		php:pecl
USE_PHP=	spl:build

CONFIGURE_ARGS=	--enable-rar

.include <bsd.port.mk>
