# $FreeBSD: head/x11-toolkits/rubygem-vte/Makefile 474173 2018-07-08 10:34:36Z miwi $

PORTNAME=	vte
PORTVERSION=	3.2.7
CATEGORIES=	x11-toolkits rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby binding for VTE

LICENSE=	LGPL21+

RUN_DEPENDS=	rubygem-gtk2>=${PORTVERSION}:x11-toolkits/rubygem-gtk2

USE_GNOME=	vte
USE_RUBY=	yes
USES=		gem gnome

.include <bsd.port.mk>
