# Created by: Michael Moll <kvedulv at kvedulv.de>
# $FreeBSD: head/devel/rubygem-equalizer/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	equalizer
PORTVERSION=	0.0.11
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby library to define equality methods

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
