# Created by: clsung@dragon2.net
# $FreeBSD: head/textproc/p5-RTF-Writer/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	RTF-Writer
PORTVERSION=	1.11
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module for generating documents in Rich Text Format

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Image-Size>=0:graphics/p5-Image-Size

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
