# $FreeBSD: head/security/py-pyaes/Makefile 450257 2017-09-21 13:10:09Z jrm $

PORTNAME=	pyaes
PORTVERSION=	1.6.1
CATEGORIES=	security python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jrm@FreeBSD.org
COMMENT=	Pure-Python implementation of AES block-cipher

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
