# $FreeBSD: head/security/py-pyaes/Makefile 436753 2017-03-23 02:33:45Z jrm $

PORTNAME=	pyaes
PORTVERSION=	1.6.0
CATEGORIES=	security python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jrm@FreeBSD.org
COMMENT=	Pure-Python implementation of AES block-cipher

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
