# $FreeBSD: head/security/py-pyaes/Makefile 455210 2017-11-30 15:50:30Z mat $

PORTNAME=	pyaes
PORTVERSION=	1.6.1
CATEGORIES=	security python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jrm@FreeBSD.org
COMMENT=	Pure-Python implementation of AES block-cipher

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
