# $FreeBSD: head/devel/hs-blaze-builder/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	blaze-builder
PORTVERSION=	0.4.1.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Efficient buffered output

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
