# $FreeBSD: head/devel/hs-DrIFT/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	DrIFT
PORTVERSION=	2.4.2
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Program to derive type class instances

LICENSE=	BSD3CLAUSE

USE_CABAL=	old-time random

EXECUTABLE=	DrIFT drift-ghc

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
