# Created by: Alex Miller (<asm@asm.kiev.ua>)
# $FreeBSD: head/www/pear-HTTP_Session2/Makefile 441000 2017-05-16 13:37:51Z joneum $

PORTNAME=	HTTP_Session2
PORTVERSION=	0.7.3
CATEGORIES=	www devel pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PHP5 Session Handler

LICENSE=	BSD3CLAUSE

USES=		dos2unix pear
NO_ARCH=	yes

.include <bsd.port.mk>
