# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-gmp/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	gmp
DISTVERSION=	0.5-13.1
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Multiple Precision Arithmetic

LICENSE=	GPLv2+

LIB_DEPENDS=	libgmp.so:math/gmp

USES=	cran:auto-plist,compiles

.include <bsd.port.mk>
