# Created by: Oliver Lehmann <oliver@FreeBSD.org>
# $FreeBSD: head/security/courier-authlib-base/Makefile 481732 2018-10-10 11:54:58Z madpilot $

PORTREVISION=	0
PKGNAMESUFFIX=	-base

COMMENT=	Courier authentication library base
CATEGORIES=	security mail

MASTERDIR=	${.CURDIR}/../../security/courier-authlib

USE_LDCONFIG=	${PREFIX}/lib/${PORTNAME}

.include "${MASTERDIR}/Makefile"
