# $FreeBSD: head/audio/gstreamer1-plugins-cdparanoia/Makefile 405242 2016-01-04 14:21:56Z kwm $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	GStreamer CDDA extraction (aka audio ripping) plugin

GST_PLUGIN=	cdparanoia
DIST=		base

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
