# Created by: Thierry Thomas (<thierry@pompo.net>)
# $FreeBSD: head/net/pear-Net_Socket/Makefile 443292 2017-06-11 07:42:25Z sunpoet $

PORTNAME=	Net_Socket
PORTVERSION=	1.0.14
CATEGORIES=	net www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR Network Socket Interface

USES=		pear

.include <bsd.port.mk>
