# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/converters/R-cran-RJSONIO/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	RJSONIO
DISTVERSION=	1.3-1.1
PORTREVISION=	1
CATEGORIES=	converters
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Serialize R objects to JSON, JavaScript Object Notation

LICENSE=	BSD3CLAUSE

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
