# $FreeBSD: head/sysutils/hs-mountpoints/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	mountpoints
PORTVERSION=	1.0.2
PORTREVISION=	2
CATEGORIES=	sysutils haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	List mount points

LICENSE=	LGPL21

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
