# $FreeBSD: head/www/p5-HTML5-DOM/Makefile 471026 2018-05-28 07:52:26Z wen $

PORTNAME=		HTML5-DOM
PORTVERSION=	1.07
CATEGORIES=		www perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ZHUMARIN
PKGNAMEPREFIX=	p5-

MAINTAINER=		wen@FreeBSD.org
COMMENT=		Super fast html5 DOM library with css selectors

LICENSE=		MIT

USES=			perl5
USE_PERL5=		configure

.include <bsd.port.mk>
