# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/net/pear-Horde_Url/Makefile 407900 2016-02-02 22:56:26Z mm $

PORTNAME=	Horde_Url
PORTVERSION=	2.2.5
CATEGORIES=	net www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde URL class

USES=	horde
USE_HORDE_RUN=	Horde_Exception

.include <bsd.port.mk>
