# Created by: Kaspars Bankovskis <kaspars@bankovskis.lv>
# $FreeBSD: head/textproc/hs-csv/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	csv
PORTVERSION=	0.1.2
PORTREVISION=	17
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	CSV library for Haskell

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
