# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: head/multimedia/gstreamer-plugins-x264/Makefile 457488 2017-12-29 02:55:42Z jbeich $
#   $MCom: ports/multimedia/gstreamer-plugins-x264/Makefile,v 1.3 2008/03/19 14:05:37 ahze Exp $

PORTREVISION=	7
CATEGORIES=	multimedia

COMMENT=	Gstreamer x264 plugin

GST_PLUGIN=	x264

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
