# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: head/multimedia/gstreamer-plugins-x264/Makefile 422672 2016-09-23 13:14:29Z jbeich $
#   $MCom: ports/multimedia/gstreamer-plugins-x264/Makefile,v 1.3 2008/03/19 14:05:37 ahze Exp $

PORTREVISION=	6
CATEGORIES=	multimedia

COMMENT=	Gstreamer x264 plugin

GST_PLUGIN=	x264

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
