# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-DEoptimR/Makefile 449533 2017-09-10 10:58:13Z tota $

PORTNAME=	DEoptimR
DISTVERSION=	1.0-8
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Differential Evolution Optimization in Pure R

LICENSE=	GPLv2+

USES=		cran:auto-plist

.include <bsd.port.mk>
