# Created by: Jon Nistor <nistor@snickers.org>
# $FreeBSD: head/devel/p5-Data-Structure-Util/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	Data-Structure-Util
PORTVERSION=	0.16
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	nistor@snickers.org
COMMENT=	Perl5 module to change the nature of data within a structure

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-Pod>=0:devel/p5-Test-Pod

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
