# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/irc/pear-Net_SmartIRC/Makefile 445661 2017-07-13 16:14:25Z joneum $

PORTNAME=	Net_SmartIRC
PORTVERSION=	1.1.11
CATEGORIES=	irc www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR class for communication with IRC networks

LICENSE=	LGPL21
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		pear

.include <bsd.port.mk>
