# Created by: Tom Judge <tj@FreeBSD.org>
# $FreeBSD: head/www/p5-Dancer-Plugin-FlashMessage/Makefile 484353 2018-11-06 21:13:54Z rene $

PORTNAME=	Dancer-Plugin-FlashMessage
PORTVERSION=	0.314
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Dancer plugin for implementing Flash Messages

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Dancer>=1.2001:www/p5-Dancer

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
