# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/security/php70-hash/Makefile 422569 2016-09-21 15:43:47Z tz $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php70

PKGNAMESUFFIX=	-hash

.include "${MASTERDIR}/Makefile"
