# Created by: Alexey V. Degtyarev <alexey@renatasystems.org>
# $FreeBSD: head/devel/rubygem-unicode/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	unicode
PORTVERSION=	0.4.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	alexey@renatasystems.org
COMMENT=	Unicode string manipulation library for Ruby

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
