# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: head/audio/gstreamer-plugins-shout2/Makefile 428152 2016-12-08 19:52:19Z tijl $
#   $MCom: ports/audio/gstreamer-plugins-shout2/Makefile,v 1.3 2008/03/19 14:05:31 ahze Exp $

PORTREVISION=	3
CATEGORIES=	audio

COMMENT=	Gstreamer icecast plugin

GST_PLUGIN=	shout2

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
