# Created by: Tom Judge <tj@FreeBSD.org>
# $FreeBSD: head/devel/py-statsd/Makefile 484959 2018-11-14 21:44:28Z sunpoet $

PORTNAME=	statsd
PORTVERSION=	3.3.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	python@FreeBSD.org
COMMENT=	Simple statsd client

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	autoplist concurrent distutils

NO_ARCH=	yes

.include <bsd.port.mk>
