# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/math/R-cran-Matching/Makefile 469989 2018-05-15 02:49:50Z wen $

PORTNAME=	Matching
DISTVERSION=	4.9-3
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Multivariate and Propensity Score Matching with Balance Optimization

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
