# Created by: Olivier Duchateau <duchateau.olivier@gmail.com>
# $FreeBSD: head/security/py-certifi/Makefile 442826 2017-06-07 10:49:23Z koobs $

PORTNAME=	certifi
PORTVERSION=	2017.4.17
CATEGORIES=	security python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	python@FreeBSD.org
COMMENT=	Mozilla SSL certificates

LICENSE=	ISCL

NO_ARCH=	yes
USES?=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
