# Created by: Olivier Duchateau <duchateau.olivier@gmail.com>
# $FreeBSD: head/security/py-certifi/Makefile 449725 2017-09-12 20:56:43Z sunpoet $

PORTNAME=	certifi
PORTVERSION=	2017.7.27.1
CATEGORIES=	security python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	python@FreeBSD.org
COMMENT=	Mozilla SSL certificates

LICENSE=	MPL20

NO_ARCH=	yes
USES?=		python
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
