# Created by: Tim Bishop <tdb@FreeBSD.org>
# $FreeBSD: head/sysutils/puppet-lint/Makefile 447486 2017-08-07 09:18:58Z tdb $

PORTNAME=	puppet-lint
PORTVERSION=	2.3.0
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	puppet@FreeBSD.org
COMMENT=	Checks Puppet manifests against the style guide

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_RUBY=	yes
USES=		gem
PLIST_FILES=	bin/puppet-lint
NO_ARCH=	yes

.include <bsd.port.mk>
