# Created by: Ju Pengfei <jupengfei@gmail.com>
# $FreeBSD: head/ftp/py-tftpy/Makefile 479780 2018-09-14 20:36:03Z sunpoet $

PORTNAME=	tftpy
PORTVERSION=	0.8.0
CATEGORIES=	ftp python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Pure Python TFTP library

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		python
USE_PYTHON=	autoplist concurrent distutils

NO_ARCH=	yes

.include <bsd.port.mk>
