# Created by: wen@FreeBSD.org
# $FreeBSD: head/databases/pymongo/Makefile 425317 2016-11-04 12:17:54Z wg $

PORTNAME=	pymongo
PORTVERSION=	3.3.1
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Python driver for MongoDB

LICENSE=	APACHE20

CONFLICTS_INSTALL=	py[0-9][0-9]-pymongo28

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
