# Created by: rpsfa@rit.edu
# $FreeBSD: head/devel/rubygem-simple_form/Makefile 441146 2017-05-18 11:44:01Z jrm $

PORTNAME=	simple_form
PORTVERSION=	3.5.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Forms made easy

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

RUN_DEPENDS=	rubygem-activemodel4>=4:databases/rubygem-activemodel4 \
		rubygem-actionpack4>=4:www/rubygem-actionpack4

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
