# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-pkg-config/Makefile 452555 2017-10-20 20:44:42Z sunpoet $

PORTNAME=	pkg-config
PORTVERSION=	1.2.8
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	pkg-config implementation for Ruby

LICENSE=	LGPL21+
LICENSE_FILE=	${WRKSRC}/LGPL-2.1

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem pkgconfig

.include <bsd.port.mk>
