# Created by: Koichiro IWAO <meta+ports@vmeta.jp>
# $FreeBSD: head/japanese/uim-mozc/Makefile 494682 2019-03-05 07:05:53Z hrs $

PKGNAMEPREFIX=	ja-uim-

COMMENT=	Mozc engine for uim

MASTERDIR=	${.CURDIR}/../../japanese/mozc-server
FILESDIR=	${.CURDIR}/files
DATADIR=	${PREFIX}/share/uim
SUB_FILES=	pkg-message

BUILD_MOZC_LIST=uim_mozc

.include "${MASTERDIR}/Makefile"
