# Created by: Thierry Thomas (<thierry@FreeBSD.org>)
# $FreeBSD: head/net/pear-Net_DIME/Makefile 443278 2017-06-11 07:41:17Z sunpoet $

PORTNAME=	Net_DIME
PORTVERSION=	1.0.2
PORTEPOCH=	1
CATEGORIES=	net pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	The PEAR::Net_DIME class implements DIME encoding

USES=		pear

.include <bsd.port.mk>
