# $FreeBSD: head/x11/sessreg/Makefile 435109 2017-02-28 22:54:12Z rezny $

PORTNAME=	sessreg
PORTVERSION=	1.1.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Manage utmp/wtmp entries for non-init X clients

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	x11

PLIST_FILES=	bin/sessreg man/man1/sessreg.1.gz

.include <bsd.port.mk>
