# Created by: Shaun Amott <shaun@FreeBSD.org>
# $FreeBSD: head/devel/py-kaitaistruct/Makefile 478168 2018-08-26 20:37:59Z shaun $

PORTNAME=	kaitaistruct
PORTVERSION=	0.8
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	shaun@FreeBSD.org
COMMENT=	Kaitai Struct declarative parser generator for binary data

LICENSE=	MIT

USES?=		python
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
