# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/misc/kde4-l10n-kk/Makefile 439367 2017-04-25 08:20:30Z riggs $

PORTNAME=	kde-l10n
PORTVERSION=	${KDE4_VERSION}
PORTREVISION=	1
CATEGORIES=	misc kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Kazakh messages and documentation for KDE SC 4

KDE4_L10N=	kk

.include "${.CURDIR}/../kde4-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
