# Created by: Johannes Meixner <xmj@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-rails-deprecated_sanitizer-rails5/Makefile 439897 2017-05-01 13:42:41Z jrm $

PORTNAME=	rails-deprecated_sanitizer
PORTVERSION=	1.0.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	-rails5

MAINTAINER=	jrm@FreeBSD.org
COMMENT=	Deprecated sanitizer API extracted from Action View

LICENSE=	MIT

RUN_DEPENDS=	rubygem-activesupport5>0:devel/rubygem-activesupport5

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
