# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libXfixes/Makefile 479538 2018-09-11 18:34:27Z zeising $

PORTNAME=	libXfixes
PORTVERSION=	5.0.3
PORTREVISION=	2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Fixes extension library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 xorgproto
USES+=	cpe
CPE_PRODUCT=	libxfixes
CPE_VENDOR=	x

.include <bsd.port.mk>
