# Created by: Eric Schnoebelen <eric@cirr.com>
# $FreeBSD: head/devel/p5-Getopt-ArgvFile/Makefile 487965 2018-12-21 09:00:16Z amdmi3 $

PORTNAME=	Getopt-ArgvFile
PORTVERSION=	1.11
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module for processing argument vectors

LICENSE=	ART10

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
