# Created by: Tom Judge <tom@tomjudge.com>
# $FreeBSD: head/security/rubygem-razorback-scriptNugget/Makefile 432064 2017-01-21 17:29:23Z sunpoet $

PORTNAME=	razorback-scriptNugget
PORTVERSION=	0.5.0
PORTREVISION=	1
CATEGORIES=	security rubygems
MASTER_SITES=	SF/razorbacktm/Bindings
DISTNAME=	scriptNugget-ruby-${PORTVERSION}

MAINTAINER=	tj@FreeBSD.org
COMMENT=	Framework for an intelligence driven security - Script Nugget Ruby

NO_ARCH=	yes
USE_RUBY=		yes
USES=		gem shebangfix
SHEBANG_FILES=	lib/razorback.rb

.include <bsd.port.mk>
