# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-spData/Makefile 479978 2018-09-18 06:52:59Z tota $

PORTNAME=	spData
PORTVERSION=	0.2.9.4
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Datasets for Spatial Analysis

LICENSE=	CC0-1.0

USES=		cran:auto-plist

.include <bsd.port.mk>
