# $FreeBSD: head/textproc/rubygem-case_transform/Makefile 447386 2017-08-05 03:25:17Z jrm $

PORTNAME=	case_transform
PORTVERSION=	0.2
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Extraction of the key_transform abilities of ActiveModelSerializers

LICENSE=	MIT

RUN_DEPENDS=	rubygem-activesupport5>0:devel/rubygem-activesupport5

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
