# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libXxf86misc/Makefile 479538 2018-09-11 18:34:27Z zeising $

PORTNAME=	libXxf86misc
PORTVERSION=	1.0.4
PORTREVISION=	2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X XF86-Misc Extension

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 xext xorgproto

.include <bsd.port.mk>
