# Created by: Philip Paeps <philip@FreeBSD.org>
# $FreeBSD: head/devel/py3-click/Makefile 422784 2016-09-26 17:34:19Z philip $

MASTERDIR=	${.CURDIR}/../py-click

USES=		python:3.2+

.include "${MASTERDIR}/Makefile"
