# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-rack-mini-profiler/Makefile 441544 2017-05-23 18:52:14Z sunpoet $

PORTNAME=	rack-mini-profiler
PORTVERSION=	0.10.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Profiles loading speed for rack applications

LICENSE=	MIT

RUN_DEPENDS=	rubygem-rack>=1.2.0:www/rubygem-rack

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
