# $FreeBSD: head/devel/cx_Freeze/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	cx_Freeze
PORTVERSION=	4.3.3
PORTREVISION=	5
CATEGORIES=	devel python
MASTER_SITES=	SF/cx-freeze/${PORTVERSION}

MAINTAINER=	araujo@FreeBSD.org
COMMENT=	The cx_Freeze is a set of utilities for freezing Python scripts

USE_GCC=	yes
USES=		python:2.7
USE_PYTHON=	distutils

.include <bsd.port.mk>
