# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/net/rubygem-http_parser.rb/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	http_parser.rb
PORTVERSION=	0.6.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Simple callback-based HTTP request/response parser

LICENSE=	MIT

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
