# Created by: Palle Girgensohn <girgen@partitur.se>
# $FreeBSD: head/databases/postgresql10-plperl/Makefile 447680 2017-08-10 14:23:31Z girgen $

WANT_PGSQL_VER=	10

.include "${.CURDIR}/../postgresql95-plperl/Makefile"
