# $FreeBSD: head/devel/hs-prelude-extras/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	prelude-extras
PORTVERSION=	0.4.0.3
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Higher-order versions of Prelude classes

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
