# Created by: James Raftery <james@now.ie>
# $FreeBSD: head/textproc/p5-Text-Netstring/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Text-Netstring
PORTVERSION=	0.07
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	james@now.ie
COMMENT=	Perl module to create and manipulate netstring encoded strings

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
