# Created by: Torsten Zuhlsdorff <ports@toco-domains.de>
# $FreeBSD: head/devel/rubygem-ice_cube/Makefile 445524 2017-07-11 17:00:52Z sunpoet $

PORTNAME=	ice_cube
PORTVERSION=	0.16.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Recurring date library for Ruby

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
