# $FreeBSD: head/devel/statik/Makefile 413776 2016-04-22 12:40:04Z mat $

PORTNAME=	statik
PORTVERSION=	20141209
CATEGORIES=	devel

MAINTAINER=	cheffo@freebsd-bg.org
COMMENT=	Embed static files into a Go executable

LICENSE=	APACHE20

ONLY_FOR_ARCHS=	i386 amd64

USES=		go
USE_GITHUB=	yes
GH_ACCOUNT=	rakyll
GH_TAGNAME=	4a16c83

.include <bsd.port.mk>
