# Created by: John Chen <johnpupu@gmail.com>
# $FreeBSD: head/devel/pecl-yaconf/Makefile 489349 2019-01-05 15:47:56Z rene $

PORTNAME=	yaconf
DISTVERSION=	1.0.7
CATEGORIES=	devel

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PHP Persistent Configurations Container

LICENSE=	PHP301
LICENSE_FILE=	${WRKSRC}/LICENSE

IGNORE_WITH_PHP= 73
USES=		php:pecl

.include <bsd.port.mk>
