# Created by: John Chen <johnpupu@gmail.com>
# $FreeBSD: head/devel/pecl-yaconf/Makefile 481878 2018-10-12 06:23:47Z antoine $

PORTNAME=	yaconf
DISTVERSION=	1.0.7
CATEGORIES=	devel

MAINTAINER=	johnpupu@gmail.com
COMMENT=	PHP Persistent Configurations Container

LICENSE=	PHP301
LICENSE_FILE=	${WRKSRC}/LICENSE

IGNORE_WITH_PHP= 56 73
USES=		php:pecl

.include <bsd.port.mk>
