# Created by: John Chen <johnpupu@gmail.com>
# $FreeBSD: head/devel/pecl-yaconf/Makefile 456296 2017-12-14 13:57:28Z tz $

PORTNAME=	yaconf
PORTVERSION=	1.0.5
CATEGORIES=	devel

MAINTAINER=	johnpupu@gmail.com
COMMENT=	PHP Persistent Configurations Container

LICENSE=	PHP301
LICENSE_FILE=	${WRKSRC}/LICENSE

IGNORE_WITH_PHP=56 72
USES=		php:pecl

.include <bsd.port.mk>
