# Created by: gahr
# $FreeBSD: head/x11/ooxcb/Makefile 455210 2017-11-30 15:50:30Z mat $

PORTNAME=	ooxcb
PORTVERSION=	1.2
CATEGORIES=	x11
MASTER_SITES=	CHEESESHOP

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Python binding to the X server using xcb

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes

USES=		python:2.7
USE_PYTHON=	distutils autoplist
USE_XORG=	xcb

.include <bsd.port.mk>
