# $FreeBSD: head/www/py-flup6/Makefile 457300 2017-12-26 18:33:18Z lwhsu $

PORTNAME=	flup6
PORTVERSION=	1.1.1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	FreeBSD@Shaneware.biz
COMMENT=	Random assortment of WSGI servers

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
