# $FreeBSD: head/mail/p5-Email-MIME-ContentType/Makefile 439325 2017-04-24 15:20:49Z sunpoet $

PORTNAME=	Email-MIME-ContentType
PORTVERSION=	1.018
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Parse a MIME Content-Type Header

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
