# Created by: Neil Booth
# $FreeBSD: head/net/py3-pysocks/Makefile 451356 2017-10-06 07:59:42Z ak $

MASTERDIR=	${.CURDIR}/../py-pysocks

PORTSCOUT=	ignore:1

USES=		python:3.3+

.include "${MASTERDIR}/Makefile"
