# Created by: Neil Booth
# $FreeBSD: head/net/py3-pysocks/Makefile 446898 2017-07-29 19:26:41Z sunpoet $

MASTERDIR=	${.CURDIR}/../py-pysocks

PORTSCOUT=	ignore:1

USES=		python:3.3+

.include "${MASTERDIR}/Makefile"

