# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: head/mail/rubygem-pony/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	pony
PORTVERSION=	1.11
CATEGORIES=	mail rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Express way to send mail from Ruby

LICENSE=	MIT

RUN_DEPENDS=	rubygem-mail>=2.0:mail/rubygem-mail

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
