# $FreeBSD: head/databases/qt5-sqldrivers-ibase/Makefile 490472 2019-01-16 11:13:44Z tijl $

PORTREVISION=	1

DB=		IBase
DB_DESC=	InterBase/Firebird

USES=		firebird

ONLY_FOR_ARCHS=	i386 amd64

.include "${.CURDIR:H:H}/devel/qt5/Makefile.sqldrivers"
