# $FreeBSD: head/databases/qt5-sqldrivers-ibase/Makefile 468288 2018-04-25 18:40:14Z acm $

PORTREVISION=	1

DB=		IBase
DB_DESC=	InterBase/Firebird

USES=		firebird

ONLY_FOR_ARCHS=	i386 amd64

.include "${.CURDIR:H:H}/devel/qt5/Makefile.sqldrivers"
