# $FreeBSD$

PORTNAME=	omniauth-kerberos
PORTVERSION=	0.3.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	tz@FreeBSD.org
COMMENT=	An OmniAuth strategy for Kerberos

LICENSE=	MIT

RUN_DEPENDS=	rubygem-omniauth-multipassword>0:security/rubygem-omniauth-multipassword \
		rubygem-timfel-krb5-auth>=0.8:security/rubygem-timfel-krb5

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
