# Created by: Johannes Meixner <johannes@perceivon.net>
# $FreeBSD: head/devel/rubygem-slack-notifier/Makefile 444596 2017-06-28 15:43:44Z sunpoet $

PORTNAME=	slack-notifier
PORTVERSION=	2.2.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby wrapper for posting to slack webhooks

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
