# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/mail/pear-Contact_Vcard_Parse/Makefile 443264 2017-06-11 07:40:10Z sunpoet $

PORTNAME=	Contact_Vcard_Parse
PORTVERSION=	1.32.0
CATEGORIES=	mail www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR class to parse vCard 2.1 and 3.0 files

USES=		pear

.include <bsd.port.mk>
