# $FreeBSD: head/databases/py-unqlite/Makefile 455210 2017-11-30 15:50:30Z mat $

PORTNAME=	unqlite
PORTVERSION=	0.5.3
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Fast Python bindings for the UnQLite embedded NoSQL database

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist cython

.include <bsd.port.mk>
