# Created by: Yuri Victorovich <yuri@rawbw.com>
# $FreeBSD: head/net/py-txrestapi/Makefile 462887 2018-02-25 00:40:37Z yuri $

PORTNAME=	txrestapi
PORTVERSION=	0.2
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	yuri@FreeBSD.org
COMMENT=	Easing the creation of REST API services in Python

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
