# $FreeBSD: head/misc/elixir-uuid/Makefile 436138 2017-03-14 09:20:49Z olgeni $

PORTNAME=	elixir-uuid
PORTVERSION=	1.1.7
DISTVERSIONPREFIX=	v
CATEGORIES=	misc

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	UUID generator and utilities for Elixir

LICENSE=	APACHE20

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	zyro

ELIXIR_APP_NAME=uuid

.include <bsd.port.mk>
