# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-polyglot/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	polyglot
PORTVERSION=	0.3.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Provides a registry of file types

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
