# Created by: mike@LITech.lviv.ua
# $FreeBSD: head/ukrainian/webalizer/Makefile 412349 2016-04-01 14:25:16Z mat $

MASTERDIR=	${.CURDIR}/../../www/webalizer
CATEGORIES=	ukrainian

MAINTAINER=	mikef@LITech.lviv.ua

LIB_DEPENDS=	libgd.so:ukrainian/gd

WEBALIZER_LANG=	ukrainian

.include "${MASTERDIR}/Makefile"
