# $FreeBSD: head/net/hs-hostname/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	hostname
PORTVERSION=	1.0
PORTREVISION=	17
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cross-platform means of determining the hostname

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
