# $FreeBSD: head/net/hs-hostname/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	hostname
PORTVERSION=	1.0
PORTREVISION=	18
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cross-platform means of determining the hostname

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
