# $FreeBSD: head/multimedia/bcmatroska2/Makefile 488341 2018-12-25 20:25:39Z tcberner $

PORTNAME=	bcmatroska2
PORTVERSION=	0.23
CATEGORIES=	multimedia
MASTER_SITES=	https://www.linphone.org/releases/sources/bcmatroska2/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Belledonne Communications Matroska media container support

USES=		cmake
USE_LDCONFIG=	yes

CMAKE_ARGS=	-DENABLE_STATIC=NO

.include <bsd.port.mk>
