# Created by: rpsfa@rit.edu
# $FreeBSD: head/devel/rubygem-require_all/Makefile 463908 2018-03-08 15:39:03Z sunpoet $

PORTNAME=	require_all
PORTVERSION=	2.0.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Wonderfully simple way to load your code

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
