# $FreeBSD: head/x11-themes/qtcurve-gtk2/Makefile 424491 2016-10-22 23:20:21Z jhale $

PORTNAME=	qtcurve
PORTREVISION=	1

COMMENT=	QtCurve GTK+ 2.x engine and theme

QTCURVE_SLAVE=	gtk2

MASTERDIR=	${.CURDIR}/../qtcurve

.include "${MASTERDIR}/Makefile"
