# Created by: tcberner
# $FreeBSD: head/devel/kf5-threadweaver/Makefile 449591 2017-09-10 20:55:38Z gerald $

PORTNAME=	threadweaver
PORTVERSION=	${KDE_FRAMEWORKS_VERSION}
PORTREVISION=	1
CATEGORIES=	devel kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KF5 addons to QtDBus

USES=		cmake:outsource compiler:c++11-lib kde:5 tar:xz
USE_KDE=	ecm
USE_QT5=	buildtools_build core network qmake_build testlib widgets xml

.include <bsd.port.mk>
