# $FreeBSD: head/x11-wm/rubygem-uh-layout/Makefile 457195 2017-12-24 20:00:41Z swills $

PORTNAME=	uh-layout
PORTVERSION=	0.5.2
CATEGORIES=	x11-wm rubygems
MASTER_SITES=	RG

MAINTAINER=	tj+freebsd_ports@a13.fr
COMMENT=	Tiling and stacking layout for uh-wm ruby gem

LICENSE=	BSD3CLAUSE

USE_RUBY=	yes
USES=		gem
NO_ARCH=	yes

.include <bsd.port.mk>
