# $FreeBSD: head/textproc/py-trans/Makefile 455210 2017-11-30 15:50:30Z mat $

PORTNAME=	trans
PORTVERSION=	2.0.1
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	d.pryadko@rambler-co.ru
COMMENT=	Module for performing transliteration

LICENSE=	BSD

USES=		python:2.7 tar:bzip2
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
