# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-notiffany/Makefile 427672 2016-12-03 19:31:05Z sunpoet $

PORTNAME=	notiffany
PORTVERSION=	0.1.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Single wrapper for most popular notification libraries

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

RUN_DEPENDS=	rubygem-nenv>=0.1:devel/rubygem-nenv \
		rubygem-shellany>=0:sysutils/rubygem-shellany

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
