# Created by: Clement Laforet <sheepkiller@cultdeadsheep.org>
# $FreeBSD: head/net/pear-Net_NNTP/Makefile 443286 2017-06-11 07:41:56Z sunpoet $

PORTNAME=	Net_NNTP
PORTVERSION=	1.5.0
PORTEPOCH=	1
CATEGORIES=	net news pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR implementation of the NNTP protocol

BUILD_DEPENDS=	${PEARDIR}/Net/Socket.php:net/pear-Net_Socket
RUN_DEPENDS=	${PEARDIR}/Net/Socket.php:net/pear-Net_Socket

USES=		pear

.include <bsd.port.mk>
