# $FreeBSD: head/ftp/p5-Net-FTP-Common/Makefile 444792 2017-06-30 22:13:50Z sunpoet $

PORTNAME=	Net-FTP-Common
PORTVERSION=	7.0.d
PORTREVISION=	2
CATEGORIES=	ftp perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl module to provide simplify common usages of Net::FTP

LICENSE=	MIT

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
