# Created by: Gerrit Beine <gerrit.beine@gmx.de>
# $FreeBSD: head/mail/squirrelmail-qmailadmin_login-plugin/Makefile 431402 2017-01-13 16:54:55Z mat $

PORTNAME=	qmailadmin_login
PORTVERSION=	1.1
PORTREVISION=	4
CATEGORIES=	mail www
DISTNAME=	${PORTNAME}-${PORTVERSION}-1.4.3

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Using the QmailAdmin cgi interface from SquirrelMail

RUN_DEPENDS=	${LOCALBASE}/www/cgi-bin.default/qmailadmin/qmailadmin:mail/qmailadmin

USE_GENERIC_PKGMESSAGE=	yes

.include "${.CURDIR}/../squirrelmail/bsd.squirrelmail.mk"
.include <bsd.port.mk>
