# $FreeBSD: head/devel/p5-Class-ErrorHandler/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Class-ErrorHandler
PORTVERSION=	0.04
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Base class for error handling

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
