# $FreeBSD: head/x11-drivers/xf86-video-ark/Makefile 479538 2018-09-11 18:34:27Z zeising $

PORTNAME=	xf86-video-ark
PORTVERSION=	0.7.5
PORTREVISION=	9
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org ark display driver

XORG_CAT=	driver

.include <bsd.port.mk>
