# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-pkgconfig/Makefile 477852 2018-08-23 04:18:00Z tota $

PORTNAME=	pkgconfig
PORTVERSION=	2.0.2
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Private Configuration for 'R' Packages

LICENSE=	MIT

USES=		cran:auto-plist

.include <bsd.port.mk>
