# Created by: Tom Judge <tj@FreeBSD.org>
# $FreeBSD: head/mail/py-email-reply-parser/Makefile 415063 2016-05-12 13:13:36Z mat $

PORTNAME=	email-reply-parser
PORTVERSION=	0.1.5
DISTVERSIONPREFIX=	v
CATEGORIES=	mail python
MASTER_SITES=	GH
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	tj@FreeBSD.org
COMMENT=	GitHubs Email Reply Parser library for python

USES=		python
USE_PYTHON=	distutils autoplist
USE_GITHUB=	yes
GH_ACCOUNT=	zapier

.include <bsd.port.mk>
