# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: head/net-mgmt/p5-Cisco-Reconfig/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Cisco-Reconfig
PORTVERSION=	0.912
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Parse and generate Cisco configuration files

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

NO_ARCH=	yes
USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
