# Created by: William Grzybowski <wg@FreeBSD.org>
# $FreeBSD: head/devel/py-more-itertools/Makefile 456990 2017-12-22 17:07:13Z yuri $

PORTNAME=	more-itertools
PORTVERSION=	4.0.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	More routines for operating on iterables, beyond itertools

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
