# $FreeBSD: head/devel/geany-plugin-geanypy/Makefile 456181 2017-12-12 18:35:32Z antoine $

PORTNAME=	geany-plugin-geanypy
PORTVERSION=	${GEANY_VER}
CATEGORIES=	devel

MAINTAINER=	madpilot@FreeBSD.org
COMMENT=	Geany plugin: ${${GEANY_PLUGIN}_DESC}

USES=		python:2.7
USE_GNOME=	pygtk2

.include "${.CURDIR}/../geany-plugins/files/Makefile.common"
.include <bsd.port.mk>
