# $FreeBSD: head/devel/geany-plugin-geanypy/Makefile 426874 2016-11-22 22:02:11Z antoine $

PORTNAME=	geany-plugin-geanypy
PORTVERSION=	${GEANY_VER}
CATEGORIES=	devel

MAINTAINER=	madpilot@FreeBSD.org
COMMENT=	Geany plugin: ${${GEANY_PLUGIN}_DESC}

USES=		python
USE_GNOME=	pygtk2

.include "${.CURDIR}/../geany-plugins/files/Makefile.common"
.include <bsd.port.mk>
