# Created by: Johannes Meixner <johannes@perceivon.net>
# $FreeBSD: head/devel/linux-c6-libpciaccess/Makefile 432937 2017-01-31 16:54:21Z tijl $

PORTNAME=	libpciaccess
PORTVERSION=	0.13.4
PORTREVISION=	2
CATEGORIES=	devel

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	Generic PCI access library (CentOS ${LINUX_DIST_VER})

DESCR=		${.CURDIR}/../${PORTNAME}/pkg-descr
RPMVERSION=	1.el6
USES=		linux:c6
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes

.include <bsd.port.mk>
