# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/graphics/R-cran-png/Makefile 443845 2017-06-18 18:09:16Z dbn $

PORTNAME=	png
DISTVERSION=	0.1-7
PORTREVISION=	4
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Read and write PNG images

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

LIB_DEPENDS=	libpng.so:graphics/png

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
