# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/graphics/R-cran-png/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	png
DISTVERSION=	0.1-7
PORTREVISION=	3
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Read and write PNG images

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

LIB_DEPENDS=	libpng.so:graphics/png

USES=	cran:auto-plist

.include <bsd.port.mk>
