# $FreeBSD: head/www/rubygem-jsobfu/Makefile 431905 2017-01-19 19:26:40Z sunpoet $

PORTNAME=	jsobfu
PORTVERSION=	0.4.2
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Javascript code obfuscator

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	rubygem-rkelly-remix>=0:www/rubygem-rkelly-remix

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

PLIST_FILES=	bin/jsobfu

.include <bsd.port.mk>
