# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/databases/py-dbf/Makefile 471337 2018-06-02 01:00:31Z wen $

PORTNAME=	dbf
PORTVERSION=	0.97.5
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Pure python package for reading/writing dbf files

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
