# Created by: Philip Paeps <philip@FreeBSD.org>
# $FreeBSD: head/math/p5-Roman/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Roman
PORTVERSION=	1.24
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	philip@FreeBSD.org
COMMENT=	Perl module to convert between Arabic and Roman numerals

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

PLIST_FILES=	%%SITE_PERL%%/Roman.pm \
		%%PERL5_MAN3%%/Roman.3.gz

.include <bsd.port.mk>
