# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/lang/hs-unlambda/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	unlambda
PORTVERSION=	0.1.4.2
PORTREVISION=	3
CATEGORIES=	lang haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unlambda interpreter

LICENSE=	GPLv2

USE_CABAL=	mtl

EXECUTABLE=	unlambda

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
