# $FreeBSD: head/x11-toolkits/rubygem-gtksourceview2/Makefile 445386 2017-07-09 07:00:27Z sunpoet $

PORTNAME=	gtksourceview2
PORTVERSION=	3.1.6
CATEGORIES=	x11-toolkits rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby binding for gtksourceview-2.x

LICENSE=	LGPL21+

RUN_DEPENDS=	rubygem-gtk2>=${PORTVERSION}:x11-toolkits/rubygem-gtk2

USE_GNOME=	gtksourceview2
USE_RUBY=	yes
USES=		gem gnome

.include <bsd.port.mk>
