# $FreeBSD: head/x11-toolkits/rubygem-gtksourceview2/Makefile 493301 2019-02-18 18:21:47Z sunpoet $

PORTNAME=	gtksourceview2
PORTVERSION=	3.3.2
CATEGORIES=	x11-toolkits rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby binding for gtksourceview-2.x

LICENSE=	LGPL21+

RUN_DEPENDS=	rubygem-gtk2>=${PORTVERSION}:x11-toolkits/rubygem-gtk2

USES=		gem gnome
USE_GNOME=	gtksourceview2
USE_RUBY=	yes

.include <bsd.port.mk>
