# Created by: Ryan Steinmetz <rpsfa@rit.edu>
# $FreeBSD: head/databases/rubygem-dm-observer/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	dm-observer
PORTVERSION=	1.2.0
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	DataMapper plugin for observing Resources

LICENSE=	MIT

RUN_DEPENDS=	rubygem-dm-core>=${PORTVERSION}:databases/rubygem-dm-core

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
