# $FreeBSD: head/math/R-cran-polynom/Makefile 478651 2018-09-01 02:25:22Z wen $

PORTNAME=	polynom
DISTVERSION=	1.3-9
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Functions to Implement a Class for Univariate Polynomial Manipulations

LICENSE=	GPLv2

USES=		cran:auto-plist

.include <bsd.port.mk>
