# Created by: Douglas Thrift <douglas@douglasthrift.net>
# $FreeBSD: head/converters/py-unidecode/Makefile 444859 2017-07-02 02:09:42Z wen $

PORTNAME=	unidecode
PORTVERSION=	0.04.21
CATEGORIES=	converters python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Unidecode-${PORTVERSION}

MAINTAINER=	douglas@douglasthrift.net
COMMENT=	ASCII transliterations of Unicode text

LICENSE=	GPLv2

USES=		python
USE_PYTHON=	distutils autoplist concurrent
NO_ARCH=	yes

.include <bsd.port.mk>
