# $FreeBSD: head/devel/rubygem-tilt/Makefile 436647 2017-03-21 20:40:06Z sunpoet $

PORTNAME=	tilt
PORTVERSION=	2.0.7
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Generic interface to multiple Ruby template engines

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

PLIST_FILES=	bin/tilt

.include <bsd.port.mk>
