# Created by: Jean-Yves Lefort <jylefort@brutele.be>
# $FreeBSD: head/games/xpilot-ng-client/Makefile 476013 2018-07-31 18:41:30Z zeising $

PORTREVISION=	5
PKGNAMESUFFIX=	-client

COMMENT=	Enhanced version of XPilot (client program)

MASTERDIR=	${.CURDIR}/../xpilot-ng-server

USE_XORG=	x11 xext xxf86misc
USE_GL=		gl

.include "${MASTERDIR}/Makefile"
