# Created by: Jean-Yves Lefort <jylefort@brutele.be>
# $FreeBSD: head/games/xpilot-ng-client/Makefile 480381 2018-09-22 12:49:01Z zeising $

PORTREVISION=	6
PKGNAMESUFFIX=	-client

COMMENT=	Enhanced version of XPilot (client program)

MASTERDIR=	${.CURDIR}/../xpilot-ng-server

USE_XORG=	x11 xext xxf86misc
USES=		gl

.include "${MASTERDIR}/Makefile"
