# Created by: Anes Mukhametov <anes@anes.su>
# $FreeBSD: head/textproc/p5-Text-Hyphen/Makefile 452736 2017-10-23 20:21:34Z swills $

PORTNAME=	Text-Hyphen
PORTVERSION=	0.2
PORTEPOCH=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	anes@anes.su
COMMENT=	Determine positions for hyphens inside words

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
