# $FreeBSD: head/www/rubygem-rails_stdout_logging/Makefile 447386 2017-08-05 03:25:17Z jrm $

PORTNAME=	rails_stdout_logging
PORTVERSION=	0.0.5
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Overrides Rails' built in logger to send all logs to stdout

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
