# $FreeBSD: head/devel/rubygem-strong_migrations/Makefile 482537 2018-10-20 14:52:09Z sunpoet $

PORTNAME=	strong_migrations
PORTVERSION=	0.3.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Catch unsafe migrations at dev time

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

RUN_DEPENDS=	rubygem-activerecord5>=3.2.0:databases/rubygem-activerecord5

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
