# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: head/devel/py-oletools/Makefile 429046 2016-12-21 06:48:39Z wen $

PORTNAME=	oletools
PORTVERSION=	0.50
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	python@FreeBSD.org
COMMENT=	Tools to analyze security characteristics of MS OLE2 files

USES=		python zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
