# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: head/www/p5-CGI-Simple/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	CGI-Simple
PORTVERSION=	1.115
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simple totally OO CGI interface that is CGI.pm compliant

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-IO-stringy>=0:devel/p5-IO-stringy

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
