# Created by: vanilla@
# $FreeBSD: head/devel/spdlog/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	spdlog
PORTVERSION=	1.2.1
PORTREVISION=	1
DISTVERSIONPREFIX=	v
CATEGORIES=	devel

MAINTAINER=	vanilla@FreeBSD.org
COMMENT=	Super fast C++ logging library

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	gabime

USES=		cmake compiler:c++11-lib pathfix

.include <bsd.port.mk>
