# Created by: vanilla@
# $FreeBSD: head/devel/spdlog/Makefile 481689 2018-10-10 03:54:52Z vanilla $

PORTNAME=	spdlog
PORTVERSION=	1.2.0
DISTVERSIONPREFIX=	v
CATEGORIES=	devel

MAINTAINER=	vanilla@FreeBSD.org
COMMENT=	Super fast C++ logging library

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	gabime

USES=		cmake compiler:c++11-lib pathfix

.include <bsd.port.mk>
