# $FreeBSD: head/graphics/php71-gd/Makefile 475983 2018-07-31 08:44:56Z tz $

CATEGORIES=	graphics

PORTREVISION=	1

MASTERDIR=	${.CURDIR}/../../lang/php71

PKGNAMESUFFIX=	-gd

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"

LIB_DEPENDS+=	libgd.so:graphics/gd
