# $FreeBSD: head/graphics/php71-gd/Makefile 475229 2018-07-24 08:44:32Z tz $

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php71

PKGNAMESUFFIX=	-gd

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
