# Created by: Dmitry Sivachenko <demon@FreeBSD.org>
# $FreeBSD: head/devel/py-country/Makefile 430922 2017-01-09 08:49:56Z demon $

PORTNAME=	country
PORTVERSION=	17.1.8
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	pycountry-${PORTVERSION}

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Python API for ISO country, subdivision, language and currency

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
