# Created by: Lars Thegler <lars@thegler.dk>
# $FreeBSD: head/devel/p5-Class-Base/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Class-Base
PORTVERSION=	0.08
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Useful base class for deriving other modules

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
