# $FreeBSD: head/textproc/hs-libyaml/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	libyaml
PORTVERSION=	0.1.0.0
PORTREVISION=	1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Low-level, streaming YAML interface

LICENSE=	BSD3CLAUSE

USE_CABAL=	conduit resourcet

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
