# $FreeBSD: head/net-mgmt/prometheus-collectd-exporter/Makefile 458824 2018-01-12 12:59:04Z mat $

PORTNAME=	prometheus-collectd-exporter
PORTVERSION=	0.3.1
CATEGORIES=	net-mgmt
DISTNAME=	0.3.1

MAINTAINER=	dsp@php.net
COMMENT=	Collectd exporter for prometheus

LICENSE=	APACHE20

USES=		go gmake
USE_GITHUB=	yes
GH_ACCOUNT=	prometheus
GH_PROJECT=	collectd_exporter

PLIST_FILES=	bin/prometheus-collectd-exporter

.include <bsd.port.mk>
