# $FreeBSD: head/net-mgmt/prometheus-collectd-exporter/Makefile 468916 2018-05-03 09:16:21Z mat $

PORTNAME=	prometheus-collectd-exporter
PORTVERSION=	0.3.1
CATEGORIES=	net-mgmt

MAINTAINER=	dsp@php.net
COMMENT=	Collectd exporter for prometheus

LICENSE=	APACHE20

USES=		go gmake
USE_GITHUB=	yes
GH_ACCOUNT=	prometheus
GH_PROJECT=	collectd_exporter

PLIST_FILES=	bin/prometheus-collectd-exporter

.include <bsd.port.mk>
