# $FreeBSD: head/devel/erlang-protobuffs/Makefile 419235 2016-07-29 10:16:17Z olgeni $

PORTNAME=	protobuffs
PORTVERSION=	0.9.0
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Protocol Buffers interface for Erlang

LICENSE=	APACHE20

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	basho
GH_PROJECT=	erlang_protobuffs

.include <bsd.port.mk>
