# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: head/chinese/p5-Lingua-Han-Utils/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	Lingua-Han-Utils
PORTVERSION=	0.13
CATEGORIES=	chinese perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Utility tools of Chinese character(HanZi)

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Encode-Detect-CJK>=0:converters/p5-Encode-Detect-CJK

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
