# $FreeBSD: head/devel/hs-preprocessor-tools/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	preprocessor-tools
PORTVERSION=	2.0.2
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Framework for extending Haskell's syntax via quick-and-dirty preprocessors

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl>=1 syb>=0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
