# $FreeBSD: head/devel/hs-bitarray/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	bitarray
PORTVERSION=	0.0.1.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Mutable and immutable bit arrays

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
