# $FreeBSD: head/sysutils/atf-sun50i_a64/Makefile 492250 2019-02-05 15:30:29Z manu $

MASTERDIR=	${.CURDIR}/../atf-master

PORTVERSION=	2.0.20181123
ATF_VERSION=	98aab97
PLAT=	sun50i_a64
BL31=	bl31.bin

.include "${MASTERDIR}/Makefile"
