# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/net/pear-Net_IPv4/Makefile 487192 2018-12-10 17:18:12Z joneum $

PORTNAME=	Net_IPv4
DISTVERSION=	1.3.5
CATEGORIES=	net pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	IPv4 network calculations and validation

LICENSE=	PHP301

USES=		pear

.include <bsd.port.mk>
