# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/net/pear-Net_IPv4/Makefile 441000 2017-05-16 13:37:51Z joneum $

PORTNAME=	Net_IPv4
DISTVERSION=	1.3.4
CATEGORIES=	net pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	IPv4 network calculations and validation

LICENSE=	PHP301

USES=		pear

.include <bsd.port.mk>
