# $FreeBSD: head/www/py-azure-common/Makefile 488093 2018-12-22 13:11:57Z dbaio $

PORTNAME=	azure-common
PORTVERSION=	1.1.16
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dbaio@FreeBSD.org
COMMENT=	Microsoft Azure common code

LICENSE=	APACHE20

USES=		python zip
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
