# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: head/textproc/p5-Lingua-EN-Numbers-Ordinate/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Lingua-EN-Numbers-Ordinate
PORTVERSION=	1.04
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Go from cardinal number (3) to ordinal ("3rd")

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
