# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-rspec-support/Makefile 440165 2017-05-05 15:34:35Z sunpoet $

PORTNAME=	rspec-support
PORTVERSION=	3.6.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Support utilities for RSpec gems

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.md

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
