# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-vcd/Makefile 478555 2018-08-31 13:36:25Z wen $

PORTNAME=	vcd
DISTVERSION=	1.4-4
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	pfg@FreeBSD.org
COMMENT=	Visualization techniques, data sets for categorical data

LICENSE=	GPLv2

RUN_DEPENDS=	R-cran-colorspace>0:graphics/R-cran-colorspace \
		R-cran-lmtest>0:finance/R-cran-lmtest

USES=		cran:auto-plist

.include <bsd.port.mk>
