# Created by: Artyom Mirgorodskiy <artyom.mirgorodsky@gmail.com>
# $FreeBSD: head/security/linux-c6-libssh2/Makefile 432937 2017-01-31 16:54:21Z tijl $

PORTNAME=	libssh2
PORTVERSION=	1.4.2
PORTREVISION=	6
CATEGORIES=	security linux

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	Library implementing the SSH2 protocol (Linux CentOS ${LINUX_DIST_VER})

DESCR=		${.CURDIR}/../${PORTNAME}/pkg-descr
RPMVERSION=	2.el6_7.1
USES=		linux:c6
USE_LDCONFIG=	yes
USE_LINUX=	openssl
USE_LINUX_RPM=	yes

.include <bsd.port.mk>
