# Created by: Yen-Ming Lee <leeym@FreeBSD.org>
# $FreeBSD: head/devel/p5-accessors/Makefile 430405 2017-01-02 20:13:16Z adamw $

PORTNAME=	accessors
PORTVERSION=	1.01
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:SPURKIS
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Create accessor methods in caller's package #'

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
