# Created by: Kimura Fuyuki <fuyuki@hadaly.org>
# $FreeBSD: head/security/p5-Crypt-CAST5_PP/Makefile 487494 2018-12-15 09:00:09Z amdmi3 $

PORTNAME=	Crypt-CAST5_PP
PORTVERSION=	1.04
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	CAST5 block cipher in pure Perl

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
