# Created by: Mikle Davidkin <skylord@vt.net.ru>
# $FreeBSD: head/net-p2p/verlihub-plugins-messanger/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	messanger
PORTVERSION=	1.2
PORTREVISION=	6
CATEGORIES=	net-p2p
MASTER_SITES=	SF/verlihub/VH_Messanger/${DISTVERSION}

MAINTAINER=	me@skylord.ru

PLUGIN_DESC=	Messanger

.include "../verlihub-plugins/Makefile.plugins"
.include <bsd.port.mk>
