# $FreeBSD: head/security/hs-cryptohash-sha1/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=      cryptohash-sha1
PORTVERSION=   0.11.100.1
PORTREVISION=  2
CATEGORIES=    security haskell

MAINTAINER=    haskell@FreeBSD.org
COMMENT=       A practical incremental and one-pass, pure API to the SHA-1 hash algorithm

LICENSE=       BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
