# Created by: Dmitry Marakasov <amdmi3@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-r18n-core/Makefile 441403 2017-05-21 14:57:04Z sunpoet $

PORTNAME=	r18n-core
PORTVERSION=	2.1.6
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	i18n tool to translate your Ruby application

LICENSE=	LGPL3
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
