# Created by: Zach Thompson <hideo@lastamericanempire.com>
# $FreeBSD: head/devel/p5-Data-Types/Makefile 486709 2018-12-05 18:49:21Z sunpoet $

PORTNAME=	Data-Types
PORTVERSION=	0.16
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Validate and convert data types

LICENSE_COMB=	dual
LICENSE=	ART10 GPLv1+

USES=		perl5
USE_PERL5=	modbuild

NO_ARCH=	yes

.include <bsd.port.mk>
