# $FreeBSD: head/devel/rubygem-jasmine-core/Makefile 483202 2018-10-27 23:24:23Z sunpoet $

PORTNAME=	jasmine-core
PORTVERSION=	3.3.0
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Test JavaScript without any framework dependencies

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
