# $FreeBSD: head/devel/rubygem-jasmine-core/Makefile 477272 2018-08-15 19:33:57Z sunpoet $

PORTNAME=	jasmine-core
PORTVERSION=	3.2.1
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Test JavaScript without any framework dependencies

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
