# $FreeBSD: head/devel/rubygem-jasmine-core/Makefile 443748 2017-06-17 10:01:33Z sunpoet $

PORTNAME=	jasmine-core
PORTVERSION=	2.6.4
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Test JavaScript without any framework dependencies

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
