# Created by: Roland van Laar <roland@micite.net>
# $FreeBSD: head/databases/py-sqlparse/Makefile 435258 2017-03-02 17:59:22Z sunpoet $

PORTNAME=	sqlparse
PORTVERSION=	0.2.3
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Non-validating SQL parser for Python

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes
USE_PYTHON=	autoplist concurrent distutils
USES=		python

.include <bsd.port.mk>
