# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/ftp/pear-Net_FTP/Makefile 443253 2017-06-11 07:39:17Z sunpoet $

PORTNAME=	Net_FTP
PORTVERSION=	1.4.0
CATEGORIES=	ftp www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR OO interface to the PHP FTP functions plus some additions

LICENSE=	BSD2CLAUSE

USE_PHP=	ftp
USES=		pear php

.include <bsd.port.mk>
