# $FreeBSD: head/japanese/font-ricty-discord/Makefile 471135 2018-05-30 15:21:28Z meta $

PKGNAMESUFFIX=	-discord
COMMENT=	Ricty Discord - fonts for programming

MASTERDIR=	${.CURDIR}/../font-ricty

.include        "${MASTERDIR}/Makefile"
