# Created by: Mathieu Arnold <m@absolight.net>
# $FreeBSD: head/devel/p5-B-Keywords/Makefile 493210 2019-02-17 19:40:41Z sunpoet $

PORTNAME=	B-Keywords
PORTVERSION=	1.20
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Lists of reserved barewords and symbol names

LICENSE=	ART10 GPLv2
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

NO_ARCH=	yes

.include <bsd.port.mk>
