# Created by: Mathieu Arnold <m@absolight.net>
# $FreeBSD: head/devel/p5-B-Keywords/Makefile 460402 2018-01-30 15:39:10Z sunpoet $

PORTNAME=	B-Keywords
PORTVERSION=	1.18
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Lists of reserved barewords and symbol names

LICENSE=	ART10 GPLv2
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
