# $FreeBSD: head/devel/hs-profunctors/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	profunctors
PORTVERSION=	5.2.2
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Profunctors

LICENSE=	BSD3CLAUSE

USE_CABAL=	base-orphans bifunctors comonad contravariant \
		distributive tagged

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
