# Created by: IWATSUKI Hiroyuki <don@na.rim.or.jp>
# $FreeBSD: head/devel/rubygem-platform/Makefile 432064 2017-01-21 17:29:23Z sunpoet $

PORTNAME=	platform
PORTVERSION=	0.4.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
DISTNAME=	Platform-${PORTVERSION}

MAINTAINER=	don@na.rim.or.jp
COMMENT=	Hopefully robust platform sensing

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
