# $FreeBSD: head/deskutils/qownnotes/Makefile 490472 2019-01-16 11:13:44Z tijl $

PORTNAME=	qownnotes
DISTVERSION=	18.07.2
PORTREVISION=	1
CATEGORIES=	deskutils
MASTER_SITES=	https://download.tuxfamily.org/qownnotes/src/

MAINTAINER=	stobbsm@gmail.com
COMMENT=	Manage notes using nextcloud and markdown

LICENSE=	GPLv2

USES=		gmake qmake qt:5 tar:xz
USE_QT=		buildtools_build linguisttools_build core dbus gui network sql svg webkit xml

.include <bsd.port.mk>
