# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: head/devel/p5-Term-ScreenColor/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	Term-ScreenColor
PORTVERSION=	1.20
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Term::Screen based screen positioning and coloring module

LICENSE=	ART10 GPLv2
LICENSE_COMB=	dual

RUN_DEPENDS=	p5-Term-Screen>=0:devel/p5-Term-Screen

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
