# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/textproc/pear-Horde_JavascriptMinify/Makefile 450171 2017-09-19 21:48:42Z mm $

PORTNAME=	Horde_JavascriptMinify
PORTVERSION=	1.1.5
CATEGORIES=	textproc www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Javascript Minification

USES=	horde

.include <bsd.port.mk>
