# Created by: tcberner
# $FreeBSD: head/devel/kf5-kpty/Makefile 438880 2017-04-19 14:59:40Z tcberner $

PORTNAME=	kpty
PORTVERSION=	${KDE_FRAMEWORKS_VERSION}
CATEGORIES=	devel kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KF5 pty abstraction

USES=		cmake:outsource compiler:c++11-lib gettext kde:5 tar:xz
USE_KDE=	coreaddons ecm i18n
USE_QT5=	buildtools_build core qmake_build

.include <bsd.port.mk>
