# $FreeBSD: head/devel/kf5-kpty/Makefile 475857 2018-07-29 22:18:44Z gerald $

PORTNAME=	kpty
DISTVERSION=	${KDE_FRAMEWORKS_VERSION}
PORTREVISION=	1
CATEGORIES=	devel kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KF5 pty abstraction

USES=		cmake:outsource compiler:c++11-lib gettext kde:5 qt:5 tar:xz
USE_KDE=	coreaddons ecm i18n
USE_QT=		buildtools_build core qmake_build

.include <bsd.port.mk>
