# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/devel/pear-PHP_CodeSniffer/Makefile 475653 2018-07-29 12:18:14Z joneum $

PORTNAME=	PHP_CodeSniffer
DISTVERSION=	3.3.1
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PHP Script Tokenises and Sniffs PHP and JavaScript code

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes
USES=		pear php
USE_PHP=	ctype simplexml tokenizer xmlwriter

.include <bsd.port.mk>
