# $FreeBSD: head/databases/qt5-sqldrivers-sqlite3/Makefile 490472 2019-01-16 11:13:44Z tijl $

PORTNAME=	sqlite3
PORTREVISION=	1

DB=		SQLite
DB_DESC=	SQLite 3

USES=		sqlite:3
CONFIGURE_ARGS=	-system-sqlite

.include "${.CURDIR:H:H}/devel/qt5/Makefile.sqldrivers"
