# $FreeBSD: head/textproc/hs-hs-bibutils/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	hs-bibutils
PORTVERSION=	6.2.0.1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Bindings to bibutils, the bibliography conversion utilities

LICENSE=	GPLv2

USE_CABAL=	syb

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
