# $FreeBSD: head/multimedia/gstreamer1-plugins-dts/Makefile 405242 2016-01-04 14:21:56Z kwm $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	GStreamer dts audio decode plugin

GST_PLUGIN=	dts
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
