# $FreeBSD: head/databases/postgresql11-pgtcl/Makefile 482456 2018-10-19 21:32:08Z girgen $

PKGNAMESUFFIX=	-postgresql11

CONFLICTS=	pgtcl-[0-9]* pgtcl-postgresql9[0123456]-[0-9]* pgtcl-postgresql10-*

PGTCL_SLAVE=	11
MASTERDIR=	${.CURDIR}/../pgtcl

.include "${MASTERDIR}/Makefile"
