# $FreeBSD: head/devel/template-glib/Makefile 480951 2018-09-30 11:58:29Z kwm $

PORTNAME=	template-glib
PORTVERSION=	3.28.0
CATEGORIES=	devel
MASTER_SITES=	GNOME

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Templating library for GLib

BUILD_DEPENDS=	valac:lang/vala

USES=		bison gettext gnome meson pkgconfig tar:xz
USE_GNOME=	glib20 introspection

.include <bsd.port.mk>
