# Created by: Dejan Lesjak <lesi@FreeBSD.org>
# $FreeBSD: head/x11/compositeproto/Makefile 465952 2018-03-30 09:03:25Z amdmi3 $

PORTNAME=	compositeproto
PORTVERSION=	0.4.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Composite extension headers

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

XORG_CAT=	proto

.include <bsd.port.mk>
