# Created by: ache@FreeBSD.org
# $FreeBSD: head/www/geolizer/Makefile 490700 2019-01-19 07:08:22Z dinoex $

MAINTAINER=	dinoex@FreeBSD.org

MASTERDIR?=	${.CURDIR}/../webalizer

OPTIONS_DEFAULT=BDB1 GEOIP

WEBALIZER_SUFFIX=	-geoip

.include "${MASTERDIR}/Makefile"
