# $FreeBSD: head/devel/py-fastentrypoints/Makefile 436609 2017-03-21 14:17:16Z wg $

PORTNAME=	fastentrypoints
PORTVERSION=	0.9
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Makes entry_points specified in setup.py load more quickly

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	autoplist concurrent distutils
NO_ARCH=	yes

.include <bsd.port.mk>
