# $FreeBSD: head/devel/p5-Data-Rand/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Data-Rand
PORTVERSION=	0.0.4
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tj@FreeBSD.org
COMMENT=	Perl module for generating random strings or arrays

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
