# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: head/textproc/p5-Lingua-EN-Sentence/Makefile 477685 2018-08-20 22:14:59Z sunpoet $

PORTNAME=	Lingua-EN-Sentence
PORTVERSION=	0.31
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Module for splitting text into sentences

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENCE

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
