# Created by: Pawel Worach
# $FreeBSD: head/x11-fonts/font-screen-cyrillic/Makefile 495395 2019-03-11 21:25:57Z zeising $

PORTNAME=	font-screen-cyrillic
PORTVERSION=	1.0.4
PORTREVISION=	4
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Screen Cyrillic font

XORG_CAT=	font

.include <bsd.port.mk>
