# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/sysutils/rubygem-syslog-logger/Makefile 445978 2017-07-16 00:47:40Z sunpoet $

PORTNAME=	syslog-logger
PORTVERSION=	1.6.8
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Improved Logger replacement that logs to syslog

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
