# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/science/R-cran-eco/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	eco
PORTVERSION=	3.1.6
PORTREVISION=	7
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${PORTVERSION:C/\./-/g:C/-/./1}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	R Package for Ecological Inference in 2x2 Tables

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
