# Created by: Charlie & <root@meatwad.mouf.net>
# $FreeBSD: head/devel/rubygem-bacon/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	bacon
PORTVERSION=	1.2.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Bacon is a small RSpec clone

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

PLIST_FILES=	bin/bacon

.include <bsd.port.mk>
