# Created by: Philip Paeps <philip@paeps.cx>
# $FreeBSD: head/devel/p5-Date-Roman/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	Date-Roman
PORTVERSION=	1.06
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	philip@FreeBSD.org
COMMENT=	Perl module to play with Roman dates

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Roman>=0:math/p5-Roman

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
