# $FreeBSD: head/textproc/hs-regex-base/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	regex-base
PORTVERSION=	0.93.2
PORTREVISION=	18
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Interface API for regex-posix,pcre,parsec,tdfa,dfa

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
