# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-xts/Makefile 412348 2016-04-01 14:16:16Z mat $

PORTNAME=	xts
DISTVERSION=	0.9-7
PORTREVISION=	5
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Extensible Time Series

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

RUN_DEPENDS=	R-cran-zoo>=1.7.10:math/R-cran-zoo

USES=	cran:auto-plist

.include <bsd.port.mk>
