# $FreeBSD: head/devel/hs-Boolean/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	Boolean
PORTVERSION=	0.2.4
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Generalized Booleans and numbers

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
