# Created by: Frederic Culot <culot@FreeBSD.org>
# $FreeBSD: head/textproc/p5-HTML-HTML5-Entities/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	HTML-HTML5-Entities
PORTVERSION=	0.004
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:TOBYINK
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Pure Perl drop-in replacement for HTML::Entities

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
