# Created by: Alfred Perlstein <alfred@freebsd.org>
# $FreeBSD: head/www/py-django-bootstrap-form/Makefile 470517 2018-05-21 08:01:05Z alfred $

PORTNAME=	django-bootstrap-form
PORTVERSION=	3.4
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	alfred@FreeBSD.org
COMMENT=	Bootstrap forms for django

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}django>=1.5:www/py-django@${FLAVOR}

.include <bsd.port.mk>
