# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: head/textproc/grc-aspell/Makefile 438338 2017-04-12 09:09:47Z mat $

PORTNAME=	${DICT}-aspell
SPELLVERSION=	6-${DICT}-0.02-0
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Ancient Greek dictionary

DICT=	 	grc

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
