# $FreeBSD: head/textproc/hs-regex-applicative/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	regex-applicative
PORTVERSION=	0.3.3
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Regex-based parsing with applicative interface

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
