# Created by: Mikle Davidkin <skylord@vt.net.ru>
# $FreeBSD: head/net-p2p/verlihub-plugins-forbid/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	forbid
PORTVERSION=	1.3
PORTREVISION=	7
CATEGORIES=	net-p2p
MASTER_SITES=	SF/verlihub/VH_Forbid/${DISTVERSION}

MAINTAINER=	me@skylord.ru

PLUGIN_DESC=	ForbiddenWords

.include "../verlihub-plugins/Makefile.plugins"
.include <bsd.port.mk>
