# $FreeBSD: head/x11-themes/xcursor-themes/Makefile 493618 2019-02-22 22:18:57Z zeising $

PORTNAME=	xcursor-themes
PORTVERSION=	1.0.6
CATEGORIES=	x11-themes

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.org cursors themes

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

BUILD_DEPENDS=	xcursorgen:x11/xcursorgen

NO_ARCH=	yes

XORG_CAT=	data

.include <bsd.port.mk>
