# Created by: Lewis Thompson <purple@lewiz.net>
# $FreeBSD: head/devel/pear-HTML_BBCodeParser/Makefile 459174 2018-01-16 14:26:57Z joneum $

PORTNAME=	HTML_BBCodeParser
PORTVERSION=	1.2.3
CATEGORIES=	devel www pear

MAINTAINER=	lewiz@compsoc.man.ac.uk
COMMENT=	Parser to replace UBB style tags with their HTML equivalents

BUILD_DEPENDS=	${PEARDIR}/HTML/Common.php:devel/pear-HTML_Common
RUN_DEPENDS=	${PEARDIR}/HTML/Common.php:devel/pear-HTML_Common

USES=	pear

.include <bsd.port.mk>
