# Created by: olevole@olevole.ru
# $FreeBSD: head/deskutils/py-spice-gtk/Makefile 424123 2016-10-17 15:15:07Z marino $

PORTREVISION=	1
COMMENT=	Python bindings for SPICE remote desktop servers
MASTERDIR=	${.CURDIR}/../spice-gtk

CONFLICTS=	spice-gtk-[0-9]*
SPICE_SLAVE=	yes

.include "${MASTERDIR}/Makefile"
