# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/p5-CPAN-Changes/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	CPAN-Changes
PORTVERSION=	0.40.0002
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:R}${PORTVERSION:E}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Read and write CPAN Changes files

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
