# Created by: Joe Marcus Clarke <marcus@FreeBSD.org>
# $FreeBSD: head/devel/mate-common/Makefile 407209 2016-01-25 12:31:21Z kwm $

PORTNAME=	mate-common
PORTVERSION=	1.12.0
CATEGORIES=	devel mate
MASTER_SITES=	MATE
DIST_SUBDIR=	mate

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Common automake macros for MATE

PORTSCOUT=	limitw:1,even

USES=		gmake pkgconfig:both tar:xz
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
