# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/py-asynctest/Makefile 473462 2018-06-27 23:30:24Z sunpoet $

PORTNAME=	asynctest
PORTVERSION=	0.12.2
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Enhance unittest for testing asyncio libraries

LICENSE=	APACHE20

NO_ARCH=	yes
USE_PYTHON=	autoplist distutils
USES=		python:3.4+

.include <bsd.port.mk>
