# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: head/lang/p5-Quantum-Superpositions/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	Quantum-Superpositions
PORTVERSION=	2.03
CATEGORIES=	lang science perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	QM-like superpositions in Perl

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Class-Multimethods>=0:devel/p5-Class-Multimethods

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
