# Created by: lippe
# $FreeBSD: head/devel/p5-Test-Portability-Files/Makefile 494944 2019-03-07 13:41:12Z culot $

PORTNAME=	Test-Portability-Files
PORTVERSION=	0.10
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Check file names portability

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	YES
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
