# $FreeBSD: head/sysutils/u-boot-a13-olinuxino/Makefile 431327 2017-01-12 22:49:08Z imp $

MAINTAINER=	imp@FreeBSD.org
MASTERDIR=	${.CURDIR}/../u-boot-master

MODEL=		sun5i-a13-olinuxino
BOARD_CONFIG=	A13-OLinuXino_defconfig
FAMILY=		allwinner

.include "${MASTERDIR}/Makefile"
