# $FreeBSD: head/misc/erlang-mimetypes/Makefile 479406 2018-09-10 13:14:50Z mat $

PORTNAME=	mimetypes
PORTVERSION=	1.1.0
CATEGORIES=	misc
PKGNAMEPREFIX=	erlang-

MAINTAINER=	erlang@FreeBSD.org
COMMENT=	Erlang MIME types library

LICENSE=	BSD3CLAUSE

USES=		erlang:rebar3
USE_GITHUB=	yes
GH_ACCOUNT=	spawngrid

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
