# $FreeBSD: head/misc/erlang-mimetypes/Makefile 418824 2016-07-20 08:33:24Z olgeni $

PORTNAME=	mimetypes
PORTVERSION=	1.0
CATEGORIES=	misc
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Erlang MIME types library

LICENSE=	BSD3CLAUSE

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	spawngrid

.include <bsd.port.mk>
