# Created by: Ben Woods <woodsb02@FreeBSD.org>
# $FreeBSD: head/devel/py3-nose/Makefile 415456 2016-05-18 16:50:21Z woodsb02 $

MASTERDIR=	${.CURDIR}/../py-nose

USES=		python:3.1+

.include "${MASTERDIR}/Makefile"
