# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@sunpoet.net>
# $FreeBSD: head/databases/p5-PostgreSQL-PLPerl-Call/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	PostgreSQL-PLPerl-Call
PORTVERSION=	1.006
PORTREVISION=	1
CATEGORIES=	databases perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:TIMB
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Simple interface for calling SQL functions from PostgreSQL PL/Perl

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

BUILD_DEPENDS=	p5-DBI>=1.60.5:databases/p5-DBI

NO_ARCH=	yes
USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
