# $FreeBSD: head/security/hs-crypto-pubkey-types/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	crypto-pubkey-types
PORTVERSION=	0.4.3
PORTREVISION=	5
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Generic cryptography Public keys algorithm types

LICENSE=	BSD3CLAUSE

USE_CABAL=	asn1-encoding asn1-types>=0.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
