# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/xf86vidmodeproto/Makefile 468087 2018-04-23 09:03:47Z amdmi3 $

PORTNAME=	xf86vidmodeproto
PORTVERSION=	2.3.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XFree86-VidModeExtension extension headers

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

XORG_CAT=	proto

.include <bsd.port.mk>
