# $FreeBSD: head/archivers/hs-zlib-enum/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	zlib-enum
PORTVERSION=	0.2.3.1
PORTREVISION=	6
CATEGORIES=	archivers haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Enumerator interface for zlib compression

LICENSE=	MIT

USE_CABAL=	enumerator>=0.4 zlib-bindings>=0.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
