# $FreeBSD: head/devel/py-setuptools_scm/Makefile 455210 2017-11-30 15:50:30Z mat $

PORTNAME=	setuptools_scm
PORTVERSION=	1.15.5
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Setuptools plugin to manage your versions by scm tags

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
