# $FreeBSD: head/biology/vcftools/Makefile 476330 2018-08-04 01:29:29Z jwb $

PORTNAME=	vcftools
PORTVERSION=	0.1.16
DISTVERSIONPREFIX=	v
CATEGORIES=	biology

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Tools for working with VCF genomics files

LICENSE=	LGPL3

USES=		autoreconf gmake perl5 pkgconfig

GNU_CONFIGURE=	yes
USE_GITHUB=	yes

.include <bsd.port.mk>
