# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD: head/biology/vcftools/Makefile 455000 2017-11-27 23:05:40Z jwb $

PORTNAME=	vcftools
PORTVERSION=	0.1.15
DISTVERSIONPREFIX=	v
CATEGORIES=	biology

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Tools for working with VCF genomics files

LICENSE=	LGPL3

USES=		autoreconf gmake perl5 pkgconfig

GNU_CONFIGURE=	yes
USE_GITHUB=	yes

.include <bsd.port.mk>
