# $FreeBSD: head/x11-drivers/xf86-video-tdfx/Makefile 441503 2017-05-23 05:03:14Z rezny $

PORTNAME=	xf86-video-tdfx
PORTVERSION=	1.4.7
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org tdfx display driver

USE_GL=		gl
XORG_CAT=	driver

.include <bsd.port.mk>
