# $FreeBSD: head/sysutils/u-boot-beaglebone/Makefile 472714 2018-06-18 20:22:13Z linimon $

MASTERDIR=	${.CURDIR}/../u-boot-master

MODEL=		beaglebone
BOARD_CONFIG=	am335x_boneblack_defconfig
FAMILY=		omap

.include "${MASTERDIR}/Makefile"
