# $FreeBSD: head/devel/hs-STMonadTrans/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	STMonadTrans
PORTVERSION=	0.4.3
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monad transformer version of the ST monad

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
