# $FreeBSD: head/devel/hs-STMonadTrans/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	STMonadTrans
PORTVERSION=	0.4.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monad transformer version of the ST monad

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
