# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-oj/Makefile 447858 2017-08-12 18:59:25Z sunpoet $

PORTNAME=	oj
PORTVERSION=	3.3.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Fast JSON parser and serializer

LICENSE=	MIT

LIB_DEPENDS=	libgmp.so:math/gmp \
		libunwind.so:devel/libunwind

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
