# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-oj/Makefile 445111 2017-07-06 00:03:21Z sunpoet $

PORTNAME=	oj
PORTVERSION=	3.2.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Fast JSON parser and serializer

LICENSE=	MIT

LIB_DEPENDS=	libgmp.so:math/gmp

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
