# Created by: Mark Felder <feld@FreeBSD.org>
# $FreeBSD: head/devel/py-certsrv/Makefile 482207 2018-10-16 07:48:58Z wen $

PORTNAME=	certsrv
PORTVERSION=	2.0.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Python client for the Microsoft Certificate Authority

LICENSE=	MIT

USES=		python
USE_PYTHON=	autoplist distutils
NO_BUILD=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
