# $FreeBSD: head/devel/py-mygpoclient/Makefile 433323 2017-02-04 15:56:01Z rm $

PORTNAME=	mygpoclient
PORTVERSION=	1.7
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP \
		http://thp.io/2010/mygpoclient/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	rm@FreeBSD.org
COMMENT=	gpodder.net API client library for Python

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/COPYING

NO_ARCH=	yes
USES=		python:2.7
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
