# $FreeBSD: head/sysutils/u-boot-riotboard/Makefile 472717 2018-06-18 21:26:36Z linimon $

MASTERDIR=	${.CURDIR}/../u-boot-master

MODEL=		riotboard
BOARD_CONFIG=	riotboard_defconfig
FAMILY=		riotboard

UBOOT_PLIST=	u-boot.imx

.include "${MASTERDIR}/Makefile"
