# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libXxf86dga/Makefile 479538 2018-09-11 18:34:27Z zeising $

PORTNAME=	libXxf86dga
PORTVERSION=	1.1.4
PORTREVISION=	5
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X DGA Extension

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 xext xorgproto
USES+=	cpe
CPE_PRODUCT=	libxxf86dga
CPE_VENDOR=	x

.include <bsd.port.mk>
