# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/www/rubygem-uglifier/Makefile 485271 2018-11-18 20:38:11Z sunpoet $

PORTNAME=	uglifier
PORTVERSION=	4.1.20
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby wrapper for UglifyJS JavaScript compressor

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

RUN_DEPENDS=	rubygem-execjs>=0.3.0:devel/rubygem-execjs

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
