# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/www/rubygem-uglifier/Makefile 476899 2018-08-11 14:17:30Z sunpoet $

PORTNAME=	uglifier
PORTVERSION=	4.1.18
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby wrapper for UglifyJS JavaScript compressor

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

RUN_DEPENDS=	rubygem-execjs>=0.3.0:devel/rubygem-execjs

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
