# Created by: Yonatan <onatan@gmail.com>
# $FreeBSD: head/games/bsdtris/Makefile 408087 2016-02-04 19:59:11Z marino $

PORTNAME=	bsdtris
PORTVERSION=	1.1
PORTREVISION=	2
CATEGORIES=	games
MASTER_SITES=	http://www.mavetju.org/download/adopted/
DISTNAME=	${PORTNAME}-01092003

MAINTAINER=	ports@FreeBSD.org
COMMENT=	BSD version of text-based Tetris game

USES=		ncurses
MAKE_ARGS=	TMPLDFLAGS="-lncurses"
NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
