# $FreeBSD: head/devel/hs-th-expand-syns/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	th-expand-syns
PORTVERSION=	0.4.4.0
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Expands type synonyms in Template Haskell ASTs

LICENSE=	BSD3CLAUSE

USE_CABAL=	syb

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
