# $FreeBSD: head/net/dpinger/Makefile 410100 2016-03-04 11:43:22Z garga $

PORTNAME=	dpinger
PORTVERSION=	2.0
DISTVERSIONPREFIX=	v
CATEGORIES=	net

MAINTAINER=	garga@FreeBSD.org
COMMENT=	IP device monitoring tool

LICENSE=	BSD2CLAUSE

USES=		uidfix
USE_GITHUB=	yes
GH_ACCOUNT=	dennypage
MAKEFILE=	Makefile.freebsd

PLIST_FILES=	bin/dpinger

.include <bsd.port.mk>
