# Created by: Rui Lopes (<rgl ruilopes com>)
# $FreeBSD: head/devel/rubygem-gem_plugin/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	gem_plugin
PORTVERSION=	0.2.3
PORTREVISION=	1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Gem Based Plugin System

LICENSE=	LGPL21 RUBY
LICENSE_COMB=	dual
LICENSE_FILE_LGPL21=	${WRKSRC}/COPYING
LICENSE_FILE_RUBY=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

PLIST_FILES=	bin/gpgen

.include <bsd.port.mk>
