# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-abind/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	abind
DISTVERSION=	1.4-5
PORTREVISION=	1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Combine Multidimensional Arrays

LICENSE=	LGPL20+

USES=		cran:auto-plist

.include <bsd.port.mk>
