# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-abind/Makefile 467023 2018-04-11 03:17:01Z tota $

PORTNAME=	abind
DISTVERSION=	1.4-5
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Combine Multidimensional Arrays

LICENSE=	LGPL20+

USES=		cran:auto-plist

.include <bsd.port.mk>
