# Created by: Gerrit Beine (<tux@pinguru.net>)
# $FreeBSD: head/devel/pear-HTML_Table/Makefile 419219 2016-07-28 13:03:41Z bofh $

PORTNAME=	HTML_Table
PORTVERSION=	1.8.4
CATEGORIES=	devel www pear

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Makes design of HTML tables easy, flexible, reusable, and efficient

LICENSE=	BSD3CLAUSE

BUILD_DEPENDS=	${PEARDIR}/HTML/Common.php:devel/pear-HTML_Common
RUN_DEPENDS=	${PEARDIR}/HTML/Common.php:devel/pear-HTML_Common

USES=	pear
NO_ARCH=	yes

.include <bsd.port.mk>
