# Created by: Neil Booth
# $FreeBSD: head/security/py-slowaes/Makefile 462307 2018-02-19 11:10:43Z antoine $

PORTNAME=	slowaes
DISTVERSION=	0.1a1
PORTREVISION=	2
CATEGORIES=	security python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	kyuupichan@gmail.com
COMMENT=	Implementation of AES in pure Python

LICENSE=	APACHE20

USES=		python:2.7
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
