# $FreeBSD: head/devel/shell-toolbox/Makefile 477222 2018-08-15 12:39:19Z 0mp $

PORTNAME=	shell-toolbox
DISTVERSION=	20180719
CATEGORIES=	devel

MAINTAINER=	0mp@FreeBSD.org
COMMENT=	Collection of shell script development tools

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes

GNU_CONFIGURE=	yes
USE_GITHUB=	yes
GH_ACCOUNT=	kusalananda

.include <bsd.port.mk>
