# $FreeBSD: head/devel/shell-toolbox/Makefile 468627 2018-04-29 13:01:25Z riggs $

PORTNAME=	shell-toolbox
DISTVERSION=	20180422
CATEGORIES=	devel

MAINTAINER=	0mp@FreeBSD.org
COMMENT=	Collection of shell script development tools

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes

GNU_CONFIGURE=	yes
USE_GITHUB=	yes
GH_ACCOUNT=	kusalananda

.include <bsd.port.mk>
