# $FreeBSD: head/databases/rubygem-mario-redis-lock/Makefile 446620 2017-07-25 19:57:49Z jrm $

PORTNAME=	mario-redis-lock
PORTVERSION=	1.2.0
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	jrm@FreeBSD.org
COMMENT=	Ruby distributed lock using Redis, with emphasis in transparency

LICENSE=	MIT

RUN_DEPENDS=	rubygem-redis>=3.3.3:databases/rubygem-redis

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
