# Created by: fernan@iib.unsam.edu.ar
# $FreeBSD: head/graphics/p5-SpringGraph/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	SpringGraph
PORTVERSION=	0.05
PORTREVISION=	8
CATEGORIES=	graphics perl5
MASTER_SITES=	CPAN/GraphViz/TEEJAY
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Directed graph alternative to GraphViz

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-GD>=1:graphics/p5-GD

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
