# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/textproc/pear-YAML/Makefile 463917 2018-03-08 19:48:41Z mat $

PORTNAME=	YAML
PORTVERSION=	1.0.6
CATEGORIES=	textproc www pear
MASTER_SITES=	http://pear.symfony-project.com/get/
PKGNAMEPREFIX=	${PEAR_PKGNAMEPREFIX}

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	The Symfony YAML Component

USES=	pear
PEAR_CHANNEL=	symfony

.include <bsd.port.mk>
