# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: head/audio/gstreamer-plugins-jack/Makefile 428152 2016-12-08 19:52:19Z tijl $
#   $MCom: ports/audio/gstreamer-plugins-jack/Makefile,v 1.5 2008/03/19 14:05:29 ahze Exp $

PORTREVISION=	2
CATEGORIES=	audio

COMMENT=	Gstreamer low-latency audio server plugin

GST_PLUGIN=	jack

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
