# $FreeBSD: head/math/hs-ieee754/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	ieee754
PORTVERSION=	0.8.0
PORTREVISION=	4
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Utilities for dealing with IEEE floating point numbers

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
