# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: head/textproc/p5-String-Strip/Makefile 479390 2018-09-10 11:16:59Z des $

PORTNAME=	String-Strip
PORTVERSION=	1.02
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension for fast, commonly used, string operations

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
