# $FreeBSD: head/devel/rubygem-highline/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	highline
PORTVERSION=	1.7.8
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	High-level IO library for command-line interfaces

LICENSE=	GPLv2 RUBY
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
