# $FreeBSD: head/devel/rubygem-highline/Makefile 457409 2017-12-27 19:53:12Z sunpoet $

PORTNAME=	highline
PORTVERSION=	1.7.10
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	High-level IO library for command-line interfaces

LICENSE=	GPLv2 RUBY
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
