--- revision.h.orig	2020-12-13 12:54:45 UTC
+++ revision.h
@@ -0,0 +1,7 @@
+/*
+ * THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT EDIT
+ *
+ * Generated by bin/svn-revision.
+ */
+
+#define REVISION      106
