# $FreeBSD: head/devel/erlang-backoff/Makefile 479406 2018-09-10 13:14:50Z mat $

PORTNAME=	backoff
PORTVERSION=	1.1.6
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	erlang@FreeBSD.org
COMMENT=	Simple exponential backoffs in Erlang

LICENSE=	MIT

USES=		erlang:rebar3
USE_GITHUB=	yes
GH_ACCOUNT=	ferd

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
