# $FreeBSD: head/devel/erlang-backoff/Makefile 406895 2016-01-22 09:15:33Z olgeni $

PORTNAME=	backoff
PORTVERSION=	1.1.3
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Simple exponential backoffs in Erlang

LICENSE=	MIT

USES=		erlang:rebar3
USE_GITHUB=	yes
GH_ACCOUNT=	ferd

.include <bsd.port.mk>
