# $FreeBSD: head/devel/gorm/Makefile 480741 2018-09-26 15:23:37Z brooks $

PORTNAME=	gorm
PORTVERSION=	1.2.23
PORTREVISION=	2
CATEGORIES=	devel gnustep
MASTER_SITES=	GNUSTEP/dev-apps

MAINTAINER=	theraven@FreeBSD.org
COMMENT=	Graphical Object Relationship Modeller

LICENSE=	GPLv3

USES=		gnustep
USE_GNUSTEP=	back build
USE_LDCONFIG=	${GNUSTEP_SYSTEM_LIBRARIES}

DEFAULT_LIBVERSION=	1.1.0

.include <bsd.port.mk>
