# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/devel/pear-Horde_Token/Makefile 411757 2016-03-24 07:39:22Z mm $

PORTNAME=	Horde_Token
PORTVERSION=	2.0.9
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Token API

USES=	horde
USE_HORDE_RUN=	Horde_Exception \
		Horde_Translation \
		Horde_Url \
		Horde_Util
USE_PHP=	hash

.include <bsd.port.mk>
