# $FreeBSD: head/devel/erlang-gen_smtp/Makefile 442280 2017-06-01 10:53:21Z olgeni $

PORTNAME=	gen_smtp
PORTVERSION=	0.12.0
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Extensible SMTP server and client for Erlang

LICENSE=	BSD2CLAUSE

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	Vagabond

.include <bsd.port.mk>
