# Created by: David Naylor <naylor.b.david@gmail.com>
# $FreeBSD: head/math/R-cran-stabledist/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	stabledist
DISTVERSION=	0.7-1
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	Stable Distribution Functions

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

TEST_DEPENDS=	R-cran-RUnit>0:devel/R-cran-RUnit \
		R-cran-fBasics>0:finance/R-cran-fBasics \
		R-cran-Rmpfr>0:math/R-cran-Rmpfr

USES=		cran:auto-plist

.include <bsd.port.mk>
