# Created by: Ryan Steinmetz <rpsfa@rit.edu>
# $FreeBSD: head/databases/rubygem-dm-paperclip/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	dm-paperclip
PORTVERSION=	2.5.0
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	File attachments as attributes for DataMapper

LICENSE=	MIT

RUN_DEPENDS=	rubygem-dm-core>=1.2.0:databases/rubygem-dm-core \
		rubygem-dm-migrations>=1.2.0:databases/rubygem-dm-migrations \
		rubygem-dm-validations>=1.2.0:databases/rubygem-dm-validations \
		rubygem-extlib>=0:devel/rubygem-extlib

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
