# Created by: Alonso Cardenas Marquez <acm@FreeBSD.org>
# $FreeBSD: head/archivers/fpc-unzip/Makefile 466532 2018-04-05 04:52:36Z acm $

CATEGORIES=	archivers lang
PKGNAMESUFFIX=	-unzip

COMMENT=	Free Pascal routines for unzipping zip files

USES=	fpc

MASTERDIR=	${.CURDIR}/../../lang/fpc
WRKUNITDIR=	${FPCSRCDIR}/packages/${PKGNAMESUFFIX:S/-//}
EXTRACTUNITDIR=	${WRKUNITDIR}

.include "${MASTERDIR}/Makefile"
