# $FreeBSD: head/devel/hs-EdisonAPI/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	EdisonAPI
PORTVERSION=	1.3.1
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A library of efficient, purely-functional data structures (API)

LICENSE=	MIT

USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
