# $FreeBSD: head/devel/hs-EdisonAPI/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	EdisonAPI
PORTVERSION=	1.3.1
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A library of efficient, purely-functional data structures (API)

LICENSE=	MIT

USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
