# $FreeBSD: head/audio/gstreamer1-plugins-speex/Makefile 405242 2016-01-04 14:21:56Z kwm $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	GStreamer speex voice encode/decode plugin

GST_PLUGIN=	speex
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
