# Created by: tobez
# $FreeBSD: head/lang/p5-Data-JavaScript/Makefile 479390 2018-09-10 11:16:59Z des $

PORTNAME=	Data-JavaScript
PORTVERSION=	1.13
PORTREVISION=	1
CATEGORIES=	lang www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Data::JavaScript - Dump perl structures to JavaScript code

USES=		perl5 tar:tgz
USE_PERL5=	configure

.include <bsd.port.mk>
