# $FreeBSD: head/devel/R-cran-fansi/Makefile 474955 2018-07-19 10:14:26Z tota $

PORTNAME=	fansi
PORTVERSION=	0.2.3
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	ANSI Control Sequence Aware String Functions

LICENSE=	GPLv2+

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
