# $FreeBSD: head/devel/R-cran-fansi/Makefile 477769 2018-08-22 06:26:44Z tota $

PORTNAME=	fansi
PORTVERSION=	0.3.0
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	ANSI Control Sequence Aware String Functions

LICENSE=	GPLv2+

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
