# $FreeBSD: head/www/py-httplib2/Makefile 493413 2019-02-20 07:42:10Z lwhsu $

PORTNAME=	httplib2
PORTVERSION=	0.12.1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	Comprehensive HTTP client library

LICENSE=	MIT

USES=		python

NO_ARCH=	yes
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
