# Created by: Johannes Meixner <johannes@perceivon.net>
# $FreeBSD: head/net/rubygem-octokit/Makefile 477028 2018-08-12 17:34:56Z sunpoet $

PORTNAME=	octokit
PORTVERSION=	4.10.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Simple wrapper for the GitHub API

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.md

RUN_DEPENDS=	rubygem-sawyer>=0.8.0:www/rubygem-sawyer

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
