# $FreeBSD: head/www/py-plone.app.locales/Makefile 413428 2016-04-16 10:36:51Z rm $

PORTNAME=	plone.app.locales
PORTVERSION=	4.3.10
CATEGORIES=	www python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Translation files for Plone

LICENSE=	GPLv2

NO_ARCH=	yes
USES=		python:2.7
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
