# Created by: Anes Mukhametov <anes@anes.su>
# $FreeBSD: head/devel/p5-Test-Able/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	Test-Able
PORTVERSION=	0.11
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	anes@anes.su
COMMENT=	Xunit with Moose

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Moose>=0.94:devel/p5-Moose

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
