# $FreeBSD: head/devel/xtoolchain-llvm40/Makefile 495363 2019-03-11 16:51:52Z brooks $

LLVM_SUFFIX=40

DEPRECATED=		No supported release uses this version
EXPIRATION_DATE=	2019-03-31

MASTERDIR=	${.CURDIR}/../xtoolchain-llvm-devel

.include "${MASTERDIR}/Makefile"
