# $FreeBSD: head/sysutils/hs-cpu/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	cpu
PORTVERSION=	0.1.2
PORTREVISION=	3
CATEGORIES=	sysutils haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	CPU information and properties helpers

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
