# $FreeBSD: head/sysutils/hs-cpu/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	cpu
PORTVERSION=	0.1.2
PORTREVISION=	7
CATEGORIES=	sysutils haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	CPU information and properties helpers

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
