# $FreeBSD: head/www/rubygem-carrierwave/Makefile 476121 2018-07-31 23:54:47Z sunpoet $

PORTNAME=	carrierwave
PORTVERSION=	1.3.1
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Upload files, map them to a range of ORMs, store on different backends

LICENSE=	MIT

RUN_DEPENDS=	rubygem-activemodel50>=4.0.0:databases/rubygem-activemodel50 \
		rubygem-activesupport50>=4.0.0:devel/rubygem-activesupport50 \
		rubygem-mime-types>=1.16:misc/rubygem-mime-types

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
