# Created by: Masahiro Teramoto <markun@onohara.to>
# $FreeBSD: head/devel/p5-Event-Notify/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	Event-Notify
PORTVERSION=	0.00004
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	markun@onohara.to
COMMENT=	Simple Observer/Notifier

BUILD_DEPENDS=	p5-Test-MockObject>=0:devel/p5-Test-MockObject
RUN_DEPENDS=	p5-Test-MockObject>=0:devel/p5-Test-MockObject

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
