# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-nio4r/Makefile 464694 2018-03-16 15:20:51Z sunpoet $

PORTNAME=	nio4r
PORTVERSION=	2.3.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Cross-platform asynchronous I/O primitives

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
