# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-nio4r/Makefile 457520 2017-12-29 18:46:55Z sunpoet $

PORTNAME=	nio4r
PORTVERSION=	2.2.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Cross-platform asynchronous I/O primitives

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
