# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/textproc/R-cran-brew/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	brew
DISTVERSION=	1.0-6
PORTREVISION=	1
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Templating Framework for Report Generation

LICENSE=	GPLv2

USES=		cran:auto-plist

.include <bsd.port.mk>
