# Created by: ache
# $FreeBSD: head/security/p5-Digest-MD5/Makefile 410743 2016-03-10 09:09:16Z jadawin $

PORTNAME=	Digest-MD5
PORTVERSION=	2.55
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 interface to the MD5 algorithm

LICENSE=	ARTPERL10

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
