# $FreeBSD: head/www/php71-tidy/Makefile 475229 2018-07-24 08:44:32Z tz $

CATEGORIES=	www

MASTERDIR=	${.CURDIR}/../../lang/php71

PKGNAMESUFFIX=	-tidy

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
