# Created by: Yuichiro NAITO <naito.yuichiro@gmail.com>
# $FreeBSD: head/devel/rubygem-schash/Makefile 418160 2016-07-07 05:01:33Z pi $

PORTNAME=	schash
PORTVERSION=	0.1.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	naito.yuichiro@gmail.com
COMMENT=	Ruby hash validator

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
