# Created by: Autrijus Tang <autrijus@autrijus.org>
# $FreeBSD: head/databases/p5-DBIx-Password/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	DBIx-Password
PORTVERSION=	1.9
PORTREVISION=	1
CATEGORIES=	databases perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Allows you to create a global password file for DB passwords

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-DBI>=0:databases/p5-DBI

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
