# $FreeBSD: head/devel/hs-mmorph/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	mmorph
PORTVERSION=	1.1.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monad morphisms

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl transformers-compat

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
