# $FreeBSD: head/devel/p5-Tie-LLHash/Makefile 438309 2017-04-11 19:36:09Z swills $

PORTNAME=	Tie-LLHash
PORTVERSION=	1.004
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	swills@FreeBSD.org
COMMENT=	Perl module which implements an ordered hash-like object

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
