# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/www/pear-Services_Amazon/Makefile 443351 2017-06-11 07:47:26Z sunpoet $

PORTNAME=	Services_Amazon
PORTVERSION=	0.9.0
CATEGORIES=	www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PHP interface to Amazon Product Advertising API

BUILD_DEPENDS=	${PEARDIR}/HTTP/Request.php:www/pear-HTTP_Request \
		${PEARDIR}/XML/Serializer.php:devel/pear-XML_Serializer
RUN_DEPENDS=	${PEARDIR}/HTTP/Request.php:www/pear-HTTP_Request \
		${PEARDIR}/XML/Serializer.php:devel/pear-XML_Serializer

USES=		pear

.include <bsd.port.mk>
