# $FreeBSD: head/devel/hs-system-filepath/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	system-filepath
PORTVERSION=	0.4.14
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	High-level, byte-based file and directory path manipulations

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
