# $FreeBSD: head/devel/hs-data-pprint/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	data-pprint
PORTVERSION=	0.2.4.1
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Prettyprint and compare Data values

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl parallel

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
