# Created by: Shin-ya MURAKAMI <murashin@gfd-dennou.org>
# $FreeBSD: head/math/rubygem-narray_miss/Makefile 414169 2016-04-28 13:42:40Z swills $

PORTNAME=	narray_miss
PORTVERSION=	1.2.8
CATEGORIES=	math rubygems
MASTER_SITES=	RG

MAINTAINER=	murashin@gfd-dennou.org
COMMENT=	Additional class with processing of missing value to NArray

RUN_DEPENDS=	rubygem-narray>0:math/rubygem-narray

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
