# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-convertible/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	convertible
PORTVERSION=	1.1.1.0
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Typeclasses and instances for converting between types

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl old-locale old-time text>=0.8

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
