# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/net/pecl-yp/Makefile 486751 2018-12-06 11:22:12Z rene $

PORTNAME=	yp
PORTVERSION=	1.0.1
PORTREVISION=	1
CATEGORIES=	net pear

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	YP/NIS functions binding for PHP

DEPRECATED=	Works only with EOL php 5.6
EXPIRATION_DATE=	2018-12-30

LICENSE=	PHP301

USES=		php:pecl
IGNORE_WITH_PHP=	71 72 73

.include <bsd.port.mk>
