# Created by: Dmitry Sivachenko <dima@Chg.RU>
# $FreeBSD: head/graphics/p5-GD-TextUtil/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	GD-TextUtil
PORTVERSION=	0.86
PORTREVISION=	5
CATEGORIES=	graphics perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	GDTextUtil-${PORTVERSION}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Text utilities for use with GD drawing package

RUN_DEPENDS=	p5-GD>=0:graphics/p5-GD

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
