# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-arrows/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	arrows
PORTVERSION=	0.4.4.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell arrow classes and transformers

LICENSE=	BSD3CLAUSE

USE_CABAL=	Stream

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
