# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: head/sysutils/rubygem-sys-admin/Makefile 462636 2018-02-22 19:51:20Z sunpoet $

PORTNAME=	sys-admin
PORTVERSION=	1.7.0
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Unified, cross platform replacement for the Etc module

LICENSE=	APACHE20

RUN_DEPENDS=	rubygem-ffi>=1.1.0:devel/rubygem-ffi

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
