# $FreeBSD: head/polish/calligra-l10n/Makefile 439367 2017-04-25 08:20:30Z riggs $

PORTNAME=	calligra-l10n
PORTVERSION=	${CALLIGRA_VERSION}
PORTREVISION=	2
CATEGORIES=	polish editors kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Polish messages and documentation for Calligra

CALLIGRA_L10N=	pl

.include "${.CURDIR:H:H}/editors/calligra-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
