# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-nloptr/Makefile 481705 2018-10-10 10:13:08Z tota $

PORTNAME=	nloptr
PORTVERSION=	1.2.1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	R interface to NLopt

LICENSE=	LGPL3

LIB_DEPENDS=	libnlopt.so:math/nlopt

USES=		cran:auto-plist,compiles pkgconfig

.include <bsd.port.mk>
