# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-extlib/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	extlib
PORTVERSION=	0.9.16
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	General Ruby extensions

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
