# $FreeBSD: head/devel/rubygem-declarative/Makefile 436582 2017-03-21 11:00:00Z tz $

PORTNAME=	declarative
PORTVERSION=	0.0.9
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	DSL for nested schemas

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
