# $FreeBSD: head/devel/py-podcastparser/Makefile 460982 2018-02-05 17:06:46Z rm $

PORTNAME=	podcastparser
PORTVERSION=	0.6.3
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	rm@FreeBSD.org
COMMENT=	Simplified, fast RSS parser

LICENSE=	ISCL
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
