# $FreeBSD: head/devel/py-podcastparser/Makefile 459696 2018-01-22 20:27:13Z rm $

PORTNAME=	podcastparser
PORTVERSION=	0.6.2
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	rm@FreeBSD.org
COMMENT=	Simplified, fast RSS parser

LICENSE=	ISCL
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
