# Created by: Ben Woods <woodsb02@FreeBSD.org>
# $FreeBSD: head/databases/py3-bsddb3/Makefile 415968 2016-05-27 23:00:15Z woodsb02 $

MASTERDIR=	${.CURDIR}/../py-bsddb3

USES=		bdb python:3.2+

.include "${MASTERDIR}/Makefile"
