# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: head/devel/p5-Sys-RunAlways/Makefile 479390 2018-09-10 11:16:59Z des $

PORTNAME=	Sys-RunAlways
PORTVERSION=	0.05
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Make sure there is always one invocation of a script active

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
