# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-validatable/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	validatable
PORTVERSION=	1.6.7
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Library for adding database/object validations

LICENSE=	BSD2CLAUSE RUBY
LICENSE_COMB=	dual

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
