# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: head/devel/p5-Config-Tiny/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Config-Tiny
PORTVERSION=	2.23
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Read/Write .ini style files with as little code as possible

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5 tar:tgz
USE_PERL5=	configure

.include <bsd.port.mk>
