# $FreeBSD: head/www/hs-http-date/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	http-date
PORTVERSION=	0.0.6.1
PORTREVISION=	5
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	HTTP Date parser/formatter

LICENSE=	BSD3CLAUSE

USE_CABAL=	attoparsec

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
