# $FreeBSD: head/www/hs-http-date/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	http-date
PORTVERSION=	0.0.6.1
PORTREVISION=	4
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	HTTP Date parser/formatter

LICENSE=	BSD3CLAUSE

USE_CABAL=	attoparsec

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
