# $FreeBSD: head/textproc/hs-regex-posix/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	regex-posix
PORTVERSION=	0.95.2
PORTREVISION=	14
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Replaces/enhances Text.Regex

LICENSE=	BSD3CLAUSE

USE_CABAL=	regex-base>=0.93

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
