# $FreeBSD: head/x11-drivers/xf86-input-void/Makefile 476013 2018-07-31 18:41:30Z zeising $

PORTNAME=	xf86-input-void
PORTVERSION=	1.4.1
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org void input driver

XORG_CAT=	driver

.include <bsd.port.mk>
