# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: head/textproc/p5-String-Fraction/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	String-Fraction
PORTVERSION=	0.30
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Convert fractions into Unicode chars

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-HTML-Fraction>=0.40:textproc/p5-HTML-Fraction

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
