# $FreeBSD: head/portuguese/webalizer-pt_BR/Makefile 409731 2016-02-28 09:32:43Z dinoex $

CATEGORIES=	portuguese
PKGNAMEPREFIX?=	pt_BR-

MAINTAINER=	ports@FreeBSD.org

MASTERDIR?=	${.CURDIR}/../../www/webalizer
WEBALIZER_LANG=	portuguese_brazil

.include "${MASTERDIR}/Makefile"
