# Created by: Evan Sarmiento <bsdports@wayfair.com>
# $FreeBSD: head/devel/rubygem-bson/Makefile 430002 2016-12-30 16:51:24Z swills $

PORTNAME=	bson
PORTVERSION=	4.2.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Full featured BSON specification implementation in Ruby

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
