# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: head/audio/gstreamer-plugins-speex/Makefile 428152 2016-12-08 19:52:19Z tijl $
#   $MCom: ports/audio/gstreamer-plugins-speex/Makefile,v 1.5 2008/03/19 14:05:32 ahze Exp $

PORTREVISION=	2
CATEGORIES=	audio

COMMENT=	Gstreamer speex voice plugin

GST_PLUGIN=	speex

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
