# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libdmx/Makefile 470146 2018-05-16 19:50:24Z zeising $

PORTNAME=	libdmx
PORTVERSION=	1.1.4
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	DMX extension library

XORG_CAT=	lib
USE_XORG=	x11 xext xextproto dmxproto:both
USES+=	cpe
CPE_VENDOR=	x

.include <bsd.port.mk>
