# Created by: Ju Pengfei <jupengfei@gmail.com>
# $FreeBSD: head/net/hs-pcap/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	pcap
PORTVERSION=	0.4.5.2
PORTREVISION=	12
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	System-independent interface for user-level packet capture

LICENSE=	BSD3CLAUSE

USE_CABAL=	network

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
