# Created by: Ju Pengfei <jupengfei@gmail.com>
# $FreeBSD: head/net/hs-pcap/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	pcap
PORTVERSION=	0.4.5.2
PORTREVISION=	13
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	System-independent interface for user-level packet capture

LICENSE=	BSD3CLAUSE

USE_CABAL=	network

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
