# Created by: Ju Pengfei <jupengfei@gmail.com>
# $FreeBSD: head/net/hs-pcap/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	pcap
PORTVERSION=	0.4.5.2
PORTREVISION=	14
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	System-independent interface for user-level packet capture

LICENSE=	BSD3CLAUSE

USE_CABAL=	network

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
