# $FreeBSD: head/textproc/rubygem-escape_utils11/Makefile 466442 2018-04-04 16:25:30Z mfechner $

PORTNAME=	escape_utils
PORTVERSION=	1.1.1
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	11

MAINTAINER=	idefix@fechner.net
COMMENT=	Faster string escaping routines for your web apps

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

PORTSCOUT=	limit:^1\.1\.

USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
