# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/devel/pear-Math_Fraction/Makefile 489884 2019-01-10 17:45:30Z joneum $

PORTNAME=	Math_Fraction
PORTVERSION=	0.4.1
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Classes that represent and manipulate fractions

LICENSE=	PHP30

USES=		pear

.include <bsd.port.mk>
