# $FreeBSD: head/www/fpc-libmicrohttpd/Makefile 460557 2018-02-01 07:09:44Z acm $

CATEGORIES=	www lang
PKGNAMESUFFIX=	-libmicrohttpd

COMMENT=	Free Pascal libmicrohttpd unit

USE_FPC=	rtl-extra

MASTERDIR=	${.CURDIR}/../../lang/fpc
WRKUNITDIR=	${FPCSRCDIR}/packages/${PKGNAMESUFFIX:S/-//}
EXTRACTUNITDIR=	${WRKUNITDIR}

.include "${MASTERDIR}/Makefile"
