# Created by: Ilya Bakulin <webmaster@kibab.com>
# $FreeBSD: head/devel/pecl-libevent/Makefile 481545 2018-10-08 15:08:13Z antoine $

PORTNAME=	libevent
PORTVERSION=	0.1.0
PORTREVISION=	3
CATEGORIES=	devel

MAINTAINER=	webmaster@kibab.com
COMMENT=	Libevent extension for PHP

LICENSE=	PHP301

LIB_DEPENDS=	libevent.so:devel/libevent

USES=	php:pecl

IGNORE_WITH_PHP=	70 71 72 73

.include <bsd.port.mk>
