# Created by: Wen Heping<wenheping@gmail.com>
# $FreeBSD: head/devel/py-tinyarray/Makefile 455210 2017-11-30 15:50:30Z mat $

PORTNAME=	tinyarray
PORTVERSION=	1.2.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Arrays of numbers for Python, optimized for small sizes

LICENSE=	BSD2CLAUSE

BUILD_DEPENDS=	${PYTHON_PKGNAMEPREFIX}nose>=0:devel/py-nose@${FLAVOR}

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
