# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/devel/pear-channel-horde/Makefile 417940 2016-07-02 19:52:20Z mm $

PORTNAME=	horde
PORTVERSION=	20160602
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	pear.horde.org

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.channel.mk"
.include <bsd.port.post.mk>
