# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: head/databases/rubygem-mysql/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	mysql
PORTVERSION=	2.9.1
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	MySQL API module for Ruby

LICENSE=	GPLv2 RUBY
LICENSE_COMB=	dual

USE_MYSQL=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
