# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: head/databases/rubygem-mysql/Makefile 444337 2017-06-26 03:24:13Z sunpoet $

PORTNAME=	mysql
PORTVERSION=	2.9.1
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	MySQL API module for Ruby

LICENSE=	GPLv2 RUBY
LICENSE_COMB=	dual

USE_RUBY=	yes
USES=		gem mysql

.include <bsd.port.mk>
