# $FreeBSD: head/devel/rubygem-ruby-macho/Makefile 494500 2019-03-03 11:48:59Z antoine $

PORTNAME=	ruby-macho
PORTVERSION=	2.2.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Library for parsing Mach-O files

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
