# $FreeBSD: head/x11-clocks/amor-kde4/Makefile 462619 2018-02-22 19:03:17Z tcberner $

PORTNAME=	amor
PORTVERSION=	${KDE4_VERSION}
PORTREVISION=	3
CATEGORIES=	x11-clocks kde kde-kde4

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Small animation which sits on top of active window

USES=		cmake:outsource kde:4 tar:xz
USE_KDE=	kdelibs automoc4
USE_QT4=	moc_build qmake_build rcc_build uic_build

.include <bsd.port.mk>
