# Created by: Espen Volden aka voldern <voldern@hoeggen.net>
# $FreeBSD: head/databases/rubygem-do_postgres/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	do_postgres
PORTVERSION=	0.10.17
PORTREVISION=	1
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	voldern@hoeggen.net
COMMENT=	Ruby DataObjects driver for PostgreSQL

RUN_DEPENDS=	rubygem-data_objects>=0.10.17:databases/rubygem-data_objects

USE_RUBY=	yes
USES=		gem pgsql

.include <bsd.port.mk>
