# Created by: Espen Volden aka voldern <voldern@hoeggen.net>
# $FreeBSD: head/databases/rubygem-do_postgres/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	do_postgres
PORTVERSION=	0.10.13
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	voldern@hoeggen.net
COMMENT=	Ruby DataObjects driver for PostgreSQL

RUN_DEPENDS=	rubygem-data_objects>=0.10.13:databases/rubygem-data_objects

USE_RUBY=	yes
USES=		gem pgsql

.include <bsd.port.mk>
