# $FreeBSD: head/devel/hs-boxes/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	boxes
PORTVERSION=	0.1.4
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	2D text pretty-printing library

LICENSE=	BSD3CLAUSE

USE_CABAL=	split>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
