# $FreeBSD: head/devel/php71-pcntl/Makefile 475229 2018-07-24 08:44:32Z tz $

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php71

PKGNAMESUFFIX=	-pcntl

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
