# Created by: Sergey Skvortsov <skv@FreeBSD.org>
# $FreeBSD: head/textproc/p5-XML-Generator-DBI/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	XML-Generator-DBI
PORTVERSION=	1.00
PORTREVISION=	2
CATEGORIES=	textproc databases perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Generate SAX events from SQL queries

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-XML-SAX>=0:textproc/p5-XML-SAX

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
