# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: head/textproc/nn-aspell/Makefile 438338 2017-04-12 09:09:47Z mat $

PORTNAME=	${DICT}-aspell
SPELLVERSION=	-nn-0.50.1-1
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Norwegian Nynorsk dictionary

DICT=	 	nn

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
