# Created by: krion
# $FreeBSD: head/x11/xtermcontrol/Makefile 421635 2016-09-09 19:42:46Z amdmi3 $

PORTNAME=	xtermcontrol
PORTVERSION=	3.3
CATEGORIES=	x11
MASTER_SITES=	http://www.thrysoee.dk/xtermcontrol/ \
		http://fossies.org/linux/privat/

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Tool for dynamic control of xterm properties

LICENSE=	GPLv2+

GNU_CONFIGURE=	yes
CONFIGURE_ENV=	ac_cv_header_libintl_h=no

PLIST_FILES=	bin/xtermcontrol man/man1/xtermcontrol.1.gz

.include <bsd.port.mk>
