# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-sfsmisc/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	sfsmisc
DISTVERSION=	1.1-2
PORTREVISION=	1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Utilities from 'Seminar fuer Statistik' ETH Zurich

LICENSE=	GPLv2+

USES=		cran:auto-plist

.include <bsd.port.mk>
