# Created by: Christoph Kick
# $FreeBSD: head/devel/rubygem-ffi/Makefile 471783 2018-06-05 18:56:02Z sunpoet $

PORTNAME=	ffi
PORTVERSION=	1.9.25
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Extension for dynamic libraries & binding functions

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

LIB_DEPENDS=	libffi.so:devel/libffi

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
