# Created by: Johannes Meixner <johannes@perceivon.net>
# $FreeBSD: head/science/py-coards/Makefile 462307 2018-02-19 11:10:43Z antoine $

PORTNAME=	coards
PORTVERSION=	1.0.5
PORTREVISION=	1
CATEGORIES=	science python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	johannes@perceivon.net
COMMENT=	COARDS compliant time parser

LICENSE=	MIT

USES=		python:2.7
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
