# Created by: Johannes Meixner <johannes@perceivon.net>
# $FreeBSD: head/science/py-coards/Makefile 417356 2016-06-23 09:48:53Z tz $

PORTNAME=	coards
PORTVERSION=	1.0.5
CATEGORIES=	science python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	johannes@perceivon.net
COMMENT=	COARDS compliant time parser

LICENSE=	MIT

USES=		python:2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
