# $FreeBSD: head/math/R-cran-numbers/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTNAME=	numbers
DISTVERSION=	0.7-1
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Number-Theoretic Functions

LICENSE=	GPLv3+

RUN_DEPENDS=	R-cran-gmp>=0.5.1:math/R-cran-gmp

USES=		cran:auto-plist

.include <bsd.port.mk>
