# $FreeBSD: head/sysutils/u-boot-nanopi-a64/Makefile 473804 2018-07-03 08:09:25Z linimon $

MASTERDIR=     ${.CURDIR}/../u-boot-master

MODEL=         nanopi_a64
BOARD_CONFIG=  nanopi_a64_defconfig
FAMILY=                allwinner64

.include "${MASTERDIR}/Makefile"
