# Created by: Oliver Lehmann <oliver@FreeBSD.org>
# $FreeBSD: head/devel/physfs-devel/Makefile 478087 2018-08-25 19:58:59Z oliver $

PORTNAME=	physfs
PORTVERSION=	3.0.1
CATEGORIES=	devel
MASTER_SITES=	http://icculus.org/${PORTNAME}/downloads/
PKGNAMESUFFIX=	-devel

MAINTAINER=	oliver@FreeBSD.org
COMMENT=	Library to provide abstract access to various archives

CONFLICTS_INSTALL=	physfs-[0-9]*

USES=		cmake tar:bzip2
USE_LDCONFIG=	yes

.include <bsd.port.mk>
