# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/dmxproto/Makefile 466212 2018-04-02 09:03:28Z amdmi3 $

PORTNAME=	dmxproto
PORTVERSION=	2.3.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	DMX extension headers

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

XORG_CAT=	proto

.include <bsd.port.mk>
