# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/textproc/rubygem-tomlrb/Makefile 475810 2018-07-29 19:23:16Z sunpoet $

PORTNAME=	tomlrb
PORTVERSION=	1.2.7
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Racc-based TOML parser

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem shebangfix

SHEBANG_FILES=	bin/setup

.include <bsd.port.mk>
