# Created by: Ben Woods <woodsb02@FreeBSD.org>
# $FreeBSD: head/devel/p5-Data-URIEncode/Makefile 415603 2016-05-21 16:39:34Z woodsb02 $

PORTNAME=	Data-URIEncode
PORTVERSION=	0.11
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	woodsb02@FreeBSD.org
COMMENT=	Allow complex data structures to be encoded using flat URIs

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

NO_ARCH=	yes

.include <bsd.port.mk>
