# Created by: IWATSUKI Hiroyuki <don@na.rim.or.jp>
# $FreeBSD: head/net/rubygem-net-netrc/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	net-netrc
PORTVERSION=	0.2.2
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	don@na.rim.or.jp
COMMENT=	Net::Netrc provides ftp(1)-style .netrc parsing

RUN_DEPENDS=	rubygem-platform>=0.3.0:devel/rubygem-platform

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
