# Created by: Kubilay Kocak <koobs@FreeBSD.org>
# $FreeBSD: head/www/py-django-mezzanine-filebrowser/Makefile 474283 2018-07-09 19:13:41Z miwi $

PORTNAME=	django-mezzanine-filebrowser
PORTVERSION=	0.4.7
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	filebrowser_safe-${PORTVERSION}

MAINTAINER=	koobs@FreeBSD.org
COMMENT=	Fork of django-filebrowser for Mezzanine CMS

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes

USES=		gettext python
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
