# $FreeBSD: head/devel/hs-old-time/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	old-time
PORTVERSION=	1.1.0.3
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Time library

LICENSE=	BSD3CLAUSE

USE_CABAL=	old-locale>=1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
