# $FreeBSD: head/devel/hs-old-time/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	old-time
PORTVERSION=	1.1.0.3
PORTREVISION=	6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Time library

LICENSE=	BSD3CLAUSE

USE_CABAL=	old-locale>=1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
