# Created by: Wen Heping<wenheping@gmail.com>
# $FreeBSD: head/www/pear-HTTP_WebDAV_Server/Makefile 443350 2017-06-11 07:47:21Z sunpoet $

PORTNAME=	HTTP_WebDAV_Server
PORTVERSION=	1.0.0.r4
CATEGORIES=	www devel pear
DISTNAME=	${PORTNAME}-1.0.0RC4

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	WebDAV Server Baseclass

USES=		pear

.include <bsd.port.mk>
