# Created by: Johannes Meixner <johannes@perceivon.net>
# $FreeBSD: head/dns/linux-c6-libasyncns/Makefile 479406 2018-09-10 13:14:50Z mat $

PORTNAME=	libasyncns
PORTVERSION=	0.8
PORTREVISION=	3
CATEGORIES=	dns devel linux

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	C library for executing DNS queries asynchronously (Linux CentOS ${LINUX_DIST_VER})

RPMVERSION=	1.1.el6
USES=		linux:c6
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
