# $FreeBSD: head/devel/py-serpent/Makefile 474386 2018-07-10 16:59:23Z rm $

PORTNAME=	serpent
PORTVERSION=	1.25
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	rm@FreeBSD.org
COMMENT=	Simple serialization library based on ast.literal_eval

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		dos2unix python
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
