# Created by: Sergey Akifyev <asa@gascom.ru>
# $FreeBSD: head/net-mgmt/zabbix2-agent/Makefile 474259 2018-07-09 14:06:32Z dbaio $

PORTNAME=	zabbix2
PKGNAMESUFFIX=	-agent
CATEGORIES=	net-mgmt

MASTERDIR=	${.CURDIR}/../zabbix2-server

PLIST=		${PKGDIR}/pkg-plist.agent

OPTIONS_DEFINE=	IPV6

.include "${MASTERDIR}/Makefile"
