# $FreeBSD: head/x11-drivers/xf86-video-r128/Makefile 441503 2017-05-23 05:03:14Z rezny $

PORTNAME=	xf86-video-r128
PORTVERSION=	6.10.2
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org r128 display driver

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

USE_GL=		gl
XORG_CAT=	driver
USE_XORG=	xf86miscproto

.include <bsd.port.mk>
