# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-checkers/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	checkers
PORTVERSION=	0.4.7
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Check properties on standard classes and data structures

LICENSE=	BSD3CLAUSE

USE_CABAL=	QuickCheck>=2.3 random

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
