# $FreeBSD: head/devel/rubygem-simple-navigation-rails50/Makefile 447386 2017-08-05 03:25:17Z jrm $

PORTNAME=	simple-navigation
PORTVERSION=	4.0.5
PORTREVISION=	1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	-rails50

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Create navigations for Rails, Sinatra or Padrino applications

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-activesupport50>0:devel/rubygem-activesupport50

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
