# $FreeBSD: head/devel/hs-io-streams/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	io-streams
PORTVERSION=	1.5.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple and easy-to-use primitives for I/O using streams

LICENSE=	BSD3CLAUSE

USE_CABAL=	attoparsec network primitive vector zlib-bindings

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
