# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: head/math/p5-Statistics-Distributions/Makefile 479412 2018-09-10 13:21:19Z des $

PORTNAME=	Statistics-Distributions
PORTVERSION=	1.02
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Calculate critical values of common statistical distributions

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
