# Created by: tcberner
# $FreeBSD: head/x11-toolkits/kf5-attica/Makefile 438880 2017-04-19 14:59:40Z tcberner $

PORTNAME=	attica
PORTVERSION=	${KDE_FRAMEWORKS_VERSION}
CATEGORIES=	x11-toolkits kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Open Collaboration Services API library KDE5 version

USES=		cmake:outsource compiler:c++11-lib kde:5 pathfix tar:xz
USE_KDE=	ecm
USE_QT5=	buildtools_build core gui network qmake_build testlib_build widgets

.include <bsd.port.mk>
