# $FreeBSD: head/textproc/elixir-earmark/Makefile 479406 2018-09-10 13:14:50Z mat $

PORTNAME=	earmark
PORTVERSION=	1.2.5
DISTVERSIONPREFIX=	v
CATEGORIES=	textproc
PKGNAMEPREFIX=	elixir-

MAINTAINER=	erlang@FreeBSD.org
COMMENT=	Markdown parser for Elixir

LICENSE=	APACHE20

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	pragdave

MIX_REWRITE=	yes

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
