# Created by: Jov amutu@amutu.com
# $FreeBSD: head/databases/pgFormatter/Makefile 479698 2018-09-13 21:52:22Z sunpoet $

PORTNAME=	pgFormatter
PORTVERSION=	3.1
DISTVERSIONPREFIX=	v
CATEGORIES=	databases

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	PostgreSQL SQL syntax beautifier

LICENSE=	PostgreSQL
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		perl5
USE_PERL5=	configure

USE_GITHUB=	yes
GH_ACCOUNT=	darold

NO_ARCH=	yes

.include <bsd.port.mk>
