# Created by: Jov amutu@amutu.com
# $FreeBSD: head/databases/pgFormatter/Makefile 477332 2018-08-16 13:04:31Z miwi $

PORTNAME=	pgFormatter
PORTVERSION=	3.0
DISTVERSIONPREFIX=	v
CATEGORIES=	databases

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PostgreSQL SQL syntax beautifier

LICENSE=	PostgreSQL
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		perl5
USE_PERL5=	configure
USE_GITHUB=	yes
GH_ACCOUNT=	darold
NO_ARCH=	yes

.include <bsd.port.mk>
