# Created by: Lars Balker Rasmussen <lbr@FreeBSD.org>
# $FreeBSD: head/www/p5-HTML-LinkList/Makefile 405968 2016-01-12 21:41:40Z sunpoet $

PORTNAME=	HTML-LinkList
PORTVERSION=	0.1701
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Create a 'smart' list of HTML links

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
