# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: head/graphics/poppler-qt4/Makefile 430818 2017-01-07 18:15:08Z rakuco $

PORTREVISION=	1
PKGNAMESUFFIX=	-qt4

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Qt 4 bindings to poppler

MASTERDIR=	${.CURDIR}/../../graphics/poppler
SLAVEPORT=	qt4
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
