# Created by: Robert Gogolok <gogo@cs.uni-sb.de>
# $FreeBSD: head/devel/rubygem-ruby-prof/Makefile 458092 2018-01-04 23:15:24Z swills $

PORTNAME=	ruby-prof
PORTVERSION=	0.17.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Fast profiler for Ruby

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_RUBY=	yes
USES=		gem

PLIST_FILES=	bin/ruby-prof bin/ruby-prof-check-trace

.include <bsd.port.mk>
