# $FreeBSD: head/devel/hs-wl-pprint-text/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	wl-pprint-text
PORTVERSION=	1.1.1.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A clone of wl-pprint for use with the text library

LICENSE=	BSD3CLAUSE

USE_CABAL=	base-compat text

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
