# $FreeBSD: head/devel/hs-wl-pprint-text/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	wl-pprint-text
PORTVERSION=	1.1.1.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A clone of wl-pprint for use with the text library

LICENSE=	BSD3CLAUSE

USE_CABAL=	base-compat

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
