# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: head/devel/p5-Log-Message-Simple/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	Log-Message-Simple
PORTVERSION=	0.10
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Provides standardized logging facilities using the Log::Message module

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Log-Message>=0:devel/p5-Log-Message

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
