# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-xpath/Makefile 482539 2018-10-20 14:52:26Z sunpoet $

PORTNAME=	xpath
PORTVERSION=	3.2.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	DSL for generating XPath Expressions

LICENSE=	MIT

RUN_DEPENDS=	rubygem-nokogiri>=1.8:textproc/rubygem-nokogiri

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
