# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-xpath/Makefile 471001 2018-05-27 20:17:44Z sunpoet $

PORTNAME=	xpath
PORTVERSION=	3.1.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	DSL for generating XPath Expressions

LICENSE=	MIT

RUN_DEPENDS=	rubygem-nokogiri>=1.8:textproc/rubygem-nokogiri

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
