# $FreeBSD: head/databases/erlang-epgsql/Makefile 431676 2017-01-16 16:21:03Z olgeni $

PORTNAME=	epgsql
PORTVERSION=	3.3.0
CATEGORIES=	databases
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Erlang PostgreSQL Database Client

LICENSE=	BSD3CLAUSE

USES=		erlang:rebar
USE_GITHUB=	yes

.include <bsd.port.mk>
