# $FreeBSD: head/databases/erlang-epgsql/Makefile 451744 2017-10-11 12:38:49Z olgeni $

PORTNAME=	epgsql
PORTVERSION=	3.4.0
CATEGORIES=	databases
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Erlang PostgreSQL Database Client

LICENSE=	BSD3CLAUSE

USES=		erlang:rebar3
USE_GITHUB=	yes

.include <bsd.port.mk>
