# $FreeBSD: head/devel/erlang-msgpack/Makefile 479406 2018-09-10 13:14:50Z mat $

PORTNAME=	msgpack
PORTVERSION=	0.7.0
PORTREVISION=	1
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	erlang@FreeBSD.org
COMMENT=	MessagePack (de)serializer for Erlang

LICENSE=	APACHE20

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	msgpack
GH_PROJECT=	msgpack-erlang

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
