# $FreeBSD: head/devel/erlang-msgpack/Makefile 428381 2016-12-11 20:16:26Z olgeni $

PORTNAME=	msgpack
PORTVERSION=	0.7.0
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	MessagePack (de)serializer for Erlang

LICENSE=	APACHE20

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	msgpack
GH_PROJECT=	msgpack-erlang

.include <bsd.port.mk>
