# Created by: Dan Langille <dvl@FreeBSD.org>
# $FreeBSD: head/devel/py-anyconfig/Makefile 405193 2016-01-03 23:00:02Z rakuco $

PORTNAME=	anyconfig
PORTVERSION=	0.0.5
DISTVERSIONPREFIX=	RELEASE_
CATEGORIES=	devel python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dvl@FreeBSD.org
COMMENT=	Generic access to configuration files in many formats

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.MIT

USE_GITHUB=	yes
GH_ACCOUNT=	ssato
GH_PROJECT=	python-${PORTNAME}

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
