# Created by: Hung-Yi Chen <gaod@hychen.org>
# $FreeBSD: head/www/pecl-solr/Makefile 438175 2017-04-10 15:08:47Z mat $

PORTNAME=	solr
PORTVERSION=	2.4.0
CATEGORIES=	www

MAINTAINER=	gaod@hychen.org
COMMENT=	PHP extension for Apache Solr

LICENSE=	PHP301

LIB_DEPENDS=	libcurl.so:ftp/curl \
		libxml2.so:textproc/libxml2

USES=		php:pecl
USE_PHP=	json:build

.include <bsd.port.mk>
