# $FreeBSD: head/security/p5-Crypt-Format/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Crypt-Format
PORTVERSION=	0.07
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	pi@FreeBSD.org
COMMENT=	Conversion utilities for encryption applications

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
