# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: head/devel/p5-Data-Path/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	Data-Path
PORTVERSION=	1.4.1
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ZAPHAR
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	XPath-like access to complex data structures

BUILD_DEPENDS=	p5-Test-MockObject>=1.08:devel/p5-Test-MockObject \
		p5-Test-Exception>0:devel/p5-Test-Exception

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
