# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/www/rubygem-net-http-digest_auth/Makefile 434232 2017-02-16 16:46:16Z sunpoet $

PORTNAME=	net-http-digest_auth
PORTVERSION=	1.4.1
CATEGORIES=	www net rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Implementation of RFC 2617 - Digest Access Authentication

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
