# $FreeBSD: head/emulators/mess/Makefile 466375 2018-04-03 20:35:24Z danilo $

PORTNAME=	mess
MTARGET=	mame
MSUBTARGET=	mess
COMMENT=	Multiple Emulator Super System

MASTERDIR=	${.CURDIR}/../mame
DESCR=		${.CURDIR}/pkg-descr
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
