# Created by: Jonathan Weiss (<jw@innerewut.de>)
# $FreeBSD: head/devel/rubygem-hoe/Makefile 479221 2018-09-08 00:15:09Z sunpoet $

PORTNAME=	hoe
PORTVERSION=	3.17.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Simple rake/rubygems helper for project Rakefiles

LICENSE=	MIT

RUN_DEPENDS=	rubygem-rake>=0.8:devel/rubygem-rake

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

PLIST_FILES=	bin/sow

.include <bsd.port.mk>
