# Created by: Jonathan Weiss (<jw@innerewut.de>)
# $FreeBSD: head/devel/rubygem-hoe/Makefile 454724 2017-11-22 23:35:45Z sunpoet $

PORTNAME=	hoe
PORTVERSION=	3.16.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Simple rake/rubygems helper for project Rakefiles

LICENSE=	MIT

RUN_DEPENDS=	rubygem-rake>=0.8:devel/rubygem-rake

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

PLIST_FILES=	bin/sow

.include <bsd.port.mk>
