# $FreeBSD: head/devel/py-configparser/Makefile 492315 2019-02-06 16:49:59Z robak $

PORTNAME=	configparser
PORTVERSION=	3.5.3
PORTEPOCH=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	robak@FreeBSD.org
COMMENT=	INI style configuration file parser

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

NO_ARCH=	yes

.include <bsd.port.mk>
