# $FreeBSD: head/devel/py-configparser/Makefile 445861 2017-07-15 09:38:06Z koobs $

PORTNAME=	configparser
PORTVERSION=	3.5.0
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	robak@FreeBSD.org
COMMENT=	INI style configuration file parser

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

NO_ARCH=	yes

.include <bsd.port.mk>
