# $FreeBSD: head/devel/py-configparser/Makefile 420280 2016-08-16 11:33:08Z robak $

PORTNAME=	configparser
PORTVERSION=	3.5.0
PORTEPOCH=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	robak@FreeBSD.org
COMMENT=	INI style configuration file parser

LICENSE=	MIT

USES=		python:2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
