# $FreeBSD: head/security/hs-digest/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	digest
PORTVERSION=	0.0.1.2
PORTREVISION=	14
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Various cryptographic hashes for Bytestrings

LICENSE=	BSD3CLAUSE

USE_CABAL=	zlib

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
