# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/py-ordereddict/Makefile 453381 2017-11-02 21:41:47Z olgeni $

PORTNAME=	ordereddict
PORTVERSION=	1.1
PORTREVISION=	1
CATEGORIES=	devel
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Drop-in substitute for Py2.7's new collections

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python:2		# for graphics/py-blocking
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
