# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/science/rubygem-rgeo-geojson/Makefile 466738 2018-04-07 16:32:45Z sunpoet $

PORTNAME=	rgeo-geojson
PORTVERSION=	2.0.0
CATEGORIES=	science rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	GeoJSON formatting and parsing in Ruby

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

RUN_DEPENDS=	rubygem-rgeo>=1.0:science/rubygem-rgeo

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
