# Created by: Alexander Churannov <churanov.port.maintainer@gmail.com>
# $FreeBSD: head/devel/exercisix/Makefile 363399 2014-07-29 21:43:17Z adamw $

PORTNAME=	exercisix
PORTVERSION=	1.2
CATEGORIES=	devel
MASTER_SITES=	http://alexanderchuranov.com/files/

MAINTAINER=	exercisix@alexanderchuranov.com
COMMENT=	Innovative lightweight unit-test framework for C++

USES=	tar:bzip2

OPTIONS_DEFINE=	EXAMPLES

.include <bsd.port.mk>
