# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-memisc/Makefile 429271 2016-12-23 15:26:54Z tota $

PORTNAME=	memisc
DISTVERSION=	0.99.8
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Provides an infrastructure for the management of survey data

LICENSE=	GPLv2

USES=	cran:auto-plist,compiles

.include <bsd.port.mk>
