# Created by: Ditesh Shashikant Gathani <ditesh@gathani.org>
# $FreeBSD: head/www/pear-Services_TinyURL/Makefile 443362 2017-06-11 07:48:20Z sunpoet $

PORTNAME=	Services_TinyURL
PORTVERSION=	0.1.2
CATEGORIES=	www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PHP interface to TinyURL's API

USES=		pear php
USE_PHP=	curl

.include <bsd.port.mk>
