# Created by: Michael Moll <kvedulv at kvedulv.de>
# $FreeBSD: head/devel/rubygem-coercible/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	coercible
PORTVERSION=	1.0.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby coercion library

LICENSE=	MIT

RUN_DEPENDS=	rubygem-descendants_tracker>=0.0.1:devel/rubygem-descendants_tracker

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
