# Created by: Pedro Giffuni
# $FreeBSD: head/graphics/R-cran-qcc/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTNAME=	qcc
DISTVERSION=	2.7
PORTREVISION=	1
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	pfg@FreeBSD.org
COMMENT=	Quality Control Charts

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=	cran:auto-plist

.include <bsd.port.mk>
