# $FreeBSD: head/devel/hs-unexceptionalio/Makefile 447548 2017-08-08 17:21:45Z tcberner $

PORTNAME=	unexceptionalio
PORTVERSION=	0.3.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	IO without any non-error, synchronous exceptions

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
