# $FreeBSD: head/devel/p5-Devel-FindPerl/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Devel-FindPerl
PORTVERSION=	0.014
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Find the path to your perl

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
