# $FreeBSD: head/devel/p5-Devel-FindPerl/Makefile 479311 2018-09-09 16:59:12Z sunpoet $

PORTNAME=	Devel-FindPerl
PORTVERSION=	0.014
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Find the path to your perl

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
