# $FreeBSD: head/security/py-spake2/Makefile 417950 2016-07-03 01:53:35Z swills $

PORTNAME=	spake2
PORTVERSION=	0.7
CATEGORIES=	security
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	swills@FreeBSD.org
COMMENT=	SPAKE2 password-authenticated key exchange (pure python)

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
