# $FreeBSD: head/security/py-spake2/Makefile 464721 2018-03-16 18:36:28Z swills $

PORTNAME=	spake2
PORTVERSION=	0.8
CATEGORIES=	security
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	swills@FreeBSD.org
COMMENT=	SPAKE2 password-authenticated key exchange (pure python)

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
