# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/math/R-cran-sp/Makefile 429715 2016-12-28 06:53:01Z wen $

PORTNAME=	sp
DISTVERSION=	1.2-4
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	R Classes and Methods for Spatial Data

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=	cran:auto-plist

.include <bsd.port.mk>
