# $FreeBSD: head/devel/mips-xtoolchain-gcc/Makefile 464084 2018-03-10 17:46:04Z gerald $

PORTREVISION=	1
PKGNAMEPREFIX=	mips-

MASTERDIR=	${.CURDIR}/../powerpc64-xtoolchain-gcc

.include "${MASTERDIR}/Makefile"
