# $FreeBSD: head/security/rubygem-six/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	six
PORTVERSION=	0.2.0
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Very simple authorization gem

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
