# $FreeBSD: head/www/rubygem-rack-test/Makefile 463252 2018-02-28 15:53:44Z sunpoet $

PORTNAME=	rack-test
PORTVERSION=	0.8.3
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Small, simple testing API for Rack apps

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE.txt

RUN_DEPENDS=	rubygem-rack16>=1.0:www/rubygem-rack16

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
