# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/net/pear-Auth_RADIUS/Makefile 463917 2018-03-08 19:48:41Z mat $

PORTNAME=	Auth_RADIUS
PORTVERSION=	1.1.0
CATEGORIES=	net security pear

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	PEAR wrapper classes for the RADIUS PECL

LICNSE=		BSD3CLAUSE

USE_PHP=	radius
USES=		pear php:flavors

.include <bsd.port.mk>
