# Created by: Michael Schout <mschout@gkg.net>
# $FreeBSD: head/devel/pear-HTML_Select/Makefile 463917 2018-03-08 19:48:41Z mat $

PORTNAME=	HTML_Select
PORTVERSION=	1.3.1
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR::HTML_Select is a class for generating HTML form select elements

BUILD_DEPENDS=	${PEARDIR}/HTML/Common.php:devel/pear-HTML_Common@${PHP_FLAVOR}
RUN_DEPENDS=	${PEARDIR}/HTML/Common.php:devel/pear-HTML_Common@${PHP_FLAVOR}

USES=		pear

.include <bsd.port.mk>
