# Created by: Ying-Chieh Liao <ijliao@FreeBSD.org>
# $FreeBSD: head/misc/shc/Makefile 485429 2018-11-20 14:05:01Z ehaupt $

PORTNAME=	shc
PORTVERSION=	4.0.1
CATEGORIES=	misc

MAINTAINER=	ehaupt@FreeBSD.org
COMMENT=	Generic script compiler

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		tar:tgz

GNU_CONFIGURE=	yes

USE_GITHUB=	yes
GH_ACCOUNT=	neurobin

PLIST_FILES=	bin/shc man/man1/shc.1.gz

.include <bsd.port.mk>
