# Created by: rpsfa@rit.edu
# $FreeBSD: head/devel/rubygem-simple_form-rails50/Makefile 485826 2018-11-24 22:31:53Z sunpoet $

PORTNAME=	simple_form
PORTVERSION=	4.1.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	-rails50

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Forms made easy

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

RUN_DEPENDS=	rubygem-activemodel50>=4:databases/rubygem-activemodel50 \
		rubygem-actionpack50>=4:www/rubygem-actionpack50

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
