# Created by: Nakata Maho <maho@FreeBSD.org>
# $FreeBSD: head/math/qd/Makefile 437439 2017-04-01 15:23:30Z gerald $

PORTNAME=	qd
PORTVERSION=	2.3.7
PORTREVISION=	6
CATEGORIES=	math
MASTER_SITES=	http://www.cs.berkeley.edu/~yozo/software/

MAINTAINER=	maho@FreeBSD.org
COMMENT=	Double-Double and Quad-Double Arithmetic

GNU_CONFIGURE=	yes
USES=		fortran

.include <bsd.port.mk>
