# Created by: Andrew Pantyukhin <infofarmer@FreeBSD.org>
# $FreeBSD: head/www/xpi-noscript/Makefile 440783 2017-05-13 10:59:11Z miwi $

PORTNAME=	noscript
PORTVERSION=	2.6.6.1
DISTVERSIONSUFFIX=	-sm+fx+fn
CATEGORIES=	www

MAINTAINER=	gecko@FreeBSD.org
COMMENT=	Security-enhancing Java/JS filtering extension

BROKEN=		checksum mismatch
XPI_ID=		{73a6fe31-595d-460b-a920-fcc0f8843232}
XPI_NUM=	722

.include "${.CURDIR}/../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
