# $FreeBSD: head/converters/hs-dataenc/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	dataenc
PORTVERSION=	0.14.0.7
PORTREVISION=	4
CATEGORIES=	converters haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Data encoding library

LICENSE=	BSD3CLAUSE

CONFLICTS_INSTALL=	hs-sandi-[0-9]*

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
