# $FreeBSD: head/converters/hs-dataenc/Makefile 457241 2017-12-25 15:49:23Z amdmi3 $

PORTNAME=	dataenc
PORTVERSION=	0.14.0.7
PORTREVISION=	3
CATEGORIES=	converters haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Data encoding library

LICENSE=	BSD3CLAUSE

CONFLICTS_INSTALL=	hs-sandi-[0-9]*

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
