# $FreeBSD: head/devel/hs-base16-bytestring/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	base16-bytestring
PORTVERSION=	0.1.1.6
PORTREVISION=	6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast base16 (hex) encoding and deconding for ByteStrings

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
