# $FreeBSD: head/devel/hs-base16-bytestring/Makefile 461362 2018-02-10 08:03:22Z tcberner $

PORTNAME=	base16-bytestring
PORTVERSION=	0.1.1.6
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast base16 (hex) encoding and deconding for ByteStrings

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
