# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/devel/py-setuptools_darcs/Makefile 455210 2017-11-30 15:50:30Z mat $

PORTNAME=	setuptools_darcs
PORTVERSION=	1.2.11
PORTREVISION=	2
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Setuptools plugin for darcs

BUILD_DEPENDS=		darcsver:devel/py-darcsver

USES=		python:2.7
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
