# Created by: Alex Miller (<asm@asm.kiev.ua>)
# $FreeBSD: head/devel/pear-XML_Parser/Makefile 438111 2017-04-09 18:16:13Z bofh $

PORTNAME=	XML_Parser
PORTVERSION=	1.3.7
CATEGORIES=	devel pear

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	PEAR XML parsing class based on PHP's bundled expat

LICENSE=	BSD2CLAUSE

USES=		pear
NO_ARCH=	yes

.include <bsd.port.mk>
