# $FreeBSD: head/graphics/kf5-kplotting/Makefile 492794 2019-02-12 17:48:25Z tcberner $

PORTNAME=	kplotting
DISTVERSION=	${KDE_FRAMEWORKS_VERSION}
CATEGORIES=	graphics kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KF5 lightweight plotting framework

USES=		cmake compiler:c++11-lib kde:5 qt:5 tar:xz
USE_KDE=	ecm
USE_QT=		buildtools_build core gui qmake_build testlib widgets

.include <bsd.port.mk>
