# $FreeBSD: head/devel/hs-ListLike/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	ListLike
PORTVERSION=	4.6
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Generic support for list-like structures in Haskell

LICENSE=	BSD3CLAUSE

USE_CABAL=	dlist fmlist primitive utf8-string vector

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
