# $FreeBSD: head/dns/bind-tools/Makefile 438945 2017-04-20 13:12:35Z mat $

# Define PORTREVISION in ${MASTERDIR}
MASTERDIR=	${.CURDIR}/../../dns/bind911

DESCR=		${.CURDIR}/pkg-descr
PLIST=		${.CURDIR}/pkg-plist

BIND_TOOLS_SLAVE=	YES

INSTALL_WRKSRC=	${WRKSRC}/bin

.include "${MASTERDIR}/Makefile"
