# $FreeBSD: head/dns/bind-tools/Makefile 459829 2018-01-24 10:43:21Z mat $

# Define PORTREVISION in ${MASTERDIR}
MASTERDIR=	${.CURDIR}/../../dns/bind912

DESCR=		${.CURDIR}/pkg-descr
PLIST=		${.CURDIR}/pkg-plist

BIND_TOOLS_SLAVE=	YES

INSTALL_WRKSRC=	${WRKSRC}/bin

.include "${MASTERDIR}/Makefile"
