# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: head/devel/libdbusmenu-qt5/Makefile 422409 2016-09-18 20:36:31Z tcberner $

PORTNAME=	libdbusmenu-qt
PORTREVISION=	0
PKGNAMESUFFIX=	5

COMMENT=	Qt5 implementation of the DBusMenu protocol

MASTERDIR=	${.CURDIR:H}/libdbusmenu-qt

.include "${MASTERDIR}/Makefile"
