# Created by: philip@p6m7g8.com
# $FreeBSD: head/textproc/p5-Filter-Simple/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	Filter-Simple
PORTVERSION=	0.94
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simplified source filtering

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
