# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-benelux/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	benelux
PORTVERSION=	0.6.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Mad way to time Ruby codes

LICENSE=	MIT

RUN_DEPENDS=	rubygem-attic>=0.5.3:devel/rubygem-attic \
		rubygem-storable>=0.8.6:devel/rubygem-storable

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
