# Created by: Danilo G. Baio <dbaio@bsd.com.br>
# $FreeBSD: head/textproc/py3-numpydoc/Makefile 442937 2017-06-08 14:43:45Z woodsb02 $

MASTERDIR=	${.CURDIR}/../py-numpydoc

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}sphinx>=1.0.1:textproc/py3-sphinx
TEST_DEPENDS=	${PYTHON_PKGNAMEPREFIX}nose>=0:devel/py3-nose

USES=	python:3.4+

.include "${MASTERDIR}/Makefile"
