# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/security/pear-Crypt_HMAC2/Makefile 443310 2017-06-11 07:44:04Z sunpoet $

PORTNAME=	Crypt_HMAC2
PORTVERSION=	1.0.0
CATEGORIES=	security www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Implementation of Hashed Message Authentication Code for PHP5

USES=		pear

.include <bsd.port.mk>
