# $FreeBSD: head/devel/elixir-nimble_csv/Makefile 431749 2017-01-17 15:55:43Z olgeni $

PORTNAME=	nimble_csv
PORTVERSION=	0.1.1
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	CSV parsing and dumping library for Elixir

LICENSE=	APACHE20

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	plataformatec

MIX_REWRITE=	yes

.include <bsd.port.mk>
