# $FreeBSD: head/www/hs-css-text/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	css-text
PORTVERSION=	0.1.3.0
PORTREVISION=	2
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	CSS parser and renderer

LICENSE=	BSD3CLAUSE

USE_CABAL=	attoparsec>=0.10.2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
