# Created by: Yuan-Chung Hsiao <ychsiao@ychsiao.org>
# $FreeBSD: head/textproc/p5-YAML-Tiny/Makefile 409649 2016-02-27 04:44:01Z adamw $

PORTNAME=	YAML-Tiny
PORTVERSION=	1.69
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ychsiao@ychsiao.org
COMMENT=	Read/Write YAML files with as little code as possible

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
