# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-haskell-src-exts/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	haskell-src-exts
PORTVERSION=	1.20.2
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Manipulating Haskell source

LICENSE=	BSD3CLAUSE

USE_CABAL=	cpphs
USE_HAPPY=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
