# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-haskell-src-exts/Makefile 489474 2019-01-06 12:18:06Z arrowd $

PORTNAME=	haskell-src-exts
PORTVERSION=	1.21.0
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Manipulating Haskell source

LICENSE=	BSD3CLAUSE

USE_CABAL=	cpphs
USE_HAPPY=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
