# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-retryable/Makefile 427678 2016-12-03 19:31:32Z sunpoet $

PORTNAME=	retryable
PORTVERSION=	2.0.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Allow for retrying of code blocks

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.md

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
