# Created by: Oliver Eikemeier <eikemeier@fillmore-labs.com>
# $FreeBSD: head/textproc/p5-XML-NodeFilter/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	XML-NodeFilter
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	XML::NodeFilter is an object that know how to "filter out" nodes

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-XML-LibXML>=0:textproc/p5-XML-LibXML

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
