# $FreeBSD: head/devel/hs-date-cache/Makefile 473611 2018-06-30 09:57:59Z arrowd $

PORTNAME=	date-cache
PORTVERSION=	0.3.0
PORTREVISION=	13
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Date cacher

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
