# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/xproto/Makefile 425440 2016-11-05 19:29:54Z bapt $

PORTNAME=	xproto
PORTVERSION=	7.0.31
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X11 protocol headers

LICENSE=	MIT

XORG_CAT=	proto

CONFIGURE_ARGS+=--disable-specs --without-fop --without-xmlto --without-xsltproc

.include <bsd.port.mk>
