# Created by: Dmitry Marakasov <amdmi3@FreeBSD.org>
# $FreeBSD: head/devel/py3-flake8-docstrings/Makefile 433411 2017-02-05 14:27:21Z amdmi3 $

MASTERDIR=	${.CURDIR}/../py-flake8-docstrings

RUN_DEPENDS?=	${PYTHON_PKGNAMEPREFIX}flake8>=0:devel/py3-flake8 \
		${PYTHON_PKGNAMEPREFIX}flake8-polyfill>=0:devel/py3-flake8-polyfill \
		${PYTHON_PKGNAMEPREFIX}pydocstyle>=0:devel/py3-pydocstyle

USES=		python:3

.include "${MASTERDIR}/Makefile"
