# Created by: Emanuel Haupt <ehaupt@critical.ch>
# $FreeBSD: head/audio/checkmate/Makefile 444886 2017-07-02 14:11:39Z ehaupt $

PORTNAME=	checkmate
PORTVERSION=	0.21
CATEGORIES=	audio
MASTER_SITES=	http://checkmate.gissen.nl/ \
		LOCAL/ehaupt

MAINTAINER=	ehaupt@FreeBSD.org
COMMENT=	Command-line utility for checking mp3 files for errors

LICENSE=	GPLv2

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/mpck man/man1/mpck.1.gz

.include <bsd.port.mk>
