# Created by: Bryan Drewery <bryan@shatow.net>
# $FreeBSD: head/devel/rubygem-backports/Makefile 439531 2017-04-27 07:59:57Z sunpoet $

PORTNAME=	backports
PORTVERSION=	3.8.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby 1.9 backports for 1.8

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
