# Created by: johnpupu <johnpupu@gmail.com>
# $FreeBSD: head/databases/pecl-leveldb/Makefile 438175 2017-04-10 15:08:47Z mat $

PORTNAME=	leveldb
PORTVERSION=	0.1.5
PORTREVISION=	1
CATEGORIES=	databases

MAINTAINER=	johnpupu@gmail.com
COMMENT=	This extension is a PHP binding for Google LevelDB

LICENSE=	PHP301

LIB_DEPENDS=	libleveldb.so:databases/leveldb

USES=		php:pecl
IGNORE_WITH_PHP=	70

.include <bsd.port.mk>
