# $FreeBSD: head/security/rubygem-rex-socket/Makefile 445703 2017-07-13 18:37:56Z antoine $

PORTNAME=	rex-socket
PORTVERSION=	0.1.8
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Ruby Exploitation(Rex) socket abstraction library

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-rex-core>=0:security/rubygem-rex-core

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
