# Created by: James FitzGibbon <jfitz@FreeBSD.org>
# $FreeBSD: head/finance/p5-Business-CreditCard/Makefile 465675 2018-03-27 09:03:23Z amdmi3 $

PORTNAME=	Business-CreditCard
PORTVERSION=	0.32
PORTREVISION=	1
CATEGORIES=	finance perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl5 module to validate/generate credit card checksums/names

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
