# Created by: Palle Girgensohn <girgen@pingpong.net>
# $FreeBSD: head/databases/postgresql10-docs/Makefile 447680 2017-08-10 14:23:31Z girgen $

WANT_PGSQL_VER=10

.include "${.CURDIR}/../postgresql96-docs/Makefile"
