# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/devel/rubygem-columnize/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	columnize
PORTVERSION=	0.9.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Sorts an Array in Column Order

LICENSE=	GPLv2 RUBY
LICENSE_COMB=	dual

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
