# $FreeBSD: head/devel/hs-refact/Makefile 470870 2018-05-25 21:44:12Z tcberner $

PORTNAME=	refact
PORTVERSION=	0.3.0.2
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	This library provides a datatype which can be interpreted by apply-refact

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
